### ISSUE TITLE
Installation of Typesetter 4.6

### ISSUE THREAD

**Issue by Knuzen** [Typesetter/Typesetter#103]
Hello, please be patiece, it's my first time, that I ask something here
I have used gpeasy 4.5 without any error and got the info this year about the new 
version typesetter 4.6
So I deleted everything and installed everything with typesetter 4.6
and got now an System-Error, which was not funny. why?
So, I deleted typesetter 4.6 and installed gpeasy 4.5 again and could update from there
successful. After that, this "update" menupoint wasn't seen anymore.
Is this normal ?
Is there also an typesetter 4.6. Version which could be installed in a single way
for my friends, who don't have the older version of 4.5.
Thanks for reading

**Comment by Knuzen** [comment]
Oh Sorry, my Fault,
there are two files
Typesetter_4.6 + Typesetter-master

**Comment by oyejorge** [comment]
> Typesetter_4.6 + Typesetter-master
> and no one works for installation, sorry.
What doesn't work? Is it the same issue you're seeing with gpEasy 4.5?

> So, this nice cms is not made for "small money-domains with PHP"
No, you're right, it should be built to work on small money domains as well. There's one piece of the current package that is a real memory hog but not entirely necessary. I'll make some changes and will get back to you in just a few.

**Comment by oyejorge** [comment]
This package should work on your server with max 16M memory: [Typesetter-Less-Memory.zip](https://github.com/Typesetter/Typesetter/files/76139/Typesetter-Less-Memory.zip)

Let me know if that works better for you. And I'll change Typesetter-master branch back to 4.6 so the other problem you reported doesn't happen again.

**Comment by Knuzen** [comment]
OK tnx,, new installed Less-Version and I've switched the PHP Version to 5.5 on the low-cost Server, too and got 
Memory Limit - Failed - Please have a look at http://pmk-services.com/cms/
At the low-cost-server adjustment I can't get more than 16M, sorry.

Now, this new typesetter-less-Memory Version works now well after installation on my big domain, without trouble.

**Comment by oyejorge** [comment]
Glad that worked on the big domain and I might have a solution for the low-cost-server. I'll hopefully have another upload for you by the end of the day.

**Comment by oyejorge** [comment]
Ok, this version should work on both servers: [Typesetter-2016-01-02-.zip](https://github.com/Typesetter/Typesetter/files/76502/Typesetter-2016-01-02-.zip)

Note thought that some themes (anything that uses bootstrap/bootswatch) will cause the memory limit error. I hope to have a solution for this in 4.7

**Comment by Knuzen** [comment]
Sorry, I have been a littel late, I've deleted all, I've installed everythink new, but the message was:
"gpEasy cannot be installed on your server with the current settings.", (see link above)
It's really a pitty, that we can't realize it on a low-cost-server.

**Comment by oyejorge** [comment]
Oops. Thanks for checking that. Looks like the memory check in the install
script is still too restrictive. Your current settings indicate 16M is
available so the script should allow installation. I'll have time to work
on it later today.

**Comment by oyejorge** [comment]
Ok, this should be the last one: [Typesetter-2016-01-05.zip](https://github.com/Typesetter/Typesetter/files/79434/Typesetter-2016-01-05.zip)

**Comment by Knuzen** [comment]
No, not the last, sorry. BTW: I'm glad to help you Josh with testing
You can please analyse:
pmk-service.com/ts02 (as the day)

pmk-services.com/ts05 (as the day)
Here you see NOW some of my dirty code from the root, which I have placed there, that my doughter can show their business partners.
If you suggest to put Typesetter into the root, then I have to change something with the path of the the Domainname, so I do not disturb the presentation now.
What shall we do?

**Comment by oyejorge** [comment]
Sorry, I screwed up the last zip (it had the correct fix, but was from the dev branch instead of the master branch). [Here's what I meant to attach yesterday](https://github.com/Typesetter/Typesetter/files/80664/Typesetter-2106-01-06.zip)

**Comment by Knuzen** [comment]
http://www.pmk-services.com/ts05
Now !!!
Forbidden
You don't have permission to access /ts05/ on this server.
------------------
Your possible FTP.access is available for analyse

**Comment by oyejorge** [comment]
Hmm. My first guess is it has something to do with the .htaccess file. I'd be happy to poke around if you'd like. You can send FTP info to me [via the contact for on Typesettercms.com](http://www.typesettercms.com/Contact)

**Comment by Knuzen** [comment]
done

**Comment by oyejorge** [comment]
Thanks for getting me FTP access... and the installation is ready to go!

The install was writing to the .htaccess file when it shouldn't have. Note, your server does not have apache mod_rewrite so urls will be ```http://www.pmk-services.com/ts05/index.php/page-name``` instead of ```http://www.pmk-services.com/ts05/page-name```

**Comment by Knuzen** [comment]
OK, now have looked in the settings of the low-cost server, and you are right, this mod_rewrite is not in the package.
Sorry for that.

What can I do now, when I am recommending TYPESETTER for this kind of server,
because, it's cheap and easy in connection with your software.

Thanks a lot for your afforts, because there will be some artists like me, which I can help now to realize their Internet.presentation.

Do I need now a spezial version, or do you fix this problem in the installation ?

**Comment by oyejorge** [comment]
The code on your server has the fixes. [I also released 4.6.1](https://github.com/Typesetter/Typesetter/releases/tag/v4.6.1) that has some other fixes.

**Comment by oyejorge** [comment]
And thanks so much for working with me on these issues!
