### ISSUE TITLE
5.01 b1 Include section do not work

### ISSUE THREAD

**Issue by a2exfr** [Typesetter/Typesetter#108]
Include File section just don't work.

http://testbeta5/?section=1&cmd=include_dialog&gpreq=json&jsoncallback=jQuery11130633009195200913_1453381688425&_=1453381688426

TypeError: gp_editor.updateElement is not a function
http://tb5/include/thirdparty/js/jquery.js?v=5.0b1 line 2 > eval
Line 153

**Comment by oyejorge** [comment]
Thanks!
