### ISSUE TITLE
Update 4.6 to 4.61

### ISSUE THREAD

**Issue by PeterS1** [Typesetter/Typesetter#109]
Hi, I get this message at the point "Preparation and settings" updating to 4.61:

Warning: file_exists(): open_basedir restriction in effect. 
File(/customers/d/0/c/odwserv.de/httpd.www/mbs1/themes/index.html/template.php) is not within the allowed path(s): (/customers/d/0/c/odwserv.de/httpd.www:/customers/d/0/c/odwserv.de/httpd.private:/customers/d/0/c/odwserv.de/tmp:/customers/odwserv.de/odwserv.de:/var/www/diagnostics:/usr/share/php) in /customers/d/0/c/odwserv.de/httpd.www/mbs1/include/tool/update.php on line 273 Warning: file_exists(): open_basedir restriction in effect. File(/customers/d/0/c/odwserv.de/httpd.www/mbs1/themes/index.html-old-4269/template.php) is not within the allowed path(s): (/customers/d/0/c/odwserv.de/httpd.www:/customers/d/0/c/odwserv.de/httpd.private:/customers/d/0/c/odwserv.de/tmp:/customers/odwserv.de/odwserv.de:/var/www/diagnostics:/usr/share/php) in /customers/d/0/c/odwserv.de/httpd.www/mbs1/include/tool/update.php on line 273

Who can help me in troubleshooting?

Thanks and regards
Peter

**Comment by oyejorge** [comment]
Curious... For reference, [here's php's description of the open_basdir configuration](http://php.net/manual/en/ini.core.php#ini.open-basedir).

So the error is happening when this file is being checked:
> /customers/d/0/c/odwserv.de/httpd.www/mbs1/themes/index.html/template.php

But your list of allowed paths includes this entry:
> /customers/d/0/c/odwserv.de/httpd.www

Seems like it should work. Is the ```.../index.html/template.php``` file a symbolic link?

**Comment by PeterS1** [comment]
Hi oyejorge, 
thanks for your reply.

"But your list of allowed paths includes this entry: /customers/d/0/c/odwserv.de/httpd.www"

Hmm, this must be a typeerror, or? odwserv.de/https.www should be correct?

Did you have any idea how I can fix the errors? I´m not a programmer :) !!

Thanks and many regards
Peter

**Comment by oyejorge** [comment]
So, I'm not sure why it's throwing that error.

Rather than attempt to figure out why your open_basedir setting is causing problems on your system, the easiest way to upgrade to 4.6.1 is to [do a manual update](https://github.com/Typesetter/Typesetter/issues/109#issuecomment-174300705). Don't worry, even if you thought installation was cumbersome, updating manually is a snap.

**Comment by PeterS1** [comment]
Thanks oyejorge for your answer. You think I should install like this way (http://www.gpeasy.com/Docs/Installation), by uploading all new files manually?

**Comment by oyejorge** [comment]
Oops, I submitted the wrong url didn't I. Here's the one I meant: http://www.typesettercms.com/Docs/Upgrading

**Comment by PeterS1** [comment]
Thank you !! I will test it tomorror :)

**Comment by PeterS1** [comment]
Thanks, it works :)

**Comment by oyejorge** [comment]
Awesome!
