### ISSUE TITLE
Area Markup & Class

### ISSUE THREAD

**Issue by thomasfrobieter** [Typesetter/Typesetter#111]
Hey there,

i try to build a theme (with **version 5.0b2**) and i make extensive use of the area functionality, so the logged in users can change the text (only the text, not the entire markup) of an area.

This works great, but i have two problems with the output coming from Output.php, Line 485:

```
echo '<div class="'.$class.' GPAREA">';
self::ExecArea($info);
echo '</div>';
```

1. I got this unwanted div surrounding the area (this may should be optional using the gpOutput::Area function inside the template?)
2. The generated class is something like "gpArea_[text]section_2_title_Title Section 2 GPAREA", while the technical section name is "section_2_title" and the content is "Title Section 2". So this seems like a bug?

In my opinion the perfect class would be something like "section-2-title GPAREA", i don´t think we need the content as class also?

**Comment by oyejorge** [comment]
> I got this unwanted div surrounding the area

Not sure we can do anything about that because of how the edit interface works

> The generated class is something like "gpArea_[text]section_2_title_Title Section 2 GPAREA",

Hmm, I'm not seeing that. I do have these:
* &lt;div class="GPAREA filetype-text"&gt; 
* &lt;div class="GPAREA gpArea_Extra_Side_Menu"&gt;

**Comment by thomasfrobieter** [comment]
Ok, got it, thx :) I have to live with it.

To clarify this .. it´s a onepage theme, so i don´t need pages. As a result, i don´t have the regular navigation available. So i build this custom anchor menu directly inside the template.php. So i got this <div> inside the <ul><li>...-Structure, which destroys my css selectors e.g. ul > li > a. .. so i just alter my CSS - everything is fine.

Any idea why i got this destroyed classes? I defined the Areas like this:

On the top of the template.php:
`<?php gpOutput::Area('section_2_title','<h2 class="full-width-section__title">%s</h2>'); ?>`

Inside the layout:
`<?php gpOutput::GetArea('section_2_title','Titel Section 2'); ?>`

Class result: "gpArea_[text]section_2_title_Titel Section 2 GPAREA

**Comment by oyejorge** [comment]
Ok, I just plugged in the gpOutput::Area() & GetArea() calls you have. Sure enough, it generated some pretty ugly classes. I just fixed it so it will be the following instead:

> &lt;div class="gpArea_section_2_title"&gt;
