### ISSUE TITLE
File include in 5.0 Release Candidate 1

### ISSUE THREAD

**Issue by a2exfr** [Typesetter/Typesetter#113]
File include  section( in 5.0 Release Candidate 1) when editing, appears with already opened autocomplete list, so it's impossible to insert gadget  because input field is closed by autocompete list.

**Comment by oyejorge** [comment]
I don't understand the problem

> appears with already opened autocomplete list

I follow you here

> so it's impossible to insert gadget because input field is closed by autocompete list.

but I'm a little lost here. The gadgets are shown in the already opened autocomplete list and you should be able to just select them.

Yes, if you type something into the input field at the top, it will filter the list, but only according to what you've typed.

**Comment by juek** [comment]
If I may join in: 
@a2exfr: The list now contains Gadgets and Pages as well, there is nothing covered.

**Comment by a2exfr** [comment]
Sorry guys it was a quick look at new release.
I didn't noticed that list contains gadget as well, and used to be two input field there.
