### ISSUE TITLE
HTML validation: Image Sections require alt attribute

### ISSUE THREAD

**Issue by juek** [Typesetter/Typesetter#120]
W3C validator criticizes missing alt attribute in Image Sections. Maybe add an input field to the editor and if value is empty create sth. like 
$langmessage('Image') . ': ' . pathinfo( $image_src , PATHINFO_FILENAME )

**Comment by thomasfrobieter** [comment]
I agree, we need an alt + title field inside this dialog:

![typesetter_missing_alt_field](https://cloud.githubusercontent.com/assets/4060313/15919971/a0d4bb84-2e16-11e6-8a6e-7e7132041373.PNG)

**Comment by juek** [comment]
Oops, quite possible that I pushed an unfinished attempt by accident.

**Comment by juek** [comment]
Would you take it on?

**Comment by mahotilo** [comment]
Little problem in image_edit.js need some time.

**Comment by mahotilo** [comment]
Pulled a requests "Img alt"

**Comment by mahotilo** [comment]
By the way (as always:) 

If look attentively at the console one may see errors in image_edit.js during editing new inserted image section. (In the current beta and with my addings)

For example.

function SaveData(){

			save_obj.posx		= field_x.value; <---
Uncaught TypeError: Cannot read property 'value' of null

I can't find way to fix it.
