### ISSUE TITLE
ver. 5 Buildin gallery

### ISSUE THREAD

**Issue by a2exfr** [Typesetter/Typesetter#122]
This issue only for editing gallery section on page.

**1. Could not create new folder**

request
> _1456129031867
> cmd	new_dir
> dir	/image
> gpreq	json
> gpx_content	gpabox
> jsoncallback	jQuery111308504785251159114_1456129031860

respond

> jQuery111308504785251159114_1456129031860([{DO:"admin_box_data",SELECTOR:"",CONTENT:""}]);

But no dialog window appears.

**2.  when I create new  folder on /Admin/Uploaded  page(_uploaded\image\test)  and try to upload in this folder _ from gallery editing dialog _, uploaded images go into "_uploaded\  " not into _uploaded\image\test**

 /Admin/Uploaded   page work perfect.

**Comment by oyejorge** [comment]
Forgot to tag this issue in the commit with the fix. [Here it is](https://github.com/Typesetter/Typesetter/commit/a56cc0827f2b22dad1590e7590b7e44c1d0b037e)

Thanks!

**Comment by a2exfr** [comment]
New folder is created, but files still upoaded in "_uploaded\ " not into _uploaded\image\test
vers.5 cr3

**Comment by oyejorge** [comment]
Hmm, it seems to be working correctly on my server. Is that on a Windows server by chance?

**Comment by a2exfr** [comment]
Actually yes. local windows server
