### ISSUE TITLE
Problem when Installing

### ISSUE THREAD

**Issue by Jelenadria** [Typesetter/Typesetter#137]
Fatal error: Call to undefined function gp\hash() in /storage/sdcard0/htdocs/Typesetter/include/tool.php on line 1714
Lighttpd with php 5.9.9

**Comment by JPustkuchen** [comment]
Please re-download and try again. This is a source error, the function can not be found. PHP 5.9.9 is really untypical, better switch to a more commom PHP version? See http://php.net/downloads.php
