### ISSUE TITLE
Cant select .SVG images inside the image file browser

### ISSUE THREAD

**Issue by thomasfrobieter** [Typesetter/Typesetter#138]
I tried to replace an existing image with an svg image. The upload works, i see the .svg file inside the folder via FTP.
But i can´t see it in the Typesetter file browser. Seems that .svg is not declared as a supported image extension, can we change this?

Thank you :)

**Comment by juek** [comment]
Works here. No thumbnail generation but selecting and inserting into the content works. 
Wild guess: Does your webserver send the correct mime type?
Try adding 

```
AddType image/svg+xml svg svgz
AddEncoding gzip svgz
```
to the .htaccess file in the typesetter installation directory

**Comment by thomasfrobieter** [comment]
Ok, thank you. Using Firefox too, so this is not the reason.

But i think its a misunderstanding, inserting SVG via WYSIWYG is work great, as you said, except the thumbnail, but that´s fine.
But insert an SVG via "Page" (or via template : gpOutput::GetImage) as an image object still fails.
![typesetter_logo_svg_file](https://cloud.githubusercontent.com/assets/4060313/15919849/7a308dc4-2e15-11e6-94b6-8f84f0017a3e.PNG)

It is uploaded, but not visible inside this "small filebrowser" at the right side. I can click at the 100% logo.svg message, but the existing image will not replaced by the svg.

**Comment by juek** [comment]
I see, well since there are no thumbs generated for SVGs, nothing will show up here (PHP/gd still cannot convert SVG to raster). But maybe we could A) generate a placeholder thumb or B) use a copy of the SVG as thumb, and maybe add the square clipping and resizing using PHPs XML functions.

**Comment by juek** [comment]
Fixed with [this commit](https://github.com/Typesetter/Typesetter/commit/228da6db2ebda2ae0d680c0e46ce997a30ce572c)

![svg-thumbs-for-galleries](https://cloud.githubusercontent.com/assets/704283/25552122/f033ce84-2c91-11e7-95d0-14660bfc87c4.PNG)

**Comment by juek** [comment]
... but we will need a fix for Colorbox on IE. 
IE (and probably Edge too - I have yet to test) cannot read the correct size of SVGs, so the Colorbox is 0 x 0 in size.

**Comment by juek** [comment]
> IE (and probably Edge too - I have yet to test) cannot read the correct size of SVGs...

sort of [fixed](https://github.com/Typesetter/Typesetter/commit/96df9922c291c04917de7e6796aaff484b3f84c5)

**Comment by juek** [comment]
Please do some additional testing on occasion. SVGs may come in different flavors, depending on generator/source.
Issue can be closed IMO.

**Comment by thomasfrobieter** [comment]
Hey,

just tested, work's fine, i can see the preview image and add an image via CK 👍 
The only problem i found is adding an image section. You can choose and add it, but you can't save:
"Oops, that didn't work, please try again. (Couldn't create image [1])"

**Comment by juek** [comment]
> The only problem i found is adding an image section...

True. I only implemented the thumbnail creation for now. 
Rectangular cropping for SVGs should work similar. IMO the image section itself needs an overhaul to be useful in a responsive context. I fear this will need a bit more time.

The problem with SVG cropping via DOMDocument is that we can only set a new viewBox and display dimensions. This means the vector data (shapes) remain untouched and the SVG will have the same file size after cropping. This also applies to the current thumbnail solution.
