### ISSUE TITLE
Installing Plugins for Development

### ISSUE THREAD

**Issue by jozefkrz** [Typesetter/Typesetter#141]
Hi,
I'm developing my addon for Typesseter, and try to instal this addon in "developer mode" - feature described on doc page (http://www.typesettercms.com/Docs/Plugins/Development).

After placing addon code in /addons/-plugin- there is no "Develop", only "Install" option on Available Addons page. 
Is this feature ("developer mode") still supported/available?

Regards,
Krzysztof

**Comment by a2exfr** [comment]
Hi. That is right. Only install.
Just install and change your code in addon folder.
Somethimes you will be  need to press update to your plugin. (when adding new action or hook/filters)

**Comment by jozefkrz** [comment]
Install and Update (when needed) works fine.
Documentation mislead me a little.

**Comment by thomasfrobieter** [comment]
Sehr geehrte Damen und Herren,

vom 11.07 bis zum einschl. 15.07 bin ich nicht im Büro zu erreichen.

Da ich meine E-Mails nur unregelmäßig abrufen kann, wenden Sie sich in dringenden Fällen bitte an Herrn Julian Pustkuchen (E-Mail: jp@webks.de - Tel.: 0571 39815860).

Ich beantworte Ihre E-Mails umgehend nach meiner Rückkehr.

Vielen Dank für Ihr Verständnis.


Mit freundlichen Grüßen
Thomas Frobieter
