### ISSUE TITLE
Multiple XSS vulnerabilities in Typesetter

### ISSUE THREAD

**Issue by robert81** [Typesetter/Typesetter#143]
Hello we identified mutliple XSS vulnerabilities in Typesetter. Can you please give us an email address where we can report the issues? Thank you.

**Comment by juek** [comment]
If they're in the CMS core or one of the the plugins listed on
https://github.com/Typesetter/ please write to Josh S. <oyejorge@gmail.com>

Josh wasn't very responsive in the past weeks. I hope he will reply
soon. Unfortunately I only have the mentioned e-mail address.

Thanks for your effort.


Jürgen Krausz, Grafik Krausz
Design | Crossmedia | VFX
e-mail jk@grafiKrausz.at | www.grafiKrausz.at

Am 02.08.2016 um 18:34 schrieb Robert Abela:

**Comment by robert81** [comment]
Thank you @juek. Will Contact Josh.
