### ISSUE TITLE
Translation for admin texts (Plugin) (Typesetter 5)

### ISSUE THREAD

**Issue by JPustkuchen** [Typesetter/Typesetter#144]
Hi,

thank you very much for this great project. I'm searching for a documentation on how to make texts on plugin admin pages translatable, but could not find any documentation or matching function for that yet.

Can someone help?

**Comment by thomasfrobieter** [comment]
Please take a look at: https://www.typesettercms.com/Forum?show=t1815

**Comment by juek** [comment]
There is no standard for it (yet) and only a few plugins have i8n built in. If I implement multiple languages, I adopt the $langmessage (PHP array) and gplang (JS object) style Typesetter CMS uses internally.

You can get the selected UI language like this in PHP:

```
global $config;
msg("lang = " . $config['language']);
```
