### ISSUE TITLE
Feature request: Server-side login delay on wrong password

### ISSUE THREAD

**Issue by JPustkuchen** [Typesetter/Typesetter#146]
Hi there,

a basic security feature we know from other systems would be an ip-based server-side delay for the admin login form on failed login attempts.

See:
http://security.stackexchange.com/questions/94432/should-i-implement-incorrect-password-delay-in-a-website-or-a-webservice

**Comment by juek** [comment]
There is already a 10 minute block after 5 failed login attempts built in. It is not IP but user based. Admittedly, an attacker can guess user names this way (whereof he won't find too many on a typesetter setup). But the 10 minutes will give him a hard time to brute-force the password.

**Comment by JPustkuchen** [comment]
Thank you, I did not know that. So I think this issue can be closed :) :+1:
