### ISSUE TITLE
Timing conflict between autosave and Publish Draft

### ISSUE THREAD

**Issue by juek** [Typesetter/Typesetter#147]
Sometimes clicking Publish Draft when autosave is executed simultaneously, it will cause an error -> "not a draft!" and the current edit is lost.

IMO the best way was to cancel autosave when hitting Publish Draft and re-enabling it in the callback.

**Comment by florincatalin** [comment]
This error can also occur due to a server delay ? Sometimes after a "not a draft!" error the content of the page disappears entirely and the only possibility to recover is a return to a previous save (and lost curent edit). Can adjust the automatic saving time could be a solution in this case?

**Comment by juek** [comment]
> due to a server delay?

Yes, IMO it's because there are two **asynchronous requests** sent within a short time-frame, and both process page data. While "Publish Draft" converts the stored draft into the current page, the autosave request wants to store the current edit into the draft, which doesn't exist anymore at this time. 

Adjusting the autosave interval wouldn't fix the problem. We should implement some mutual block to prevent parallel execution.

**Comment by florincatalin** [comment]
You are right; maybe this can help?
http://caolan.github.io/async/docs.html#parallel

**Comment by juek** [comment]
> You are right; maybe this can help?
> http://caolan.github.io/async/docs.html#parallel

I'd guess we actually don't need a thirdparty lib here. Unfortunately, AJAX is not exactly my core competence but I will try to find a fix. Josh certainly could do better ;-) Josh?

**Comment by florincatalin** [comment]
> but I will try to find a fix

I found something, is not a solution, just a temporary improvisation, which is sometimes effective:
change `5E3 ` with `3E5`. I think it can be done also by setting true or false for `CanAutoSave`. Also, don't forget to save. The problem with simultaneous asynchronous requests still remain.

**Comment by juek** [comment]
A really cheap trick, but seems to work:

/include/js/inline_edit.js:

replace line 143

`gp_editing.is_dirty || gp_editing.IsDirty() ? $("#ckeditor_wrap").addClass("not_saved") : $("#ckeditor_wrap").removeClass("not_saved");`

with 

```
if( gp_editing.is_dirty || gp_editing.IsDirty() ){
  $('#ckeditor_wrap').addClass('not_saved');
    $("a.msg_publish_draft").hide();
  }else{ 
    $('#ckeditor_wrap').removeClass('not_saved');
    $("a.msg_publish_draft").show();
  }
},
```

(If you're using the unminified version from here, its lines 482 - 486)

**Comment by florincatalin** [comment]
> replace line 143
> 
> `gp_editing.is_dirty || gp_editing.IsDirty() ? $("#ckeditor_wrap").addClass("not_saved") : $("#ckeditor_wrap").removeClass("not_saved");`
> 
> with
> 
> ```
> if(gp_editing.is_dirty || gp_editing.IsDirty() ){
>   $('#ckeditor_wrap').addClass('not_saved');
>   $("a.msg_publish_draft").hide();
> }else{ 
>   $('#ckeditor_wrap').removeClass('not_saved');
>   $("a.msg_publish_draft").show();
> }
> ```


A cheap trick, but effective! Tested and checked. Thank you, Juek!

**Comment by juek** [comment]
While simply hiding the Publish button until everything is saved is not exactly brilliant from the UX perspective, it prevents the wole "not a draft" issue very effectilvely. Initially, I wanted to intercept $gp.links.PublishDraft, check for the save status (gp_editor.checkDirty) and - in case of unsaved changes - execute SaveData with PublishDraft in the callback. but the window.onbeforeunload event came in my way. Changing the event handlers should be possible, but hiding/showing the Publish Draft button was tempting for it's simplicity. I hope sth. better will emerge over time.
