### ISSUE TITLE
Updating

### ISSUE THREAD

**Issue by angerangel** [Typesetter/Typesetter#151]
I try to update with the online tool and I get:
**DECOMPRESSING AND SUBSTITUING:**
`Fatal error: Uncaught exception 'UnexpectedValueException' with message 'Cannot create phar '', file extension (or combination) not recognised or the directory does not exist' in /web/htdocs/www.rometec.it/home/gpEasy/include/tool/Archive.php:60 Stack trace: #0 /web/htdocs/www.rometec.it/home/gpEasy/include/tool/Archive.php(60): PharData->__construct('') #1 /web/htdocs/www.rometec.it/home/gpEasy/include/tool/Archive.php(34): gp\tool\Archive->InitTar() #2 /web/htdocs/www.rometec.it/home/gpEasy/include/tool/update.php(735): gp\tool\Archive->__construct(NULL) #3 /web/htdocs/www.rometec.it/home/gpEasy/include/tool/update.php(659): update_class->UnpackAndSort(NULL) #4 /web/htdocs/www.rometec.it/home/gpEasy/include/tool/update.php(475): update_class->UnpackAndReplace() #5 /web/htdocs/www.rometec.it/home/gpEasy/include/tool/update.php(107): update_class->Update() #6 /web/htdocs/www.rometec.it/home/gpEasy/include/tool/update.php(83): update_class->Run() #7 /web/htdocs/www.rometec.it/home/gpEasy/include/install/update.php(22): upd in /web/htdocs/www.rometec.it/home/gpEasy/include/tool/Archive.php on line 60`

What caused this error?

**Comment by geromueller** [comment]
See here: http://stackoverflow.com/a/16725770
Happens on 5.4.45 (Debian oldstable)
