### ISSUE TITLE
Current menu id inside MenuPageOptions filter

### ISSUE THREAD

**Issue by a2exfr** [Typesetter/Typesetter#156]
Is there a way to get **current menu id** inside **MenuPageOptions filter**?
I'm getting it through js, and append to my command link, but I'm not fond of this solution.

```
check();

$("div#gp_admin_html")[0].addEventListener("DOMNodeInserted", check);
$("div#gp_admin_html")[0].addEventListener("DOMNodeRemoved", check);

function check(){
	if($('a.pb_menu').attr('href').split('=').pop()==""){
		var menu_id = $('#admin_menu_tools').find("[href*='menu=']").attr('href').split('=').pop();
		var url = $('a.pb_menu').attr('href');
		$('a.pb_menu').attr('href', url + menu_id);
	}
	
}
```

**Comment by juek** [comment]
Hi Alex, 

you should be able to get this info from either …
$_COOKIE['gp_menu_prefs'], see 

> https://github.com/Typesetter/Typesetter/blob/5966a684550a4565517ef27865c58b398b4ae42c/include/admin/Menu.php#L69

or
 
$_REQUEST['menu'] if the menu display in page manager was just changed using the dropdown

**Comment by a2exfr** [comment]
Hi Juergen,
nice I didn't find $_COOKIE['gp_menu_prefs']
I check another $_COOKIE but gp_menu_prefs I miss somehow. thats comes in that funny js.

**Comment by a2exfr** [comment]
But cookie is erased after admin box stated and submitted, so may be, this js is not so bad.
