### ISSUE TITLE
Allow "Extra" content blocks as include

### ISSUE THREAD

**Issue by thomasfrobieter** [Typesetter/Typesetter#157]
Hey Guy´s,

is it possible to allow /Admin/Extra snippets to be included via GPAREA filetype-include?

So we have reusable snipptes for eg. contact data or something .. without creating a whole page to get this available inside the include select.

With kind regards

**Comment by juek** [comment]
Works now with [this commit](https://github.com/Typesetter/Typesetter/commit/d2f044e8e3f2bd406ca22db4b6de3544d8cc08c8).
