### ISSUE TITLE
Directories created by Typesetter lose setgid

### ISSUE THREAD

**Issue by diamond-msc** [Typesetter/Typesetter#160]
My ISP uses a permission setup like this:

`drwxr-s---  6 username apache    4096 Dec 18 15:54 Typesetter`

After finishing the Typesetter setup dialog, directories added by Typesetter don't have the `apache` group, and the `s` bit is missing. Files written into these directories inherit the wrong ownership.

This caused an installed theme to show an empty screenshot in the theme list. The browser was not allowed to read the screenshot image.

The reason is in this line:
https://github.com/Typesetter/Typesetter/blame/master/include/tool/Files.php#L899
My tests identified that `setgid` is lost due to the `chmod` after `mkdir` (see http://unix.stackexchange.com/a/23967)

After commenting out this line, I could successfully install Typesetter. The screenshot of an added theme is now visible.

I just started working with Typesetter, so I'm not sure if there are other unwanted consequences of the wrong permission setting.

**Comment by juek** [comment]
Unfortunately I'm not an expert in this field, but may this info will help:

You can change the gp_chmod_dir and gp_chmod_file constants by editing /gpconfig.php

**Comment by juek** [comment]
> ...so I'm not sure if there are other unwanted consequences of the wrong permission setting.

I'd guess as long as the files generated by Typesetter can be served, written and executed, commenting the line in Files.php is fine. It only will get overwritten when you update the CMS so you will have to comment it again afterwards.

**Comment by diamond-msc** [comment]
Thanks. Closing.
