### ISSUE TITLE
Update phpMailer > Critical issue!

### ISSUE THREAD

**Issue by thomasfrobieter** [Typesetter/Typesetter#161]
https://threatpost.com/phpmailer-bug-leaves-millions-of-websites-open-to-attack/122775/

(German: https://www.heise.de/newsticker/meldung/Luecke-in-PHPMailer-erlaubt-die-Ausfuehrung-fremden-Codes-3582072.html)

~~Please update to the current version of phpMailer https://github.com/PHPMailer/PHPMailer~~
Created a pull request: https://github.com/Typesetter/Typesetter/pull/162

**Comment by thomasfrobieter** [comment]
**Quickfix:**

1. Download current release of PHPMailer: https://github.com/PHPMailer/PHPMailer
2. Override just the four files inside /include/thirdparty/PHPMailer (class.phpmailer.php, class.pop3.php, class.smtp.php, PHPMailerAutoload.php)
3. You're done.

**Comment by juek** [comment]
Thx Thomas! Hopefully 5.2.20/21 is now really fixed. Should be posted to the TS forum as well.

**Comment by thomasfrobieter** [comment]
Sehr geehrte Damen und Herren,

vom 29.12.16 bis zum einschl. 01.01.2017 bin ich nicht im Büro zu erreichen.
Ich beantworte Ihre E-Mails umgehend nach meiner Rückkehr.

In dringenden Fällen senden Sie bitte eine E-Mail an ticket [AT] webks.de

Vielen Dank für Ihr Verständnis.


Mit freundlichen Grüßen
Thomas Frobieter

**Comment by juek** [comment]
Just merged, I better keep the issue open unless new version (5.0.4) is out.
