### ISSUE TITLE
Allow Special_Links to have no label (hide them as callbacks)

### ISSUE THREAD

**Issue by JPustkuchen** [Typesetter/Typesetter#163]
Hi all,

Special links are currently defined as follows in Addon.ini:
http://www.typesettercms.com/Docs/Addon.ini

_; Register callback handler for JS:
[Special_Link:ContactformSectionSendHandler]
label = 'Callback Handler'
script = 'ContactformSectionSendHandler.php'_

"label" is required currently. Leaving it empty (empty string) removes the handler completely.
But what we sometimes need is a callback URL for JavaScripts. These Callbacks shell not appear in the Admin UI but the URL has to work like for special links with a full bootstrap to have all Typesetter variables available.

Is it possible to make label optional for this callback case?
Otherwise we'd have to introduce a new hook for callbacks I think?

**Comment by a2exfr** [comment]
I see possible solutions here:

-hide label in admin menu with js something like this
```
$(document).ready( function() {
  $("body.gpAdmin a[title='Callback Handler'])
    .closest("ul").hide()
    .closest("li").removeClass("expand_child");
});
```
but this page still will be visible in file include;


- use PageRunScript and **use as handler, same page**  where script runs.
   example of PageRunScript using you can find [here ](http://www.typesettercms.com/Forum?show=t1989#post_8361)
In this case you wil have all TS vars and can perform any actions with page content.


- also you can try unset this page like this in GetHead hook.  We use this way to hide finder connector link in plugin, so if in your case this may be do not help, but still...
 
```
static function GetHead() {
    global $page, $addonRelativeCode;

     global $gp_titles, $gp_index;
      if( isset($gp_titles['special_ContactformSectionSendHandler']) ){
        unset(
          $gp_titles['special_ContactformSectionSendHandler'],
         $gp_index['special_ContactformSectionSendHandler'],
          );
        \gp\admin\Tools::SavePagesPHP();
      }
    }
  } 
```

**Comment by JPustkuchen** [comment]
Thank you for your quick reply, Alex!
These are all good workarounds and will of course help when we need a quickfix.

Anyway I think this is a relevant feature request for typesetter core. Is typesetter core no more maintained? Can we label this as feature request?

**Comment by a2exfr** [comment]
> Is typesetter core no more maintained? 

do not know anything about that, sadly but Josh is away for sometime ...

As I see from Special_Link:ContactformSectionSendHandler you develop some contact form with ajax submit ? In this case PageRunScript will be good solution.

And one more way:
 If it special page you can use some mycontactform_specialpage/success   mycontactform_specialpage/error   or  mycontactform_specialpage/handler   pages but do not declare them in addon.ini    Then  we parse url in plugin and echo depending content.

**Comment by JPustkuchen** [comment]
Thank you very much for your detailed reply! We'll have a look at these 
possibilities :)

**Comment by juek** [comment]
Hi all, 
yep, the PageRunScript hook is exactly the right route to go here. But I agree – a Special Page hidden to admins for pure backend processing would be nice to have in some cases. 

@a2exfr: you certainly remember our finder_BE discussion ;-)
