### ISSUE TITLE
Change or add option to generate URLs lowercase

### ISSUE THREAD

**Issue by JPustkuchen** [Typesetter/Typesetter#166]
URLs are typically generated in lowercase. It would be nice to have that by default and if required, add an option in the settings for this conversion.

**Comment by juek** [comment]
There is a filter hook [PostedSlug](https://github.com/Typesetter/Typesetter/blob/5966a684550a4565517ef27865c58b398b4ae42c/include/admin/Tools.php#L1140).

I never used it but it seems to be appropriate.
