### ISSUE TITLE
Maintainers / contributors > FUTURE PLAN?

### ISSUE THREAD

**Issue by JPustkuchen** [Typesetter/Typesetter#167]
Hi all,

since the maintainer of typesetter seems to be completely absent and doesn't seem to work on this project anymore it would make sense to create a plan how to proceed with this project in community.

The project is just too cool to let it die. I'd be happy to hear about the original maintainer and creator of Typesetter and his opinion. But if not (or generally) we should make a plan, shouldn't we?

Are there community / contributor plans for creating new releases of typesetter?
Is somesone still in contact with the maintainer?
How can we proceed best technically? Create an OFFICIAL fork with all active maintainers?
Shell we keep this repository and add new maintainers to make this more "community"? ;) (does someone have access?)
Should the contributors and their responsibility for issues, merging etc. be listed on the repository page?

Further questions to be answered? 👍 

Feedback please :)

**Comment by juek** [comment]
Hi Julian,

> The project is just too cool to let it die.

Definitely!

> Are there community / contributor plans for creating new releases of typesetter?

In fact we should get a 5.0.4 version out, only because PHPmailer.

> Is somesone still in contact with the maintainer?

Josh gave me maintainer role for the GitHub repo some 3 weeks ago but I haven't heard from him since. To make a release in typesettercms.com we will need him.
