### ISSUE TITLE
Unconventional Port

### ISSUE THREAD

**Issue by mahotilo** [Typesetter/Typesetter#174]
I have test local site like http://www.test:8080/
All work fine, but when I change a page layout via
Top menu - > Options -> Current Layout
TS changes current address from http://www.test:8080 to http://www.test.
On other admin pages TS respect my port

**Comment by juek** [comment]
Does your local webserver actually resolve this domain name "www.test" or do you only redirect to it's IP via hosts?

**Comment by mahotilo** [comment]
Only hosts

**Comment by juek** [comment]
Does it work if you use the IP:8080 ?

**Comment by mahotilo** [comment]
No, 
on 127.0.0.1:8080 same situation

**Comment by thomasfrobieter** [comment]
Take a look at this: https://stackoverflow.com/a/21586034/6266306

**Comment by mahotilo** [comment]
Thx again!
I'll try it.
I wanted only to draw your attention that 
`Top menu - > Options -> Current Layout`
open http://www.test
But
`Appearance -> Layouts`
or
`Content -> Page Manager ->Layout`
taking me through a series of pages to http://www.test:8080

Maybe it's due method of URL generating for this item in top menu?
Other top menu items work fine with my port.

**Comment by mahotilo** [comment]
By the way, host file and fake http://www.test I need only to fool reCapture. 
Google doesn't permit addresses like 127.0.0.1 but happy enough with www.test. 
sh! :)

**Comment by juek** [comment]
Fixed with [this commit](https://github.com/Typesetter/Typesetter/commit/d54e37ab98016c9f40e153c47685be6e73bee0f0).

Although I tested most TS functionality with it I hope it won't break anything. 
The ServerName() function will be used in various conditions.

Please report any issues that seem to be related.

**Comment by juek** [comment]
Needed additional fixes, use with [this commit](https://github.com/Typesetter/Typesetter/commit/f544a5972be3462d5f7980331130d50b25fa62dc)

**Comment by mahotilo** [comment]
I can confirm, that all is ok for me now. See no problem.

**Comment by thomasfrobieter** [comment]
It seems now we have a problem (worked in the past) - If i switch the layout, an "80" is added to the URL, eg. http://example.com will become http://example.com80

**Comment by juek** [comment]
> It seems now we have a problem...

Yep, should be [fixed now](https://github.com/Typesetter/Typesetter/commit/57df799caa03f91b906b503df838b43bdb95a99f).
