### ISSUE TITLE
Update Backend logo GPEASY > Typesetter

### ISSUE THREAD

**Issue by thomasfrobieter** [Typesetter/Typesetter#175]
This is not quit important, but it's a little confusing to customers. We always talk about "Typesetter" and the Backend still shows the "GPEASY" Logo.

The only Typesetter Logo i found is here on Github: https://avatars0.githubusercontent.com/u/16497604?v=3&s=200

The logo is OKAY to me. It's also fine to create something new. But i don't know if its a good idea doing this without Josh.

What do you guys think?

**Comment by juek** [comment]
The backend doesn't show any logos normally. 

I'd guess you are using [Flat Admin 2015](https://www.typesettercms.com/Plugins/279_FlatAdmin_2015) 
This (GP|EASY) logo' is buried in the plugin's CSS using pseudo content.

**Comment by thomasfrobieter** [comment]
Oh man *facepalm*. You are RIGHT! :D Thank you declaring this!

**Comment by juek** [comment]
;) You really shouldn't use it anymore. It was solely made for gpEeasy 4.3 to 4.5

**Comment by thomasfrobieter** [comment]
Yeah, just noticed the hint on the plugin page. But i didn't experienced any issues so far and i really like the modifications you did there. I forked it and wil try to remove critical modifications to just get this modern look :)

**Comment by juek** [comment]
But there were some gpEasy leftovers [in the code](https://github.com/Typesetter/Typesetter/commit/092e3c946beaddc4235279bb953f84edf4fd0fae)
