### ISSUE TITLE
Section type include missing "edit [Included content]" link

### ISSUE THREAD

**Issue by thomasfrobieter** [Typesetter/Typesetter#177]
If we add an include section regulary via section manager, some very helpfull extra links appear inside the section context menu, like a link to the included content (it's a page include in our case).

But if we create an extra content (type include), add this via layout, etc. we dont get those helpful links :(

Just searched through the Sections.php but i can't figure it out..

**To be clear:**
1. Create a simple page with some content
2. Go to content -> extra content
3. Create a new extra with type "File Include"
4. Go back to your page, edit the layout and add the new created extra content to your layout. Save & close.
5. Edit the include and choose the page created in step 1

**Comment by juek** [comment]
Good point. Should be fixed with [this commit](https://github.com/Typesetter/Typesetter/commit/574115a187d8f67d9678460a4079d148a3d6d455)

**Comment by thomasfrobieter** [comment]
Yeah, great :) working! Thank you so much!
