### ISSUE TITLE
install bug when not in root folder

### ISSUE THREAD

**Issue by freedomlives** [Typesetter/Typesetter#182]
If trying to install with TS in a subfolder (e.g. example.com/typesetter/ ), after running the checks, putting in username/password info, and clicking "install", the error message "File not found" comes up.

Honestly, I didn't dig any deeper, and just moved everything to the root folder, like I'm sure 99.99% of TS installations are done.  But just to for-warn, that this a problem, as I'm sure there is some 0.01% use case where TS is in a subfolder of the site. One potential use case being to test new versions without setting up a new VHOST. :-D

**Comment by juek** [comment]
Although not recommended, it should work nomally. Have to check if sth. is screwed up in the current version.

**Comment by juek** [comment]
Do you have a .htaccess file in the Document Root? Could be the cause.

**Comment by freedomlives** [comment]
I am using NGINX as the webserver, so its config could be the cause too.  If it works for you, it is probably that.

**Comment by thomasfrobieter** [comment]
Just tried http://example.de/typesetter_temp/ on our NGINX based webserver, everything is working!

**Comment by freedomlives** [comment]
@thomasfrobieter you must have a better nginx config than I have!

**Comment by thomasfrobieter** [comment]
It's just a managed server, so i do not deserve credit for that ;D
