### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by mahotilo** [Typesetter/Typesetter#185]
1. We don't have strings for localization of Manage Classes settings

2. I suddenly realized that we have
"Settings", "Configuration" and "Preferences"
Synonymous richness of language... 
It is hard to understand what is difference and give correct translation.

May be update it?
Settings -> Settings
Configuration -> General Settings
Preferences -> User Permissions

**Comment by juek** [comment]
I agree in that all three terms have quite a similar meaning - also in german.

> Preferences -> User Permissions

It's not only about permissions (which can also be found via Settings -> User Permissions) but more about personal user settings. Therefore I consider 'Preferences' to be the correct term.

I'd keep the english terms for all the existing mentions in the forum, which might become misleading then. 
For other languages/translations, nothing speaks against more precise wording.

**Comment by juek** [comment]
Oh, and ...

> We don't have strings for localization of Manage Classes settings

True. From a german speaker's perspective, I wouldn't actually try to translate it because we solely deal with CSS casses, which is a technical term and nobody ususally says 'Klasse' here, just as no one would say 'Kennung' to 'ID' . But that might be different in other languages (certainly in french where anything gets translated). 

I'll add it to the next commits.

**Comment by mahotilo** [comment]
> From a german speaker's perspective, I wouldn't actually try to translate it because we solely deal with CSS casses, which is a technical term and nobody usually says 'Klasse' here, just as no one would say 'Kennung' to 'ID' .

Oh, great progress after Datei und Fußball :)
We also use slang words in English but need to write it in Cyrillic :)

> I'll add it to the next commits.

Thx

**Comment by juek** [comment]
Terms for 'Classes' are now in, see [this commit](https://github.com/Typesetter/Typesetter/commit/bd957143c4bd84e119c60f7fefdfb6ec1b854bce)

**Comment by mahotilo** [comment]
Thx
But we have also

> - className(s) 
> - Description (optional)
> - Add Row
> - CSS classNames you set here will be easily selectable in the Section Attributes dialog.
> - Single classNames (like gpRow) will show as checkboxes
> - Multiple, space separated classNames (like gpCol-1 gpCol-2 gpCol-3 […] will show as checkable dropdown list.
> - The list is drag’n’drop sortable.
> - Load the Bootstrap Preset 
> - Load the Default Preset

May we have translation for this lines too? Sometime later, when it will not distract from more important things (if I have correctly understood "Copy to Clipboard" )

**Comment by juek** [comment]
Sure thing. 

if I have correctly understood "Copy to Clipboard"

You have. It's [already in](https://github.com/Typesetter/Typesetter/commit/8edd671be36bd631a77386208013d105fef8a4e1).
