### ISSUE TITLE
No login after installation possible

### ISSUE THREAD

**Issue by nickbe** [Typesetter/Typesetter#186]
Did a fresh install. Domain is localhost. Onyl thing I see is a cookie warning which is nonsense. Cookies are enabled.

**Comment by juek** [comment]
Which platform/server/php versions are you using? 
The cookie is probably not possible to be set server side. Most likely not a browser issue.

**Comment by nickbe** [comment]
Windows, PHP 5.6.30
Never had a problem like this before.

Beste Grüße | Best regards
Nicolaus Berglmeir

Creative Consulting | CEO Allgäu Informatik

Lindauer Str. 4, 87439 Kempten, Germany
+49 831 20699 877 • mail@berglmeir.com
HRB 1363 Kempten • DE281261678

Am 15. Juli 2017, 20:17 +0200 schrieb Juergen <notifications@github.com>:

**Comment by juek** [comment]
I can't reproduce the issue here on Windows but I don't have a PHP 5.6.3 build.
Are you using Apache or IIS (or even lighttp or nginx)?

**Comment by nickbe** [comment]
I tried apache and also PHP -S 0.0.0.0:80 which usually works as well

**Comment by juek** [comment]
Does [this](https://gist.github.com/art2code/2584441) work?

**Comment by nickbe** [comment]
The resulting output is:

Add Program Script or Includes

Session Cookies: Enabled
Javascript: Enabled
Cookies: Enabled
