### ISSUE TITLE
Ckeditor span

### ISSUE THREAD

**Issue by gtbu** [Typesetter/Typesetter#204]
When i translate text from google-translate(as an example or dict.cc) and paste it into a ckeditor-text then lots of span gets into the source-text which very often cannot be removed by the deformat-knob-plugin
and must then be removed by hand in the sourcecode.

In forums like stackoverflow  i read that an entry like 'config.allowedContent = true;' and in the other direction  CKEDITOR.editorConfig = function( config ) {  config.extraAllowedContent = 'span(*)'; 
can switch this behaviour on and off - my proposal is to expand the menu in 5.1 so that the user can enter some values in a text-window or make a hook into a field.

**Comment by juek** [comment]
Use CK Editor's 'Paste as Plain Text' icon. 2nd row - 4th item.

**Comment by juek** [comment]
I personally always go the paste-into-a-text-editor-and-then-copy-again route, except I want to keep formatting. But 'paste as plain text' does merely the same thing.
