### ISSUE TITLE
Full TLS compatibility.

### ISSUE THREAD

**Issue by scottprovost** [Typesetter/Typesetter#208]
![typesettersucks](https://user-images.githubusercontent.com/591676/29604085-fde49340-87ab-11e7-82f2-0e195f429a72.png)

**Comment by thomasfrobieter** [comment]
Do you have some more details to this? I wonder if this a problem of the CMS, isn't it a problem of the used certificate?

**Comment by scottprovost** [comment]
grep -R "http\:" * | wc
    558    8008  248253
Why would any non https link be used ever?

**Comment by thomasfrobieter** [comment]
Yes, we should replace this with "//". This will inherit the current used protocol.

eg. <script src="//code.jquery.com/jquery-3.2.1.min.js"></script>

**Comment by juek** [comment]
> The problem is unsafe scripts.

Which?

**Comment by thomasfrobieter** [comment]
I also get some results with grep, mostly inside documentation texts or something. Didn't found a http related to (CDN) ressources in the frontend markup (using one of the default themes). 

Did you use a custom theme?

**Comment by scottprovost** [comment]
Yes. The Lock 1.3 theme.

**Comment by scottprovost** [comment]
![typesetterinsecure](https://user-images.githubusercontent.com/591676/29607787-f3746bd6-87b7-11e7-87bc-c43ddb060077.png)

**Comment by thomasfrobieter** [comment]
Okay, yes there are some http ressources, eg. in "1_default/template.php", i recommend you report this issue to a2exfr -> https://www.typesettercms.com/Forum?show=f1288

Or simply replace the http ressources, i don't know if he is still updating this theme..

**Comment by scottprovost** [comment]
GoogleAPIs and gstatic.

**Comment by juek** [comment]
For the time being you can change the protocols by editing both template.php

**Remote installation (from inside Typesetter's admin UI):**
[typesetter installation directory]/data/_themes/[random string]/1_default/template.php
[typesetter installation directory]/data/_themes/[random string]/2_add_sidebar/template.php

**Manual theme installation:**
[typesetter installation directory]/themes/Lock/1_default/template.php
[typesetter installation directory]/themes/Lock/2_add_sidebar/template.php
