### ISSUE TITLE
how to read and write directly users and passwords

### ISSUE THREAD

**Issue by mckaygerhard** [Typesetter/Typesetter#209]
i whant to manage remotelly from the server command line.. how can i read and write users and passwords.. event creating using the typesetter frontend?¡

there's no wiki or documentations about it! read the code without any explanation are nonsense due the lack of time from implementator!

**Comment by juek** [comment]
Look [here](https://github.com/Typesetter/Typesetter/blob/master/include/admin/Settings/Users.php#L238)

**Comment by juek** [comment]
But don't expect plain text passwords.

**Comment by mckaygerhard** [comment]
ok ok thanks... i can see the USer.php so my intention its write new passowrd using command line.. not recue password or hacking..

i have typesetter lasted and also gpeasy 4, in gpeasy i noted are quite different, but i can track the changes property, can ilustrate me the main differences and process?

**Comment by juek** [comment]
Typesetter (5+) running on PHP 5.5+ will use the more secure [password_hash](https://secure.php.net/manual/de/function.password-hash.php) function to encrypt passwords stored server-side. This can be changed back to the previously used sha512 algorithm in user preferences. 

To manage users via console you will have to replicate Typesetter's functions in shell scripts. But I fear  you will not have anything like PHP's password_hash algorithm available in bash, so you will most likely end up executing PHP scripts.
