### ISSUE TITLE
Lost favicon on admin pages

### ISSUE THREAD

**Issue by mahotilo** [Typesetter/Typesetter#216]
Not a big problem, but...

When I look at the console on Admin/Configuration page (and on other Admin/ pages too), I see the error
> GET http://www.test/favicon.ico 404 (Not Found)

On non admin pages there is no such error.

**Comment by juek** [comment]
Chrome requests /favicon.ico by default and shows an error if not found (which is a bit overacting in my point of view). In your case I believe the port number is missing in the request. Don't know why this is so but on the other hand - if the favicon shows up when logged off, it's nothing much to worry about IMO.
