### ISSUE TITLE
Fake Updates. Appears to update successfully but continues to report the old version. 

### ISSUE THREAD

**Issue by scottprovost** [Typesetter/Typesetter#220]
Does the update with no errors.
![image](https://user-images.githubusercontent.com/591676/31042971-7b50c994-a579-11e7-9e29-e9aad8039ef5.png)
![image](https://user-images.githubusercontent.com/591676/31042975-9c8fe43c-a579-11e7-8cf6-92607de160c4.png)
![image](https://user-images.githubusercontent.com/591676/31042986-bc137666-a579-11e7-959b-8105c449a2bf.png)
![image](https://user-images.githubusercontent.com/591676/31042990-cbf0ba9e-a579-11e7-99d2-50dfc283b46b.png)
![image](https://user-images.githubusercontent.com/591676/31043000-e5c35a1c-a579-11e7-9aec-6f6debea29ea.png)
![image](https://user-images.githubusercontent.com/591676/31043014-18503914-a57a-11e7-8032-5dcd9cb63600.png)
Then reports old version.

ls reveals old file dates for includes and themes.
oot@www:/var/www/deepsec/setter# ls -la
total 80
drwxr-xr-x  6 www-data www-data  4096 Jul 10 07:39 .
drwxr-xr-x  5 www-data www-data  4096 Jul 10 07:51 ..
-rw-r--r--  1 www-data www-data    80 Jul 10 07:39 Addon.ini
drwxr-xr-x  4 www-data www-data  4096 Jul 10 07:39 addons
drwxr-xr-x 13 www-data www-data  4096 Sep 30 00:31 data
-rw-r--r--  1 www-data www-data   125 Jul 10 07:39 .editorconfig
-rw-r--r--  1 www-data www-data  4173 Jul 10 07:39 gpconfig.php
-rw-r--r--  1 www-data www-data 18092 Jul 10 07:39 gpl.txt
-rw-rw-rw-  1 www-data www-data    99 Jul 10 07:42 .htaccess
drwxr-xr-x 12 www-data www-data  4096 Jul 10 07:39 include
-rw-r--r--  1 www-data www-data   611 Jul 10 07:39 index.php
-rw-r--r--  1 www-data www-data  2287 Jul 10 07:39 README.md
-rw-r--r--  1 www-data www-data    23 Jul 10 07:39 robots.txt
drwxr-xr-x  5 www-data www-data  4096 Jul 10 07:39 themes
-rw-r--r--  1 www-data www-data    72 Jul 10 07:39 web.config
root@www:/var/www/deepsec/setter# 

root@www:/var/www/deepsec/setter# ls -la include/
total 144
drwxr-xr-x 12 www-data www-data  4096 Jul 10 07:39 .
drwxr-xr-x  6 www-data www-data  4096 Jul 10 07:39 ..
drwxr-xr-x  9 www-data www-data  4096 Jul 10 07:39 admin
-rw-r--r--  1 www-data www-data   814 Jul 10 07:39 Base.php
-rw-r--r--  1 www-data www-data 16187 Jul 10 07:39 common.php
drwxr-xr-x  2 www-data www-data  4096 Jul 10 07:39 css
-rw-r--r--  1 www-data www-data  6718 Jul 10 07:39 image.php
drwxr-xr-x  2 www-data www-data  4096 Jul 10 07:39 imgs
drwxr-xr-x  2 www-data www-data  4096 Jul 10 07:39 install
drwxr-xr-x  4 www-data www-data  4096 Jul 10 07:39 js
drwxr-xr-x  2 www-data www-data  4096 Jul 10 07:39 languages
-rw-r--r--  1 www-data www-data   783 Jul 10 07:39 main.php
drwxr-xr-x  2 www-data www-data  4096 Jul 10 07:39 Page
-rw-r--r--  1 www-data www-data  8180 Jul 10 07:39 Page.php
drwxr-xr-x  2 www-data www-data  4096 Jul 10 07:39 special
drwxr-xr-x 17 www-data www-data  4096 Jul 10 07:39 thirdparty
drwxr-xr-x  4 www-data www-data  4096 Jul 10 07:39 tool
-rw-r--r--  1 www-data www-data 53800 Jul 10 07:39 tool.php
root@www:/var/www/deepsec/setter# ls -la themes/
total 24
drwxr-xr-x  5 www-data www-data 4096 Jul 10 07:39 .
drwxr-xr-x  6 www-data www-data 4096 Jul 10 07:39 ..
drwxr-xr-x  8 www-data www-data 4096 Jul 10 07:39 Bootswatch_Flatly
drwxr-xr-x 18 www-data www-data 4096 Jul 10 07:39 Bootswatch_Scss
-rw-r--r--  1 www-data www-data   13 Jul 10 07:39 index.html
drwxr-xr-x  4 www-data www-data 4096 Jul 10 07:39 Three_point_5

**Comment by scottprovost** [comment]
When all is done. Still reporting old version and offering to update.
![image](https://user-images.githubusercontent.com/591676/31043044-ae807782-a57a-11e7-99e8-ace0485a4a40.png)

**Comment by juek** [comment]
The updater code was broken and only fixed after 5.0.3 was released.

Please see [this forum post](https://www.typesettercms.com/Forum?show=t2433) to fix it.
