### ISSUE TITLE
Contact Form (Advanced) error

### ISSUE THREAD

**Issue by bigalgeorge** [Typesetter/Typesetter#221]
I dont know where gpeasy keeps its email logs but always I get the error below as do others seems nobody has been able to sort this issue whereas normal contact form works:
'XSS Verification Parameter Mismatch' earlier versions <5.1 did not have this issue.

**Comment by thomasfrobieter** [comment]
Have you seen this? https://www.typesettercms.com/Forum?show=t1915

**Comment by bigalgeorge** [comment]
Thanks but Ive had to give up on Freemailform advanced after much ado even replicating the above info (appreciate) that did not work either. Im now using Special Contact Form, which even though limited (I cant include date fields) works every time:
[http://thehomenz.co.nz/booking](url)

**Comment by thomasfrobieter** [comment]
Another hint: If you need more advanced forms, see: https://github.com/webksde/Typesetter-Custom-Sections--Contact-Form

But this uses also Typesetters core implementation of phpmailer - so this will probably not solve your problem.
