### ISSUE TITLE
Export doesn't contain custom css

### ISSUE THREAD

**Issue by DarkDau** [Typesetter/Typesetter#222]
In Typesetter 5.1 the export does not contain custom settings in css
I.e 
` .filetype-special_search input.submit { display:none; }
.gpArea_Extra_BC_Header { display:none; }
.nav>li>a {
    padding: 15px; 
}
footer p {
    margin: 0;
    padding: 0px 0;
        padding-top: 5px;
        padding-right: 0px;
        padding-bottom: 5px;
        padding-left: 0px;
}
p {
    font-size: 1.10em;
    line-height: 1.2;
    color: #000;
}`
Defined as proposed in Typesetter/index.php/Admin_Theme_Content/edit/
Theme was Business Casual/1_gcb

**Comment by juek** [comment]
Thanks for spotting. This [commit](https://github.com/Typesetter/Typesetter/commit/bd56fbac71c1989274b1ebfeef70aa300ecb6990) should fix it.

**Comment by DarkDau** [comment]
Thanx for the awesome Reply Time and for this fine Software
