### ISSUE TITLE
Add compression for cached files

### ISSUE THREAD

**Issue by mahotilo** [Typesetter/Typesetter#223]
Google PageSpeed Tools force us to compress css, js files. 
Is it possible/reasonable to add into TS some minify-CSS-JS library(-ies) for automatic compression of data/cache files?

**Comment by juek** [comment]
> Google PageSpeed Tools force us to compress css, js files.

Force? No. But recommend to do so.

js/css minification and gzip/deflate compression are two completely different things.

With Typesetter (in release versions, not in the master branch here) most core js files are minified to some extent (see [oyejorge/phpEasyMin](https://github.com/oyejorge/phpEasyMin)), but still readable. Most agressive minification tends to produce unreadable code.

For css, it's mostly up to the author. If you spare indentation, your css will hardly become any smaller when minified. Admittedly, Scss/LESS may easily generate bloated CSS if one overuses cascading thus often leading to needless redundancies.

For theme and addon development - if you're after page loading performance, don't hesitate to use a minifyer. But do other devs a favor and include the development files as well.

With active gzip or deflate compression on server level, un-minified js and even needless css redundancies will become a minor problem.

I wouldn't go for on-the-fly minification. Processing time would cancel out the size reduction.

**Comment by mahotilo** [comment]
> Force? No. But recommend to do so.

Oh, recommendation from Google sometimes is a rough force for developer:) Especially when  customer test your(his) site on [PageSpeed Tools](https://developers.google.com/speed/pagespeed/insights/) and asks "Why my site score is so LOW"? And all "bad" files for Google are *.js and *.scss from `data\_cache`.

> js/css minification and gzip/deflate compression are two completely different things.

Sorry for the term misuse, I want to talk about minimization.

> For css, it's mostly up to the author.

Maybe I am seriously wrong, but  as for me we almost have no minimized JS, CSS in addons. And thanks to the authors for this! So I can learn how to create own addons for TS and make some customization for myself:).

> I wouldn't go for on-the-fly minification. Processing time would cancel out the size reduction.

Not complete "on fly". I mean only `data\_cache` files minimization on their creation. Are you think that this will create big load on CMS? But from another side, we will speed up page loading and fix addon author's  "wastefulness".

**Comment by juek** [comment]
> … when customer test your(his) site on PageSpeed Tools and asks "Why my site score is so LOW"?

I agree. But I have seen quite some SEO optimizing tools who's own website didn't score more than 60% when tested with their own tool :)

If we test Pagespeed Insights itself, it will score 71% ([see yourself](https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fdevelopers.google.com%2Fspeed%2Fpagespeed%2F))

And it even complains e.g. for poorly optimized google fonts css :)
So don't overestimate the results. If you get 70% you're already an optimization guru.

> Maybe I am seriously wrong, but as for me we almost have no minimized JS, CSS in addons.

True. I myself only do it for released addons and only if there is a *significant* amount of savings. 
Example SliderFactory: minified+combined js = 16KB, developer versions = 31 KB. 17 KB difference matters. SliderFactory.css is ~2.8 KB, minified it would be ~1.6 KB. So, I don't care for these 1.2 KB. Of course, Pagespeed will see ~40% possible optimization here. And this is uncompressed. With gzip compression activated, the difference is merely 250 bytes! Per cent is rarely a good measure.

Off topic: For Pagespeed's image optimizations, I mostly disagree with Google here. Both their JPG and PNG optimizations are too aggressive and frequently produce clearly visible artifacts. Algorithms simply cannot estimate optimal image quality/compression ratio. Not as good as I can. Period.

> Not complete "on fly". I mean only data\_cache files minimization on their creation. Are you think that this will create big load on CMS?

Hmm, maybe worth a try. I haven't yet checked how much resources the minifyier scripts actually need. We should stay within 48 MB of available PHP memory. Many cheap shared hosts still even provide less than that. If we do it, we need to trigger it after Scss/LESS compilation - both may use quite some RAM themselves.

**Comment by mahotilo** [comment]
> If we test Pagespeed Insights itself, it will score 71% (see yourself)

:)

> I mostly disagree with Google here.

Yes, I too more believe TinyPNG. And great [TinyPNG plugin](http://www.typesettercms.com/Plugins/321_TinyPNG)  inspire me on optimizations more then Pagespeed.

> We should stay within 48 MB of available PHP memory.

Unfortunately, this is true, I did not take into account

Thanks for conversation.
