### ISSUE TITLE
Responsive Galleries > Masonry gets scrollbar if logged in

### ISSUE THREAD

**Issue by thomasfrobieter** [Typesetter/Typesetter#227]
https://github.com/Typesetter/Typesetter/blob/master/include/css/default_gallery.css - line 15

`body.gpAdmin .gp_gallery{
   overflow:auto!important; /* for gallery display in admin content */
}`

This causes a scrollbar in the masonry preview, as a result, the container is getting less wide, so the preview differs from the real output.

Can we remove this? Or make this selector more specific?

**Comment by juek** [comment]
Josh put it in. AFAIK you can safely kick/overrule it but I haven't tested all browsers. 
I believe it's a relic from gpEasy times where gallery items were sortable directly in the content. Can't imagine what it should be for otherwise.

**Comment by juek** [comment]
[Removed](https://github.com/Typesetter/Typesetter/commit/4e1e41219ef61c8f2ce319b32143c35f79b80838)
