### ISSUE TITLE
Overlapping / conflicting section overlays while editing the layout

### ISSUE THREAD

**Issue by thomasfrobieter** [Typesetter/Typesetter#228]
In some cases, the section overlays z-index is a problem (maybe not just while editing a layout).

Eg:
![ts_section_overlay_z_index_bug](https://user-images.githubusercontent.com/4060313/32564805-9a3b9bd0-c4b5-11e7-8e5b-0422371968f8.jpg)

If i cross the red line with the cursor, the next overlay is getting active. So i have no chance to click the buttons.

I fixed it simply by adding:
`.edit_layout .draggable_element:hover{
      z-index:9999999999999999999999999 !important;
}`

Maybe this z-index is a little to high ;) but works.

**Comment by juek** [comment]
> Maybe this z-index is a little to high ;) but works.
Slightly ;)

Have you noticed the small [-] icon in the top right corner. By clicking it you can reduce the z-index by 1, thus making covered areas accessible.

**Comment by thomasfrobieter** [comment]
Awww .. yeah i noticed it, but i never figured out what it should do. 

This is smart, got it! Thank you!

**Comment by juek** [comment]
> but i never figured out what it should do.

Just another brick in the 'not in the docs' wall ;-)
