### ISSUE TITLE
Ckeditor 4.62

### ISSUE THREAD

**Issue by gtbu** [Typesetter/Typesetter#233]
Is there any chance that ckeditor will be updated to 4.62 (at first in the master). It has some interesting plugins - and i had two cases in which ckeditor refused to save - and backup-revert did not help and i had to make a new installation (- hopefully not beeing hacked)

**Comment by juek** [comment]
I guess we can update to 4.62 for version 5.1.1 but of course we need to test everything. 
Have you alredy tried replacing current CKE with 4.62?

**Comment by gtbu** [comment]
It does somehow not function

**Comment by juek** [comment]
Did you try the new build on a fresh Typesetter installation (without possible incompatible plugins)?

**Comment by gtbu** [comment]
It seems that there are several versions of ckeditor. In 
https://github.com/alincode/ckeditor-sandbox only the load of
<script src="https://cdn.ckeditor.com/4.6.2/full/ckeditor.js"></script> lets lots of icons appear.

**Comment by gtbu** [comment]
I have put (for a time) a new version of 4.73 tested with typesetter 5.1 for download at 
 http://net.square7.ch/ckeditor473.7z
which i generated with ckeditor-dev and ckbuilder.jar
