### ISSUE TITLE
Search function

### ISSUE THREAD

**Issue by gtbu** [Typesetter/Typesetter#234]
The search function does not find everything, and it is slow at big sites. My proposal is to add all sites to a onepage, save that file as a temporary file and search in that file. That is faster and easier. One can actualize this file manually within the search-plugin.

**Comment by juek** [comment]
> The search function does not find everything…

What type of content doesn't it find?

> …and it is slow at big sites.

This is where database driven CMS definitely have huge advantages.

> … save that file as a temporary file and search in that file.

Not so trivial. We'd have to build a lookup table as a search cache which would have to be cleared with every admin action/content change and rebuilt @ the next search. But it wouldn't work with dynamic content such as pending blog posts or any other plugin based dynamically generated content.

**Comment by gtbu** [comment]
One could use two parallel search-functions and make a hook in the cms with the notice - 'cached search not for dynamic changing sites' - ( or implement a function which updates cyclical ).
It would be an argument for the next version of Typesetter

**Comment by juek** [comment]
After thinking of it, I believe we'd only get significant search performance boost if we'd build caches for specific search phrases. 

Especially with larger sites and frequent use of the search function, doing so, the amout of required disk space could quickly grow out of available bounds. I fear that Typesetter simply isn't the type of CMS for such applications and it is often choosed for it's rather small footprint.

**Comment by gtbu** [comment]
You would have a similar memory-problem with Your onepage-Plugin. The cache-file would only have some megabytes. I can compare the search mit the search of the one-file flat-cms cmsimple XH - whose search is more than 5 times faster, and this cms has no memory-problems nor on harddisk.

**Comment by juek** [comment]
If it's really 5 times faster, we should probably give the search cache idea a go. Wouldn't have thought so. 

But CMSimple_XH is way simpler than Typesetter in terms of structur, abstraction and storage. In fact, it's not only a flat-file system but has a monolithic flat content model with no relations or inter-dependencies. (Assuming it's still similar to the days when I used it a lot.)

But of course, a well built cache LUT would resolve and flatten Typesetter's complexity.

> You would have a similar memory-problem with Your onepage-Plugin.

Sure, but I cannot imagine anyone building a one-pager with such an amount of content to cause noticeable search delay.
