### ISSUE TITLE
The type attribute is unnecessary for JavaScript resources

### ISSUE THREAD

**Issue by SimonMupz** [Typesetter/Typesetter#235]
after checking website on https://validator.w3.org I get this error,

Warning: The type attribute is unnecessary for JavaScript resources.
From line 79, column 1; to line 79, column 98
div>↩↩  ↩↩<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>

Where can I change this, it looks like this should be done in the typesetter code.

**Comment by juek** [comment]
The type attribute for script elements only was stripped in HTML**5**.
Typesetter doesn't demand a specific HTML version for themes and there are still some older HTML4 themes available and in use. Removing the attribute in HTML4 would cause an error. What you get is only a warning. Keeping it will not have any negative impact. 

But if you still want to get rid of all the type attributes, there are [quite a few occurrences](https://github.com/Typesetter/Typesetter/search?p=1&q=%27type%3D%22text%2Fjavascript%22%27&type=&utf8=%E2%9C%93) in the CMS core, themes and addons.

If you decide to remove them, bear in mind that they will resurface when you upgrade Typesetter.

**Comment by SimonMupz** [comment]
Thank you for your reply! that helps a lot!
