### ISSUE TITLE
missing links redirection not working with http://website/xxx/yyy

### ISSUE THREAD

**Issue by SimonMupz** [Typesetter/Typesetter#236]
When i try to make a redirection with my website with multiple / / / it's not working,
is there a way to solve this?

**Comment by juek** [comment]
No sure. Works here? 
What exactly happens with the redirection URL?

**Comment by SimonMupz** [comment]
It's redirecting to 404
http://degoochelaar.nl/goochelaar-inhuren/goochelaar-vinden
should redirect to http://degoochelaar.nl

**Comment by juek** [comment]
I see, I only tested it the other way round. ( /old-url --> http://newsite.tld/new-url/subdir )

I haven't made the redirect function, so I don't fully understand what it excatly does and what it tries to solve/prevent by splitting and re-joining the URLs with slashes. 

However, you can edit /include/special/[Missing.php](https://github.com/Typesetter/Typesetter/blob/d02debf46bf934ede31d60cafe27976ec344869c/include/special/Missing.php#L55), lines 61 to 79:

```php
$parts = explode('/',$this->requested);
$first_part = array_shift($parts);
/* ### ADDED LINE ### */ $first_part = $this->requested;

if( !isset($this->error_data['redirects'][$first_part]) ){
  return;
}

$target = $this->error_data['redirects'][$first_part]['target'];

$target = $this->GetTarget($target);

if( $target === false ){
  return;
}

if( !empty($parts) && is_string($target) ){
  /* ### COMMENTED LINE ### */ // $target .= '/'.implode('/',$parts);
}
```



With these both modifications - see the comments - it seems to work. I hope I doesn't have negative side effects. Please test extensively and bear in mind that any changes to core scripts will not survive CMS updates.
