### ISSUE TITLE
Can't change gallery theme

### ISSUE THREAD

**Issue by mahotilo** [Typesetter/Typesetter#239]
On last TS-master
1. Insert gallery
2. Change theme to masonry or some one else not default
3. Gallery redraws in new theme
3. Save section
4. Gallery returns to default theme

**Comment by juek** [comment]
Thanks, should be fixed with [this commit](https://github.com/Typesetter/Typesetter/commit/f7207882e0eb0e40f8965956c8ded518727da8ad)

**Comment by mahotilo** [comment]
Works fine now. 
Thanks
