### ISSUE TITLE
Problem with Layouts editor

### ISSUE THREAD

**Issue by mahotilo** [Typesetter/Typesetter#243]
It is impossible to see page in Layouts editor when I have some `<div>` with style `min-height: 100vh` in template.php.
Sample page in Layout editor infinitely continues to load.
I see problem with SCSS theme both BS3 and BS4

**Comment by juek** [comment]
Yes, I'm also a bit unhappy with the current implementation, but there are reasons for that behaviour. IMO the iframe adapting script should be reworked.

**Comment by juek** [comment]
I simplified the whole thing with [this commit](https://github.com/Typesetter/Typesetter/commit/8a835b9c14bf9862f9dc991b0b149354213de15d). vh units should also work now.

**Comment by mahotilo** [comment]
It works good for me.
Can we also hide vertical scroll in main window. It's look like redundant

**Comment by mahotilo** [comment]
Something like [this](https://github.com/Typesetter/Typesetter/pull/268/commits/ee64f7f33d492cd7c818501fda0390a092944eb6)

**Comment by juek** [comment]
In which browser do you get the vertical scrollbar? 

I hoped to make it go away with [this calc rule in](https://github.com/Typesetter/Typesetter/blob/master/include/css/theme_content_outer.scss#L10) in all browser/OS combos.

overflow-y: hidden in the body element would work too, but i'd rather avoid it because it might render cetain elements inaccessible in some situations.

**Comment by mahotilo** [comment]
Hmm, yes indeed,
I see it only in Opera. Thus, it may be not a global problem, and we can close an issue.

It would be possible to breathe a sigh of relief, but I found another problem:)
If we have msg with "Sorry, this site is currently locked for editing by another user..." an old problem with many right sidebar appears again.

![image](https://user-images.githubusercontent.com/14929385/41612054-676adb04-73fa-11e8-9882-fec5faeb0313.png)

**Comment by mahotilo** [comment]
Juergen, sorry. Problem in Opera was only due caching of `theme_content_outer.js`. After editing and reloading problem with vertical scrollbar gone.

**Comment by juek** [comment]
Does the iframe-nesting still occur? 
Maybe it has sth. to do with Cross-Frame-Scripting, because of no [FQDN](https://en.wikipedia.org/wiki/Fully_qualified_domain_name) in your dev environment(?)

**Comment by juek** [comment]
> Can you check it on live server with simultaneous login?

No promlems here. But we have to fix it anyway. Working on it.

**Comment by juek** [comment]
Maybe rather a timing issue

**Comment by juek** [comment]
Ok, I hopefully addressed the timing stuff with [this commit](https://github.com/Typesetter/Typesetter/commit/92f2850998eecfb4e5ad498b4743379a6939d6ac), could you please check it once again on your side?

**Comment by mahotilo** [comment]
No. Now it looks like this:
1. One right sidebar. No layout preview
-  1 sec.
2. Two right sidebars. Second has vertical scrollbar. No layout preview
-  1 sec.
3. Three right sidebars. Second and third have vertical scrollbar.
-  1 sec.
4. Goto step 1.

**Comment by juek** [comment]
... and what do you mean with '1 sec'?
We don't have any continuous interval iframe checking anymore.

**Comment by juek** [comment]
Just FYI–maybe you have an idea what it could be:

Both, the main window and the iframe load in parallel. Both documents may take a bit, the main window because of codemirror, the layout preview because of Scss/LESS compilation. So we have different timing 
until both DOMs are ready and all scripts are loaded.

In the latest version it goes like this:

Iframe content executes the $gp.iframe_ready function at domready, which checks for the local variable $gp.iframe_ready_triggered to be _false_ AND the main window's (parent's) variable $gp.editor_ready (which in turn is only set when the parent's DOM is ready) is available. If both conditions match, it executes parent.$gp.handle_iframe() in the parent DOM and sets $gp.iframe_ready_triggered to _true_. This will only happen once every time the iframe page (re-)loads. If the conditions don't match, it will not try it again but give control over to the parent window.

In the parent window, $gp.editor_ready will be set to _true_ at domready (that's the var to be checked from out of the iframe's JS). It will furthermore execute $gp.check_iframe_ready(). This function looks for the iframe DOM and scripts being accessible. If they aren't, it will execute itself again afer 150ms. If they are, it will call $gp.iframe_ready() in the iframe, which is the function mentioned in the paragraph above. This function then will then call $gp.handle_iframe() in the parent, if it wasn't already executed in the meantime. 

$gp.handle_iframe() in the parent window will check if there is a nested iframe #gp_layout_iframe (for whatever reason) and reload the page if there is (it will furthermore try to append the spacer div to the iframe's body and should throw an error to the JS console it the body element doesn't exist).

So, the last step could lead to the infinte loop that you see, if nested iframes occur, because the relaoding of the iframe content will re-trigger the whole process.

Therefore we must find the reason for the nesting.

**Comment by mahotilo** [comment]
Thx. I have read your description and will try to inspect this process at my test site.

Just one more observation.

I noticed that I see multiply message about locked session via msg(). Is it called in context of iframe? Why not in the main window? As I can see, msg() has very high priority. Is it worth our attention?

**Comment by mahotilo** [comment]
May be it is easier to kick the user out of the Layouts editor while his session is locked?

**Comment by juek** [comment]
> I noticed that I see multiply message about locked session via msg(). Is it called in context of iframe? Why not in the main window? 

Typesetter is running in the main window and im the iframe as well, it's only called differently thus leading to different views.

> Can it break described logic?

No.

> Is it worth our attention?

Yes it does! 
IMO it tells us that Typesetters treats the iframe view as if it was a different browser and creates an additional user session–based on the active client authentication. This must not happen and it might well lead to the weird behavior you encounter. 

With Firefox, you can rightclick in the iframe and select 'Current Frame' -> 'Open frame in new window'.
What do you see then, and does the URL in the address bar end with '?cmd=in_iframe'?

**Comment by mahotilo** [comment]
No no no. Sorry Juergen, I'm misleading you. This happens exactly when I have a locked session due to two simultaneous logins in different browsers.

So, again. Does it worth our attention?

**Comment by juek** [comment]
The multiple messages themselves will not break the parent<->iframe logic.
But I still wonder where the iframe nesting comes from.

**Comment by juek** [comment]
BTW: the [latest commit](https://github.com/Typesetter/Typesetter/commit/48717ffdf3a08f525542b7c6be236dc8bc73bd8a) will not fix the nesting, it's only required to hide the loader in the parent when Scss/LESS/CSS is previewed or saved. (I had just commented it to prevent a occasional JS error when the parent wasn't ready at initial load - should be fixed now as well).

**Comment by mahotilo** [comment]
Maybe it will be helpful. I have no errors in Opera during nesting loop. But in IE I found errors in row 2 of Layouts editor page. But columns have no sense.

Theme uses BS4

![image](https://user-images.githubusercontent.com/14929385/41670994-837303fc-74be-11e8-94d9-9a3571bd346a.png)

**Comment by juek** [comment]
The 'Permission denied' also hints to a XSS/XCF issue, meaning the iframe and the parent aren't treated as being of the 'same origin', domain-wise.

**Comment by juek** [comment]
what loacel server are you using?

**Comment by mahotilo** [comment]
Apache HTTP Server 2.4

**Comment by juek** [comment]
One of these? 

- ApacheHaus
- Apache Lounge
- BitNami WAMP Stack
- Devserver EasyPHP
- WampServer
- XAMPP

**Comment by juek** [comment]
At least with WampServer, Apache's headers_module must be activated, so Typesetter can set the 
'X-Frame-Options: SAMEORIGIN' [CORS header](https://github.com/Typesetter/Typesetter/blob/b2368a30ea0647f69fceaa3a15e29cc7c39c9b98/include/admin/Page.php#L32).

E.g. see [this on stackoverflow](https://stackoverflow.com/questions/27058104/enable-cors-with-wamp-on-windows-8)

If in doubt, you might want to check the headers from the Inspector's Network tab. With Layout Manager loaded, you should see **X-Frame-Options: SAMEORIGIN**

![grafik](https://user-images.githubusercontent.com/704283/41676999-6b89a396-74c7-11e8-9025-904d3fbc4a45.png)

**Comment by mahotilo** [comment]
Sorry for the pause, was leaving
I have string X-Frame-Options: SAMEORIGIN
For testing I use UsbWebserver reassembled by myself.

![image](https://user-images.githubusercontent.com/14929385/41678690-67349d84-74d4-11e8-8ea3-fc7731882849.png)

**Comment by mahotilo** [comment]
I tried to reproduce it on live site with Nginx right now. Same result as on local.

**Comment by juek** [comment]
Is it a plain Typesetter install or do you have plugins installed?

**Comment by mahotilo** [comment]
Yes, I am guilty. It was not a plain but a working site. 
But I checked it right now with plain install. Problem persist.

**Comment by juek** [comment]
Just installed on niginx 1.14.0 + php-fgci 7.2.7

Everything is fine.  I'm somewhat clueless.

**Comment by mahotilo** [comment]
It is curiouser and curiouser...
I use MSE, Win7 internal brandmauer, browser private mode (no addons). Nothing special, as for me.
But if you can't reproduce an error, I will try to check on another computer with another internet provider.

I tried to manipulate with $gp.check_iframe_ready() and another, but didn't get the no expected results. Need to check my installation and environment in did. 
I`ll try to do it ASAP.

**Comment by mahotilo** [comment]
I tried it in another place with another computer and clear Firefox and live server. Same result.

I clearly see endless loop in $gp.check_iframe_ready = function(){...} but cant find way to break it.

**Comment by juek** [comment]
Thanks for testing. Baffling, isn't it? I'll investigate further.

Just for good mesaure - are you absolute certain you're running all the latest commits?

**Comment by mahotilo** [comment]
I downloaded TS right now and checked again. Problem in place.
Tough one...

One idea. If `srcdoc` will be used instead of `src` in `iframe`, will everything be easer?

**Comment by juek** [comment]
> If srcdoc will be used instead of src in iframe, will everything be easer?

At first, IE and Edge<17 [don't support it](https://caniuse.com/#feat=iframe-srcdoc) but 2nd, with the current implementation, we need an independent document in the iframe.

I'd love to change Layout Editor to be useable on real pages, just like editing content, but this would be a complete change of the achitecture and I'm unceratin if my skills suffice for such an endeavour.

**Comment by mahotilo** [comment]
It was just an attempt :)
Yes, as you said, the current implementation of Layout editor is extremely "not simple".

I really think that the current situation with Layouts Editor is not so bad and we can close our eyes to the problem I discovered. It is not a big problem in real life. You can't even reproduce it. Even if it exists, it only signals to us about the imperfect solution with iframe. I suggest to close this bug.

**Comment by juek** [comment]
>  is not so bad

No we can't leave it at that for 5.1.1. 
But maybe I just need a break and get it when I look at the code again in a few days.

**Comment by mahotilo** [comment]
Ok, and I'll also take the time to watch the Apache logs

**Comment by gtbu** [comment]
Have You tried it with a new version of   layout-editor Codemirror  ?

see  http://typesetter5.bplaced.net/Issues

**Comment by mahotilo** [comment]
I tried an updated Codemirror and find, that I can no longer reproduce this problem on TS 5.1.1-b1. And with old version of Codemirror as well. So maybe I'll close the issue.
