### ISSUE TITLE
[unable to change homepage(homepath/homepath_key) after insert into menu]

### ISSUE THREAD

**Issue by hotcomkarl** [Typesetter/Typesetter#246]
hi typesettercms,

there is a problem setting the homepage in Typesetter 5.1.1-b1

if in page manager an new page is created via "Insert Into Menu" (before/after/child) then homepath und homepath_key is written to data/site/_config.php. since then you cannot change the homepage (the first called by index.php) through reordering in page manager.

after deleting homepath_key and homepath from config.php everything works again as expected

thx, 
greetings
karl.

ps:
fantastic CMS, really. true. great.

**Comment by juek** [comment]
Can confirm it, at least back to 4.6.1. It might have always been this way but my memories feel different.
We will probably have to add a 'Auto/Custom' switch but I'll yet have to get the underlying logic.

**Comment by juek** [comment]
Should be fixed with [this commit](https://github.com/Typesetter/Typesetter/commit/d60c0cd66ed59a3bd19776638f087f9a8a73c540).

**Comment by thomasfrobieter** [comment]
Sehr geehrte Damen und Herren,

vom 30.04.18 bis zum einschl. 04.05.2018 bin ich nicht im Büro zu erreichen.
Ich beantworte Ihre E-Mails umgehend nach meiner Rückkehr.

In dringenden Fällen senden Sie bitte eine E-Mail an ticket@webks.de
Wir antworten schnellstmöglich.

Vielen Dank für Ihr Verständnis.


Mit freundlichen Grüßen
Thomas Frobieter

Geschäftsführer / Gesellschafter

webks: websolutions kept simple
webks GmbH
Kreuzacker 6
D-32457 Porta Westfalica

E-Mail: jp@webks.de
Internet: http://www.webks.de | http://www.DROWL.de
Tel.: +49 571 3981586-0
Fax: +49 571 3981586-6

Geschäftsführer: Julian Pustkuchen, Thomas Frobieter
Eintragung im Handelsregister: Registergericht: Bad Oeynhausen; Registernummer: HRB 14976
USt-IdNR.: DE305549361

Es gelten unsere allgemeinen Geschäftsbedingungen, einsehbar unter:
http://www.webks.de/agb

Missbrauch dieser Daten wird rechtlich verfolgt.
Sollten Sie nicht der korrekte Adressat dieser E-Mail sein, bitten wir Sie um umgehende Löschung und eine kurze Rückmeldung.
