### ISSUE TITLE
Codemirror no colors

### ISSUE THREAD

**Issue by gtbu** [Typesetter/Typesetter#249]
The included codemirror 5.1 has no colours in the ckeditor. 
The plugin form cksource has Colors.
 Is it somehow possible to update it to 5.37, and can the colors only be achieved by the plugin ?

**Comment by juek** [comment]
The codemirror script that comes with Typesetter is not used in CKEditor but only in Layout Editor. 
But you can install e.g. this [CKEditor codemirror plugin](https://github.com/w8tcha/CKEditor-CodeMirror-Plugin/releases).

**Comment by gtbu** [comment]
The Layouteditor has no line numbers. May i propose to add them in the master.

**Comment by juek** [comment]
Since Scss, LESS and CSS in Layout Editor will be processed, combined, cached and even minified, the generated CSS will look completely different. Line numbers simply do not make much sense here. They would primarily consume already scarce screen real estate.

**Comment by gtbu** [comment]
I hope we do not talk about two different editors : The layout-window in the right corner for additional user-css has no line-numbers

**Comment by juek** [comment]
> I hope we do not talk about two different editors…

I don't think so, Layout Editor => www.yourwebsite.com/Admin_Theme_Content/Edit
If you want line numbers, simply add 'lineNumbers : true' to
/include/js/theme_content_outer.js (the development version from GitHub), 
line 96 to (then) line 100:

```
var codeMirrorConfig = {
	mode : 'text/x-less',
	lineWrapping : false,
	lineNumbers : true
};
```

**Comment by gtbu** [comment]
Many thanks - that conjures up not only line numbers but also colors !
You should activate this in the master.
