### ISSUE TITLE
Feature Request: Image handling

### ISSUE THREAD

**Issue by stth1998** [Typesetter/Typesetter#25]
Hi,

I would like better support for image uploading and resizing.

The features I discovered yet, is that images which are uploaded, automatically get a thumbnail in the preferred thumbnail size and are resized, if they exceed the maximum size. As far as I can see, both are deleted, if I delete the picture.

I need my pictures as thumbnail, in a fixed format and in original size.

So it would be nice if I could configure a set of image resolution configurations which all are resized on upload (e.g. { [x] thumbnail, [x] max. 640 px/keep aspect ratio, [ ] max. width 800px/keep aspect ratio, [x] original, [ ] maximum size/keep aspect ratio }. All those files should be connected like the thumbnail and the image are conneced now.
- Then, it should be possible, to choose one of the pre-defined resolutions in the edit-image-dialog.
- If a custom size is given, the edit-image-dialog could select the tiniest possible source-image to use.
- there should be an option in the edit-image-dialog to put a hyperlink to the { (*) original, ( ) max, ( ) ... } of the image around it
- there should be an menu to view/download the image in a particular size from the gallery overview and from the opened gallery

candy:
- if a new resolution configuration is defined, you may choose [create for all existing images]
- if a resolution configuration is removed it is just greyed out, you may choose [remove all scaled images] to delete it 
- if an image is smaller than some configuration, it could be linked instead of upscaling or copying
- to save disk space, an image in a particular resolution could be created on first usage.

what do you think about that? is it possible to extend the thumbnail-function like that?

Cheers, Stefan

**Comment by 2braincells2go** [comment]
Do not mean to step on others threads, but this would be a wonderful feature if possible to implement. I have been in a very similar situation as @stth1998  and wishing for same solution.

**Comment by thomasfrobieter** [comment]
Old request from 2013, but still a persisting problem. I recently saw a comment at the typesetter forum to this topic.. can´t find it again.. but they will face this problem in the future.

There is already an amazing image plugin that solves a lot of problems:https://www.typesettercms.com/Plugins/293_Responsive_Image

**Comment by juek** [comment]
Thumbnail generation has been improved in Typesetter ver 5.1 by supporting proportional thumbs and arbitrary aspect ratios. However, Typesetter does not generate multiple image sizes by default (e.g. like WordPress does).

Feel free to implement custom image handling by using the plugin hook [FileUploaded](https://github.com/Typesetter/Typesetter/blob/b5084735ead606159be70bcc43e325454b26798c/include/admin/Content/Uploaded.php#L250) and existing methods like [\gp\tool\Image::CreateRect(args)](https://github.com/Typesetter/Typesetter/blob/08dfc7a5e2e5356cd37a5b0f5a2d741e98b947bf/include/tool/Image.php#L128)
