### ISSUE TITLE
Ckeditor missing plugins

### ISSUE THREAD

**Issue by gtbu** [Typesetter/Typesetter#253]
Ckeditor shows a list of installed plugins, but 6 of the plugins (like floatpanel) are not installed. 
Reinstalling from a zip is not possible.  I get the error, that the functionality is already installed. 
(or : Could not install forms. It is already defined by Typesetter or another add-on -- at forms-4-6-2.zip.)

A momentary problem is the forms-plugin(in connection with bootstrap-visible), but the forms are not visible as in  https://ckeditor.com/cke4/addon/forms (in  upper line shown).
Some of the  plugins are necessary for bootstrap-plugins...(widget, dialog - dep: dialogui, table)

How can i deactivate this behaviour ? (in \include\js\ is a ckeditor-config.js )
( You have http://typesetter-addons.grafikrausz.at/CKE-StylesCombo ... and obviously know such problems)

**Comment by juek** [comment]
The forms plugin is preinstalled in Typesetter's CKEditor build. You need to activate the toolbar buttons.
There are 2 ways to do it, either via Admin UI or programmatically.

**1. Admin UI**

Admin Toolbox -> Settings -> CKEditor -> Configuration: insert the followin JSON
```
{
    "toolbar" :[
        [ "Sourcedialog", "Templates", "ShowBlocks", "Undo", "Redo", "RemoveFormat" ],
        [ "Cut", "Copy", "Paste", "PasteText", "PasteFromWord", "SelectAll", "Find", "Replace" ],
        [ "HorizontalRule", "Smiley", "SpecialChar", "PageBreak", "TextColor", "BGColor" ],
        [ "Link", "Unlink", "Anchor", "Image", "Flash", "Table" ],
        [ "Format", "Font", "FontSize" ],
        [ "JustifyLeft", "JustifyCenter", "JustifyRight", "JustifyBlock", "NumberedList", "BulletedList", "Outdent", "Indent" ],
        [ "Bold", "Italic", "Underline", "Strike", "Blockquote", "Subscript", "Superscript", "About" ],
        [ "Checkbox", "Radio", "TextField", "Textarea", "Select", "Button", "ImageButton", "HiddenField" ]
    ]
}
```
in the confiuration textarea, then click [ Save ].
This will replace the 'toolbar' key in CKEditor's config. Note the last line ["Checkbox", ... ], that's the form elements.

**2. Programmatically, via plugin hook**

E.g. check the [FreeMailForm Enhanced](https://www.typesettercms.com/Plugins/316_FreeMailForm_Enhanced) plugin. It uses Typesetter's CKEditorConfig plugin hook.
FreeMailForm.php, lines 221-224:

```
function CKEditorConfig($options){
  $options['toolbar'][] = array('Checkbox', 'Radio', 'TextField', 'Textarea', 'Select', 'Button', 'ImageButton', 'HiddenField');
  return $options;
}
```

**Comment by juek** [comment]
> ... but 6 of the plugins (like floatpanel) are not installed.

Admin Toolbox -> Settings -> CKEditor -> Manage Plugins

Note the list of intalled plugins, Floatpanel is listed as being installed.

**Comment by juek** [comment]
Floatpanel and Dialog are part of the CKEditor build, Typesetter uses. (Both are 'required' if you look them up on ckeditor.com.) You will find tem (using text search) in /include/thirdparty/ckeditor_34/ckeditor.js

> How relevant is the list in the js/ckeditor-config.js or are there further mechanisms and files.

It defines the default toolbar items, and appends possible additional plugin buttons defined in [editor instance].ui.items to the toolbars. It also adds autocomplete functionality to some dialogs in order to easier selecrt existing pages.

>  Where is stored that they are installed ? [...] The json under 1. Admin Ui lets in fact the form-buttons appear. Where is it stored ?

Both will be stored in /data/_ckeditor/config.php

> I can do of course the above, but i want to create a version from scratch, which contains also all modules of the full-version 4.6.2 …

You can replace CKEditor with a custom build that includes the additional components you need. As long as it satisfies Typesetter's core needs, it should work.

>  … i do not want to be blocked by some mechanisms which i do not understand.

Typesetter comes with it's default demands in terms of components and configuration. It also provides ways to affect them, such as the CKEditor Configuration Admin UI options and the plugin hooks. 
As far as I understand it, the order/hierarchy is …

1. Typesetter's hardcoded base/default configuration, extended by…
2. possible plugin hooks (CKEditor_Config, CKEditorPlugins)
3. possible Admin UI config (including plugins, config JSON)

**Comment by gtbu** [comment]
This really answers my questions.
 I still have another problem to add a new config.php (in data/_ckeditor) to an old config.php(while updating while additional plugins exist). Just to replace it makes existing plugins invisible.
Typesetter writes into the config.php which routines are responsible ? - or do You know a bteer method ?

**Comment by juek** [comment]
> Is there anywhere a filter ? Same for ttf and woff and woff2...

Yes, there is [$allowed_types](https://github.com/Typesetter/Typesetter/blob/e851c39db6a9af30f9c4c419674e7b505ad6f8a0/include/admin/Content/Uploaded.php#L669), 
[$upload_extensions_allow](https://github.com/Typesetter/Typesetter/blob/e851c39db6a9af30f9c4c419674e7b505ad6f8a0/gpconfig.php#L34) (to extend $allowed_types)

I already added the font types eot, otf, ttf, woff and woff2 with [this commit](https://github.com/Typesetter/Typesetter/commit/e851c39db6a9af30f9c4c419674e7b505ad6f8a0)

**Comment by juek** [comment]
This is the [UploadPlugin() method](https://github.com/Typesetter/Typesetter/blob/5966a684550a4565517ef27865c58b398b4ae42c/include/admin/Settings/CKEditor.php#L175) which calls the SaveConfig() method to save the configuration.

You will find all the CKEditor configuration methods in [/include/admin/Settings/CKEditor.php](https://github.com/Typesetter/Typesetter/blob/5966a684550a4565517ef27865c58b398b4ae42c/include/admin/Settings/CKEditor.php)

**Comment by juek** [comment]
>  It is quite fiddely to append code to the two parts of the config.php [...] or do You know a better method?

The config.php file is not meant to be optimized for human readability or manual editing. If you mean a graphical UI to edit config keys/values: no, we do not have such in Typesetter.

**Comment by gtbu** [comment]
I had thought of people using ckeditor 4.6.2 with manual installed addons.  When they update to a version with full spectrum and bootsprap - plugins i must  overtake the config.php in data/_ckeditor or replace it or melt it somehow.  But the ploadPlugin() method  is quite useful for automatic installing of additional plugins. I will see.
------------------------------------------------------------------------------------------------------
The unsolved problem is https://ckeditor.com/cke4/addon/glyphicons . I made an installation in the web on fedora 8 and php5.6 and Typesetter 5.1 (5.1 as before on xampp ) and got the same error. 
Oops, that didn't work, please try again. (File type not allowed:glyphicons/css/fonts/glyphicons-halflings-regular.eot) 
The fonts are not installable. I removed the fonts from the plugin and the installation was successful. 
After i copied them manually into the fonts directory they are only visible in the choice menu but not in the html. Perhaps You can try it yourself ?

**Comment by juek** [comment]
> The fonts are not installable. 

Have you added the changes from [this commit](https://github.com/Typesetter/Typesetter/commit/e851c39db6a9af30f9c4c419674e7b505ad6f8a0)?

If not, you can edit /gpconfig.php, find the line [$upload_extensions_allow](https://github.com/Typesetter/Typesetter/blob/e851c39db6a9af30f9c4c419674e7b505ad6f8a0/gpconfig.php#L34)
and change ot to 

`$upload_extensions_allow = ('eot', 'otf', 'ttf', 'woff', 'woff2');`

**Comment by gtbu** [comment]
I had not, but wondered that Roboto - Fonts and others make no problems. 
I get  : Parse error: syntax error, unexpected ',' in L:\xammp7025\htdocs\type51\gpconfig.php on line 34  for the line above.

**Comment by juek** [comment]
> I get : Parse error: ...

Sorry, my fault. It's 
`$upload_extensions_allow = array('eot', 'otf', 'ttf', 'woff', 'woff2');`

**Comment by gtbu** [comment]
That functions - but how can i patch the gpconfig.php with an php - routine from an installer for normal users ?

**Comment by juek** [comment]
>  had not, but wondered that Roboto - Fonts and others make no problems.

Thats because Typesetter plugin installation is different – they are PHP-based while CKEditor plugins are JavaScript. Um it's … not so easy to explain. It's a matter of trust in the source.

**Comment by gtbu** [comment]
So the system does not hinder to patch the gpconfig.php ?

**Comment by juek** [comment]
> That functions - but how can i patch the gpconfig.php with an php - routine from an installer for normal users?

You don't need to. There is also the [AllowedTypes](https://github.com/Typesetter/Typesetter/blob/e851c39db6a9af30f9c4c419674e7b505ad6f8a0/include/admin/Content/Uploaded.php#L692) plugin hook.

**Comment by juek** [comment]
I'll put a sample plugin togehter for you. Will take a few moments. Stay tuned.

**Comment by gtbu** [comment]
I do not quite understand 
$allowed_types = \gp\tool\Plugins::Filter('AllowedTypes',array($allowed_types));
So i have to define array($allowed_types) in the plugin ?

**Comment by juek** [comment]
Here is [CKEditor-Glyphicons](http://typesetter-addons.grafikrausz.at/data/_uploaded/file/CKEditor-Glyphicons-4-5-11.zip)

Only quickly tested. Seems to work.

I'll put it on my Github repo as well.

**Comment by juek** [comment]
> I'll put it on my Github repo as well.

[Done](https://github.com/juek/CKEditor-Glyphicons/)

**Comment by juek** [comment]
This would be an addont that uses the AllowedTypes hook to enable additional font file extensions.

[AllowFontUploads_1_0.zip](https://github.com/Typesetter/Typesetter/files/2016840/AllowFontUploads_1_0.zip)

**Comment by gtbu** [comment]
Thank You very much ! 
It all seems to function - its just that Your plugin is for 4.5.11, but it shows me the easy possibility to install my running but halffunctioning bootsprap3-plugins, which i will first publish after second week of June because i still have to write a cards - plugin and a panel-plugin to complete them.
Another interesting plugin is a materialize-icons - plugin. 
I will now at first update the ckeditor-462.plugin with the allowfonts-php and with a menu-patch of radiobutton etc.

**Comment by juek** [comment]
Great!

FYI: For encapsulated components like Bootstap cards, panels, alerts, navs, etc. you could also use [CustomSections](https://github.com/juek/CustomSections), which allows to build native Typsetter section types.
