### ISSUE TITLE
bootswatch templates -proposal

### ISSUE THREAD

**Issue by gtbu** [Typesetter/Typesetter#254]
I just saw that You made a small change in the bootswatch templates. 

Can You make a change similar to https://www.typesettercms.com/Forum?show=t2506
in one of the templates (small megadrop) ?

**Comment by juek** [comment]
There is no need to change the theme.
Use the new Bootswatch4 Scss theme (Bootstrap 4 based), it contains the dropdown-item classes.

If you want a dropdown-divider, you can add a Extra Content area to the menu by following these steps:

1. First of all activate the Bootswatch4 Scss theme via Admin Toolbox -> Appearance -> Manage, choose the theme and set it as default
2. Go to Admin Toolbox -> Content -> Extra Content and add a new 'Edtiable Text' Area, call it _dropdown-divider_
3. Edit the new area and remove all (Lorem Ipsum) text content, Save and Publish the area
4. Go to Admin Toolbox -> Content -> Page Manager
5. Add a new Menu Item (Insert After) and choose 'Extra Content', then select the 'dropdown-divider' area
6. Go back to Layout Editor (Admin Toolbox -> Appearance -> Layouts -> Bootswatch4 Sccs [your layout]) and add the following Scss. Save. Done.

```
.gpArea_Extra_dropdown-divider {
  @extend .dropdown-divider; 
}
```

For the Mega Dropdown menu: to target a specific dropdown menu via Scss you can do it …

1. By the item number class

```
div.navbar.fixed-top .nav-item-2 > ul.dropdown-menu.show { 
  display:flex; width:420px; flex-wrap:wrap; 
  .dropdown-item { 
    width: 33.333%; 
  }
}
```

2. By the preceding href attribute

```
div.navbar.fixed-top a[href="/More"] + ul.dropdown-menu.show { 
  display:flex; width:420px; flex-wrap:wrap; 
  .dropdown-item { 
    width: 33.333%; 
  }
}
```

3. By adding a custom class to the ul via Page Manager -> [your dropdown's parent menu item] -> Menu Output - Classes -> 'li > **ul**' : mega-menu

```
div.navbar.fixed-top ul.mega-menu { 
  display:flex; width:420px; flex-wrap:wrap; 
  .dropdown-item { 
    width: 33.333%; 
  }
}
```
