### ISSUE TITLE
Image and links checker

### ISSUE THREAD

**Issue by mahotilo** [Typesetter/Typesetter#278]
What do you think about Checker for broken links (internal for site) and image sources? 
Should we have such a feature or enough existing third-party applications? 
Should this be a plugin or a built-in CMS function?

**Comment by juek** [comment]
I believe there are plenty of online and offline tools available.

However I'd like to have a 'usage checker' for finder to warn before a used resource is deleted, moved or renamed, like "Warning: This file is currently used on [page/s or layout_area/s]. Do you really want to [user_action] it?" or "Warning: files in this folder are used on [page/s…"

But we would need to keep a lookup table for all linked resources to make it possible. We can't search all pages/layouts on-the-fly. Furthermore, there is no defined way how plugins handle resources, they may generate dynamic output with uploaded files without storing a static content we could parse.
So I can't imagine an efficient way to accomplish it.

**Comment by mahotilo** [comment]
Thx.
I close an issue.
