### ISSUE TITLE
ckeditor problem and update

### ISSUE THREAD

**Issue by gtbu** [Typesetter/Typesetter#286]
I  found problems with ckeditor update 4.62 : Ckeditor stayed grayed out after installation - only on xampp. 
Parallel to the installation-directory as 'Typesetter' was an empty directory 'Typesetterincluded'  generated with a subdirectory thirdparty , and evtl. with ckeditor installed - also in the web(all versions)... I made an update 1.03 
Can You check the version 1.03 deeper if You have time - i do not have Your experience...

I have another question : I made a Typesseter installation at bplaced.net, where file_get_contents(from remote servers) and websockets are not contained in the free version, so that webinstall of plugins is disabled. A solution in the CMS could be to download the zips into a temporaray directory and to install them then from there (first after normal installation failed):

**Comment by juek** [comment]
For ckeditor update plugin - that's not a Typesetter issue itself so other users will have a hard time understanding it. I'd recommend to discuss such issues in the [Typesetter CMS Plugins forum](https://www.typesettercms.com/Forum?show=f14) giving a referance to the plugin or, even better, if you created GitHub repositories for your plugins where we could not only discuss issues but also fork the code and make pull requests.

[GitHub Desktop](https://desktop.github.com/) makes this quite easy.

For bplaced.net: 

>A solution in the CMS could be to download the zips into a temporaray directory.

That's what Typesetter does when installing remote plugins. If the bplaced.net host doesn't allow remote connections, how should the CMS download and manage them. That's one reason we have manual d/l + installation for.

**Comment by gtbu** [comment]
(If You still  find something, You may give me  a hint in  the  support site of the ckeditor plugin)
Bplaced has 'file get contents disabled' but there are other methods like 'get' - nevertheless i installed it manually.
