### ISSUE TITLE
Adding a specific layout in a second menutree and higher

### ISSUE THREAD

**Issue by gtbu** [Typesetter/Typesetter#288]
While it is possible to add a different Template to every single site in the first menutree m0 - this is not possible in the other menutrees - the point layout is missing.  It is also not possible to change the template of a site in a higher menu in the layout-editor, because this influences the standard-layout of the other sites.
---- As i found after deeper look at : Every site gets a data - index independent of the menutree - just depending of the sequence the site has been created  :  Data Index: i     //   $gp_index;
every template gets a crypted code in the pages.php (like dzrssmt) ( about _gpnonce i am not yet clear )
The executed code is then ...menu=gpmenu&cmd=uselayout&index=i&layout=dzrssmt&_gpnonce=e591...
It should be possible to add this point in the master for all trees...

**Comment by juek** [comment]
Use Admin Top Bar -> Options -> Current Layout
This will overwrite inheritance from the Main Menu.

**Comment by juek** [comment]
![grafik](https://user-images.githubusercontent.com/704283/42978186-d16b004a-8bcb-11e8-91af-df90c805fdfe.png)

**Comment by gtbu** [comment]
Thank You - now even i understood it . But is there a problem not to integrate it as for the other trees ?

**Comment by juek** [comment]
>But is there a problem not to integrate it as for the first tree m0 ?

I don't quite understand.
Once a layout is assigned to a certain page, all it's 'child pages' (as arranged) in the Main Menu (m0) will inherit it, unless explicitly set otherwise. 
1st-level pages in the Main Menu and all pages _not_ in the Main Menu will use the default layout, unless set otherwise.

**Comment by gtbu** [comment]
No - my thought was that if the link exists under options, then it should be easy to insert it under Layout (which is missing for the higher menus) just like in the pagemanager for the tree mo.

An example is my http://typesetter5.bplaced.net/Bootstrap-material-Mui demosite for material

**Comment by juek** [comment]
You can always redefine/overwrite $GP_MENU_ELEMENTS and $GP_MENU_CLASSES prior to a menu output call.

Example:

```
$GP_MENU_ELEMENTS = 'Sidebar_menu';
$GP_MENU_CLASSES = array(
  'menu_top'          => 'nav nav-stacked',
  'selected'          => '',
  'selected_li'       => 'active expanded',
  'childselected'     => '',
  'childselected_li'  => 'expanded',
  'li_'               => '',
  'li_title'          => '',
  'haschildren'       => '', 
  'haschildren_li'    => 'expandable', 
  'child_ul'          => 'nav nav-stacked',
);
gpOutput::Get('CustomMenu',1,4,1,1);
```

If you want to have seperate template.php files for different layouts, e.g. see how Bootswatch Flatly [does it](https://github.com/Typesetter/Typesetter/blob/master/themes/Bootswatch_Flatly/template.php).

Of course there are even more possibilities, such as splitting template.php into several parts and include them based on various conditions (like $page->theme_color, $page->requested, $page->gp_index, to name a few). There are actually no limitations.

try sth. like 

`msg( 'page object vars = ' . pre(get_object_vars($page)) );`

to see what might be usable for you.
