### ISSUE TITLE
Bootswatch 4 on Typesetter 5.1

### ISSUE THREAD

**Issue by gtbu** [Typesetter/Typesetter#289]
I tried to install Bootswatch4 Scss on 2 installations of Typesetter 5.1 with the error :
array(
   [type] => (integer)1
   [message] => (string)Uncaught ArgumentCountError: Too few arguments to function Bootstrap4_menu(), 4 passed and exactly 5 expected in /mnt/web020/a1/95/514/htdocs/MBINFO/tm1/tm/themes/Bootswatch4_Scss/drop_down_menu.php:5
Stack trace:
#0 [internal function]: Bootstrap4_menu('ul', Array, NULL, '')
#1 /mnt/web020/a1/95/514/htdocs/MBINFO/tm1/tm/include/tool/Output/Menu.php(995): call_user_func('Bootstrap4_menu', 'ul', Array, NULL, '')
#2 /mnt/web020/a1/95/514/htdocs/MBINFO/tm1/tm/include/tool/Output/Menu.php(647): gp\tool\Output\Menu->FormatMenuElement('ul', Array)
#3 /mnt/web020/a1/95/514/htdocs/MBINFO/tm1/tm/include/tool/Output/Menu.php(172): gp\tool\Output\Menu->OutputMenu(Array, 0, Array)
#4 [internal function]: gp\tool\Output\Menu->GetTopTwoMenu('', Array, Object(gp\Page\Edit))
#5 /mnt/web020/a1/95/514/htdocs/MBINFO/tm1/tm/include/tool/Output.php(651): call_user_func_array(Array, Array)
#6 /mnt/web020/a1/95/51478895/htdocs/MBINFO/tm1/tm/include/tool/Output.php(622): gp\tool\Output::ExecClass(false, '\\g
   [file] => (string)/mnt/web020/a1/95/5141234567/htdocs/MBINFO/tm1/tm/themes/Bootswatch4_Scss/drop_down_menu.php
   [line] => (integer)5
)
Of course i copied also the Bootstrap4-folder with css/js. On a new 5.1b1 it functions. What must i else patch ?
P.S. I replaced Leafo with V.075 - and it did not compile - but same error.
With the new Leafo Version 0.77 the CMS hangs completely( i only used the src-directory).

**Comment by juek** [comment]
> What must i else patch?

Hmm, there are quite some new dependencies in order o make Bootstrap 4 work – at least parts of the menu rendering. But there are quite a few more changes to other scripts. Replacing only parts of the system core is always a hazardous endeavour. I'd replace thw whole /include directory:

Rename your current /include directory to /include-5.1 and copy the 5.1.1-b1 version over to the server.
This will update your intallation to the current beta. 

For scssphp: Our implemented version 0.7.5 is a backport I made to meet Typesetter's minimum requirements. Haven't yet tested 0.7.7.

**Comment by gtbu** [comment]
What i dont understand is that i hang in the error while logged in - but when i log out then the materia is added to the specific site - just the menu is missing. 
Since Leafo compiles scss to css  there must be an incompatibiliy to the bootstrap 4 style or on other words : If i use the same template just with bootstrap 4 css then id does not function either ? - or has Leafo problems ?

**Comment by juek** [comment]
> there must be an incompatibiliy to the bootstrap 4 style of the template or of the CMS

Yes, it's the BS4 menu rendering that will not work with the TS 5.1 implementation.

> What i dont understand is, that i hang in the error while logged in, but after log out the materia is added to the specific site - just the menu is missing.

Typesetter isolates faulty components (if possible) and omits them unless the error is solved and marked as being so. This way the CMS will be able to continue operation. In your case it's the menu rendering that gets blocked. Non-logged-in users will not see the error details.
