### ISSUE TITLE
$GP_MENU_CLASS $GP_MENU_ID proposal

### ISSUE THREAD

**Issue by gtbu** [Typesetter/Typesetter#297]
Many templates try to add an ID to the nav or to the first ul.
With Jquery it is possible to $ (ul).attr(id, name) - but this does not function in all Typesetter - versions.

We have $GP_MENU_CLASS  to add a class to the ul - my proposal is to implement a variable
$GP_MENU_ID into typesetter which allows easy adding the ID without jquery. 
(One problem in typesetter is that it adds a DIV between the <nav and the first <ul. ) - visible in 'inspect element')
For me personally a codesnippet which i can add to the settings.php would be sufficient.

**Comment by juek** [comment]
Adding arbitrary ID attributes programmatically shouldn't be done unless it's absolutely inevitable. Any function doing so **must avoid** to assign multiple identical IDs (which is relatively easy with JavaScript but almost impossible server-side).

There is hardly any reason for using IDs except anchor scroll-targets and linking labels with inputs.

And there is **absolutely no** reason to use IDs for styling elements or targeting them via JavaScript. 
If we can apply unique IDs, we can apply unique css classes as well, which is safe.

If you still want to target your main menu ul via ID, wrap it into a div with an id in template.php and target it e.g. using `var main_ul = $("#main-ul-wrapper ul").first();`

**Comment by juek** [comment]
> With Jquery it is possible to $ (ul).attr(id, name) - but this does not function in all Typesetter - versions.

Of course it will work. Different jQuery versions haven't changed in this regard and probably never will.

**Comment by juek** [comment]
> To add the nav-id just does not always function $("ul.sm").attr("id", "main-menu") in the various typesetter versions - ...

It will work on all Typesetter versions including former gpEasy. It's plain and very simple jQuery. There must be sth. else gone wrong that prevents it. Just remember that any DOM manipulation should be only done when the document is ready (DOM ready event). While earlier jQuery versions preferred `$(document).ready( function(){ /* your DOM manipulation code */ });` , we now should use `$(function(){ /* your DOM manipulation code */ });` . Both do the same.

> The id="sm-15361390927628298-2" is added by smartmenu - …

Aria-labelling relies on IDs, The way Smartmenu adds them (using unique hashes) is fine.
