### ISSUE TITLE
Ajax-security

### ISSUE THREAD

**Issue by gtbu** [Typesetter/Typesetter#298]
I had some monthes ago the surprising problem that my start-site was put to private - i was able to put it back to public. After new installation with 5.1b1 i waited, and now a site of the second level was put to private, which a was able to put back. 
On another installation php7.1/TP5.1 all links had suddenly disappeared. After login i got a white field to clear all erros - at which i surprised did not look) - and after the clearing all links reappeared. The files were all unchanged public. Evtl. a manipulation of the css  to 'invisible' or something else. The template in all cases is 'Two Ponit 0'.
My site is obviously (also visible in bbclone) attacked by hackers who also attack the menu.
To put a site to private the standard is http://www.domain1.de/Admin/Menu/Ajax?cmd=ToggleVisibility&index=1h&visibility=private&menu=gpmenu  - which normally only  a logged-in user can execute with success - but perhaps also hackers with some unknown ideas.
My proposal is to connect the above order with a login- variable like &login. Another possibility is to limit the lenght of the URI for not logged-in users.
If You do not want to make changes in the CMS a code and an explaination where to put it would be sufficient  for me.

**Comment by juek** [comment]
When the mentioned URL is requested without being logged-in, you will be automatically redirected to the login page. 

If you are logged-in and such a request is performed e.g. by clicking on a crafted link 
sent in a phishing mail, the page with the given index will actually be hidden but the request will also take you to Page Manager where you will see the result of the action.

>  [...] which normally only a logged-in user can execute  with success - but perhaps also hackers with some unknown ideas.

Do you have any proof of this sort of attack vector?

**Comment by gtbu** [comment]
No - i just saw these 2 missing links, and found that they were private in the pagemanager. 
In the other installation (parallel) all the links of the menu had disappeared and immediately  after 'clear all errors'  they reappeared. 
How the hackers did that i do not know - it may be a security issue or an unknown way to access gpmenu or to set the link to private - i am not an experienced programmer -  and strato has a security shield.  I have no mails received from my site except my own function-test-mails.

**Comment by juek** [comment]
> […] after login and 'clear all errors' […] 

You haven't checked the error befor clearing it, have you? Would be helpful to track it.

> […] how to limit the URI-length […]

There are several ways but I cannot see the value of doing such.
* Limit input field length client-side – easy to bypass so it will not prevent any hack attempts at all.
* Limit length of certain string values stored in the  CMS backend. Depends on the certain case. Normally simple string truncation is not an appropriate sanitizing method.
* With [Suhosin](https://suhosin.org/stories/index.html) installed, limit [query value length via php.ini](https://suhosin.org/stories/configuration.html#suhosin-get-max-value-length). I wouldn't do that either – it will likely break lots if Ajax stuff.

**Comment by gtbu** [comment]
I did not check the error because i first thought that my system was destroyed - but i have backups - and i would have updated it to 5.1b1. -
If You put the complete url into a filter and redirect to a url which has a limited 'sitename + appendix '
- how can a hacker bypass it ? I have such a filter working in the above cmsimple-xh - the programmers felt a bit compromised about my idea which was also for the removal of a '?' in the url - the existing gxsecurity was crackable... 

A security improvement might already be a sha-384 appended to the dynamic generated combined js.

**Comment by juek** [comment]
Typesetter already has anti-CSRF measures (our CSRF token is called 'post_nonce', see e.g. [here](https://github.com/Typesetter/Typesetter/blob/bbcf8a5e58972ab99b57c56a1d36b3f7279c1009/include/tool.php#L1709)) but we don't use it in GET requests, which would be bad pactice. 

I agree that setting the page visibility should use POST instead of GET, because it changes the server state – hence it doesn't really qualify as a [safe method](https://tools.ietf.org/html/rfc7231#page-22). GET requests should only be used for reading stuff.

Anyway, if you believe you site was hacked without you having clicked a dubious link (e.g. in a phishing mail) while being logged-in to your TS site, the hacker must have used an authentication bypass vulnerability, we do not know. The page visibility cannot be changed unauthenticated. I firmly believe he would have done more severe stuff then.
