### ISSUE TITLE
Anchor problem with bootstrap4 templates

### ISSUE THREAD

**Issue by gtbu** [Typesetter/Typesetter#301]
I found a little problem in the Bootstrap4 templates. If you embed an anchor in an h2 or h3 heading, which is common (a in a toc), the anchor jumps under the top-header. Possibly this can be changed in the template by css?

**Comment by juek** [comment]
> Possibly this can be changed in the template by css?

Yes it can be done, and it would be reasonable to add it by default since the current Bootswatch 4 themes all have a fixed navbar. 

I'll push a commit short-term.

**Comment by juek** [comment]
Will work with [this commit](https://github.com/Typesetter/Typesetter/commit/d9fb06eb2dc2de65027bca651d626b90c1a29076)

**Comment by gtbu** [comment]
In my case (http://yogapathes.000webhostapp.com/SIVA-SAMHITA) the exchange ot the mentioned files did not help . After login : 👍 SCSS Compile Failed: Undefined mixin vp-flexbox: line: 20

**Comment by juek** [comment]
Sorry, I forgot to mention - you need to have [this recent commit](https://github.com/Typesetter/Typesetter/commit/eac99656819f330f69d786927ad0dce75251d004) that adds vendor-prefixing mixins to our Bootstrap 4 implementation. Just download the current master ZIP and replace the /include/thridparty/Bootstrap4/**scss** directory with the one from the current master.

**Comment by gtbu** [comment]
I have now also copied the comple bootstrap4-directory of the newest master - no change (and also deleted the cache)

**Comment by juek** [comment]
Do you still get a SCSS compiler error?

**Comment by gtbu** [comment]
No - i get no more errors -- the effect is in Firefox , in IE11 and in Chrome. 
The problems seems to be that the orientation is at  top:0 and not at top:(height of the top-bar)

**Comment by gtbu** [comment]
I have also tested the shift of the top of the site to under the header on Xampp - the same : You should revert the https://github.com/Typesetter/Typesetter/commit/d9fb06eb2dc2de65027bca651d626b90c1a29076 - commit because of people working with the newest master...

**Comment by juek** [comment]
Works here. The :target:before pseudo element does rather the same as the padding+margin hack. It's a matter of taste and of course the rest of the theme css. Both hacks may be easily overruled by other css, which I assume what happens with your theme if it doesn't work at your side. 

I do prefer margin+padding because I myself frequently use :before pseudo content on <a> elements (e.g. FontAwesome icons)

**Comment by gtbu** [comment]
The problem is just that i have a standard - installation at 000webhostapp.com.... ( 5.11b1 ) - just the Bootstrap4-Template You see there and no css patches. 
The alternative is to include both ! 
I had already problems with templates if i hooked 'put all css together' - or not (not with js). 
( I have put a question at the support of the to-top-button at typesetter.com)

**Comment by juek** [comment]
> What i disliked was that the top of the content was suddenly under the header

Sorry and thanks for pointing at this. My fault - I pushed a wrong version.
It will now work with [this fix](https://github.com/Typesetter/Typesetter/commit/de79c982443ece647f97949da5295f94e5306e18).
