### ISSUE TITLE
Update-check and plugin-download

### ISSUE THREAD

**Issue by gtbu** [Typesetter/Typesetter#306]
Since some time there is a cloudflare DDos-Filter before TypesetterCMS.com which blocks all downloads from within the cms. 
Is there a possibility to write an additional routine which communicates with cloudflare in the case of an error  - and waits for 10 seconds and tries anew (or to change the provider of the plugin - repository).
* PS Another possibility is to change the  download to https .  
For example 
https://www.typesettercms.com/Plugins/125_Anti_Spam_Math?cmd=download 
functions also

**Comment by juek** [comment]
I believe this should work again, for some time
