### ISSUE TITLE
Forgotten password sending wrong temporary password

### ISSUE THREAD

**Issue by bigalgeorge** [Typesetter/Typesetter#307]
Hi subject says it all - fortunately, old password works but emailed one never does.

**Comment by gtbu** [comment]
After test i found out, that i have the same 'problem'.  I  'solved' it for a moment by adding another user with the same rights...

**Comment by gtbu** [comment]
I had this problem with 5.1. After a new test i found out, that i still have the same 'problem' - only at Php7.x  I  'solved' it for a moment by adding another user with the same rights...

The problem is still more complicated . There are 2 possibilities to change the password after login. The second is to klick after login into : username >  'preferences' at the right side and then 'change password'. This will end in an error.... :  Oops, that didn't work. Make sure your old password is correct and try again.
 Your changes were saved. -- (they are not saved)

Evtl. this is connected with the above and i hope it will be fixed in a near time !

P.S. The Problem with not functioning lost password  exists only for users who use password_hash instead of sha512.

**Comment by juek** [comment]
> The Problem with not functioning lost password exists only for users who use password_hash

Currently I cannot confirm the bug (PHP 7.3 and password_hash), meaning that I can log in using the new password sent by e-mail. 

But we will hopefully be able to track it down.

**Comment by bigalgeorge** [comment]
Hi Jeurgen. I thought you had gone as there seems to be little activity on this project any more? But Typesetter is still the best flat-file CMS IMHO. I had to include Google Analytics into my site yesterday, and lo and behold someone has already written a plugin for that. Lovely.
Best wishes, Alistair.

**Comment by juek** [comment]
@gtbu 

> The problem is still more complicated . There are 2 possibilities to change the password after 
> login. The second is to klick after login into : username > 'preferences' at the right side and 
> then 'change password'. This will end in an error.... : Oops, that didn't work. Make sure your 
> old password is correct and try again.
> Your changes were saved. -- (they are not saved)

Most likely fixed with [this commit](https://github.com/Typesetter/Typesetter/commit/dd980b7ee6ed57254d67447d710168119534a50a), but please test on your side.

**Comment by juek** [comment]
@bigalgeorge 

> I thought you had gone as there seems to be little activity on this project any more? 

I had to take a backseat for a while and set other priorities. 

> But Typesetter is still the best flat-file CMS IMHO. 

Agreed ;) 
In fact, if possible, I still use it for many projects. And in recent months, there has been quite a few "by-catch", code-wise. I hope that I can at least bring some of it "into the wilderness" in the near future.

But let's get 5.1.1 (or 5.2) out first.

**Comment by gtbu** [comment]
Hm... - nobody seems to like my beta 2 at  https://github.com/gtbu/Typesetter5.1.1b2.
Do You want me to make a push ?

**Comment by mahotilo** [comment]
@gbtu
I appreciate any kind of progress with TS. I noticed your fork from its start and even have already successfully used it in one project, despite some problems with sections/page editor background sizing. I also found that it is possible to upgrade the Jquery to 2.x branch without any problems (but not to 3.x). 

As for me, I would be glad to see your updates in the TS master branch. But if you want to try to push community driven fork for 6.0, it will also be very interest.

**Comment by gtbu** [comment]
For jquery 2.x and higher etv. additionbal  jquery migrate 1.30 - 1.4.1 helps ?

**Comment by mahotilo** [comment]
I haven't tried "migrate" yet. What do you think about security issues in outdated Jquery versions, will "migrate" allow us to overcome them?

**Comment by gtbu** [comment]
I am nut sure 
* https://github.com/jquery/jquery-migrate/blob/master/warnings.md
* https://www.drupal.org/project/jquery_update/issues/2939759
but i think that the migrate - developers know this. 
I am planing jquery 12.4 in my coming CE 6-beta1

**Comment by juek** [comment]
Please let's start over the jQuery discussion in a new thread. That's not the right issue for that topic.

**Comment by juek** [comment]
> Do You want me to make a push ?

If you mean a pull request, sure. 
But not a single one for everything. Separate them in meaningful parts. which can be discussed individually.

> I would prefer a Typesetter 6 to get rid of the old code and expand the ckeditor and the UI.

I agree, basically. But if we do, we will likely have to sacrifice most existing unmaintained plugins.

**Comment by mahotilo** [comment]
> I agree, basically. But if we do, we will likely have to sacrifice most existing unmaintained plugins.

Can we propose a new branch TS 6.0 without automatic prompting for upgrade for TS 5.1?
Plugins do can be a problem but many of them are outdated anyway or could be easily fixed like e.g. BootstrapCarousel.

**Comment by juek** [comment]
> Can we propose a new branch TS 6.0 without automatic prompting for upgrade for TS 5.1?

If we break the support of older plugins and themes without Josh, we would also have to abandon typesettercms.com as a platform with all its remote install / update capabilities, the forum, and everything.
There is neither a 'max_gpeasy_version' in the plugins 'Addon.ini' nor anything like 'testing with versions x to y'. And we do not have access to most of them on typesettercms.com.

Mind that jQuery incompatibilities as well as CKEditor errors can brick a whole installation, with no way for non-developers to fix it.

Should be considered carefully whether it is worth it.

**Comment by bigalgeorge** [comment]
If it does happen, I'll put my hand up again to do a review on Youtube or comparison between TS & Bludit [http://alistairgeorge.com/Bludit_vs_Typesetter_CMS](url)

**Comment by gtbu** [comment]
I let You open what You want to to with my CE-Versions. But also 5.11b1 has problems with php 7.3 (less and scss-compilers) and the phpmailer is only 5.2.1 with security issuses - the js-compressor has errors. Perhaps can Joshua say something to that - his silence is  abit strange - but we can live with it.
If things go on  as at the moment then typesetter will have less than 0.02 % of the websites...

**Comment by mahotilo** [comment]
> There is neither a 'max_gpeasy_version' in the plugins 'Addon.ini' nor anything like 'tested with versions x to y'. And we do not have access to most of them on typesettercms.com.

But we have min_gpeasy_version. Can we block prompt for update if there is at least one plugin without minx_gpeasy_version=6?

**Comment by gtbu** [comment]
The update is only offered, if the installed version is older than the one in the repository. So there is no real problem.

**Comment by mahotilo** [comment]
> ...and not just proposals
:) Sorry for my bad English. 
I only try to propose to prohibit update for sites with old TS and old plugins after we will decide to broke their support and move with TS 6 to new technologies. So we can keep typesettercms.com as platform for new version and new plugins. Also, old installations will be protected from damages.

**Comment by mahotilo** [comment]
We have
```
 		if( version_compare($config['gpversion'],'1.6','<') ){
			die('Please upgrade to version 1.6, then 1.7 before upgrading to this version. You current version is '.$config['gpversion']);
		}

```
in Upgrade.php.

Thus, we can prohibit upgrading from 1.x, - 5.x. It is allowed only clear installation for 6.0 and following upgrade from 6.0 to 6.1 and further.

**Comment by gtbu** [comment]
We have  a min-gepeasy entry in the addon.ini. There is a point in typesetter to show only the plugins which are ready for the installed version. The user must act carefully. We should improve the documentantion.

**Comment by mahotilo** [comment]
This is not about protection against installing obsolete plugins, but about how to protect against upgrading to TS, which will kill plugins already installed.
And according to the Forum, many TS users are far from PHP and JS.

**Comment by juek** [comment]
> This is not about protection against installing obsolete plugins, but about how to protect against upgrading to TS 6.0

Exactly, *but also* older plugins may break a new Typesetter 6 installation.

**Comment by mahotilo** [comment]
> Exactly, but also older plugins may break a new Typesetter 6 installation.
So, I propose to completely prevent installation of TS 6.0 on sites with obsolete plugins.

**Comment by gtbu** [comment]
For what do we have a backup-function under Tools (evtl. not in older gpeasy versions ?) .....hm ...i will have to write a full-backup-plugin (i have the code - written for Cmsimple XH) . The zip lands the in the uplads directory. Please waite one week )
