### ISSUE TITLE
Cloudflare blocking problem

### ISSUE THREAD

**Issue by gtbu** [Typesetter/Typesetter#312]
After publishing the blocking - problem within the  cloudflare community  at
https://community.cloudflare.com/t/cloudflare-delay-hinders-downloads-from-typesettercms/77205/6  I was informed that a person which activated cloudflare for the typesetter cms has activated the 'attac mode' (there are other modes)  - i just do not know if Joshua Schmidt activated the firewall for typesettercms in cloudflare  - he must have the rights to do it !

**Comment by mahotilo** [comment]
Yes, current situation with Cloudflare protection is show stopper.

**Comment by mahotilo** [comment]
May be closed because the Cloudflare blocking is off now
