### ISSUE TITLE
Any progress on this problem? - to not being able to fetch addons and themes through the UI?

### ISSUE THREAD

**Issue by FAFDK** [Typesetter/Typesetter#313]
Just a followup:

It works somewhat on 7.2.18-1. There are no details on the addons, but they are downloadable nonetheless.

Any progress on this problem? - to not being able to fetch addons and themes through the UI?
----------
Error Message: Sorry, the addon data could not be fetched.

Is it PHP7.* related?

Backtrace
--
File | /include/admin/Addon/Install.php
Line | 363
Class | gp\admin\Addon\Install
Function | ParseResponse

Redir | 0
FailedMethods | stream,
NotSupported |  
stream | no handle
lang_key | Sorry, data not fetched

PHP Version | 7.2.14-1+0~20190113100742.14+stretch~1.gbpd83c69
CMS Version | 5.1
index.php Rewrite | True
Server Software | Apache/2.4.25 (Debian) mod_fcgid/2.3.9 OpenSSL/1.0.2q

_Originally posted by @FAFDK in https://github.com/Typesetter/Typesetter/issues/308#issuecomment-468919826_

**Comment by gtbu** [comment]
Though this is more for the forum : I have 3 installations at php 7.2 and one with php 7.3 which function without problem : If You go in the cms at tools - > site status : Are all files ok. Otheriwse please klick within filezilla portable (sftp) with the right mousekey at the installation directory - in the popup at rights ans set the rights of this directory and of the subordinate directorie and files to 755. If this does not help please open a new directory and make a new installation, set the rights to 755 and put a subdomain at it.
I never had problems with this method

**Comment by FAFDK** [comment]
Thank you for your comment. I will go to the forum next time. The files are ok in the check, so I will go further and see how the rights are set. I host myself though so I have free hands. Also, I think that 755 is a bit open but I will see if there are any permissions that can be set to fix this problem. Thank you again for the hint.
