### ISSUE TITLE
no option to discard the draf contents one the old revision are restored

### ISSUE THREAD

**Issue by mckaygerhard** [Typesetter/Typesetter#315]
currently after restored the contents of a edited page the message and edited content still are offered and said "publish draf" once inclusivelly if i restored sussesfully a older revision

using typesetter 5.1 lasted stable

the php and server i guess dont make sense

**Comment by gtbu** [comment]
How did You restore ?  - from a backup of the cms ?

**Comment by mckaygerhard** [comment]
**see the picture**, it's a draf! men! not a backup.. **i make a "new edit of the same page" and then i want to get back to the previous.. restored but the draft still are there!**

![http://www.typesettercms.com/data/_addondata/x_Addons/user/50/4963/Pantallazo-1.png](http://www.typesettercms.com/data/_addondata/x_Addons/user/50/4963/Pantallazo-1.png)

**Comment by angerangel** [comment]
Untill you don't edit the current page, the draft will be there. Draft is a version never published. I think it will flow to the bottom as soon you make new edits.

**Comment by juek** [comment]
Yep, this one should be fixed.

**Comment by juek** [comment]
Ok, I just checked that. Let's clarify the behavior.

> see the picture, it's a draf! men! not a backup.. i make a "new edit of the same page" and then i want to get back to the previous.. restored but the draft still are there!

When you restore an older revision by clicking [ Restore this revision (Nov 13, 2019 @ 10:48) ], **this revision** will become a new Working Draft (old, existing drafts will be discarded).

Therefore, you will have to click [ Publish Draft ] to eventually make the **just restored revision** your 'Current Page'. 

Although, 'Draft' is a bit misleading in this special situation, the way it works is intended and correct. This way, you can still edit your restored page revision before you make it public again.
The button could in this case actually read 'Finalize restoration' and only turn back into 'Publish Draft' once you make edits. 

Anyway, your assumption that an old draft is used is not true.
