### ISSUE TITLE
Parameter must be an array or an object

### ISSUE THREAD

**Issue by gtbu** [Typesetter/Typesetter#317]
https://github.com/Typesetter/Typesetter/blob/master/include/Page/Edit.php
 line 1111 :::  $is_wrapper = count($types) > 1 || is_array($types[0]);
gives a debug error
Warning: count(): Parameter must be an array or an object that implements Countable in /include/Page/Edit.php on line 1111.
should be 
$is_wrapper = count((array)$types) > 1 || is_array($types[0]);

**Comment by juek** [comment]
should be fixed with [this pull request](https://github.com/Typesetter/Typesetter/pull/310/commits/b18149568005d67c786cec7a3f0e8da602a04f02)
