### ISSUE TITLE
Cloudflare loading

### ISSUE THREAD

**Issue by gtbu** [Typesetter/Typesetter#319]
In include /tool / Output / Combine.php in line 74-75
'CloudFlare'	=> '//cdnjs.cloudflare.com/ajax/libs/jqueryui/1.10.4/css/jquery-ui.min.css',
													'Google'		=> '//ajax.googleapis.com/ajax/libs/jqueryui/1.10.4/themes/smoothness/jquery-ui.min.css',

Should be 'themes/smoothness/jquery-ui.min.css' in both cases- otherwise  content -> Uploaded files doesnt function, if the js-es are loaded from cloudflare (google and local function)

* As there seems to be no more support, i have  opened https://github.com/gtbu/Typesetter5.1.1b2 which contains all known issuses and more...

**Comment by juek** [comment]
Works here. Must be sth. different on your side.
