### ISSUE TITLE
child thumbnails plugin syntax error

### ISSUE THREAD

**Issue by gtbu** [Typesetter/Typesetter#321]
in  line 73 of Child_thumbnails.php should stand
} else  {     
ie. {  
 instead of (

corrected in  https://github.com/gtbu/Typesetter5.1.1b2

**Comment by juek** [comment]
Original [Child Thumbnails plugin](https://www.typesettercms.com/Plugins/238_Child_Thumbnails) ver. 1.0 does not have this issue. Line 73 is empty and there is no '} else {' at all. You are probably using a version from a different source.
