### ISSUE TITLE
Bootswatch flatly 1.01

### ISSUE THREAD

**Issue by gtbu** [Typesetter/Typesetter#323]
In the repository is a 4 yeárs old flatly 1.01 https://www.typesettercms.com/Themes/245_Bootswatch_Flatly - which is offered as update in typesetter - small bug only
[Frontend framework section] makes problems  for flatly and scss under plugins (not scss4)

**Comment by juek** [comment]
[This](https://github.com/Typesetter/Typesetter/commit/1bea249c8f0deb3e68d0cb6908589774a8f34201) will prevent the update.
Unfortunately it will also update the theme on existing sites when updating to the next Typesetter release, which will cause loss of possible adjustments if not done properly.

> … makes problems for flatly and scss under plugins …
can you specify 'problems'?

**Comment by gtbu** [comment]
In my version 5.11b2 appear two plugins - one for flatly (which also  offers update to 5.01) and one for scss under 'plugins'. Removal of the [Frontend framework section]  in the addon.ini lets them disappear.... (neither for scss4 nor for cajon)

**Comment by juek** [comment]
You should be more precise with version numbers.
Such as 5.1.1 instead of 5.11, which is a completely different thing, also 1.0.1 and 1.01, etc.
Any version comparison with such inaccuracies leads to false results.

**Comment by juek** [comment]
For plugins and themes: 
In fact, themes should only get (also) listed under plugins when they contain plugin functionality, such as Cajón Scss. 

[FrontEndFramework] is a new (beta) feature and, as far as planned, it will not contain functional elements which would qualify as plugin hook. So it will probably be filtered out of the plugin list.

**Comment by juek** [comment]
I'm not sure yet about the term FrontEndFramework, as it rather makes us think of React, Angular, Vue, etc. these days.

Although Bootstrap also includes quite some JavaScript, it refers to itself as a 'front-end CSS framework' or 'CSS framework'. Sometimes it is also called 'Fronend Development Framework'.

**Comment by gtbu** [comment]
Sorry - i gave You a misinformation. It is not the  [Frontend framework section] . I looked deeper in my beta2 and in your beta 1. After installation of Bootswatch scss the theme appears as a plugin under plugins...- same with Flatly. This is a bit disturbinbg for the user.
