### ISSUE TITLE
Missing -resubmit

### ISSUE THREAD

**Issue by gtbu** [Typesetter/Typesetter#324]
In https://github.com/Typesetter/Typesetter/blob/master/include/tool/Output/Combine.php line 74/75
//jquery ui core
should be  :
https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.10.4/themes/smoothness/jquery-ui.min.css  

UI : Smoothness is missing : otherwise gpfinder does not function with cloudflare !

**Comment by juek** [comment]
> -resubmit

And again: It works here and I cannot reproduce the issue. 
I assume, it does work for others as well – if finder was broken, I firmly believe that folks would have noticed and reported it.

The relevant stylesheet will be served by cloudflare both encrypted (https) and unencrypted (http), so I cannot see why it should matter to enforce the protocol. Simply putting 'https:' in front oft the URL is treating the symptom not the cause. We won't do that.

Thus, 2 questions arise:

1. What is the symptom? Namely, what does 'does not function' mean exactly?
2. What is the cause, which seems to only exist on your side?

**Comment by gtbu** [comment]
As You see in this chapter the files for jquery ui are loaded : At the moment it is 👍 
Line 69	//jquery ui core
			'ui-theme'	=> array(							'file'			=> '/include/thirdparty/jquery_ui/jquery-ui.min.css',
									'type'			=> 'css',
									'package'		=> 'jquery_ui',
									'cdn'			=> array
'CloudFlare'	=> '//cdnjs.cloudflare.com/ajax/libs/jqueryui/1.10.4/css/jquery-ui.min.css',
'Google'		=> '//ajax.googleapis.com/ajax/libs/jqueryui/1.10.4/themes/smoothness/jquery-ui.min.css',

The /jquery-ui.min.css', from cloudflare is differetm from

**Comment by juek** [comment]
Once and for all I'd like to clarify something: 

When I say 'It works here' I mean it, OK? So please stop repeating 'just try it'. Believe me, I do.
When I ask for an error description, 'doesn't work' or 'hangs' is not sufficient. I know you can do better. Error logs, Browser inspector tools, you name it.

> … from cloudflare is different...

They are all a bit different. Cloudflare actually serves 1.11.4 when requesting 1.10.4.
E.g. [see tihs diff](https://www.diffchecker.com/oFZZqyS3)
Although not entirely impossible, it's hard to believe that a few differences in a stylesheet **completely break** functionality of gpFinder. Therefore I assume there must be something different going on. And whatever it is, this is what we need to find.

Of course, for god's sake, we can simply change the URLs. But this way we won't find the real cause.

**Comment by gtbu** [comment]
When i found this error, i made  hooks like in http://demo-11e9881b98450d4.typesettercms.com/Admin/Configuration/CDN , then emptied the cache (!) and  went into the filemanager (as
http://demo-11e9881b98450d4.typesettercms.com/Admin/Uploaded#elf_l1_Lw ) - and the icons were frozen. 
Then i looked at the CDN and at Line 69 //jquery **ui core**  and found that CDN is loading from /1.10.4/css/ and google is loading from /1.10.4/themes/smoothness/...  . So i changed the CDN from /1.10.4/css/ to /1.10.4/themes/smoothness/  and it worked - also in my CE - that all i can say (and  now i will take refuge to my deathprotector..http://www.spiritwiki.de/w/Yamantaka..  ) - thats life....
