### ISSUE TITLE
Proposal - admin Panel

### ISSUE THREAD

**Issue by gtbu** [Typesetter/Typesetter#326]
During the work in the site the **admin  panel** hangs around. A momentary solution is to shift it to the top  and make it small. Then a mouse hover gives easy access to the lines. The  position is remembered by a javascript.  
* My proposal  is to make a dropdown with mouse hover  ( beside 'Options'  as 'Dashboard') out of it.

* My alternative proposal to page and new sections  is :  building blocks or text bricks (Text - Bausteine).

* In a new version i would make  a mouse hover  dropdown  out of the 3 Points ( custom css, extra content ,page)  and take the ckeditor into a sepearte dropdown -li. ( Heading : Site - Tools )

**Comment by juek** [comment]
Hmm, "Blocks" is the name of the current WordPress 5 editor (AKA Gutenberg), which is widely rejected by the community (including myself ;o). At the moment I would not adopt this name - it is badly connoted. Our "Sections", which have been in this form for more than 5 years, are still superior IMO. 

Regarding your other suggestions: I agree that the admin UI should be overhauled, become less redundant and more task-oriented. I would like that for the next major release.

**Comment by gtbu** [comment]
I would take text bricks (german Textbausteine) because many  users do not study this point otherwise(!). 'Typesetter' and 'text bricks' - fits together. And Wordpress : Who wants to compare Typesetter with wordpress and its complicated tree-management and editing modes.
Typesetter ist for easy, fast and intuitive work - and already with this have many users problems

The next major release - when ..... will it come as alpha. It should leave php 5.x behind  and have an extended api - and still be compatible. My 'planned alpha' stands the alone because i am not an experienced programmer.
