### ISSUE TITLE
Available Classes usage is broke

### ISSUE THREAD

**Issue by mahotilo** [Typesetter/Typesetter#336]
I see such a picture with the last TS beta.

![image](https://user-images.githubusercontent.com/14929385/70095472-7f1a7080-162d-11ea-981f-2e5586e7ef76.png)

**Comment by juek** [comment]
ah, must be the new .gpselect style…

**Comment by juek** [comment]
[fixed](https://github.com/Typesetter/Typesetter/commit/e6b8ff9f8c194dca5b9b9364b459feccdcb1b773)

In fact it was a reformatting issue.

**Comment by mahotilo** [comment]
Well, it is really fixed for a standard theme. To see result we need to change current theme.

But, it does not help in the case of my "modified" TS:) FYI. All modifications are JQuery 2.2.4 and BS 4.1.3, plus Combine.php (for URL in CDN). With beta, 1 these modifications did not interfere with admin part of CMS.
