### ISSUE TITLE
Poll: keep Scss/LESS source maps?

### ISSUE THREAD

**Issue by juek** [Typesetter/Typesetter#344]
should we implement a Configuration entry (or better a gpconfig.php constant) to keep source maps for compiled Scss and LESS?

They will probably use quite some disk space but sometimes I really miss them.

What do you think?

**Comment by mahotilo** [comment]
I think it can't be a plugin, can it? Could this be an installation option or some additional installation pack age to add to an existing project without hand work?
We do need to save space, especially with LESS, for users with 500MB-1GB hosting limit.

**Comment by juek** [comment]
> I think it can't be a plugin, can it?

Nope. 

> Could this be an installation option

It's clearly a feature only developers (with file system access) would benefit from, therefore it could also go to gpconfig.php

**Comment by mahotilo** [comment]
And what about map from thirdparty (like jquery.min.map)? Do we need to include them in a *developer* installation also?

**Comment by juek** [comment]
> And what about *.map from thirdparty (like jquery.min.map)? 

Although we get errors in jquery.js some time, they normally derive from calling a jquery method with improper argument(s), so a backtrace will reveal the real fault. 

No, it's really meant for Scss/LESS debugging – especially for cases when large amounts of files are imported or classes extend each other. Even with clear naming, some rules to blame for specific issues are cumbersome to locate without source maps. 

Stuff like this:
![grafik](https://user-images.githubusercontent.com/704283/70540392-76fa8d80-1b65-11ea-8a97-38387e787e7c.png)

**Comment by oyejorge** [comment]
A gpconfig constant seems like a good way to do this

**Comment by juek** [comment]
> A gpconfig constant seems like a good way to do this

Well then I'll do it.

**Comment by juek** [comment]
basic implementation with [this commit](https://github.com/Typesetter/Typesetter/commit/c781f5a4814970a580ed2d7bec70d224e03a5a95)

**Comment by juek** [comment]
BTW: it turns out that the .map files for typical Bootstrap-based themes remain in an absolutely acceptable size range (< 100 KB).

**Comment by mahotilo** [comment]
Less .map is bigger:)
