### ISSUE TITLE
Prohibition of simultaneous editing.

### ISSUE THREAD

**Issue by mahotilo** [Typesetter/Typesetter#349]
We have no possibilities for two users to edit site at the same time. Is it hard to limit this prohibition to only simultaneous editing of same page? Sometimes it really stops cooperative work.

Of course, it is not a common situation, so this is not an issue, rather just a question.

**Comment by juek** [comment]
> Is it hard to limit this prohibition to only simultaneous editing of same page?

Unfortunately it is. We would have to (separately) lock other things too, such as extra content areas, menu settings, well almost anything that could potentially write to $config, $gp_index, $gp_titles, etc.
It's one of the drawbacks of all-in-one wysiwyg editing and flat file storage. Or, to put it this way: As Josh didn't do it, I will not even try ;)

**Comment by mahotilo** [comment]
> Since Josh didn't do it, I will not even try ;)

Just to clear  up the restrictions.

I mean simultaneous editing two different pages by two different users with maybe different rights. Could we just temporary block all Grant Usage permissions for the second logged user as well as all File Editing rights for pages edited be the first user? It will be quite sufficient to simply add some info on some page, e.g. set an image titles in a gallery. Of course, we still will have huge problems with the first user rights, they have to be dynamically restricted too... 

We now allow a second user to log into the site, see all settings and navigate through pages with warning and a set of restrictions. I am wondering maybe there is a simple and safe way to give him back safe part of his rights to make some changes and save results? Without huge reworking of all CMS.

Of course, this is not a number one priority. It is just "For My Interest" and maybe for the answer to the same "issue" in the future:)

**Comment by juek** [comment]
First of all we'd have to clarify what 'currently edited' exactly means. Is it already a user with editing permissions viewing a particular page or is it an open editor for a page's content or an extra area? I would say it is the latter.

Then we would have to define a 'protection period' until the 'currently edited' status automatically expires. With, let's say, 2 minutes or more, we should also implement a manual 'release' button, so other user(s) can take over immediately.

Furthermore - and that's the most complex part - we would need an auto-update feature for everything currently **not** edited by, but visible to other users. This could be an interval or some sort of 'push' mechanism. That's really hard to do right.

**Comment by mahotilo** [comment]
OK, now I see. We can allow simultaneous editing for responsible and sensible users, but we can't easily  protect regular users from getting into trouble.

**Comment by juek** [comment]
Yep, IMO it would need fundamental changes in the way Typesetter renders pages. 
Such as say farewell to jQuery and hello to React.js. Not after my fancy.

**Comment by juek** [comment]
Maybe its just sth. like …

![grafik](https://user-images.githubusercontent.com/704283/70854202-df74a200-1eb8-11ea-8291-5df85fcb464f.png)

![grafik](https://user-images.githubusercontent.com/704283/70854206-e8fe0a00-1eb8-11ea-8853-0fa204ce9399.png)

… but I don't believe it's much easier to do.

**Comment by juek** [comment]
… and 
![grafik](https://user-images.githubusercontent.com/704283/70854382-24013d00-1ebb-11ea-8a88-138e33b3dcc5.png)
 LOL

**Comment by mahotilo** [comment]
Or the "main" admin can lock some page for himself and granted this way the page for other users. Your notification system can show him current status of granted pages. We can consider a page under edition if there is a working draft. "Main" admin can also take control back at any moment and reject draft from another  user...

**Comment by juek** [comment]
> "Main" admin can also take control back at any moment and reject draft from another user...

This would require user roles.

Let's keep it in mind. It will certainly not make it into 5.2 but maybe I stumble upon an appropriate position for a plugin hook to manage basic temporary permissions.

**Comment by mahotilo** [comment]
> It will certainly not make it into 5.2 

Definitely.

All this is just to give an answer why do we allow the second (or the same) user to log in at all? :)

**Comment by juek** [comment]
> All this is just to give an answer why do we allow the second (or the same) user to log in at all? :)

Nobody knows. Evolution (or god - you decide) sometimes takes strange paths.

**Comment by mahotilo** [comment]
> This would require user roles.

We have some already

![image](https://user-images.githubusercontent.com/14929385/70854537-e950d200-1ec5-11ea-80b9-022b0e297936.png)

**Comment by mahotilo** [comment]
> Nobody knows. Evolution (or god - you decide) sometimes takes strange paths.

Until Yamantaka not here I prefer evolution:)

**Comment by juek** [comment]
I actually prefer Yamaha.
