### ISSUE TITLE
Problems with images created in elFinder

### ISSUE THREAD

**Issue by mahotilo** [Typesetter/Typesetter#357]
I created an image in elFinder. Don't ask me what for:)
Then I found that the image doesn't have a thumbnail. I ran "Recreate All Thumbnails" and caught an error about strange memory overflow
![image](https://user-images.githubusercontent.com/14929385/70869391-1919db80-1f93-11ea-8300-0d7f865646a4.png)
Is it only for me? 
Should we keep this ability to create/edit images?
Should we initiate thumbnail update after creating/editing image?

**Comment by juek** [comment]
How large is your original image in pixels?

**Comment by juek** [comment]
And question 2: How many images have you already uploaded? 
Recreate all thumbnails may easily exceed available memory with many and/or large images.

**Comment by juek** [comment]
Ok, I've already done some math:
The memory size 134217728 (bytes) corresponds to 128 MB. This is most likely the maximum amount of memory PHP can allocate on your server.

That means you cannot process single images larger than ~ 40 megapixels. Or with 'Recreate all thumbnails' there must be no more than ten 4-megapixel images (or forty 1-megapixel images) in your /data/_uploaded/ folders.

Have you perhaps exceeded these values?

"Recreate all thumbnails" is one of the things that could be improved. If it was called via AJAX, image after image, we could use the entire memory for each process.

**Comment by mahotilo** [comment]
Sorry for delay.

1. It is clear test TS install
2. I have 7 files for a gallery and elFinder tests. All of them are quite small.
3. Created files have default sizes  300x150 x 32bit
4. Images with Cyrillic names and spaces pass without problems

```
d:\Internet\www\root\Ts-c\data\_uploaded\image\
cofee.jpg	206466	2018.6.25	22:28.28
cofee2.jpg	157070	2019.12.8	17:37.36
index.html	13	2018.6.21	6:46.44
logo-big.png	16273	2019.12.8	17:36.50
NewFile.png	5399	2019.12.15	23:30.26
NewFile 1.png	3688	2019.12.15	23:34.46
Pieter Bruegel the Elder -Охотники в снегу.jpg	8353832	2019.12.15	0:46.30
Кричевський Василь - Три віки - 1913.jpg	1317942	2019.12.8	17:37.46
```

**Comment by mahotilo** [comment]
> Or with 'Recreate all thumbnails' there must be no more than ten 4-megapixel images (or forty 1-megapixel images) in your /data/_uploaded/ folders.

Never meet such limitation. I have successfully processed hundreds of images with a total size of abut  300 MB and the only thing I needed to do was increase php time limit.

**Comment by juek** [comment]
Sorry for the delay either. Maybe it's a permission issue for the newly created file.
I yet have to replicate the problem.

**Comment by juek** [comment]
Pieter Bruegel the Elder -Охотники в снегу.jpg

Depending on compression rate, a > 8MB JPEG could well be an edge case in terms of memory usage. What pixel dimensions does it have?

**Comment by mahotilo** [comment]
Sorry, it was 6819x4853 24 bit ~100MB. I can't even remember where he came from.
'Alter schützt vor Torheit nicht'...

Surprisingly, it was converted into a thumbnail successfully. The glitch was in the next small image. So, there is no TS problems with memory.

Nevertheless, we still don't have automatically generated thumbnails for images created via right click in elFinder.

**Comment by juek** [comment]
> Nevertheless, we still don't have automatically generated thumbnails for images created via right click in elFinder.

I'm tempted to throw this and the remote editors out. I consider it rather useless.

**Comment by juek** [comment]
> Surprisingly, it was converted into a thumbnail successfully... 6819x4853 24 bit ~100MB

With 128 MB ram it will work for a single image but most likely fail when regenerating all thumbs at once.

**Comment by mahotilo** [comment]
For sure, my "mega" image is excessive for TS , as well as the create/edit context menu related to external services and security problems.

**Comment by Sestowner** [comment]
If you don't mind, I can remove remote editors.

**Comment by juek** [comment]
> If you don't mind, I can remove remote editors.

I'm already working on it. But it seems you know elFinder better than me.
Let me push my latest edits (in a few minutes), then Let's discuss further work steps.

elFinder 2.3.2 is way too dependent on remote sources for my taste. 
I want Typesetter to works completely offline (e.g. in an intranet behind a firewall or on a local server w/o internet at all)

I am currently fighting with require.js. It's a tough fight :)

I'll be back short-term....

**Comment by juek** [comment]
ok, just sync these and then let's see

https://github.com/Typesetter/Typesetter/commit/07af67ebc7b44ff674f277b95f452fdcdadc5bd1

https://github.com/Typesetter/Typesetter/commit/22890d8e3ec5a2a19bd5d664c5c3b809662f0506

https://github.com/Typesetter/Typesetter/commit/a1511defa1b65931998de8b9ecde4462cc838bb0

**Comment by juek** [comment]
we might need to move from `/js/elfinder.full.js` to` /js/elfinder.custom.js` ( and then -> `elfinder.custom.min.js` for production)

**Comment by juek** [comment]
As you can see in my latest changes, I already …

* disabled all editors except CKEeditor and CodeMirror
* told elFinder to use our local CKEditor and CodeMirror (CodeMirror should be updated for that purpose and probably needs additional modules)
* made elFinder use our local jQuery (1.12.4), which seems to work but still needs testing
* tried to make elFinder use our local jQuery_UI (1.12.1), which should work out of the box because it's the same version, but require.js doesn't play along (see comments in main.custom.js lines 120+)

**Comment by juek** [comment]
Oops, we shouldn't use this issue for further discussion (off-topic). I'll start over a new one...
