### ISSUE TITLE
make elFinder work offline (without CDN sources)

### ISSUE THREAD

**Issue by juek** [Typesetter/Typesetter#360]
Continuation of the discussion started in https://github.com/Typesetter/Typesetter/issues/357
Requires to pull commits https://github.com/Typesetter/Typesetter/commit/07af67ebc7b44ff674f277b95f452fdcdadc5bd1 , https://github.com/Typesetter/Typesetter/commit/22890d8e3ec5a2a19bd5d664c5c3b809662f0506 and https://github.com/Typesetter/Typesetter/commit/a1511defa1b65931998de8b9ecde4462cc838bb0
update: also get https://github.com/Typesetter/Typesetter/commit/f62b0e75ddf70ea086a6acf3de11355ab882f06c

**Comment by juek** [comment]
That's merely a copy of the my last reply in https://github.com/Typesetter/Typesetter/issues/357

As you can see in my latest changes, I already …

* disabled all editors except CKEeditor and CodeMirror
* told elFinder to use our local CKEditor and CodeMirror (CodeMirror should be updated for that purpose and probably needs additional modules)
* made elFinder use our local jQuery (1.12.4), which seems to work but still needs testing
* tried to make elFinder use our local jQuery_UI (1.12.1), which should work out of the box because it's the same version, but require.js doesn't play along (see comments in main.custom.js lines 120+)

**Comment by juek** [comment]
In the end, I assume that we will need lo add a custom JS callback function for elFinder's require.js configuration in order to load jQuery and jQuery_UI components locally **or** from CDN, if CDN-loading is selected in Typesetter Admin Menu -> Configuration -> CDN

**Comment by oyejorge** [comment]
Anything you'd like me to look into?

**Comment by juek** [comment]
> Anything you'd like me to look into?

Well, I don't yet understand how to tell elFinder to use local (and already loaded) jQuery and jQuery_UI. Require.js on every corner.

**Comment by oyejorge** [comment]
How does that look?

**Comment by juek** [comment]
> How does that look?

Good!

**Comment by juek** [comment]
Could you also put some of your magic on local CodeMirror and CKEditor?

BTW: just [added](https://github.com/Typesetter/Typesetter/commit/58c78247a44ddc30988819ef58ee3adaf418d5b3) zlib.js for elFinder's archive preview.

**Comment by juek** [comment]
I also wonder if we should include a more capable dist of CodeMirror (in terms of modes and addons) and add it to loadable components? Plugins like [this one](https://github.com/juek/AddScriptPluginTypesetter) could also benefit from it.

**Comment by oyejorge** [comment]
FYI. I generated a new ckeditor package from their [Builder](https://ckeditor.com/cke4/builder)

The build configuration is [here](https://github.com/Typesetter/Typesetter/blob/master/include/thirdparty/ckeditor/build-config.js)

Note, this ckeditor package does not use /include/thirdparty/codemirror

**Comment by juek** [comment]
I just [updated](https://github.com/Typesetter/Typesetter/commit/9e266692c469d707bf4f68a381bc0273e89d9557) CodeMirror to 5.49

**Comment by juek** [comment]
My current issue with CodeMirror was with elFinder (for editing text/html/js/css, etc)

**Comment by juek** [comment]
OMG the CKEeditor codemirror plugin is a bit bloated with all the themes.
Didn't we want to get rid of bloat? Ah, what the heck.

**Comment by juek** [comment]
Oh, we already had CodeMirror in CKEditor? Well then,,,

**Comment by oyejorge** [comment]
78 files for one ckeditor plugin is a lot. Pretty sure we didn't have ckeditor in CodeMirror

**Comment by juek** [comment]
> Pretty sure we didn't have CodeMirror in CKEditor

You're right. I had already pulled your penultimate commit. 

Hmm... it adds ~ 1 MB (255 KB compressed to the distribution zip)

**Comment by juek** [comment]
On the other hand, it's a nice to have and only loads when opening "Source View".

Let's keep it. I'm pretty sure folks will like it

**Comment by oyejorge** [comment]
Works for me

**Comment by mahotilo** [comment]
> I'm pretty sure folks will like it

Yes, I will.

I see some glitches. Disabled buttons in main Ckeditor menu and buttons in source view with non-default form.

Is it due to TS custom css? Or it is just me, as always:)

![image](https://user-images.githubusercontent.com/14929385/70972985-5f635d80-20ad-11ea-862f-c5ae0738cf80.png)
![image](https://user-images.githubusercontent.com/14929385/70973015-743ff100-20ad-11ea-8acd-8c27b80acd42.png)

**Comment by juek** [comment]
> as always:)

Not this time

**Comment by juek** [comment]
/include/thirdparty/ckeditor/plugins/codemirror/js/codemirror.mode.**php**.min.js
LOL, exactly what we need

**Comment by juek** [comment]
Unfortunately it's extremely hard to find and almost impossible to remove from the compressed source.

**Comment by juek** [comment]
I'll try a new uncompressed build, fix the issues and then compress it. Let's see if it will work.

**Comment by juek** [comment]
@oyejorge Typesetter also speaks Icelandic and Bulgarian ;)

**Comment by mahotilo** [comment]
I added

> 	config.codemirror = {
> 		theme: 'material',
> 		showCommentButton: false,
> 		showFormatButton: false,
> 		showUncommentButton: false
> 	};
> 

to include\thirdparty\ckeditor\config.js 
and have positive results

**Comment by juek** [comment]
I added ...

Thx, I'll try it immediately

**Comment by juek** [comment]
```
CKEDITOR.editorConfig = function( config ) {
	// Define changes to default configuration here. For example:
	// config.language = 'fr';
	// config.uiColor = '#AADC6E';

	config.codemirror = {
		theme: 'material',
		showCommentButton: false,
		showFormatButton: false,
		showUncommentButton: false
	};
};
```

does nothing here :(

**Comment by mahotilo** [comment]
```
CKEDITOR.editorConfig = function( config ) {
	// Define changes to default configuration here. For example:
	// config.language = 'fr';
	// config.uiColor = '#AADC6E';
	
	config.codemirror = {
		showSearchButton: false,
		showCommentButton: false,
		showFormatButton: false,
		showUncommentButton: false,
		showAutoCompleteButton: false
	};
};

```

Hm, it helps me

![image](https://user-images.githubusercontent.com/14929385/70980275-afe1b780-20bb-11ea-9003-5798d761b2f3.png)

**Comment by juek** [comment]
Good hint, seems as if I managed to [hack it out](https://github.com/Typesetter/Typesetter/commit/a84d1111336ccbfff6d543fd8c0af7391e51207a) of the compressed source :1st_place_medal:

**Comment by juek** [comment]
Could you try to uncomment `config.codemirror = {...}` and see if it also works on your side?

**Comment by mahotilo** [comment]
> Could you try to uncomment config.codemirror = {...} 

Did you mean **com**ment?

In any case, it works for me fine now.

**Comment by juek** [comment]
> Did you mean comment? 

Er… yes. Exactly that.

**Comment by juek** [comment]
@Sestowner 
Your last comment about cdns in connector 

> cdns is not connector configuration option, it should be in main.custom.js. I'm not really sure if we need it at all, because we can set the editors location directly in editors.custom.js.

… seems to have vanished with one of my latest commits, where I already deleted the respective lines.

I got the hint from studio42 forum but it didn't work.

However, in the meantime, I believe that we actually do not need CKeditor or CodeMirror in elFinder … what for?

**Comment by juek** [comment]
But there are still a few other things that should work offline, e.g. the archive preview. I already included a local copy of [zlib.js](https://github.com/Typesetter/Typesetter/commit/58c78247a44ddc30988819ef58ee3adaf418d5b3) for that purpose. 

All in all I think we hardly need most of the file editing features elFinder 2.3.2 comes with.

**Comment by Sestowner** [comment]
```
cdns : {
    zlibUnzip  : window.location.origin + '/include/thirdparty/zlib.js/unzip.min.js',
    zlibGunzip : window.location.origin + '/include/thirdparty/zlib.js/gunzip.min.js'
}
```
What do you think about this?

**Comment by juek** [comment]
>What do you think about this?

Yep, that works when [changed in elfinder.full.js](https://github.com/Typesetter/Typesetter/commit/e57d913701b599ab391d8d847d94b8d5c96a99d5)

**Comment by juek** [comment]
Since the elFinder devs themselves gave up on their 'notebook' version, I will not make it either. So,  none of our local editors (CKE + CodeMirror) in elFinder. 

We will use 'Textarea' for all text files (txt, markdown, js, css, html, xml, etc.) - it's not all bad. 

Unfortunately we have made quite some changes to various files which makes maintenance difficult - simply replacing elFinder with a newer build will not work. Honestly, I'm a bit disappointed of elFinder 2.3.2 for being so hungry for remote sources and so hard to configure. But hey, it works and it looks nice.

Some smaller fixes ahead…

**Comment by mahotilo** [comment]
Juergen
how can we find where the ctrl+shift+I combination  is bonded to Select all?
It really drives me mad but I failed with elfinder.full.js

**Comment by oyejorge** [comment]
Hi all, it's getting had to keep track of everything in here. I know I'm guilty of this as well but please create new issues rather than expanding on tangents in open issues.
