### ISSUE TITLE
Poll: should we use one of these elFinder themes

### ISSUE THREAD

**Issue by juek** [Typesetter/Typesetter#361]
Just take a look and give thumb ;)

https://github.com/RobiNN1/elFinder-Material-Theme

**Comment by juek** [comment]
Or a cuistom mix of them like this
![grafik](https://user-images.githubusercontent.com/704283/70962777-94a88500-2086-11ea-8d23-a6ef253f4619.png)

**Comment by mahotilo** [comment]
> Or a custom mix of them like this

Well, buttons without a borders will be the main difference for /image. This theme continues ckeditor's style, so I find it very relevant.

**Comment by juek** [comment]
With https://github.com/Typesetter/Typesetter/commit/cf1d2fff6356fad7d0e5d18f3cebf58391b4ec3c
 and https://github.com/Typesetter/Typesetter/commit/c4f9e06e468dba0368183b02f5c6874433b30228

we got this … 

![grafik](https://user-images.githubusercontent.com/704283/71016274-3b2b6f00-20f5-11ea-9a43-ed6fc9d74c2c.png)

Will likely still need some tweaking.
