### ISSUE TITLE
Update calls to nonce methods

### ISSUE THREAD

**Issue by oyejorge** [Typesetter/Typesetter#362]
We should replace all occurrences of \gp\tool::new_nonce, nonce_hash and verify_nonce with \gp\tool\Nonce::Create , Hash and Verify then flag the old calls deprecated.

**Comment by mahotilo** [comment]
I think I've completed this task

**Comment by juek** [comment]
> I think I've completed this task

Almost. 
https://github.com/Typesetter/Typesetter/commit/78617bbdc707f564f85ef3e16264fced6baeb642 https://github.com/Typesetter/Typesetter/commit/0ef311838382c22754e2a9816b3a19ee9235bc25
https://github.com/Typesetter/Typesetter/commit/5bcd23ecd556b5b9ebee916fc9b4ed2eab60eade
But now,.

**Comment by mahotilo** [comment]
Whoa, how did my search in files miss these?
Need to investigate.

**Comment by juek** [comment]
@oyejorge I hope moving to the new nonce functions in unit tests is in your sense.

**Comment by mahotilo** [comment]
Oh I see, it was a call to the deprecated function I counted as legal.

**Comment by juek** [comment]
> Whoa, how did my search in files miss these?

You probably only looked for `\gp\tool::[nonce fnc name]` and therefore missed `self::[nonce fnc name]`. 

> Oh I see, it was a call to the deprecated function I counted as legal.

I only marked it deprecated just now.

**Comment by juek** [comment]
> … deprecated function I counted as legal.

It will still be 'legal' for quite some time. Plugins are using them. Any plugin using the new calls will be Typesetter 5.2+, even if it would be compatible with, let's say, 5.0 or earlier.  That's why I commented the warning triggers.

**Comment by juek** [comment]
closable, I think

**Comment by oyejorge** [comment]
> I hope moving to the new nonce function calls in unit tests is in your sense.

Pretty sure I did... we'll find out if I didn't though
