### ISSUE TITLE
elFinder: ctrl+shift+I is assigned to Select all

### ISSUE THREAD

**Issue by mahotilo** [Typesetter/Typesetter#367]
ctrl+shift+I combination is assigned to Select all 
This blocks attempt to open Development tool in browser

**Comment by Sestowner** [comment]
> ctrl+shift+I combination is assigned to Select all

Actually this combination assigned to **Invert selection**.

**Comment by juek** [comment]
> ctrl+shift+I combination is assigned to Select all

I think it's 'Invert Selection'.
They also assign Ctrl [+Shift] + R to refresh files.

But when you click into the address bar, it works (Firefox at least).

**Comment by juek** [comment]
I'll see if I can clean it up a bit.

**Comment by Sestowner** [comment]
I think we don't need to change this combination, because it works only if elFinder is focused.

**Comment by mahotilo** [comment]
> But when you click into the address bar, it works 

Well, it is not a common task for a regular user to open developer tool in elFinder, so we don't really have to do something with it.

Thanks for hint about address  bar, it saved me a ton of neurons.

**Comment by juek** [comment]
Too late, I already axed both of them ;)

**Comment by juek** [comment]
No mercy
