### ISSUE TITLE
ckEditor + elFinder

### ISSUE THREAD

**Issue by mahotilo** [Typesetter/Typesetter#368]
Today I almost made a record for a false alarm, but I will persist:)

1. Create new html file or try to edit existing index.html with ckEditor
2. Get an JS error

> Uncaught TypeError: Cannot set property 'dir' of undefined
>     at Object.d (eval at <anonymous> (jquery.js?v=5.1.1-b1:2), <anonymous>:264:54)
>     at e (eval at <anonymous> (jquery.js?v=5.1.1-b1:2), <anonymous>:265:177)
>     at Array.x (eval at <anonymous> (jquery.js?v=5.1.1-b1:2), <anonymous>:265:332)
>     at t (eval at <anonymous> (jquery.js?v=5.1.1-b1:2), <anonymous>:265:416)
>     at eval (eval at <anonymous> (jquery.js?v=5.1.1-b1:2), <anonymous>:266:360)

**Comment by oyejorge** [comment]
Seeing some issue too. I think I found the problem and will probably need to update the ckeditor package...

**Comment by juek** [comment]
Wait! 

@mahotilo 

You are talking about CKEditor in elFinder, right?
I have removed CKEditor support in elFinder - will push elFinder shortly.

**Comment by oyejorge** [comment]
If you want it, I have it working.

**Comment by mahotilo** [comment]
> You are talking about CKEditor in elFinder, right?

Yes

**Comment by juek** [comment]
If it works, push. I got everything saved.

**Comment by oyejorge** [comment]
There's a catch. It requires updating ckeditor which overwrites this change #369

**Comment by juek** [comment]
@oyejorge Do you see the new button row?

**Comment by mahotilo** [comment]
If you ask me, I think that inline editor is enough

**Comment by juek** [comment]
Let's discuss elFinder after this in a separate issue. (I gave up to link them together, too many problems)

**Comment by oyejorge** [comment]
I agree the inline editor should be enough. I'm going to push a change disabling ckeditor because I've also moved the configuration from the elfinder.full.js to main.custom.js

**Comment by juek** [comment]
IMO, let's do CKEditor first

**Comment by juek** [comment]
We have to be careful not to confuse the both packages. Both have sort of an inline editor (CKEditor  'Source', elFinder -> 'Textarea')

Which one are we talking about?

**Comment by mahotilo** [comment]
In this issue I mean "TextArea" editor in elFinder when talk about "inline editor". Sorry for mess

**Comment by oyejorge** [comment]
Not a problem. And correct me if I'm wrong, but I think we're done with this issue as well.

**Comment by juek** [comment]
Yes I also think so. 
I just have to put everything with elFinder together, but only tomorrow.

Mind if I just throw everything away we don't need in elFinder? It hardly has anything to do with the original distribution anymore.

**Comment by oyejorge** [comment]
Sounds great!
