### ISSUE TITLE
update ckeditor.js - remove toolbar buttons 

### ISSUE THREAD

**Issue by oyejorge** [Typesetter/Typesetter#369]
What does this commit fix exactly? a84d1111336ccbfff6d543fd8c0af7391e51207a

I'd like to find a solution that doesn't involve editing the ckeditor code

**Comment by juek** [comment]
I edited the compressed source. 
The codemirror plugin adds a toolbar row with non-functional buttons. Not all of them can be removed later via config.

**Comment by juek** [comment]
The alternative would be to edit the plugin first, but I don't know a way to create a build from source using a custom / modified plugin. If you do, we could try it.

**Comment by juek** [comment]
This was the [original issue](https://github.com/Typesetter/Typesetter/issues/360#issuecomment-566415155) (posted in the wrong topic)

**Comment by oyejorge** [comment]
Thanks, I see the row. Frustrating how that's set up. I'll see what I can do

**Comment by juek** [comment]
Ok. Maybe you see more than we have.

**Comment by oyejorge** [comment]
Does that look ok?

**Comment by juek** [comment]
Give me 3 minutes...

**Comment by juek** [comment]
Hmm, Im still seeing the buttons.  Let me check that again.

**Comment by juek** [comment]
Ok, all fine. 
Just forgot ckeditor_config.js is not in /thirdparty/ckeditor/

Yes that looks good now.

**Comment by juek** [comment]
I think we're done with CKEditor now. Great!

**Comment by oyejorge** [comment]
Awesome!
