### ISSUE TITLE
elFinder+TextArea Editor+minimise button problem

### ISSUE THREAD

**Issue by mahotilo** [Typesetter/Typesetter#370]
Extra tools are extra problems.

I pressed "minimize" icon in TextArea editor (elFinder) and editor window went to ... nowhere. But it is still opened.  I think we need to block this possibility.

It seems endless

**Comment by mahotilo** [comment]
They just set display: none; for modal window. No chance for css tricks.

**Comment by juek** [comment]
![grafik](https://user-images.githubusercontent.com/704283/71042890-4dc19a80-212d-11ea-8746-9f9ce364d7ca.png)

Funky!

**Comment by juek** [comment]
It is not modal

**Comment by mahotilo** [comment]
Well, you are right (as always:), but how can I restore the minimized window?

**Comment by mahotilo** [comment]
Oh, as for me there are too many possibilities (and problems) than just select a file to insert into the page...

**Comment by juek** [comment]
I think we can well hide the minimize button. That's what CSS is made for :)

**Comment by mahotilo** [comment]
Stop, I think I caught it in bottom bar. Indeed, css may be enough to see minimaized window.

**Comment by mahotilo** [comment]
Give me some time

**Comment by juek** [comment]
Ok. I already see I'll have to merge all that by hand ;)

**Comment by juek** [comment]
Seems like elFinder does not want to share the viewport with other elements. Make it behave!

**Comment by mahotilo** [comment]
It should be sth like 
.elfinder.elfinder-ltr div.elfinder-bottomtray{
    left: auto;
    opacity: 1;
    background: black;
}
.elfinder-dialog-minimized{
margin-right: 5px;
}

**Comment by juek** [comment]
We shouldn't use _anything_-ltr as selector. It means 'left-to-right' for western languages.

**Comment by mahotilo** [comment]
I am working on it:) Hang on a minute.

**Comment by juek** [comment]
```
#gp_admin_html .elfinder div.elfinder-bottomtray {
    position: fixed;
    bottom: 0;
    max-width: 100%;
    opacity: .8;
    left: 180px;
}
```

should do the trick

**Comment by mahotilo** [comment]
.elfinder-bottomtray{
		left: auto;
		opacity: 1;
		background: black;
	}
	.elfinder-dialog-minimized{
		margin-right: 5px;
		.ui-dialog-titlebar .elfinder-titlebar-button{
			top: 9px;
			margin-right: 4px;
		}
	}

**Comment by mahotilo** [comment]
to your scss block
#elfinder{
}

**Comment by mahotilo** [comment]
I can insert into last commit

**Comment by mahotilo** [comment]
Done

**Comment by juek** [comment]
> I can insert into last commit. I have to merge manually. I did quite some other changes in the meantime.

One after the other. 
Josh has also said the has changes for elFinder. I'll have to bake it all togehter.

**Comment by mahotilo** [comment]
Sorry, I will try to do it this way next time. Now I just edit my local TS files and copy the lines to github.

**Comment by juek** [comment]
Get yourself Github Desktop. It's not bad at all.

**Comment by mahotilo** [comment]
I used to try, but, you know, old dog and new tricks:)
Maybe this time...

**Comment by juek** [comment]
This seems to be working well.

![grafik](https://user-images.githubusercontent.com/704283/71048643-393acd80-2140-11ea-8005-383cdbc0d8c6.png)

**Comment by juek** [comment]
Works well either

![grafik](https://user-images.githubusercontent.com/704283/71049323-40fb7180-2142-11ea-9249-3f4d737db565.png)

**Comment by juek** [comment]
A fresh new look. I'm quite happy with the theme.

**Comment by juek** [comment]
And a last one

![grafik](https://user-images.githubusercontent.com/704283/71050071-8620a300-2144-11ea-8302-1ae4572049ea.png)

**Comment by oyejorge** [comment]
Great job on the theme, it looks awesome!

**Comment by mahotilo** [comment]
> One after the other.

I have deleted my common pull request and changed it with 3 small
