### ISSUE TITLE
elFinder: should we limit window position?

### ISSUE THREAD

**Issue by mahotilo** [Typesetter/Typesetter#375]
Should we limit the window's position to prevent it from being moved beyond the bottom tray (of elFinder) or right side? 
It can be done only be via JS, but if we are making our customized elFinder anyway...

![image](https://user-images.githubusercontent.com/14929385/71289460-db8fc680-2375-11ea-96bc-6cf3c4fac95f.png)

**Comment by juek** [comment]
I will push some changes for elFinder later. They will change a bit of the behavior.  We will have to see then.

**Comment by juek** [comment]
I'd say if someone actually does that, a page refresh (or browser zoom) must be enough to remedy the situation. This app has already cost me enough nerves - I don't feel like hacking elFinder anymore.

**Comment by mahotilo** [comment]
It is easy to understand your feelings especially after a few days of diving into ckEditor themes:)

**Comment by oyejorge** [comment]
I think it works great as it is now. Gonna close this

**Comment by mahotilo** [comment]
I have found a solution

elfinder.full.js
line 11718
dialogContained : true,

#gp_admin_html #elfinder {
    overflow: hidden;
}

**Comment by oyejorge** [comment]
I'm not seeing any differences when changing dialogContained to true

**Comment by mahotilo** [comment]
@oyejorge 

Are you still able to move Resize&Rotate or TextArea dialog window outside elFinder window?

**Comment by juek** [comment]
Nice. Dialog containment works. 

I only got a 'ReferenceError: elfNode is not defined' js error in elfinder.min.js. Let's see what that can be…

**Comment by juek** [comment]
[fixed](https://github.com/Typesetter/Typesetter/commit/90a4d72e2884842af012324b53aab7f1aed06a2f)

**Comment by mahotilo** [comment]
Thx.
I missed this error. 
I also have a small fix for еру buttons sizes in Resize dialog and for the margins in dialogs. I planned to make corresponding PR after this would merge.

**Comment by juek** [comment]
can you please put it directly into /include/thirdparty/elFinder/themes/material/css? 
I moved almost everything into the theme now.

**Comment by mahotilo** [comment]
OK.
I think, I can.

**Comment by juek** [comment]
> OK. I think, I can.

Just look for possibly already existing rules and your stuff there. But I can also do it if you want.

**Comment by mahotilo** [comment]
Done
https://github.com/Typesetter/Typesetter/pull/405

Plus a "bonus", if you like it
https://github.com/Typesetter/Typesetter/pull/406

**Comment by oyejorge** [comment]
Sorry, I was looking at the preview not the textarea.

My only concern is with modifying elFinder code directly. It's an active project and I'm sure we'll want to update at some point.

To avoid having to redo anything, I would either (for things like PR #401) change settings like dialogContained in the main.custom.js file or (for things like 90a4d72e2884842af012324b53aab7f1aed06a2f) create a pull request on [elFinder project](https://github.com/Studio-42/elFinder).

With that said, thanks for tackling elFinder!

**Comment by mahotilo** [comment]
Oh, the more I dive into elFinder, the more I understand Juergen.

As I just discovered, the fix I proposed causes a new error in sizing of Settings dialog All tab.
I am trying to find a solution. If I cannot, I will send a request to reject it.

**Comment by mahotilo** [comment]
Well,
I think lines 17512-17520 in elfinder.full.js 
```
	if (fm.options.dialogContained) {
		syncSize.width = syncSize.height = syncSize.enabled = true;
	} else {
		syncSize.width = (opts.maxWidth === 'window');
		syncSize.height = (opts.maxHeight === 'window');
		if (syncSize.width || syncSize.height) {
			syncSize.enabled = true;
		}
	}

```

should be like this

```
	syncSize.width = (opts.maxWidth === 'window');
	syncSize.height = (opts.maxHeight === 'window');
	if (syncSize.width || syncSize.height) {
		syncSize.enabled = true;
	}

```
I will create a PR for these changes, but we need some testing before finally accept it and create a pull request on elFinder project.

**Comment by mahotilo** [comment]
Created
https://github.com/Typesetter/Typesetter/pull/407
https://github.com/Typesetter/Typesetter/pull/408

Looks like the final solution. I think, I have checked in all the dialogs.
