### ISSUE TITLE
CKEditor+Codemirror JS error

### ISSUE THREAD

**Issue by mahotilo** [Typesetter/Typesetter#379]
How to reproduce"
1. Open section source
2. Click on fold badge to the left of the line number
3. Catch an error

> codemirror.min.js:7 Uncaught TypeError: Cannot read property 'apply' of undefined
>     at F (codemirror.min.js:7)
>     at Jc (codemirror.min.js:179)
>     at E.Qf (codemirror.min.js:168)
>     at HTMLDivElement.<anonymous> (codemirror.min.js:102)

**Comment by oyejorge** [comment]
A similar error is showing up on the official demo: http://w8tcha.github.io/CKEditor-CodeMirror-Plugin/demoInline.html

**Comment by mahotilo** [comment]
Should we just hide fold badges by proper config or simply via CSS to prevent this error from occurring?
We use codemirror in the layout editor (so we have 2 codemirror in TS :) but the left gutter is hidden there, so there is no way to rise an error.

**Comment by mahotilo** [comment]
It seems to me that we can only hide the icon with CSS

**Comment by mahotilo** [comment]
It can be done with such lines in inline_edit.css. Should I make a request?

```
.CodeMirror-gutter-wrapper,
.CodeMirror-scroll{
	pointer-events: none;
}

.CodeMirror-sizer{
	pointer-events: all;
}
.CodeMirror-foldgutter-open.CodeMirror-guttermarker-subtle,
.CodeMirror-gutter.CodeMirror-foldgutter{
	display: none;
}
```

**Comment by oyejorge** [comment]
When I click on the fold badge, I see an error in the console but the folding still works. Does it not work for you?

**Comment by Sestowner** [comment]
I fixed this error by adding this code to `ckeditor_config.js`
```
editor.config.codemirror = {
    enableCodeFolding: false
}
```

**Comment by mahotilo** [comment]
@Sestowner 
Does this IS hide badges or just disable action?

**Comment by Sestowner** [comment]
>  Does this IS hide badges or just disable action?

Badges remain visible, and the action works.

**Comment by mahotilo** [comment]
Yes, thanks! It really FIXes the problem! Is it planned to make a pull request?

**Comment by mahotilo** [comment]
It is really weird situation, disable option to enable it.

**Comment by Sestowner** [comment]
> Is it planned to make a pull request?

Yes, if @oyejorge doesn't mind.

**Comment by oyejorge** [comment]
Definitely don't mind!
