### ISSUE TITLE
CKEditor: Your browser doesn‘t support pasting...

### ISSUE THREAD

**Issue by mahotilo** [Typesetter/Typesetter#381]
All paste buttons give a message "Your browser doesn‘t support pasting with the toolbar button or context menu option." I don't have such a message with the old CKEditor.

![image](https://user-images.githubusercontent.com/14929385/71210654-0dd9ef00-22b6-11ea-8c15-1e8c70b1e39c.png)

**Comment by oyejorge** [comment]
We could try some of the solutions posted in the ckeditor4 bug report: https://github.com/ckeditor/ckeditor4/issues/469

**Comment by mahotilo** [comment]
I have made a [pull request](https://github.com/Typesetter/Typesetter/pull/382). It works smooth for me.
