### ISSUE TITLE
easy comments format proposal

### ISSUE THREAD

**Issue by gtbu** [Typesetter/Typesetter#392]
The new easy comments 1.2 is OK - just the textarea is still too big (as in the smart multi - template and in Three Point 5) :
<textarea name="comment" cols="30" rows="7"></textarea> ( in firefox : inspect element )
* My proposal is to add a class gtxt to the textarea in EasyComments_Gadget.php line 232,
 , so that overflow is preventable with max-width and also further easy styling is possible (tested in old version). Then textarea.gtxt {max-width:220px !important;} does it. The middle and narrow mode of the template need further styling.
textarea[name="comment"] {   max-width:100px !important; } has no effect .
document.querySelector etc.  is another complicated possibility.

**Comment by juek** [comment]
> textarea[name="comment"] { max-width:100px !important; } has no effect .

You can target it easily using `.easy_comment_wrap textarea {}` or `.easy_comment_form textarea {}`
but `textarea[name="comment"] {}` should also work.

If it doesn't, some of your other css must be overruling. If not even !important helps, then there must be another, stronger rule using !important somewhere in **your** css. 

In any case, it's neither Typesetter nor the plugin that is causing your issue.

**Comment by gtbu** [comment]
"" easily using .easy_comment_wrap textarea {} or .easy_comment_form textarea {} "" ... Well, easy for You as developer - but not visible in 'inspect element' - and  so not for normal users. 
Things as easy_comment_form textarea {} are ridiculous for normal users. Thats why they evtl. avoid the additional blocks - menupoint.
  ..textarea[name="comment"] { } has for me no function in custom.css inspite of !important.  
An additional class gtxt is easier for normal  users.

**Comment by juek** [comment]
`textarea[name="comment"]`, `.easy_comment_form textarea` and `textarea.gtxt` are equally [specific](https://specificity.keegan.st/) (11). A class name would not solve your issue.

> Things as easy_comment_form textarea {} are ridiculous for normal users

Possibly true, but that's how css is meant to work. I have seen tons of web designs where everything has a class name or even an id. There are even quite websites out there stating that this is the right way to go (obviously wrong). It would be <s>C</s>SS then. It's the 'cascading' what makes stylesheets good.

**Comment by oyejorge** [comment]
We simply can't add classes to every html element output by Typesetter and it's plugins.

For me, this is part of the discussion of how to allow users to get more control over the html that's currently hard-coded in plugins/themes/etc. The current html output of the Easy Comments plugin includes a &lt;table&gt; which many people would cringe at. So [similar to another discussion](https://github.com/Typesetter/Typesetter/issues/347#issuecomment-565660940), I think it would benefit us to look into a template library.

**Comment by juek** [comment]
> I think it would benefit us to look into a template library.

I'm not entirely against a template engine. There are certain situations where it would actually make sense, especially gadgets. Only caching can complicate things a bit.

**Comment by gtbu** [comment]
Well - I am not annoyed about the proposal of a template engine, a good  idea but complicated to implement - but the problem with the overlapping right margin with smart-multi and others is so not solved....
.easy_comment_wrap textarea {} or .easy_comment_form textarea {} - textarea [name = "comment"] {} don't work out of some reason. textarea.gtxt gives lazy control - a dom-expansion-library plugin from github is another idea (christmas joke)
let document.getElementsByClassName ('foo'). style.width or jquery allow further control. I don't use the plugin, but for me it works.

**Comment by juek** [comment]
Just installed the theme and tested

```
.easy_comments_wrap textarea {
    width: 100%;
    resize: vertical;
}
```

That works.

**Comment by gtbu** [comment]
Sorry - but in Laragon - php7.2 (newest Firefox, Chrome, Edge, win 10 1903) it has no effect (me again ? - not tested in the web..).
Also : You cant expect that normal users go through the source of the plugin to find the classes : easy_comments_wrap  --> easy_comments_comments --> easy_comment_form , then comes the textarea. We should find a solution which fits automatic . 
With reduced :  cols="20" rows="6" maxlength="500" the problem is solved .

**Comment by gtbu** [comment]
Sorry - but in Laragon -php 7.2 (newest firefox, Chrome, edge, win10 1903) it has no effect (me again- not tested in the web)

Also You cant expect that average users go through the source of the plugin to find the classes : 
easy_comments_wrap, easy_comments_comments,  easy_comment_form. first the comes textarea
We should find a solution which fits automatic . 
With reduced :  cols="20" rows="6" maxlength="500" the problem is solved. An additional gtxt makes it easy for users to style the fonts etc. - but....

P.S.  As a Christmas "present" : I developed the smart-multi-template with 44 colors from https://www.bootpress.org/bootstrap.html.  In version 1 i had just one bootstrap.css which i imported into the style.css. In the multi version at least 3 themes cause a crash of the styling of the CMS (the styling of the dashboard is contained!) if i have a hook in **'add all csses**'.
 So i made a strange looking $page->head .= '<link rel="stylesheet" type="text/css" href="'.$themeDir . '/' . $page->theme_color . '/bootstrap.min.css'.'" />'; in the settings.php - and the css not added (mod_deflate compresses it and transfers it safer).
*  I guess a bug in the css-adder (as far as i understand the code , the css'es are scanned with regex....) If You are interested i will upload the version i with buggy css'es.

**Comment by juek** [comment]
> no effect … 

It is pointless to further discuss that in this context. This has **nothing** to do with Typesetter, neither with the plugin nor PHP and not even the used web browser. It is a **sole CSS** issue. 
Post a link where it doesn't work and I just tell you what's wrong.

**Comment by gtbu** [comment]
That makes not much sense : The files work at bootpress.org. If i put the original bootstrap.css - file  into a mask like
https://www.cssportal.com/css-validator/ or https://codebeautify.org/cssvalidate or others i get also with the original unmodified bootstrap.css 12 hints and errors.
In my opinion the adder does too much. It puts a css in a line and modifies it. It should then give a detailed error message about whats wrong.

**Comment by juek** [comment]
Of course real-world styleheets will never validate with all the vendor-prefixes, proprietary IE filters, browser hacks, etc. 

But we're completely off-topic again.
