### ISSUE TITLE
Page Rename/Details dialog layout problem with Bootswatch 4 Scss/flatly

### ISSUE THREAD

**Issue by mahotilo** [Typesetter/Typesetter#394]
Can you see this also?

UPD
It happens with Bootswatch 4 Scss/flatly

![image](https://user-images.githubusercontent.com/14929385/71325239-79100500-24f2-11ea-9ab7-c0a0dee384f2.png)

**Comment by Sestowner** [comment]
> Can you see this also?

Nope.

**Comment by mahotilo** [comment]
I use the last master, are you also?

**Comment by Sestowner** [comment]
> I use the last master, are you also?

Yes.

**Comment by mahotilo** [comment]
Well, it only on Bootswatch 4 Scss/flatly.

**Comment by juek** [comment]
I can see it

**Comment by juek** [comment]
[fixed](https://github.com/Typesetter/Typesetter/commit/fa32361ebeab0cee99d0c81ae38d9344fb100ce9)

**Comment by juek** [comment]
… and don't ask me why it ever worked this way

**Comment by mahotilo** [comment]
I confirm and close
