### ISSUE TITLE
Request: Private page indication

### ISSUE THREAD

**Issue by mahotilo** [Typesetter/Typesetter#395]
Even with new powerful and informative Notification system, it will be more convenient to have a direct and visible sign that the current page is Private. To save the menu's real estate we can use background of the Option menu item.

![image](https://user-images.githubusercontent.com/14929385/71325295-58947a80-24f3-11ea-96f7-168dd4617d53.png)

**Comment by mahotilo** [comment]
I tried to change the colors of the Option menu and found it not a trivial task:)

Maybe the right way is to add to the top menu "notification bells" for the current page? This will be a logical development of current notifications for the entire site. 
This will even allow us to have as many custom notifications as we need.
And bells a more compact than words.

![image](https://user-images.githubusercontent.com/14929385/71550517-18456880-29db-11ea-8c4e-74d7fa4001dd.png)

**Comment by juek** [comment]
We could simply push Notification priority of 'Private Page' above 'Working Drafts' only when viewing/editing such a private page.

**Comment by mahotilo** [comment]
Do you mean the button "Visibility: Private" instead of "Publish draft"?
It will be good.

**Comment by juek** [comment]
I mean Notifications, see [this commit](https://github.com/Typesetter/Typesetter/commit/b2c762439d4f68b9eb368026539311d770d7c705)

**Comment by mahotilo** [comment]
> the precedence will only apply as of the next page reload

Of course, now it is not easy to accidentally make the page private. But I still think, it would be helpful to have a clear indication of the page's private state. Maybe it will be easier to change the background of the entire top menu for a private page to #C44830?

**Comment by juek** [comment]
My plan is to add a 'isPrivate' class to the &lt;html&gt; or &lt;body&gt; element, just like the 'gpAdmin' class. Everything else will be easy then.

**Comment by juek** [comment]
> My plan is to add a 'isPrivate' class to the <html>…

implemented with https://github.com/Typesetter/Typesetter/commit/ba423e04039f23ccbf77caded318512beb53e70f

**Comment by mahotilo** [comment]
Maybe it will be like this?

https://github.com/Typesetter/Typesetter/pull/429

**Comment by juek** [comment]
Yep. just get https://github.com/Typesetter/Typesetter/commit/7b56fa3377bfe2ff35e2c9bd06061c4cca42a262 and https://github.com/Typesetter/Typesetter/commit/43f6f44dacc5a4d6e83a91a1db34a1c8d08ca53a

**Comment by mahotilo** [comment]
With dedicated class it is much better :)

**Comment by juek** [comment]
> With dedicated class, it is much better

Admin links have been extremely difficult to target before (:nth-of-type, which was not reliable).
Unfortunately this way to add classes to the options dropdown link is far from ideal. The $admin_links array, which can be extended by plugins, currently doesn't support class names for such links. I yet have to find a way to allow it.
