### ISSUE TITLE
$this inside of static function UpdateSectionClipboard()

### ISSUE THREAD

**Issue by oyejorge** [Typesetter/Typesetter#411]
[I just came across this bug](https://scrutinizer-ci.com/g/Typesetter/Typesetter/code-structure/master/operation/gp%5CPage%5CEdit%3A%3AUpdateSectionClipboard) and wondering if we need that function. I couldn't find uses of it.

**Comment by juek** [comment]
> wondering if we need that function

No we don't need it. I can't even remember what I made it for. Therefore [deleted](https://github.com/Typesetter/Typesetter/commit/e20e104b99db0ea5bbe584c7d69f27ef57bd4382)
