### ISSUE TITLE
FYI: elFinder 2.1.50 new useful upload functions you may have missed yet

### ISSUE THREAD

**Issue by juek** [Typesetter/Typesetter#414]
elFinder <s>2.3.2</s> 2.1.50 brings two particularly useful functions when uploading files:

* folder upload – we can now drop whole folders from local file manager into the elFinder's file area.

* paste images from clipboard – using the file upload dialog triggered by the ![grafik](https://user-images.githubusercontent.com/704283/71510937-d3adb600-2890-11ea-93e7-584032e5ce65.png) icon, you can paste [Ctrl] + [V] an image from the local clipboard. elFinder will create a new PNG with a hashed file name. But note: such PNGs will not be optimized at all.

edit: where did I get this 2.3.2 version number from? it's 2.1.50

**Comment by oyejorge** [comment]
Just added that to the blog: https://www.typesettercms.com/Blog/elFinder_2.1.50_in_Upcoming_Release

**Comment by juek** [comment]
closed in favor of mention in [WHATSNEW.md](https://github.com/Typesetter/Typesetter/blob/master/WHATSNEW.md)
