### ISSUE TITLE
Poll: should we implement Admin Panel fixed to top-left?

### ISSUE THREAD

**Issue by Sestowner** [Typesetter/Typesetter#415]
I made some changes based on [Josh's commit](https://github.com/Typesetter/Typesetter/pull/340/commits/379e1d1d47de6c20aec21edb298e4c88e77cd65f), and now Admin Panel look like this

![Screenshot_2019-12-27 Home(4)](https://user-images.githubusercontent.com/36760609/71515329-63f8f480-28ab-11ea-8d8a-94f297c532cf.gif)

**Comment by mahotilo** [comment]
But somebody like it right side :)

**Comment by mahotilo** [comment]
A fixed Admin Panel can force the user to hide it, because now user can not just move it so that it does not cover certain page element.
But... 
Now we have the Notification system, we need to see warning bells, but we can not do this while the Admin Panel is hidden.
So...
We have to find a way how to display notification bells in the menu, and we can make Admin Panel fixed.
And...
When two admins with the same login work in the CMS, and one of them moves Admin Panel to right side all the time and other one moves it to left side and minimize it,... I prefer to nail Admin Panel to the menu.

**Comment by oyejorge** [comment]
I like it!

**Comment by juek** [comment]
I would like to keep it draggable. But we could make it 'dockable' so it could snap to the top left corner and then push admin links to the right. That would be similar to many application programs I use.

Most websites with [larger amounts of content](https://getbootstrap.com/docs/4.3/getting-started/introduction/) use this area for the secondary navigation.

**Comment by juek** [comment]
@mahotilo 

> When two admins with the same login work in the CMS, and one of them moves Admin Panel to right side all the time and other one moves it to left side and minimize it

Admin UI settings like the panel position is already saved for each user individually.

**Comment by mahotilo** [comment]
> Admin UI settings like the panel position is already saved for each user individually.

"same login".
It is not right, but there is:)

**Comment by mahotilo** [comment]
> But we could make it 'dockable' so it could snap to the top left corner and then push admin links to the right.

This can really be a nice new feature and a compromise.

Or we can give us some place in the top left corner to dock  here only Admin panel's "button".

![image](https://user-images.githubusercontent.com/14929385/71535765-17480480-2911-11ea-9b47-5fb87e821e8b.png)
![image](https://user-images.githubusercontent.com/14929385/71535812-a5bc8600-2911-11ea-98e4-a3331e81f1aa.png)

**Comment by juek** [comment]
I'd give it a go. I just wonder if there would be other useful docking positions besides top-left? Hmm.

**Comment by mahotilo** [comment]
We only should dock to existing CMS elements, so it is just the top menu bar. The right side is already packed with floating panels. Thus, only the top-left is possible.

**Comment by Sestowner** [comment]
If somebody want to test how to works Admin Panel fixed to top-left mail me.

**Comment by juek** [comment]
@Sestowner  

I just opened a new branch https://github.com/Typesetter/Typesetter/tree/dockable-admin-menu

Mind to make a PR?

**Comment by juek** [comment]
Sorry folks, not in 5.2. 
IMO there is more Admin UI stuff to rethink/improve. Let's do that when 5.2 is out.
