### ISSUE TITLE
Poll: How to use last versions of jQuery and Bootstrap?

### ISSUE THREAD

**Issue by mahotilo** [Typesetter/Typesetter#417]
With the last master I succeeded in using jQuery v3.4.1 and Bootstrap v4.4.1. The only thing I had to do was remove vp-flex from Bootswatch4_Scss theme. As a reward, now I have no "best practice" vulnerabilities warnings from Google Lighthouse.

So, I have two wishes. First, I want to use contemporary tools for new projects. Second, I want to have updated Admin tools for existing projects without breaking their frontends. How do you see the solution of this dilemma? 
To create two different branches of TS or to use a private update-yourself version of TS? 
That is a question.

**Comment by juek** [comment]
>  I succeeded in using jQuery v3.4.1 

Without issues? Have you checked the console?

> The only thing I had to do was remove vp-flex from Bootswatch4_Scss theme.

Without the vp- mixins we will lose support for quite some browsers. Bootstrap 4 **no longer adds** any vendor prefixes itself.

**Comment by mahotilo** [comment]
> Without issues? Have you checked the console?

Cleared caches, used private window, CDN - off. No errors, no warnings in admin or frontend.

> Without the vp- mixins we will lose support for quite some browsers.

This is what Bootstrap [decided](https://getbootstrap.com/docs/4.1/migration/?#browser-support)..
...Dropped IE8, IE9, and iOS 6 support. v4 is now only IE10+ and iOS 7+. For sites needing either of those, use v3...

>  Bootstrap 4 no longer adds any vendor prefixes itself.

[Is that about it?](https://getbootstrap.com/docs/4.1/migration/#vendor-prefix-mixins)
...Bootstrap 3’s vendor prefix mixins, which were deprecated in v3.2.0, have been removed in Bootstrap 4. **Since we use Autoprefixer**, they’re no longer necessary....

**Comment by juek** [comment]
> Is that about it?

Yes, that's what I manually implemented in our current Bootstrap 4.1.1
We do not use Autoprefixer when we compile Bootstrap Scss.

**Comment by juek** [comment]
@oyejorge Josh, do you know any compatibility issues in Typesetter core that would prevent using jQuery 3?

Plugins (especially older ones) could pose an additional challenge.

**Comment by mahotilo** [comment]
Well. What I have done.
Downloaded Bootstrap 4.1 from https://getbootstrap.com/docs/4.4/getting-started/download/
Unpacked it to include\thirdparty\Bootstrap4 
Moved bootstrap.scss to include\thirdparty\Bootstrap4\, renamed it to _bootstrap.scss and changed `@import "` to `@import "bootstrap/`
All work fine for me.

**Comment by juek** [comment]
OK, let's go 4.4.1. Our former ScssPhp version had issues compiling > 4.1 it but that should be sorted now. I'll do the vp-mixins implementation anyway. There is lots of stuff not working without them, even in recent browsers.

**Comment by mahotilo** [comment]
> OK, let's go 4.4.1. 
Will it be safe for existing TS sites?

**Comment by juek** [comment]
> Will it be safe for existing TS sites that use v4.1?

Sure. 4.4.1 is up for testing. Get https://github.com/Typesetter/Typesetter/commit/50f5fbb818f564df5a83877b3fdf34c89c3fb865 and https://github.com/Typesetter/Typesetter/commit/cfaff31fa9204cfafa37561e54046b4f042596d9

**Comment by mahotilo** [comment]
Oh, this is a huge work. Do legacy browsers deserve it?

**Comment by juek** [comment]
> Do legacy browsers deserve it?

Deserve? No.
I still have customers who don't like Edge and therefore still use … guess what? ;)

But it's not all about legacy browsers, many vendor prefixes are still required in modern browsers, such as [user-select](https://caniuse.com/#feat=user-select-none)

**Comment by oyejorge** [comment]
> do you know any compatibility issues in Typesetter core that would prevent using jQuery 3?

I couldn't think of anything off the top of my head, but found these after a quick look through the [upgrade guide](https://jquery.com/upgrade-guide/3.0/)

> .size() is deprecated as of jQuery 1.8 and removed in jQuery 3.0 in favor of the .length property.

We have a few uses of size() in dragdrop.js

> "The older .bind(), .unbind(), .delegate() and .undelegate() methods are being deprecated as of 3.0, but are still present"

Not something that will break when we switch to 3.0, but should be fixed before it becomes a problem.

**Comment by mahotilo** [comment]
Just for my interest:)
Why not Bootstrap Autoprefixer? 
Without prefix automation it will be difficult to update for next BS 4.x security fixes.

**Comment by juek** [comment]
> Why not Bootstrap Autoprefixer?

We would have to add some php-based autoprefixer. 
Adding such libraries should be considered wisely and must be tested in-depth, because it …

* could always pose new security risks
* would certainly cost additional processing time and memory and might even exceed the latter
* IMO automatic auto-prefixing only makes sense as long as it is up-to-date, hence only an online service would justify its use IMO. I don't want that.

**Comment by mahotilo** [comment]
Thx

**Comment by juek** [comment]
> Without prefix automation it will be difficult to update for next BS 4.x security fixes.

Well, yes it is quite some work. But I wouldn't be scared too much of Bootstrap security issues. Bootstrap has no PHP backend. The latest Popover.js XSS attack vector only applies to implementations which provide inline editing for popover templates to users/admins who don't have scripting permissions otherwise. It does not really apply to Typesetter CMS.

**Comment by mahotilo** [comment]
But Google Lighthouse's audit counts even such "vulnerability" and lowers "Best practices" rating...

What did you say about customers with odd preferences:)

**Comment by juek** [comment]
> But Google Lighthouse's audit counts even such "vulnerability" and lowers "Best practices" rating...

My 'best practice' advice would rather be: Use an Adblocker and your web browsing will be 500% safer and 200% faster. For some unknown reason Google seems to think different here.

**Comment by juek** [comment]
FYI: I'm currently going the jQuery upgrade route with 2 intermediate steps

* 1.12.4 -->  2.2.4 using jQuery Migrate 1.4.1 console logging
* 2.4.1   -->  3.4.1 using jQuery Migrate 3.1.0 console logging

If anyone wants to participate in this process, I can push the required (intermediate) changes.

**Comment by mahotilo** [comment]
What we have to do?

**Comment by juek** [comment]
> What we have to do?

Click everywhere and watch the console ;)

**Comment by mahotilo** [comment]
So, push it:)

**Comment by juek** [comment]
[pushed](https://github.com/Typesetter/Typesetter/commit/07542f7949c9669fb8d60f7d2409f9e77f2eebc3)

**Comment by mahotilo** [comment]
Well, I find
gpresponse is deprecated as of 3.6 
main.js?v=5.1.1-b1:216 

Is it all? 
Should I just inform you or make some changes to code  as well?

**Comment by juek** [comment]
> gpresponse is deprecated as of 3.6

should already be fixed with https://github.com/Typesetter/Typesetter/commit/276905eba03c1b2bb9f31b1180cb0efb58917dd5 and https://github.com/Typesetter/Typesetter/commit/b5d57aea4094d087307395a26121337064b2fc7d
(BTW: The gpresponse msg is not a jQuery Migrate warning.)

> Should I just inform you or make some changes to code as well?

Please just post any findings. 

jQuery Migrafte warnings look like this:

```
JQMIGRATE: jQuery.fn.load() is deprecated jquery.js:50:25
console.trace() jquery.js:52:29
    jQuery 14
        migrateWarn
        name
        imageFromContent
        each
        each
        imageFromContent
        gp_init_inline_edit
        <anonym>
        <anonym>
        globalEval
        text script
        Ab
        z
        c
```

**Comment by juek** [comment]
AFAIK the CMS core will not be of major concern. It's rather the plugins causing headache.

I have already tested SimpleBlog and will continue with all my own plugins.
E.g. Responsive Image will need an update for TS 5.2 (not jQuery related, though)

If you could test plugins, this would help a lot. We should just coordinate in this regard. 

I will test all my own plugins first.

**Comment by mahotilo** [comment]
I made clear move to last master and catch this error in BS.

It is caused in e.g.
@include font-size($font-size-base);

> SCSS Compile Failed: Undefined mixin font-size: include/thirdparty/Bootstrap4/scss/bootstrap/_reboot.scss on line 50, at column 3 Call Stack: #0 function subtract include/thirdparty/Bootstrap4/scss/bootstrap/_variables.scss on line 958 #1 function subtract include/thirdparty/Bootstrap4/scss/bootstrap/_variables.scss on line 886 #2
...
>

**Comment by mahotilo** [comment]
> E.g. Responsive Image will need an update for TS 5.2 (not jQuery related, though)

Yes, it looks like hardcoded link to ckeditor_34

**Comment by juek** [comment]
> I made clear move to last master and catch this error in BS.

Get https://github.com/Typesetter/Typesetter/commit/c8ad80dc4ea1e6e5de60d00a5885b9d05fd4a5d4 and https://github.com/Typesetter/Typesetter/commit/e5c199b3171722c18c967f40625c004ca4845dfd

@oyejorge Josh, what's about that 'vendor' string in .gitignore I just removed? Do we need it?

**Comment by mahotilo** [comment]
Well, I finally catch a Migrate warning on my test mess site.

> JQMIGRATE: Migrate is installed with logging active, version 1.4.1
> combined_7vajt4q399e0a2rd1rpsx44.js:52 console.trace
> migrateWarn @ combined_7vajt4q399e0a2rd1rpsx44.js:52
> jQuery.fn.<computed> @ combined_7vajt4q399e0a2rd1rpsx44.js:565
> (anonymous) @ combined_7vajt4q399e0a2rd1rpsx44.js:4497

How could I find source of error?

**Comment by juek** [comment]
> Well, I finally catch a Migrate warning on my test mess site. How could I find source of error?

Jikes, turn off Combine JS!

**Comment by mahotilo** [comment]
Now one can see it better:)

JQMIGRATE: Migrate is installed with logging active, version 1.4.1
jquery.js?v=5.1.1-b1:52 console.trace
migrateWarn @ jquery.js?v=5.1.1-b1:52
jQuery.fn.<computed> @ jquery.js?v=5.1.1-b1:565
(anonymous) @ ImageMarker.js?v=5.1.1-b1:11

**Comment by juek** [comment]
>Now one can see it better:)

Don't you dare to check my plugins before I do it!
Thx ;)

**Comment by mahotilo** [comment]
I confess most of the plugins on my sites are yours or my reworks of others

**Comment by mahotilo** [comment]
Anaother one

> JQMIGRATE: Migrate is installed with logging active, version 1.4.1
> jquery.js?v=5.1.1-b1:52 console.trace
> migrateWarn @ jquery.js?v=5.1.1-b1:52
> get @ jquery.js?v=5.1.1-b1:67
> (anonymous) @ jquery.mobile.custom.js?v=5.1.1-b1:177
> each @ jquery.js?v=5.1.1-b1:2
> (anonymous) @ jquery.mobile.custom.js?v=5.1.1-b1:173
> (anonymous) @ jquery.mobile.custom.js?v=5.1.1-b1:245
> (anonymous) @ jquery.mobile.custom.js?v=5.1.1-b1:5
> (anonymous) @ jquery.mobile.custom.js?v=5.1.1-b1:6
> 

It is Bootstrap-Carousel!

I had had problems with it on BS4, so I even made a [fork](https://github.com/mahotilo/Bootstrap-Carousel). I did my best:)

**Comment by juek** [comment]
[Responsive Image](https://www.typesettercms.com/Plugins/293_Responsive_Image) is now ver 1.5.6 and ready for Typesetter 5.2

**Comment by mahotilo** [comment]
>  additional height units (rem, vw, vh, vmin and vmax)

Hurrah!

**Comment by juek** [comment]
And here comes [ImageMarker 1.0-b2](https://typesetter-addons.grafikrausz.at/ImageMarker)

**Comment by mahotilo** [comment]
Wow, 
It turned out to turn compression off is so useful.
I have just caught a couple of hidden bugs in themes and removed  their "workarounds".

**Comment by oyejorge** [comment]
> what's about that 'vendor' string in .gitignore I just removed? Do we need it?

It's for composer packages I've used in development. Not a problem though, I'll work around it

**Comment by mahotilo** [comment]
My favorite Custom section also have hardcoded ckeditor_34

> Admin Notice: The following file could not be found: \n\nD:/Internet/www/root/Ts-j/include/thirdparty/ckeditor_34/ckeditor.js

**Comment by juek** [comment]
> My favorite Custom section also have hardcoded ckeditor_34

Yes, I know, I'll update the CS plugin short-term.

**Comment by mahotilo** [comment]
I have checked all my zoo and made a report. 

I think it would be great to have some kind of feedback for addons. Something like the rating system we have. The user must press "It causes a system error by me" and a brief report with the TS version and console log will fly to the plugin's page.

**Comment by juek** [comment]
Custom Sections should be fixed with [this commit](https://github.com/juek/CustomSections/commit/3eef2174629e20fe5921e2f7b82389a5030e9637)

**Comment by juek** [comment]
> I think it would be great to have some kind of feedback for addons.

We have error reporting in Configuration. It pretty much does that (and more)

![grafik](https://user-images.githubusercontent.com/704283/71579316-5d14f080-2afc-11ea-8259-b562c91786a0.png)

**Comment by mahotilo** [comment]
It is visible for addon author only?

**Comment by juek** [comment]
> It is visible for addon author only?

Yes

**Comment by mahotilo** [comment]
Thus, as regular user I have no marks on the comparability of plugin or how buggy it is. 
You know for sure that great part of plugins on typesettercms is outdated and is not working now.
So, I thought about marking system for the end user based on other users experience.

**Comment by mahotilo** [comment]
Site Explorer oversized

![image](https://user-images.githubusercontent.com/14929385/71601488-4ef6bc80-2b5c-11ea-8da1-91c746ffc977.png)

**Comment by juek** [comment]
> I think, you know it already

I will rework Site Explorer when TS 5.2 is out. E.g. strip off draft warning.

**Comment by juek** [comment]
[next round](https://github.com/Typesetter/Typesetter/commit/3ff07fb322738dcd26e094cfdd51db58a6c27ceb) in the jQuery game

**Comment by mahotilo** [comment]
> now it's getting funny:

Yeah.

jquery ui
jquery.colorbox
SliderFactory.min.js

**Comment by juek** [comment]
> jquery ui, jquery.colorbox

We can ignore deprecation warnings especially in 3rd party components.

**Comment by mahotilo** [comment]
About Colorbox
our version is 1.6.3
last version is 1.6.4

and that  1.39 dir :)

**Comment by juek** [comment]
> About Colorbox

updated with https://github.com/Typesetter/Typesetter/commit/213bb8f8127f1ce85c79f911c8c657c2f2bee3f4 and https://github.com/Typesetter/Typesetter/commit/4ef95c20150c28cdc3b04f9baa65b6bcb2089209

**Comment by mahotilo** [comment]
Oops

>  Bootstrap's JavaScript requires jQuery version 1.9.1 or higher, but lower than version 3

We need jQuery 2 for Bootstrap 3 themes :(
We need to keep it both jQuery 2 and jQuery 3
Should the jQuery version selection be automatic based on theme Framework or a user option?

**Comment by juek** [comment]
> Should the jQuery version selection be automatic based on theme Framework or a user option?

No. 

Let's check (and maybe hack) it.

**Comment by juek** [comment]
But I would also be happy with jQuery 2

**Comment by mahotilo** [comment]
Maybe this is the right decision. We should  stop the avalanche of change. 
Bootstrap 4 can live with jQuery2.
UX is more important now.

**Comment by juek** [comment]
> Let's check (and maybe hack) it.

We could make 'our' Bootstrap 3 jQuery 3 compatible but if I remember correctly there are themes that ship their own Bootstrap 3 implementations.

Let's stay with jQuery 2.

**Comment by mahotilo** [comment]
> here are themes that ship their own Bootstrap 3 implementations.

A lot of

**Comment by juek** [comment]
OK, now we have jQuery 2.2.4

https://github.com/Typesetter/Typesetter/commit/a0185f9845969479110f62a9f84829c5b997e80d https://github.com/Typesetter/Typesetter/commit/58f5d16d4c389ef7a69a54f5f9f319ba2239c90a https://github.com/Typesetter/Typesetter/commit/560b6fb16bcfd4a17443c28327d3d6d5887b1635

**Comment by mahotilo** [comment]
Can we close the issue?

**Comment by juek** [comment]
hopefully *(crossing fingers … and closes)*
