### ISSUE TITLE
elFinder: thumbnails problems

### ISSUE THREAD

**Issue by mahotilo** [Typesetter/Typesetter#421]
When upload or drag&drop images to elFinder
1. No TS's thumbnail are created
2. `.tmb` (with elFinder's small thumbs) and `.quarantine` (empty) dirs are created in `_uploaded`

After `Recreate All Thumbnails`
1. `.tmb` dir is created in image/thumbnails and filled with elFinder's thumbs for TS's thumbs

After image is deleted
1. TS's thumbs is not deleted and elFinder's one too

So we do not have automatically created TS thumbs and have a huge amount of elFinder thumbs.

**Comment by juek** [comment]
Can't confirm. I'll try a fresh clean install...

**Comment by mahotilo** [comment]
OK, will recheck it. 
I had some mess with elFinder versions during test of their nightly build.

**Comment by juek** [comment]
With the current master everything is fine. All thumbs will be created and deleted again.
(Just tested a clean installation on Linux)

**Comment by mahotilo** [comment]
Strange.
My sequence:
1. download last TS master
2. restart local server
3. clear browser history, open  private windows
4. create new installation
5 look into _uploaded
```
D:\Internet\www\root\ts-z\data\_uploaded\
index.html	13	2019.12.30	11:20.0
.quarantine\	0	2019.12.30	11:20.14
.tmb\	0	2019.12.30	11:20.14
file\	0	2019.12.30	11:20.0
index.html	13	2019.12.30	11:20.0
image\	0	2019.12.30	11:20.0
index.html	13	2019.12.30	11:20.0
media\	0	2019.12.30	11:20.0
index.html	13	2019.12.30	11:20.0
 
```

6. drag&drop images
7. look into _uploaded/images
```
D:\Internet\www\root\ts-z\data\_uploaded\image\
fvw2092h.jpg	45694	2019.12.30	11:25.14
fvw2209h.jpg	36484	2019.12.30	11:25.14
fw02506h.jpg	38115	2019.12.30	11:25.14
fw03284h.jpg	60632	2019.12.30	11:25.14
fw03293h.jpg	47724	2019.12.30	11:25.14
fw16027h.jpg	47703	2019.12.30	11:25.14
fw17087h.jpg	47814	2019.12.30	11:25.14
index.html	13	2019.12.30	11:20.0

```
Everything is as I wrote

**Comment by mahotilo** [comment]
Windows 7.
Apache/2.4.27 (Win32) PHP/7.1.10 configured
Even reboot do not help me...
Will look at

**Comment by mahotilo** [comment]
The only message in Console

> JQMIGRATE: Migrate is installed with logging active, version 1.4.1

But I also have 37 verbose

> [Violation] Forced reflow while executing JavaScript took 61ms
> [Violation] Added non-passive event listener to a scroll-blocking <some> event. Consider marking event handler as 'passive' to make the page more responsive. See <URL>
....
> require.min.js:2 [Violation] 'load' handler took 192ms
> jquery.js?v=5.1.1-b1:4 [Violation] 'load' handler took 213ms
> [Violation] Forced reflow while executing JavaScript took 83ms
> 
>

**Comment by juek** [comment]
> Well, TSb1 with old elFinder works great, so it is not due to local server.

I'll try it with XAMPP anyway ...

**Comment by mahotilo** [comment]
I found that it works fine if I add files via the gallery button "Upload files". But not via elFinder itself.

**Comment by juek** [comment]
Confirm it fails on XAMPP. 
Must be either a path conversion issue or due to a subdirectory installation.

**Comment by mahotilo** [comment]
My local site address is 
http://www.test:8080/index.php

**Comment by juek** [comment]
It's not a subdirectory issue (just tested). Must be sth. different, but I don't get it at the moment.

@Sestowner Sergiy, could this possibly derive from https://github.com/Typesetter/Typesetter/commit/c722fcf830ddc2efdf89f5a842cb7575e863ed32 ?

**Comment by Sestowner** [comment]
> could this possibly derive from [c722fcf](https://github.com/Typesetter/Typesetter/commit/c722fcf830ddc2efdf89f5a842cb7575e863ed32) ?

No.

I just tested thumbnails generation on XAMPP and seems like it doesn't work even from 9edcea127252b3d55f2f908caec71dddc639d7ac

**Comment by juek** [comment]
UPDATE: The reason appears to be that elFinder uses escaped backslashes in paths 

E:\\xampp\\htdocs\\ts511b1\\data\\_uploaded\\image\\new.jpg

while the gallery upload script uses slashes

E:/xampp/htdocs/ts511b1/data/_uploaded/image/new.jpg

[CreateThumbnail()](https://github.com/Typesetter/Typesetter/blob/master/include/admin/Content/Uploaded.php#L561) expects forward slashes.

**Comment by juek** [comment]
@oyejorge 

Josh, should we simply filter the passed paths using [Winpath() ](https://github.com/Typesetter/Typesetter/blob/b12b24a97157346e7a5e0f6981029e0180108c97/include/tool.php#L342) in CreateThumbnail()?. Would be easy but maybe there a better solution?

**Comment by mahotilo** [comment]
I have made such experiment.
I took TS 5.1 and copied as few files as possible from the current muster needed to use the new elFinder.

They are
* admin/page.php
* admin/content/uploaded.php
* tool/Nonce

So apart from the elFinder itself, they are the only places where the flow had been broken.

**Comment by oyejorge** [comment]
> The reason appears to be that elFinder uses escaped backslashes in paths

This is unique to Windows systems... and sorry, I don't have a Windows system to test on.

Our connector has a [winHashFix](https://github.com/Typesetter/Typesetter/blob/master/include/thirdparty/elFinder/connector.php#L149) setting but I'm not finding anything about it in the [elFinder configuration options](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1)

**Comment by mahotilo** [comment]
> Our connector has a winHashFix setting 

Tried to change it without a result

**Comment by juek** [comment]
A Windows-free household. OMG, the legend is true!

**Comment by oyejorge** [comment]
Ubuntu all the way!

Does [this commit](https://github.com/oyejorge/Typesetter/commit/9356d8b51f32ed060dabc82dd57e34e9b2bb0ec4) fix anything for you?

**Comment by mahotilo** [comment]
No, does not

**Comment by juek** [comment]
> Does this commit fix anything for you?

AFAIK I already tried that.

**Comment by mahotilo** [comment]
I added log to Uploaded.php  FinderChange()
Maybe it will be useful? 

I uploaded test.jpg

`[Thu Jan 02 17:58:30.712795 2020] [php7:notice] [pid 2888:tid 868] [client 127.0.0.1:60646] catch:upload | Array\n(\n    [added] => Array\n        (\n            [0] => Array\n                (\n                    [isowner] => \n                    [ts] => 1577980710\n                    [mime] => image/jpeg\n                    [read] => 1\n                    [write] => 1\n                    [size] => 465345\n                    [hash] => l1_aW1hZ2UvdGVzdC5qcGc\n                    [name] => test.jpg\n                    [phash] => l1_aW1hZ2U\n                    [tmb] => 1\n                    [url] => /data/_uploaded/image/test.jpg\n                    [realpath] => D:\\Internet\\www\\root\\Ts-z\\data\\_uploaded\\image\\test.jpg\n                )\n\n        )\n\n    [removed] => Array\n        (\n        )\n\n    [changed] => Array\n        (\n            [0] => Array\n                (\n                    [isowner] => \n                    [ts] => 1577980710\n                    [mime] => directory\n                    [read] => 1\n                    [write] => 1\n                    [size] => 0\n                    [hash] => l1_aW1hZ2U\n                    [name] => image\n                    [phash] => l1_Lw\n                    [volumeid] => l1_\n                    [dirs] => 1\n                    [realpath] => D:\\Internet\\www\\root\\Ts-z\\data\\_uploaded\\image\n                )\n\n        )\n\n)\n, referer: http://www.test:8080/index.php/Admin/Uploaded
`

**Comment by oyejorge** [comment]
> I added log to Uploaded.php FinderChange()

Could you log the same data after WinPath() is called on all the realpath's? It looks like those realpaths will be `D://Internet//www//root...` and the fix might be to replace all `\\` (instead of all `\`) with `/`.

**Comment by mahotilo** [comment]
It is here now
Where do you want me to place log?

```
		public static function FinderChange($cmd, $result, $args, $finder){
			global $dataDir,$config;

			includeFile('image.php');
			\gp_resized::SetIndex();
			$base_dir = $dataDir.'/data/_uploaded';
			$thumb_dir = $dataDir.'/data/_uploaded/image/thumbnails';
			self::SetRealPath($result,$finder);
error_log('catch:'.$cmd.' | '.print_r($result, true));
           if(isset($result['removed']) or isset($result['added']))
			switch($cmd){


```

**Comment by oyejorge** [comment]
That's the right spot, it just needs the updated SetRealPath()

```
public static function SetRealPath(&$array,$finder){
	foreach($array as $type => $list){
		if( !is_array($list) ){
			continue;
		}
		foreach($list as $key => $info){
			if( isset($info['hash']) && !isset($info['realpath']) ){
				$array[$type][$key]['realpath'] = $finder->realpath($info['hash']);
			}
			if( isset($info['realpath']) ){
				$array[$type][$key]['realpath'] = \gp\tool::WinPath($info['realpath']);
			}
		}
	}
}
```

Then, after testing that, could you test this version of SetRealPath()?

```
public static function SetRealPath(&$array,$finder){
	foreach($array as $type => $list){
		if( !is_array($list) ){
			continue;
		}
		foreach($list as $key => $info){
			if( isset($info['hash']) && !isset($info['realpath']) ){
				$array[$type][$key]['realpath'] = $finder->realpath($info['hash']);
			}
			if( isset($info['realpath']) ){
				$array[$type][$key]['realpath'] = preg_replace('#\\+#', '/', $info['realpath']);
			}
		}
	}
}
```

**Comment by mahotilo** [comment]
First. Do not help.

`[Thu Jan 02 18:31:00.645325 2020] [php7:notice] [pid 2888:tid 820] [client 127.0.0.1:60824] catch:upload | Array\n(\n    [added] => Array\n        (\n            [0] => Array\n                (\n                    [isowner] => \n                    [ts] => 1577982660\n                    [mime] => image/jpeg\n                    [read] => 1\n                    [write] => 1\n                    [size] => 465345\n                    [hash] => l1_aW1hZ2UvdGVzdC5qcGc\n                    [name] => test.jpg\n                    [phash] => l1_aW1hZ2U\n                    [tmb] => 1\n                    [url] => /data/_uploaded/image/test.jpg\n                    [realpath] => D:\\Internet\\www\\root\\Ts-z\\data\\_uploaded\\image\\test.jpg\n                )\n\n        )\n\n    [removed] => Array\n        (\n        )\n\n    [changed] => Array\n        (\n            [0] => Array\n                (\n                    [isowner] => \n                    [ts] => 1577982660\n                    [mime] => directory\n                    [read] => 1\n                    [write] => 1\n                    [size] => 0\n                    [hash] => l1_aW1hZ2U\n                    [name] => image\n                    [phash] => l1_Lw\n                    [volumeid] => l1_\n                    [dirs] => 1\n                    [realpath] => D:\\Internet\\www\\root\\Ts-z\\data\\_uploaded\\image\n                )\n\n        )\n\n)\n, referer: http://www.test:8080/index.php/Admin/Uploaded
`

**Comment by mahotilo** [comment]
Second. Does not work either...

`[Thu Jan 02 18:32:11.859398 2020] [php7:notice] [pid 2888:tid 820] [client 127.0.0.1:60833] catch:upload | Array\n(\n    [added] => Array\n        (\n            [0] => Array\n                (\n                    [isowner] => \n                    [ts] => 1577982731\n                    [mime] => image/jpeg\n                    [read] => 1\n                    [write] => 1\n                    [size] => 465345\n                    [hash] => l1_aW1hZ2UvdGVzdC5qcGc\n                    [name] => test.jpg\n                    [phash] => l1_aW1hZ2U\n                    [tmb] => 1\n                    [url] => /data/_uploaded/image/test.jpg\n                    [realpath] => D:\\Internet\\www\\root\\Ts-z\\data\\_uploaded\\image\\test.jpg\n                )\n\n        )\n\n    [removed] => Array\n        (\n        )\n\n    [changed] => Array\n        (\n            [0] => Array\n                (\n                    [isowner] => \n                    [ts] => 1577982731\n                    [mime] => directory\n                    [read] => 1\n                    [write] => 1\n                    [size] => 0\n                    [hash] => l1_aW1hZ2U\n                    [name] => image\n                    [phash] => l1_Lw\n                    [volumeid] => l1_\n                    [dirs] => 1\n                    [realpath] => D:\\Internet\\www\\root\\Ts-z\\data\\_uploaded\\image\n                )\n\n        )\n\n)\n, referer: http://www.test:8080/index.php/Admin/Uploaded
`

**Comment by oyejorge** [comment]
Strange. They both should have resulted in changes to the realpath. This SetRealPath() should give us a better idea of what's going on

```
public static function SetRealPath(&$array,$finder){

	error_log('setrealpath called '.json_encode($array));

	foreach($array as $type => $list){
		if( !is_array($list) ){
			continue;
		}
		foreach($list as $key => $info){
			if( isset($info['hash']) && !isset($info['realpath']) ){
				$array[$type][$key]['realpath'] = $finder->realpath($info['hash']);
			}
			if( isset($info['realpath']) ){

				error_log('setrealpath before winpath '.$info['realpath']);

				$array[$type][$key]['realpath'] = \gp\tool::WinPath($info['realpath']);

				error_log('setrealpath after winpath '.$info['realpath']);

			}else{
				error_log('no realpath '.json_encode($info));
			}
		}
	}

	error_log('after setrealpath '.json_encode($array));

}
```

**Comment by mahotilo** [comment]
`[Thu Jan 02 18:45:47.816068 2020] [php7:notice] [pid 5360:tid 852] [client 127.0.0.1:60867] setrealpath called {"added":[{"isowner":false,"ts":1577983547,"mime":"image\\/jpeg","read":1,"write":1,"size":"465345","hash":"l1_aW1hZ2UvdGVzdC5qcGc","name":"test.jpg","phash":"l1_aW1hZ2U","tmb":1,"url":"\\/data\\/_uploaded\\/image\\/test.jpg"}],"removed":[],"changed":[{"isowner":false,"ts":1577983547,"mime":"directory","read":1,"write":1,"size":0,"hash":"l1_aW1hZ2U","name":"image","phash":"l1_Lw","volumeid":"l1_","dirs":1}]}, referer: http://www.test:8080/index.php/Admin/Uploaded
`


```
[Thu Jan 02 18:45:47.816068 2020] [php7:notice] [pid 5360:tid 852] [client 127.0.0.1:60867] no realpath {"isowner":false,"ts":1577983547,"mime":"image\\/jpeg","read":1,"write":1,"size":"465345","hash":"l1_aW1hZ2UvdGVzdC5qcGc","name":"test.jpg","phash":"l1_aW1hZ2U","tmb":1,"url":"\\/data\\/_uploaded\\/image\\/test.jpg"}, referer: http://www.test:8080/index.php/Admin/Uploaded
[Thu Jan 02 18:45:47.816068 2020] [php7:notice] [pid 5360:tid 852] [client 127.0.0.1:60867] no realpath {"isowner":false,"ts":1577983547,"mime":"directory","read":1,"write":1,"size":0,"hash":"l1_aW1hZ2U","name":"image","phash":"l1_Lw","volumeid":"l1_","dirs":1}, referer: http://www.test:8080/index.php/Admin/Uploaded
[Thu Jan 02 18:45:47.816068 2020] [php7:notice] [pid 5360:tid 852] [client 127.0.0.1:60867] after setrealpath {"added":[{"isowner":false,"ts":1577983547,"mime":"image\\/jpeg","read":1,"write":1,"size":"465345","hash":"l1_aW1hZ2UvdGVzdC5qcGc","name":"test.jpg","phash":"l1_aW1hZ2U","tmb":1,"url":"\\/data\\/_uploaded\\/image\\/test.jpg","realpath":"D:\\\\Internet\\\\www\\\\root\\\\Ts-z\\\\data\\\\_uploaded\\\\image\\\\test.jpg"}],"removed":[],"changed":[{"isowner":false,"ts":1577983547,"mime":"directory","read":1,"write":1,"size":0,"hash":"l1_aW1hZ2U","name":"image","phash":"l1_Lw","volumeid":"l1_","dirs":1,"realpath":"D:\\\\Internet\\\\www\\\\root\\\\Ts-z\\\\data\\\\_uploaded\\\\image"}]}, referer: http://www.test:8080/index.php/Admin/Uploaded
[Thu Jan 02 18:45:47.816068 2020] [php7:notice] [pid 5360:tid 852] [client 127.0.0.1:60867] catch:upload | Array\n(\n    [added] => Array\n        (\n            [0] => Array\n                (\n                    [isowner] => \n                    [ts] => 1577983547\n                    [mime] => image/jpeg\n                    [read] => 1\n                    [write] => 1\n                    [size] => 465345\n                    [hash] => l1_aW1hZ2UvdGVzdC5qcGc\n                    [name] => test.jpg\n                    [phash] => l1_aW1hZ2U\n                    [tmb] => 1\n                    [url] => /data/_uploaded/image/test.jpg\n                    [realpath] => D:\\Internet\\www\\root\\Ts-z\\data\\_uploaded\\image\\test.jpg\n                )\n\n        )\n\n    [removed] => Array\n        (\n        )\n\n    [changed] => Array\n        (\n            [0] => Array\n                (\n                    [isowner] => \n                    [ts] => 1577983547\n                    [mime] => directory\n                    [read] => 1\n                    [write] => 1\n                    [size] => 0\n                    [hash] => l1_aW1hZ2U\n                    [name] => image\n                    [phash] => l1_Lw\n                    [volumeid] => l1_\n                    [dirs] => 1\n                    [realpath] => D:\\Internet\\www\\root\\Ts-z\\data\\_uploaded\\image\n                )\n\n        )\n\n)\n, referer: http://www.test:8080/index.php/Admin/Uploaded

```

**Comment by mahotilo** [comment]
Clearer one
```
[Thu Jan 02 18:48:51.583579 2020] [php7:notice] [pid 5360:tid 852] [client 127.0.0.1:60878] setrealpath called {"added":[{"isowner":false,"ts":1577983731,"mime":"image\\/jpeg","read":1,"write":1,"size":"465345","hash":"l1_aW1hZ2UvdGVzdC5qcGc","name":"test.jpg","phash":"l1_aW1hZ2U","tmb":1,"url":"\\/data\\/_uploaded\\/image\\/test.jpg"}],"removed":[],"changed":[{"isowner":false,"ts":1577983731,"mime":"directory","read":1,"write":1,"size":0,"hash":"l1_aW1hZ2U","name":"image","phash":"l1_Lw","volumeid":"l1_","dirs":1}]}, referer: http://www.test:8080/index.php/Admin/Uploaded
[Thu Jan 02 18:48:51.583579 2020] [php7:notice] [pid 5360:tid 852] [client 127.0.0.1:60878] no realpath {"isowner":false,"ts":1577983731,"mime":"image\\/jpeg","read":1,"write":1,"size":"465345","hash":"l1_aW1hZ2UvdGVzdC5qcGc","name":"test.jpg","phash":"l1_aW1hZ2U","tmb":1,"url":"\\/data\\/_uploaded\\/image\\/test.jpg"}, referer: http://www.test:8080/index.php/Admin/Uploaded
[Thu Jan 02 18:48:51.583579 2020] [php7:notice] [pid 5360:tid 852] [client 127.0.0.1:60878] no realpath {"isowner":false,"ts":1577983731,"mime":"directory","read":1,"write":1,"size":0,"hash":"l1_aW1hZ2U","name":"image","phash":"l1_Lw","volumeid":"l1_","dirs":1}, referer: http://www.test:8080/index.php/Admin/Uploaded
[Thu Jan 02 18:48:51.583579 2020] [php7:notice] [pid 5360:tid 852] [client 127.0.0.1:60878] after setrealpath {"added":[{"isowner":false,"ts":1577983731,"mime":"image\\/jpeg","read":1,"write":1,"size":"465345","hash":"l1_aW1hZ2UvdGVzdC5qcGc","name":"test.jpg","phash":"l1_aW1hZ2U","tmb":1,"url":"\\/data\\/_uploaded\\/image\\/test.jpg","realpath":"D:\\\\Internet\\\\www\\\\root\\\\Ts-z\\\\data\\\\_uploaded\\\\image\\\\test.jpg"}],"removed":[],"changed":[{"isowner":false,"ts":1577983731,"mime":"directory","read":1,"write":1,"size":0,"hash":"l1_aW1hZ2U","name":"image","phash":"l1_Lw","volumeid":"l1_","dirs":1,"realpath":"D:\\\\Internet\\\\www\\\\root\\\\Ts-z\\\\data\\\\_uploaded\\\\image"}]}, referer: http://www.test:8080/index.php/Admin/Uploaded

```

**Comment by oyejorge** [comment]
Ok, I see it now! Here are the two updated versions of SetRealPath()


```
public static function SetRealPath(&$array,$finder){
	foreach($array as $type => $list){
		if( !is_array($list) ){
			continue;
		}
		foreach($list as $key => $info){
			if( isset($info['hash']) && !isset($info['realpath']) ){
				$array[$type][$key]['realpath'] = $finder->realpath($info['hash']);
			}
			if( isset($array[$type][$key]['realpath']) ){
				$array[$type][$key]['realpath'] = \gp\tool::WinPath($array[$type][$key]['realpath']);
			}
		}
	}
}
```

And the second:

```
public static function SetRealPath(&$array,$finder){
	foreach($array as $type => $list){
		if( !is_array($list) ){
			continue;
		}
		foreach($list as $key => $info){
			if( isset($info['hash']) && !isset($info['realpath']) ){
				$array[$type][$key]['realpath'] = $finder->realpath($info['hash']);
			}
			if( isset($array[$type][$key]['realpath']) ){
				$array[$type][$key]['realpath'] = preg_replace('#\\+#', '/', $array[$type][$key]['realpath']);
			}
		}
	}
}
```

**Comment by mahotilo** [comment]
First.
It works!

**Comment by mahotilo** [comment]
Second
Does'n work :(

**Comment by mahotilo** [comment]
So we have a winner!

**Comment by mahotilo** [comment]
I can't wait to see the PR 
:)

**Comment by mahotilo** [comment]
I am a little bit old-fashioned, but the second variant works in this modification

> $array[$type][$key]['realpath'] = str_replace('\\', '/', $array[$type][$key]['realpath']);

**Comment by mahotilo** [comment]
Let me do this:)

**Comment by juek** [comment]
Sorry for re-opening.

Confirm it works now, but thumbnails won't be deleted when deleting images in gallery editor.

**Comment by mahotilo** [comment]
Yes, for me too :(

**Comment by juek** [comment]
It's both on Windows and Linux.

**Comment by mahotilo** [comment]
TS 5.1.1-b1 has it too.

**Comment by juek** [comment]
LOL, it's here since at least 4.6.1. I feel like an Archeologist.

**Comment by mahotilo** [comment]
DinoBug

**Comment by juek** [comment]
4.3.4 too. I don't want to dig any deeper.
