### ISSUE TITLE
Is scrolling on section hover a source of page crash?

### ISSUE THREAD

**Issue by mahotilo** [Typesetter/Typesetter#422]
It seems to me, that scrolling to hovered section can somehow break the page autosave.
If we stop scrolling on hover (the red outline can be saved and made even more bold) and scroll to section only after clicking on their name, this could help prevent page from crashing during quick and massive operations with sections.

Edit:
Another source of problems is section dragging, which is also related to page scrolling.

**Comment by juek** [comment]
Scrolling shouldn't affect other things at all. It doesn't alter any values that would be correlated with  saving or saved data. 

What kind of error(s) you you get?

**Comment by mahotilo** [comment]
Oops, not a draft

**Comment by juek** [comment]
> You get a 'Not a draft' error when scrolling?

IMO it may only occur when clicking 'Publish Draft' with unsaved changes.

**Comment by juek** [comment]
Is that behavior new at your side?

**Comment by mahotilo** [comment]
1. It is not a problem of current master. It has persisted since v5.0-5.1
2. No, not during scrolling, but after working with sections (a lot quick actions) when I press save.

The only  solution for me now is to be patient and do all the section operations with a pause looking on the save button. But sometimes it happens just after dragging a section from last line (after adding) to position I need. So the only source as for me is page scrolling and redrawing.

**Comment by juek** [comment]
Seems as if my immediate saving when a section is added still doesn't work. Ill check it.

**Comment by juek** [comment]
> Seems as if my immediate saving when a section is added still doesn't work. Ill check it.

Actually it was not implemented in AddSection. Please try if [this commit](https://github.com/Typesetter/Typesetter/commit/e9bbb365cf126bbe039ef0e40403b6394e46a8c1) helps.

**Comment by mahotilo** [comment]
Not only here. 
I was adding a bulk of section for different plugins.
I found some conflicts and started to localize it (it appeared to be catalogeasy).
I quickly clicked on visible icons to shut down sections.
And oops, I can not save page.

**Comment by juek** [comment]
We may need to enable an overlay to block clicks while saving. I hoped we could spare ourselves that.

**Comment by mahotilo** [comment]
> Please try if this commit helps.

Well, now it looks like a trouble-free flow.
But this error is not easy to reproduce, although it is difficult to avoid.
I will monitor the situation and inform you.

**Comment by mahotilo** [comment]
> We may need to enable an overlay to block clicks while saving. I hoped we could spare ourselves that.

Maybe some delay in JS .on... functions can help in this situation? I still suspect live page operations.

**Comment by juek** [comment]
Overlay added with [this commit](https://github.com/Typesetter/Typesetter/commit/8562105ee5b8f2bc7f4e1accb004643c1046b4a4). I hope we can somehow get rid of it again.

**Comment by juek** [comment]
> But this error is not easy to reproduce, although it is difficult to avoid.

It has bothered me for years. I want that bulletproof.

**Comment by mahotilo** [comment]
> Overlay added with this commit. 

It certainly helps with quick visible/invisible switching.

But what about page scrolling while moving a section :)
For example, when I need to work with a large structure in SliderFactory and move sections up and down, it drives me crazy. Closed wrappers begin to open, a dragged section appears between other sections and page start scrolls. Everything is blinking. Drag and drop failed and then I get "oops, can not save".

**Comment by mahotilo** [comment]
It will be quite suitable to scroll to section only after click on its name. What do you think?

**Comment by juek** [comment]
> scroll to section only after click

Convinced. OK, let's [do it](https://github.com/Typesetter/Typesetter/commit/f292d078abab428590123f38cca88d00a80e8a6a).

**Comment by juek** [comment]
> Maybe some delay in JS .on... functions can help in this situation? 

No, delays would only make things worse. We would rather need to save sort of a 'shadowcopy' or 'snapshot'. I'm not smart enough for that kind of stuff and I fear jQuery is not the best tool here, either.

**Comment by juek** [comment]
> I'm not smart enough for that…

… but I know someone who is (hello @oyejorge 👋) 
Snapshots could also pave the way for an often requested undo history. Just sayin'.

**Comment by mahotilo** [comment]
Well, I am not very superstitious but I will cross my fingers. Looks like FIXed!

**Comment by juek** [comment]
> I will cross my fingers

Yes, let's cross them all :)

**Comment by mahotilo** [comment]
OK, I caught it again. This time I can clearly say that it was during visibility switching. The overlay trick really helps, but glitch happened on 10th switching in a raw (I was switching visibility of all the sections one by one as quickly as overlay allowed).
On the positive side, now the page crash is localized to 1-2 last operations with sections. Also, I did not have to restore the previous version of the pages. I just reloaded the page and repeated the last operations with sections.
It still is great progress.

**Comment by juek** [comment]
> This time I can clearly say that it was during visibility switching

I speeded up the hide/unhide (slide) animation and moved the instant saving into the callback. This should be even safer now. https://github.com/Typesetter/Typesetter/commit/803ad84045f558f398a2b537c30d36a796a7176d

**Comment by mahotilo** [comment]
Yes, now it is simply impossible to switch visibility too fast!

**Comment by juek** [comment]
> It seems to me, callback is a really good idea

Oh yes it is. It shouldn't ever have been outside. 
Your tests are really invaluable. Thx a lot!
