### ISSUE TITLE
Poll: Rearrange and simplify Previous/Next revision buttons

### ISSUE THREAD

**Issue by mahotilo** [Typesetter/Typesetter#424]
Does this seem more compact and understandable?

Sometimes this text "Previous" misleads me to treat it as "previous page".

And we can make "tiltle=" more clear, like "Previous **revision**", "Next **revision**"

![image](https://user-images.githubusercontent.com/14929385/71621964-632dce80-2bdb-11ea-94cc-87686ca906f8.png)

**Comment by mahotilo** [comment]
Another idea is to treat 1еру middle part of top menu as a tray for the various notification/control buttons.

Of course, this will require some API (an array for storage and functions to use) and a lot of work. So this is nothing more than idea for discussion and plans for the future.

![image](https://user-images.githubusercontent.com/14929385/71623971-b4908a80-2be8-11ea-9e9e-275eda810eeb.png)

**Comment by juek** [comment]
> Does this seem more compact and understandable?

Yes, it does. However, I believe that the page revision navigation is too prominent and takes up too much space in the top bar. I use the page revisions almost only when something went wrong. 30 versions are not enough to restore a really older page. 

I would rather rethink the concept on a more fundamental level, including contents of Admin Menu vs. Top Bar, UI element docking and **custom rearrangement**, contents of Edit context menu, implementation of [HideAdminUi](https://github.com/juek/HideAdminUI), etc.

But not for 5.2. I'd like to get it out soon.

**Comment by mahotilo** [comment]
> But not for 5.2. I'd like to get it out soon.

Totally agree.

**Comment by juek** [comment]
See also https://github.com/Typesetter/Typesetter/issues/415
