### ISSUE TITLE
Admin pages AJAX refresh

### ISSUE THREAD

**Issue by juek** [Typesetter/Typesetter#431]
@oyejorge 

Josh, I just [re-added](https://github.com/Typesetter/Typesetter/commit/8754843016e42f37e37b8b265765573a9c77cfae) #gpx_content to the ajaxReplace array. Admin pages with AJAX saving don't refresh without it. 

Does anything speak against it?

**Comment by oyejorge** [comment]
No, it makes more sense to keep the gpx_content for better backward compat.
