### ISSUE TITLE
should we open GPUI to plugins?

### ISSUE THREAD

**Issue by juek** [Typesetter/Typesetter#437]
I currently have 2 plugins in the works that (ab)use outdated [ckx](https://github.com/juek/ExpandableEditor/blob/master/ExpandableEditor.js#L5) and [cky](https://github.com/juek/BootstrapGridTool/blob/master/src/BootstrapGridTool.js#L957) GPUI values. That's extremely convenient but of course it cannot be the final solution. 

While it wouldn't be too hard to implement a similar solution to store everything in _addondata/MyPlugin, I wonder if it would make sense to open GPUI for plugins?

**Comment by juek** [comment]
Is it too dangerous (cookie max size)?

**Comment by oyejorge** [comment]
A gpui cookie sounds familiar...

There are a couple of potential issues:
* The plugin's values will always be in $gpAdmin, even after the plugin is uninstalled
* There's nothing to guarantee plugin values don't conflict with values from other plugins

It makes me wonder if we actually need to save any gpui values on the server? They could just be [saved in the web browser with localstorage](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage).

**Comment by juek** [comment]
> There are a couple of potential issues

True. It is not worth. Let's leave plugin data where it belongs.

> … be saved in the web browser with localstorage.

Would not survive too long here :)

**Comment by juek** [comment]
[reverted](https://github.com/Typesetter/Typesetter/commit/9023fa373909c28e6f324e2cfb262516609db023) and closing.
