### ISSUE TITLE
Png Compression proposal

### ISSUE THREAD

**Issue by gtbu** [Typesetter/Typesetter#445]
Typesetter uses ccsmin as compressor for css and also a js-compressor. 
Png-images can be huge. There is a php-lib [ pngquant](https://pngquant.org/php.html) which reduces secure png's drastic. 

There is also php-fork at https://github.com/ourcodeworld/php-pngquant. 
It also been added to [symphony](https://symfony.com/index.php/doc/2.0/bundles/LiipImagineBundle/post-processors/png-quant.html) , and there is  a [code at php.net](https://www.php.net/manual/de/function.imagewebp.php)

**Comment by mahotilo** [comment]
IMO, this is certainly not for CMS, but for a plugin like that
We have https://www.typesettercms.com/Plugins/321_TinyPNG

**Comment by juek** [comment]
> There is a php-lib pngquant which reduces secure png's drastic.

That's only a wrapper for pngquant, which must be installed on the server. We can't install software on the server, normally. If we wanted to do advanced image manipulation server-side, there is a certain chance having imagemagick, which can do [PNG quantization](http://www.imagemagick.org/Usage/quantize/) and much more.
