### ISSUE TITLE
cssmin - csstidy

### ISSUE THREAD

**Issue by gtbu** [Typesetter/Typesetter#448]
After studying the 3 bugs in the smart-multi-template, which caused me to add
$page->head .= '<link rel="stylesheet" type="text/css" href="'.$themeDir . '/' .....  to the settings.php, i had to notice that the bugs have disappeared in the newest CE and in the newer 5.1.1b1 - but still 
there is  http://typesetter5.bplaced.net/smtiny--blue ( only for interested - the combined css is in the site-source in Firefox - and  i cant find the reason - but i will remove it soon).  
During these tests i experimented with csstidy instead of cssmin. If somebody is interested : Just make a directory csstidy unter thirdparty and unpack[ this zip ](http://typesetter5.bplaced.net/data/_uploaded/file/csstidy.zip) and exchange ( or rename) the contained  CombineCss.php  in the CMS.

**Comment by juek** [comment]
Firefox's viewsource reveals what's happening:

![grafik](https://user-images.githubusercontent.com/704283/71770122-8e8d2200-2f29-11ea-8779-fe372e8ebc82.png)

**Comment by gtbu** [comment]
The csses have been added - it's not the adder. If i click at the red combined css, then i get into the css - the css has no bugs - if i dont not make  a hokk into combine css'es the it functioins. So whats the bug ?

**Comment by juek** [comment]
> So whats the bug ?

The bug is the non-closed meta-viewport tag!

**Comment by gtbu** [comment]
It first i was a bit disturbed, because the other smartmenu-templates use the same template. Then i looked with ftp at the template, and everything was ok - no missing brackets.
![git1](https://user-images.githubusercontent.com/30436307/71779173-40bdfb80-2fb5-11ea-9061-a0977d995ea9.jpg)
Then i installed it at laragon - and the complete template functioned...(also the FA-icons). So it is probably the old 51b1, and i will make  new bplaced installation next week ("life is just a big challenge")

**Comment by juek** [comment]
> So it is probably the old 5.1.1b1(the same was also at xampp) 

I doubt. No one else has ever had such a problem and PHP doesn't eat braces every now and then.
