### ISSUE TITLE
Syntax error created using \gp\tool\Files::SaveData()

### ISSUE THREAD

**Issue by juek** [Typesetter/Typesetter#451]
**Error:**

```
Oops, an error occurred while generating this page.

Error Details

array(
   [type] => (integer)4
   [message] => (string)syntax error, unexpected ')', expecting end of file
   [file] => (string)[Typesetter installation directory]/data/_addondata/[PluginName]/debug.php
   [line] => (integer)17
)

Reload this page

Note: Error details are only displayed for logged in administrators
```

**Content of debug.php:**

```
<?php
defined('is_running') or die('Not an entry point...');
$fileVersion = '5.1.1-b1';
$fileModTime = '1578329725';
$file_stats = array (
  'modified' => 1578329725,
  'gpversion' => '5.1.1-b1',
  'username' => 'juergen',
);

$debug = array (
  'current_id' => 'dynamic-id-placeholder',
  'replaced_id' => 'dyn-ciUWBRnj',
);

$meta_data = array (
););

$meta_data = array (
);
```

**Comment by juek** [comment]
@oyejorge Do you need more context?

**Comment by juek** [comment]
> @oyejorge Do you need more context?

Certainly, because the debug array is created by my plugin, using 

`\gp\tool\Files::SaveData($addonPathData . '/debug.php',  'debug', $debug);`

It just never happened to me that SaveData() would create synatx errors. Can this be related to the new error catching?

**Comment by juek** [comment]
Unfortunately, I am currently unable to recreate the problem. This was most likely to happen during the page revision preview.

**Comment by oyejorge** [comment]
> Can this be related to the new error catching?

I don't think so.

It kind of looks like the debug.php file was written to by two different processes at nearly the same time.

**Comment by juek** [comment]
> It kind of looks like the debug.php file was written to by two different processes at nearly the same time

Sounds reasonable. 
This debug.php actually never gets evaluated.  
Interesting – I'll have to check it.
