### ISSUE TITLE
Revision History: « Previous Next » and chronology

### ISSUE THREAD

**Issue by juek** [Typesetter/Typesetter#453]
That's just a minor issue, merely a question. 

![grafik](https://user-images.githubusercontent.com/704283/71835983-3da93500-30b3-11ea-8eb5-92e8d0e45c22.png)

The « Previous Next » navigation in the new Revision History panel is semantically and visually correct in terms of the below items list order. But it's incorrect in terms of revision chronology.

What do you guys say? Keep it, change it?

**Comment by mahotilo** [comment]
If you ask me...
1. I prefer to have "Close" button instead of the page name (e.g. Home), because all these lines are about this page.
2. Yes, sth like "Later / Earlier" or "Older / Newer" should be clearer.
3. Instead of "Restore" we can use fa-history sign. 
4. Control Panel with the version list can be placed on the left, since  "Revision History" menu item is also located on the left side of the menu.

**Comment by oyejorge** [comment]
> But it's incorrect in terms of revision chronology.

Right. Clicking "Next" should get a newer revision, not an older. I'd say change it.

> Control Panel with the version list can be placed on the left, since "Revision History" menu item is also located on the left side of the menu.

What if the "Revision History" link was on the right with "Sections", "Extra Content" etc?

**Comment by mahotilo** [comment]
> What if the "Revision History" link was on the right with "Sections", "Extra Content" etc?
This is so unusual :) 
But there is logic in this. All control elements that cause revision are also placed on the right side.

**Comment by oyejorge** [comment]
[How about this](https://github.com/Typesetter/Typesetter/pull/455)

![Link on right](https://user-images.githubusercontent.com/1043524/71851317-805b1500-3093-11ea-8ffb-a39b01e701b2.png)

![up-down-buttons](https://user-images.githubusercontent.com/1043524/71851319-8224d880-3093-11ea-9415-88dd19ff40f8.png)

**Comment by juek** [comment]
Yes, Go East!

**Comment by juek** [comment]
[merged](https://github.com/Typesetter/Typesetter/pull/455)

**Comment by juek** [comment]
Now we got a problem ;)  Watch …
![admin-menu-and-options-01](https://user-images.githubusercontent.com/704283/71857455-e1143d00-30e7-11ea-9704-c58676015299.gif)

**Comment by mahotilo** [comment]
Move it. You always defend your right to move it right :)

**Comment by juek** [comment]
> Move it. You always defend your right to move it right :)

I knew you would say that :)

**Comment by juek** [comment]
[hotfixed](https://github.com/Typesetter/Typesetter/commit/f64c0d0098124a97b72d565c6369525c543fa3d8)

**Comment by juek** [comment]
@oyejorge off-topic question regarding indentation of last line in Scss:

```
selector{
	property: value;
	}
```
is that vim or is it intentionally for some reason?

**Comment by oyejorge** [comment]
It's unintentional. I've used a few different editors and some haven't enforced markup style.
