### ISSUE TITLE
Revision History: add Publish Draft?

### ISSUE THREAD

**Issue by juek** [Typesetter/Typesetter#454]
![grafik](https://user-images.githubusercontent.com/704283/71839898-86192080-30bc-11ea-9955-e9d7b413d10c.png)

Should we?

**Comment by mahotilo** [comment]
I think, the place for publishing a working draft should be the only one.
This is a serious action, and we should respect the Big Green Button.

**Comment by oyejorge** [comment]
I could go either way on this one

**Comment by juek** [comment]
> I think, the place for publishing a working draft should be the only one.

I'm basically with you, but in this case a revision could be fully restored without going through 'Edit'. So I'd say let's add it there.

**Comment by mahotilo** [comment]
Ok

**Comment by juek** [comment]
It's a tie, so save it for future eagerness ;)
