### ISSUE TITLE
Question: Edit current layout

### ISSUE THREAD

**Issue by mahotilo** [Typesetter/Typesetter#460]
This button opens layout editor when I have only one layout on the site. But when there are a few layouts, it opens the Themes»Manage. Should it always open a layout editor for the current page layout?

![image](https://user-images.githubusercontent.com/14929385/71885712-90cac880-3143-11ea-8103-e3b231766a78.png)

**Comment by juek** [comment]
I thought that I fixed it (some years ago) but in fact I didn't :)
I'll try it again…

**Comment by juek** [comment]
[this commit](https://github.com/Typesetter/Typesetter/commit/52a7edf48af0a23a7ebd2b20898902668c3fc75d) should fix it

**Comment by mahotilo** [comment]
Yes, it is OK for me.
The issue can be closed.
