### ISSUE TITLE
Close for Extra content

### ISSUE THREAD

**Issue by mahotilo** [Typesetter/Typesetter#462]
We now have a 'Close' button in all control panels on the right side, except Extra content. Should we add it?

UPD
It is here https://github.com/Typesetter/Typesetter/blob/1436440cd0cc9100059c530ee8bfbce3bcf264c0/include/js/inline_edit/inline_editing.js#L337
I do not know if it is wrong to see 'Saved' label but 'Close' button gives the user control of the panel.

**Comment by juek** [comment]
In fact, publishing Extra Content does not require to close the editor because it's all AJAX. 
But I agree - it should be there for UI consistency.

**Comment by juek** [comment]
Done with [this commit](https://github.com/Typesetter/Typesetter/commit/d668824f2963813cc8aa9a0ea2a4891ccb5ae668)
