### ISSUE TITLE
Extra content editor publish draft error

### ISSUE THREAD

**Issue by mahotilo** [Typesetter/Typesetter#463]
When I click 'Publish draft' in Extra content editor, nothing happens, but in reality, the content is published.

When I click 'Publish draft' for the second time, 'Homepage » Administration » Extra Content' opens and 'Oops, that didn't work, please try again. (not a draft)' appears and then 'Oops, that didn't work, please try again. (Invalid Request)'.

![image](https://user-images.githubusercontent.com/14929385/71934369-f30be380-31ac-11ea-8877-d13a8eb94e81.png)

**Comment by juek** [comment]
Confirmed.

**Comment by juek** [comment]
Yep, that does the trick. I [pushed it](https://github.com/Typesetter/Typesetter/commit/3d4d32abcd1b7507715784af4288e56fac7d6b91) (no merge option)
