### ISSUE TITLE
Extra Content "Bootstrap Dropdown Divider"

### ISSUE THREAD

**Issue by mahotilo** [Typesetter/Typesetter#466]
I found this extra content in default theme after clear install
![image](https://user-images.githubusercontent.com/14929385/71958304-a4843680-31f8-11ea-9daf-e18f9f3a5692.png)

I found a link to Bootstrap Dropdown Divider [here](https://github.com/Typesetter/Typesetter/blob/d5bd66446ca0a88ab1ad9bd4c3bff126b78e765f/themes/Bootswatch4_Scss/_common/common_style.scss#L98) and nowhere else.

Is this a bug?

**Comment by juek** [comment]
I once made it so it can be added to a menu easily.

**Comment by mahotilo** [comment]
>  can be added to a menu easily.

Not for me:) How to use it?

**Comment by mahotilo** [comment]
Can we give some explanation in content?

![image](https://user-images.githubusercontent.com/14929385/71993669-277caf80-3240-11ea-9c36-d9d2fcc46e8f.png)

**Comment by juek** [comment]
> Can we give some explanation in content?

But tThis text would be added to the menu section then.

**Comment by mahotilo** [comment]
Yes, bad idea...
