### ISSUE TITLE
Extra Content publishing error

### ISSUE THREAD

**Issue by mahotilo** [Typesetter/Typesetter#467]
I have such an error on the page "`http://www.test:8080/index.php/Admin/Extra?file=Bootstrap_Dropdown_Divider`" when I try to reload the page after the draft is published.

![image](https://user-images.githubusercontent.com/14929385/71959184-c2eb3180-31fa-11ea-90ad-1b08def7ee9d.png)

I have no warnings from browser about "send page content again".

UPD
Publication should be made here
![image](https://user-images.githubusercontent.com/14929385/71960425-adc3d200-31fd-11ea-92c7-1bd7ad034513.png)

**Comment by juek** [comment]
> Publication should be made here

It is, after saving the button gets replaced.

**Comment by mahotilo** [comment]
> > Publication should be made here
> 
> It is there, after saving the button gets replaced.

Sorry. When I was saying 'should be', I meant "to reproduce my error you should publish draft on this page and not on Extra content"

**Comment by juek** [comment]
When I publish from the editor page I end up on the list page. Feels reasonable. 
When I then refresh the page, Firefox and Chrome both show the 'resend form data' warning.

**Comment by mahotilo** [comment]
I use Opera. It is basically Chromium, but I do not have 'resend form data' warning in this situation.
Of curse, it can be an Opera "feature":)

But for the last time.
1. open Extra Content `http://www.test:8080/index.php/Admin/Extra`
2. press edit on Bootstrap Dropdown Divider (sorry it is first in the list:)
3. Extra Content » Bootstrap Dropdown Divider `http://www.test:8080/index.php/Admin/Extra?cmd=EditExtra&file=Bootstrap_Dropdown_Divider`
4. Edit and Save
5. Press Publish draft
6. Again Extra Content but with URL `http://www.test:8080/index.php/Admin/Extra?file=Bootstrap_Dropdown_Divider`
7. Reload F5 
8. Oops, that didn't work, please try again. (Not a draft)

Why at step #6 URL is not just `http://www.test:8080/index.php/Admin/Extra`?

**Comment by juek** [comment]
We should probably implement [PRG patterns](https://en.wikipedia.org/wiki/Post/Redirect/Get) for all such cases. I believe Typesetter already has all we need. It's just that I'm really not exactly good at it. :/
@oyejorge, @Sestowner ?

**Comment by oyejorge** [comment]
On it

**Comment by juek** [comment]
Now, publishing Extra Content in page editing context is broken:

![grafik](https://user-images.githubusercontent.com/704283/72319236-f3b9e380-369e-11ea-8e32-328691e427d5.png)

**Comment by mahotilo** [comment]
Confirm error. 
And when I reload plugin's admin page after setting saving, they are saved again and TS shows me relevant message. So all of these changes are not about PRG, are they?

**Comment by oyejorge** [comment]
Sorry, I can fix that tomorrow

**Comment by juek** [comment]
> And when I reload plugin's admin page after setting saving

That also depends on the plugin. Some do AJAX saving, which shouldn't be affected.

**Comment by mahotilo** [comment]
I have looked again and realized that it is only a message and a saving. If I close the yellow box, it will not appear after page reload.

**Comment by juek** [comment]
Appears to be fixed with https://github.com/Typesetter/Typesetter/commit/3545f874412c7a6d4a5f117d788f7838088c8b40

**Comment by mahotilo** [comment]
This one https://github.com/Typesetter/Typesetter/issues/467#issuecomment-574023211 - yes
But initial one https://github.com/Typesetter/Typesetter/issues/467#issue-546697479 - no. At least I still have.

**Comment by oyejorge** [comment]
> This one #467 (comment) - yes
> But initial one #467 (comment) - no. At least I still have.

Dang it, yep. They conflict with each other and I've been going in circles. One sec..
