### ISSUE TITLE
Old path

### ISSUE THREAD

**Issue by gtbu** [Typesetter/Typesetter#468]
At the bottom of ' CKEditor » Manage Plugins | Configuration | Example' stands : 
CKEditor is Typesetter's text editor of choice because it is a powerful tool with[ many configuration options](http://docs.cksource.com/ckeditor_api/symbols/CKEDITOR.config.html) and a growing list of plugins.      In it is still the old link to ckeditor 3
Old link should be replaced with https:// ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html

**Comment by gtbu** [comment]
As You once proposed the ckeditor monoo-skin. I personallay think that a [bootsptrap - skin](https://ckeditor.com/cke4/addon/bootstrapck) makes a nicer impression...!

**Comment by juek** [comment]
As far as I can see, both use the moono-lisa icons.

**Comment by gtbu** [comment]
Yes - but the skin is not so dark - it has a white background behind the icons.

**Comment by juek** [comment]
Have you tried it? Post a screenshot.
BTW: we're off-topic

**Comment by gtbu** [comment]
Not so easy .... The 'monoo-lisa' is in more than 10 files in the CMS. If i find a solution i will open again.

**Comment by juek** [comment]
1. copy the skin into the [skins](https://github.com/Typesetter/Typesetter/tree/master/include/thirdparty/ckeditor/skins) directory
2. change the skin name in [Editing.php](https://github.com/Typesetter/Typesetter/blob/master/include/tool/Editing.php#L623)

**Comment by mahotilo** [comment]
Or made a [plugin ](https://github.com/mahotilo/CKE_MoonoLisaM) and use your favourite theme:)
