### ISSUE TITLE
Section Attributes - Available Classes - popper

### ISSUE THREAD

**Issue by mahotilo** [Typesetter/Typesetter#475]
In such configuration, I have always  blinking popper.

![image](https://user-images.githubusercontent.com/14929385/72053106-0e6f0f80-32cf-11ea-8431-aa64de3605c3.png)

**Comment by juek** [comment]
Fixed with [this commit](https://github.com/Typesetter/Typesetter/commit/6a0199d981818a111b48f7c5ab15d35c7e510278)
