### ISSUE TITLE
Request: Add/Remove classes instead of Replace

### ISSUE THREAD

**Issue by mahotilo** [Typesetter/Typesetter#477]
Can we make these buttons add or remove presets to the current set of classes, but do not completely replace it? It is always a quest for me on how to add some classes from bootstrap and do not lose all my custom classes.

![image](https://user-images.githubusercontent.com/14929385/72056973-4c236680-32d6-11ea-9f81-51e2ce04f876.png)

EDIT
Juergen, it is just for discussion. I too want to see new TS ASAP, but the temptation to see an even better UX/UI is so great:)

**Comment by juek** [comment]
Basically, I would say like this:

![grafik](https://user-images.githubusercontent.com/704283/72101769-cb8c5680-3325-11ea-8d53-e2d9a2475c70.png)

Although it could also be prettier.

**Comment by mahotilo** [comment]
Without 'Remove' it will always be a one way road. You have added them and you live with them.
Removing all BS classes manually  will be a stress test.

**Comment by juek** [comment]
But then we would have to categorize them. IMO categorization never works. Example: If I would want to add Bootstraps margin or padding utility classes, I would add them to the Bootstrap category. If I then unload the Bootstrap 4 Preset, what would remain?

**Comment by juek** [comment]
Furthermore, 'Sizing', 'Colors', 'Typography', 'Custom XYZ', … would make much better categories.

**Comment by mahotilo** [comment]
> If I then unload the Bootstrap 4 Preset, what would remain?

Maybe we should split the classes of users and BS? They can overlap if a user add BS classes to their set, but they will be easier to manipulate.
Maybe an array of presets if we are talking about categories?

**Comment by juek** [comment]
Now looks like this:
![grafik](https://user-images.githubusercontent.com/704283/72495572-5ccc6300-3827-11ea-8ac3-a3d64d7e3435.png)

**Comment by mahotilo** [comment]
COOL!

The only problem I see now, is that I can prepend/apprepend Default preset twice. For other presets this is impossible.

And...
We should delete the words `Load in front of the preset name. But it is a big work with languages, so let it be as ше is for a while.

**Comment by juek** [comment]
> … that I can prepend/apprepend Default preset twice.

Hmm, indeed. But why should you want that?

> But it is a big work with languages, so let it be as it is for a while. … I'm sure you know that without me:)

Certainly. Don't hesitate to make a PR ;o)

**Comment by juek** [comment]
> Should we introduce new pair like
> `'The Default Preset' => 'The Default Preset',`

I would say so

**Comment by mahotilo** [comment]
I've just made the PR https://github.com/Typesetter/Typesetter/pull/507

**Comment by juek** [comment]
I think we should use 'Load' instead of 'Replace' now.

![grafik](https://user-images.githubusercontent.com/704283/72558453-fab14380-38a2-11ea-9844-7576f75a10b7.png)

**Comment by mahotilo** [comment]
Yes. I can do PR.

**Comment by mahotilo** [comment]
> I think we should use 'Load' instead of 'Replace' now.

I'd made a PR https://github.com/Typesetter/Typesetter/pull/508/commits/64fddf4bc058d179fbf091cae5108e95839df304, but then I thought that this button indeed replaces all the classes with the preset. So maybe it should be kept as Load?

**Comment by juek** [comment]
It's rather the order that could confuse people. At least in Engllish and German 'The Bootstrap 3 Preset' -> 'Replace' means to replace the Bootstrap Preset. I wouldn't click that button because I would be afraid to overwrite the preset. 'Load' is unambiguous.
