### ISSUE TITLE
ckeditor skin - mod

### ISSUE THREAD

**Issue by gtbu** [Typesetter/Typesetter#480]
At the moment, the ckeditor looks a bit drab and low-contrast to my taste.
Hence a mod proposal for the admin.scss

This gives the icons a white background :
 .cke_button,  span.cke_combo_text, span.cke_combo_inlinelabel  {background-color:white !important;}

**Comment by mahotilo** [comment]
Like this?

![image](https://user-images.githubusercontent.com/14929385/72085641-53fefd00-330e-11ea-8bf8-411e83b521dd.png)

Personally, I do not like to see it as default.
But, I suppose we can make a plugin with all themes from [CKEditor](https://ckeditor.com/cke4/addons/skins/all?sort_by=field_custom_downloads_value&sort_order=DESC). There are many for every taste.

**Comment by gtbu** [comment]
There is the bootstrap4-skin [https://kunstmaan.github.io/BootstrapCK4-Skin/](url)

**Comment by mahotilo** [comment]
I have been working with moono-lisa in other CMS for a while without a problem. This is the default for CKEditor 4. So I think we ought to use moono-lisa. 
And again, other themes may be easily used via plugin. I made one for my variation of moono-lisa and I am now trying to modify it for an arbitrary list of other themes.

**Comment by mahotilo** [comment]
You can try my plugin https://github.com/mahotilo/CKE_Themes and set theme you like.
You can also copy your favourite theme to /themes dir and use it.

**Comment by mahotilo** [comment]
@juek 
Juergen, thanks for your great [Colorbox-Extender](https://github.com/juek/Colorbox-Extender). It was a donor:)

**Comment by gtbu** [comment]
Yes - a great plugin - should be integrated !
