### ISSUE TITLE
Bootstrap classes overridden

### ISSUE THREAD

**Issue by oyejorge** [Typesetter/Typesetter#481]
[Found this via scrutinizer's inspections](https://scrutinizer-ci.com/g/Typesetter/Typesetter/code-structure/master/operation/gp%5Cadmin%5CSettings%5CClasses::ClassesForm)

The classes of Bootstrap3 will be overridden by Bootstrap4. Pretty sure there's just a missing `break` but figured I'd double check.
```
case 'LoadBootstrap3':
	$classes = self::Bootstrap3();
case 'LoadBootstrap4':
	$classes = self::Bootstrap4();
break;
```

**Comment by juek** [comment]
Yep, thanks. Pure sloppiness on my part. [Fixed](https://github.com/Typesetter/Typesetter/commit/906e2537e91f7eb9244824f61e3bd292a0a14fa1)
