### ISSUE TITLE
Proposal for Revision History & Layout Editor

### ISSUE THREAD

**Issue by Sestowner** [Typesetter/Typesetter#483]
I'm suggesting to prevent access to Revision History and Layout Editor, when the site is locked for editing, because, then they don't work well.

![Screenshot_2020-01-09 Administration - My Typesetter](https://user-images.githubusercontent.com/36760609/72085935-d7205300-330e-11ea-9d17-68f4178d3798.png)

![Screenshot_2020-01-09 Layouts » Bootswatch Flatly 4_Stick - My Typesetter](https://user-images.githubusercontent.com/36760609/72085979-e4d5d880-330e-11ea-931e-d53101cd839a.png)

If nobody objects, I can make a pull request.

**Comment by juek** [comment]
on the other hand, if you are logged in as 'number 2', not much else is possible.

**Comment by mahotilo** [comment]
When you 'number 2', you can see private pages and discuss them with 'number 1'. This is already sufficient

**Comment by mahotilo** [comment]
Can be closed 
https://github.com/Typesetter/Typesetter/pull/493
