### ISSUE TITLE
Undocking in /Admin

### ISSUE THREAD

**Issue by mahotilo** [Typesetter/Typesetter#484]
I can do like this! Can you too? :)
It is also possible in TS 5.1.1. Is this a feature I missed?

![image](https://user-images.githubusercontent.com/14929385/72189679-27c6a780-3406-11ea-91f5-b4cad9cdf060.png)

**Comment by juek** [comment]
This worked already in 5.1, albeit unintentional, AFAIK.

**Comment by juek** [comment]
Fixed with https://github.com/Typesetter/Typesetter/commit/7a940fbf2429f9f63e396aefe6892dc0e40e72ca
