### ISSUE TITLE
_common in Bootswatch4_Scss themes list

### ISSUE THREAD

**Issue by mahotilo** [Typesetter/Typesetter#486]
![image](https://user-images.githubusercontent.com/14929385/72206463-d9adb480-3496-11ea-9352-705b667c46ff.png)

**Comment by juek** [comment]
This must result from a recent commit

**Comment by mahotilo** [comment]
should be fixed with this PR https://github.com/Typesetter/Typesetter/pull/487

**Comment by mahotilo** [comment]
solved with https://github.com/Typesetter/Typesetter/commit/5299287d513a3708a7bee787221fb77abab594bc
