### ISSUE TITLE
Error: Admin_Link function name instead of link in UI

### ISSUE THREAD

**Issue by mahotilo** [Typesetter/Typesetter#488]
![image](https://user-images.githubusercontent.com/14929385/72216095-1f18c300-3525-11ea-8160-64d74675aca4.png)

As you can see `Special_Link:...` from Addon.ini processed correctly and `Admin_Link:...` wrongly.

I traced source of error till 
https://github.com/Typesetter/Typesetter/blob/f52a4a8bd2c5de0df7c4b6a4ed303e4a735da2f1/include/admin/Tools.php#L319-L334

If I comment this new lines (absent in November master), admin links for plugins from `/data/_addoncode ` are processed correctly. But plugins from `/addons` are still processed wrongly.

**Comment by Sestowner** [comment]
This issue derived from https://github.com/Typesetter/Typesetter/commit/97868a94bc9b6ac523b8042e2ce5e713ab571785

**Comment by mahotilo** [comment]
It seems to me the problem is in place where 'label' appears because it is now set to filtered action name and not to appropriate  label.

**Comment by mahotilo** [comment]
Ok, as of now I have discovered the following.

I commented this line
https://github.com/Typesetter/Typesetter/blob/8b53629f91e21f78682d91f902d866bc4f830730/include/admin/Tools.php#L324

It immediately starts to work for plugins from /data. For plugins from /addons, it starts to work after reinstall

**Comment by mahotilo** [comment]
This looks like a solution of a problem, but for sure will break @juek's plans for addon link labels internalization.

**Comment by juek** [comment]
> This issue derived from 97868a9

True. The problem doesn't exist as long as a plugin is installed that returns the label as a string.
Will fix it.

**Comment by juek** [comment]
Should be fixed with https://github.com/Typesetter/Typesetter/commit/dea6a8611e107856d772164cf1a13f0d4c3e8132

In fact, it was just the order of the arguments passed to the hook function. Empty filter hooks return the first argument. 

At the same time I also changed the variable names (underscores instead of camelCase for variable names).

**Comment by mahotilo** [comment]
Confirm.
Can be closed.
