### ISSUE TITLE
Poll: Show  Elementspath in CKEditor

### ISSUE THREAD

**Issue by mahotilo** [Typesetter/Typesetter#497]
What do you think of that?
Should we show the CKE bottom bar with 'Elementspath' plugin output.
We already have an installed Elementspath, so it is only one line in the CKE config and a couple of lines in css.

![image](https://user-images.githubusercontent.com/14929385/72297861-850c6400-3665-11ea-9ab1-8ee1cb1ecb2a.png)

**Comment by juek** [comment]
Hmm, for my part showing sole elements (without assigned classes) not of much value. But showing them would exceed available space.

**Comment by mahotilo** [comment]
For deep inspection we have DevTools etc. This is just what we promise the user in the Example :)

![image](https://user-images.githubusercontent.com/14929385/72299758-7eccb680-366a-11ea-84ea-d770dbe6cdcb.png)

**Comment by mahotilo** [comment]
No, it is not easy to clearly do via plugin.
I use
`$options['sharedSpaces'] = array('top' => 'ckeditor_top','bottom' => 'ckeditor_bottom');`
But it brings a problem with my favourite Custom Section CKE control. :(

**Comment by juek** [comment]
I rather use the 'Show Blocks' button in such cases:

![screenshot](https://user-images.githubusercontent.com/704283/72302816-83459f00-366b-11ea-8d14-ab1e2cb3d942.png)

**Comment by mahotilo** [comment]
Yes, but CKE proposes a one glance tool...

But I uncover a compatibility problem. So, until I find a proper solution, I close the Issue.

I want to see blank list too:)

**Comment by mahotilo** [comment]
I managed to safely add the bottom panel with some JS manipulations in plugin.
So it will be part of CKE_Theme plugin:)
