### ISSUE TITLE
Custom.css  - problem

### ISSUE THREAD

**Issue by gtbu** [Typesetter/Typesetter#499]
I used my smart3 - plugin(1 color) and my smart3-multi-plugin parallel : 1st under themes, second loaded from web. After i installed the same color in both, i suddenly have no more access to the layout-editor. The specific custom.css'es are not deleted ! Layout editor  simply returns into the dashboard. 
As i searched, the custom.css is treated in layout.php and in output.php. But i just cant find the reason, why layout-editor looses the path (also after deinstallation of smart multi - only 1 layout left). I had the same already 1 year ago without solution as by exchange of /include or set rights t 755 (..reinstallation).
3 directories of _layouts are not deleted - all have the same custom.css - content. Who knows about the evtl. storage of the pathes in 5.1.1b1 of summer 2019.

**Comment by gtbu** [comment]
Well - i found out that i have a corrupted _sites/pages.php without any entires of _layout-folders. How that can happen - unforeseen constellations of layouts ? At first i thought it was a conflict with some js....
Will try on alone ...

**Comment by juek** [comment]
/data/_layouts will only be created once an admin changed and saved the CSS/LESS/SCSS code in Layout Editor
