### ISSUE TITLE
Error: Forgotten debug message

### ISSUE THREAD

**Issue by mahotilo** [Typesetter/Typesetter#503]
After "restore" in History.
![image](https://user-images.githubusercontent.com/14929385/72458454-4d222f80-37d1-11ea-94df-1389d866589c.png)

I think it is here
https://github.com/Typesetter/Typesetter/blob/5aed1066e5b2d333c47a7bfc52c108dc29824675/include/admin/Content/Revisions.php#L273

**Comment by oyejorge** [comment]
Yep. Have that fixed in my dev branch. Will get that out later today

**Comment by juek** [comment]
Fixed with https://github.com/Typesetter/Typesetter/commit/ea8a187fb456de4355db8563b6bcccdf8409a0b7
