### ISSUE TITLE
Image section is not working as Extra Content

### ISSUE THREAD

**Issue by Sestowner** [Typesetter/Typesetter#506]
It doesn't work, is any sense to display it in the list of available sections?
![image](https://user-images.githubusercontent.com/36760609/72523681-ff590600-3868-11ea-876d-a12908673cb3.png)

**Comment by mahotilo** [comment]
It should be a problem with edit function and not with area type itself.

**Comment by mahotilo** [comment]
As I see problem is in different way that used to show image in page section and in extra content.

**Comment by juek** [comment]
The image section type is rather special. It's the only one I know that doesn't output as div. I think it was never meant to be used as extra area. I rarely use it because it doesn't play too well with responsive design.

We could filter it out of the list. Or we could change it – however, backward compatibility could pose a challenge.

**Comment by mahotilo** [comment]
I've added 

> 					$section['content']					= 'I am image';
to 
https://github.com/Typesetter/Typesetter/blob/5bcd23ecd556b5b9ebee916fc9b4ed2eab60eade/include/tool/Editing.php#L739-L746

And insert two images as page section and as extra area. 
See the result
![image](https://user-images.githubusercontent.com/14929385/72597797-2f5ee280-3917-11ea-848f-903a0e0cdb2f.png)

**Comment by juek** [comment]
I have been thinking about developing the one almighty image section for years. With all functions of the built-in image section (cropping & resizing), ResponsiveImage, ParallaxImage and SimpleImage. It's just ... well, not that easy.

**Comment by mahotilo** [comment]
Gallery works fine with its explicit 
`$section['content']		= '<ul class..`

The Image in extra area is useful as a logo holder, so I think we should to fix it some way.

**Comment by mahotilo** [comment]
And what about https://typesetter-addons.grafikrausz.at/Simple-Image

> Since a new, more powerful CMS built-in default image component is already under consideration, which will presumably cover all of Simple Image’s features (and likely some more), this plugin might never make it into Typesetter’s official addon respository.  We’ll see. Stay tuned ;^)

**Comment by juek** [comment]
> The Image in extra area is useful as a logo holder, so I think we should to fix it some way.

[SimpleImage](https://typesetter-addons.grafikrausz.at/Simple-Image) is much better for that ;)

**Comment by juek** [comment]
LOL that was at the same time

**Comment by juek** [comment]
>…, this plugin might never make it into Typesetter’s official addon respository.

Please wait … still considering :)

**Comment by juek** [comment]
Simple Image: I probably underestimate it. In fact, I use it myself in every project. Without exception.

**Comment by mahotilo** [comment]
Seriously, I can't find where Image 'rendering' happens.
Can you give me a hint where it is?

**Comment by juek** [comment]
There are several places:

https://github.com/Typesetter/Typesetter/blob/5bcd23ecd556b5b9ebee916fc9b4ed2eab60eade/include/tool/Editing.php#L739

https://github.com/Typesetter/Typesetter/blob/5bcd23ecd556b5b9ebee916fc9b4ed2eab60eade/include/tool/Editing.php#L798

https://github.com/Typesetter/Typesetter/blob/5bcd23ecd556b5b9ebee916fc9b4ed2eab60eade/include/tool/Output/Sections.php#L420

https://github.com/Typesetter/Typesetter/blob/5bcd23ecd556b5b9ebee916fc9b4ed2eab60eade/include/Page/Edit.php#L423

https://github.com/Typesetter/Typesetter/blob/5bcd23ecd556b5b9ebee916fc9b4ed2eab60eade/include/tool/Output/Ajax.php#L199

**and of course**
https://github.com/Typesetter/Typesetter/blob/master/include/js/inline_edit/image_edit.js

Not sure if I got them all

**Comment by juek** [comment]
And here: 

https://github.com/Typesetter/Typesetter/blob/5bcd23ecd556b5b9ebee916fc9b4ed2eab60eade/include/tool/Editing.php#L831

**Comment by mahotilo** [comment]
Thx.

We don't have <img> here at all. 
And I am trying to find this moment of `<img src=...>` creation.

![image](https://user-images.githubusercontent.com/14929385/72601185-997a8600-391d-11ea-985d-9bd787940447.png)

**Comment by juek** [comment]
Also relevant: 

https://github.com/Typesetter/Typesetter/blob/5bcd23ecd556b5b9ebee916fc9b4ed2eab60eade/include/tool/Output/Sections.php#L70

**Comment by juek** [comment]
> And I am trying to find this moment of <img src=...> creation.

It's a combination of `$section_data['nodeName']` and the src attribute. Somehow spread across the entire CMS.

**Comment by juek** [comment]
In fact, whatever we do, and if we actually mess with the image section type, I believe it should eventually be wrapped inside a &lt;div&gt; container liek other sections. the &lt;img&gt; tag is way too limited for proper responsive styling (overflow control, flex, etc.)

**Comment by mahotilo** [comment]
> edit: But I'm afraid that it's almost impossible to change the current image type without breaking existing occurences on updated Typsestter sites.

Yes, it should be the new type, e.g. Simple Image :)

**Comment by juek** [comment]
Advanced Image ;)

**Comment by mahotilo** [comment]
No, we need reserve it for 

> almighty image

**Comment by juek** [comment]
A few things a modern image section type should also support (for the records): 

- [&lt;figure&gt;/&lt;figcaption&gt;](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/figure)
- [&lt;picture&gt;/&lt;srcset&gt;](https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images)

**Comment by mahotilo** [comment]
In this case it will be Advanced image really

**Comment by mahotilo** [comment]
This is code of Include section with Image extra area.
It looks like a place to investigate. 

The highlighted code below is the included Gallery
![image](https://user-images.githubusercontent.com/14929385/72607173-c8e2c000-3928-11ea-9643-ef760565b9b0.png)

**Comment by mahotilo** [comment]
Well
1. when Image is a section inserted into the page, it is rendered as Text section of the page 
2. when Image is an Extra area, it is not rendered at all
3. if I add rendering for Image as Extra, it doubles output for Image inserted as page section
4. in any case, Image as Extra does not have a proper context editing menu

So, as Sergiy @Sestowner wisely said at the beginning of the saga

> It doesn't work, is any sense to display it in the list of available sections?

**Comment by mahotilo** [comment]
We do need Advanced (Simple) Image!

**Comment by oyejorge** [comment]
[Or make image editing work](https://github.com/Typesetter/Typesetter/pull/524)?

**Comment by juek** [comment]
> Or make image editing work?

Josh, with your last commit it will work as extra area in include section, but not as layout section (no editing context menu)

**Comment by mahotilo** [comment]
And we have no preview in Administration » Extra Content

**Comment by mahotilo** [comment]
@oyejorge 
is there any news on this issue?

**Comment by oyejorge** [comment]
How does it look with these changes?

**Comment by mahotilo** [comment]
Preview in Administration » Extra Content - Ok.
Layout - Ok
Extra area in include section - Ok
Extra area - Ok

With my PR https://github.com/Typesetter/Typesetter/pull/550 it also has a context menu as an extra area :)
