### ISSUE TITLE
UI: Runaway "Delete" section dialog

### ISSUE THREAD

**Issue by mahotilo** [Typesetter/Typesetter#521]
1. Add Image (or several Text) section to TS home page and then click Delete section
2. "Delete" confirmation dialog appears
3. Page try to locate the section to delete and Dialog runs above the screen. It can even disappear at all.

UPD
To reproduce for sure, activate the top section in list and then try to delete the bottom one.

![image](https://user-images.githubusercontent.com/14929385/72633744-c3559c00-3961-11ea-81cb-b8d1572914f9.png)

It is very annoying

UPD
Clear TS installation, last master

**Comment by mahotilo** [comment]
It can be fixed, e.g., by adding
`position: fixed; `
to
`#gp_admin_boxc`

**Comment by juek** [comment]
It's basically the stroll to section on click instead of hover we now use

**Comment by mahotilo** [comment]
Yes, previously the delay in onhover reaction saved us.

**Comment by juek** [comment]
As previously announced, I will implement [ExpandableEditor ](https://github.com/juek/ExpandableEditor) functionality in the CMS core, which will also make the admin box position:fixed. I just wanted to wait and see the discussions about more general admin UI things.

**Comment by mahotilo** [comment]
1. It is great news.
2. Well, can we disable expanded state for CKE with text panel set? I think we should do this, don't you?

**Comment by juek** [comment]
> Well, can we disable expanded state for CKE with text panel set? I think we should do this, don't you?

Hmm, yeah. Unfortunately – with the current setup – CK Editor cannot benefit from a wider editor area. because of tools are split into toolbars. Most other editors do because they are 'responsive' to some extent. I wouldn't change expansion state on-the-fly when switching between multiple editor instances, merely for a consistent behavior of the UI icon. But I think of it…

**Comment by mahotilo** [comment]
> I wouldn't change expansion state on-the-fly when switching between multiple editor instances

Honestly, I'd tried it before I asked for. It is not really a trivial task.

**Comment by juek** [comment]
> Maybe, some CSS magic with IDs and full classes sets will help us.

If we had parent selectors in CSS, maybe. With the new editor:loaded JS event it should be rather easy.

**Comment by oyejorge** [comment]
I remember why position:fixed wasn't used for the modal. If the modal is taller than the window, the bottom of the modal won't be  usable.

![modal](https://user-images.githubusercontent.com/1043524/72666748-67772b80-39d2-11ea-972f-9c930035c86e.png)

Of course we could give the modal a max height

```
#gp_admin_box{ 
  max-height: 80vh;
  overflow: scroll;
}

**Comment by mahotilo** [comment]
Or maybe change the object to trigger the onclick event so that the delete icon does not trigger it.

**Comment by juek** [comment]
check [this](https://github.com/juek/ExpandableEditor/commit/54a9e309f0d00284ecbde5702147395048a384d0) out

**Comment by juek** [comment]
@oyejorge 
> I remember why position:fixed wasn't used for the modal. If the modal is taller than the window, the bottom of the modal won't be usable.

This is fixed with overflow-y:scoll handling and calc'd max-height in my solution

**Comment by juek** [comment]
One rather special thing has to be noted, though: 
With a position:fixed admin box, vertical scrolling via mousewheel has issues in some browsers together with smooth-scolling JS used in my Parallax Image plugin and Theme Cajón. The JS doesn't properly delegate/bubble the scroll events, so it will always scroll the viewport, not the admin box content. That puzzled me for quite some hours ;)

**Comment by mahotilo** [comment]
With last commit it works fine for me.
