### ISSUE TITLE
uncombined CSS: link outputs filepath instead of url

### ISSUE THREAD

**Issue by juek** [Typesetter/Typesetter#525]
`<!-- File Not Found: /var/www/html/data/_layouts/ugzgpi4/custom.css  -->`

should be a URL `/_layouts/ugzgpi4/custom.css`

Probably due to the new FormatAssets call, perhaps somewhere [around this line](https://github.com/Typesetter/Typesetter/blob/master/include/tool/Output/Assets.php#L61)

edit: also appears to happen when combine CSS is swiched on.

**Comment by mahotilo** [comment]
mayby like this
`				echo self::FormatAsset($type, \gp\tool\Output\Css::GetRelPath($file) );`

**Comment by juek** [comment]
> mayby like this echo self::FormatAsset($type, \gp\tool\Output\Css::GetRelPath($file) );

Have you tried?

**Comment by mahotilo** [comment]
Yep

**Comment by mahotilo** [comment]
But my solutions are usually made with duct tape:)

**Comment by juek** [comment]
Same error with combine CSS off.

I'd like to leave that to @oyejorge Josh.

> But my solutions are usually made with duct tape:)

I've already switched to hot glue :P

**Comment by mahotilo** [comment]
I checked in this mode and it helped me for Three Point 5/Shore with modified custom.css
![image](https://user-images.githubusercontent.com/14929385/72664116-c359a880-3a02-11ea-8f6e-9b2979a4ed49.png)

> I'd like to leave that to @oyejorge Josh.
Best solution

**Comment by juek** [comment]
Seems to work but I still get the error comment in the  `<head>` section

**Comment by mahotilo** [comment]
Oh, I see `Report Errors - off` was unnecessary. That's why I didn't see the error message in page source.

**Comment by oyejorge** [comment]
I'm on it

**Comment by juek** [comment]
@mahotilo: I'd suggest to disable error reporting (via Configuration) when working on a beta version. Josh will appreciate it :)

**Comment by mahotilo** [comment]
Come on, it was done in a hurry:)
