### ISSUE TITLE
doubled Section link

### ISSUE THREAD

**Issue by mahotilo** [Typesetter/Typesetter#526]
Do we need a second Section link?
Is this some kind of antique artefact?

![image](https://user-images.githubusercontent.com/14929385/72667330-7df9a300-3a23-11ea-9ebb-4a05e7cde006.png)

**Comment by juek** [comment]
> Is this some kind of antique artefact?

No, it only was covered earlier before editing links expanded due to Revision History.

**Comment by mahotilo** [comment]
Should it be located and deleted?

**Comment by juek** [comment]
I consider it a 'cosmetic' issue, which might well vanish with future UI changes. I wouldn't combat it right now.

**Comment by mahotilo** [comment]
Have just done PR https://github.com/Typesetter/Typesetter/pull/527
