### ISSUE TITLE
Proposal: Include section icon

### ISSUE THREAD

**Issue by mahotilo** [Typesetter/Typesetter#528]
Is sth like this more clear? In terms of understanding.

![section-include](https://user-images.githubusercontent.com/14929385/72671400-45bd8900-3a52-11ea-80c7-df1422bd7498.png)

![image](https://user-images.githubusercontent.com/14929385/72670587-c32fcc00-3a47-11ea-9cb3-2f33bc866b33.png)

The icons represent the types of content that can be included in the section.

**Comment by juek** [comment]
> The icons represent the types of content that can be included in the section.

Hmm, perhaps, if one already knows the selection list.

**Comment by mahotilo** [comment]
>  if one already knows the selection list.

Otherwise, this section type is forbidden to use :)

**Comment by juek** [comment]
It looks a bit like a game collection box with puzzle, dice and card games. 
I'm not yet sure if I like it. The game you're starting when you click on it is not as funny.

**Comment by mahotilo** [comment]
Well, I agree
But what is it about? (Take it easy. I like all the other section icons:)

![image](https://user-images.githubusercontent.com/14929385/72671778-20cc1480-3a58-11ea-875e-927201565109.png)

**Comment by juek** [comment]
> But what is it about? 

Er … um … it says: Put something in from somewhere else. No? Hmm.

**Comment by juek** [comment]
[Joined forces](https://github.com/Typesetter/Typesetter/commit/e6331872a974ac4860dd38786d2e7365e8abe989)

**Comment by mahotilo** [comment]
I never claimed to surpass your design skills:)
Well done!

**Comment by juek** [comment]
Thx. 

I believe it's a good solution. It has now similarities with the empty wrapper icon. The include type is also sort of a wrapper (I used it a lot when we didn't have real wrappers, some 6-7 years ago.
