### ISSUE TITLE
we can't dismiss an Extra Content draft, shouldn't we?

### ISSUE THREAD

**Issue by juek** [Typesetter/Typesetter#530]
Title says it all, what do you think?

**Comment by mahotilo** [comment]
Yes. Now, the only way to undo changes in extra is Revert in export or manually. It is very user unfriendly.

**Comment by juek** [comment]
I'll check if a dismiss function is still there. I think I can remember that we had such back in 4.6 or so.

**Comment by juek** [comment]
> I'll check if a dismiss function is still there.

Nope ;(. And no translations for it either.

**Comment by juek** [comment]
Awesome!
