### ISSUE TITLE
Strange message while publishing Extra 

### ISSUE THREAD

**Issue by mahotilo** [Typesetter/Typesetter#533]
Can you see this? It appears and disappears in a moment.
I was publishing Lorem extra section.

![image](https://user-images.githubusercontent.com/14929385/72685873-e6fe1b00-3af6-11ea-93c6-da3fab7b67f9.png)

**Comment by oyejorge** [comment]
I was seeing something but it never stayed long enough for me to see what it was. I know how to fix it now.
