### ISSUE TITLE
Problem: Popper causes Section Attributes dialog jitter

### ISSUE THREAD

**Issue by mahotilo** [Typesetter/Typesetter#537]
In Section Attributes, we need some timeout before popper appears with description of hovered class.
As of now, when the long BS preset is scrolled, the popper misses the position and causes a dialog jitter (vertical scrollbar appears and disappears).

**Comment by mahotilo** [comment]
Popper.js is ... er... not funny to add same timeouts.

Therefore, I again propose adding some fixed area for class description. This will save us many problems in one step.

![image](https://user-images.githubusercontent.com/14929385/72724109-1b231b80-3b8b-11ea-950b-1347aa891f7b.png)

**Comment by juek** [comment]
> Therefore, I again propose adding some fixed area for class description. This will save us many problems in one step.

Not a bad idea but as long as it doesn't have a fixed height, it will cause way more jittering

**Comment by mahotilo** [comment]
> as long as it doesn't have a fixed height

It has to have! 
It may also have `overflow-y: scroll`.

**Comment by juek** [comment]
> It may also have overflow-y: scroll.

No, because when it shows when hovering a button, you will never reach it to scroll it.

> It can still be a popper, but assigned to e.g. "Available Classes" panel to be pinned.

It was in the first place but with only 3 class buttons there wasn't enough space. Remember?

**Comment by mahotilo** [comment]
> Remember?

Honestly, I lost the details.
Did it pop down or up?

**Comment by juek** [comment]
> Did it pop down or up?

It pops where it finds space. That's all what popper.js is merely about.

**Comment by mahotilo** [comment]
Can we configure it to pop only up above "Available Classes" panel?
Popper.js documentation is an enigma for me. I can not understand anything.

**Comment by juek** [comment]
[This commit](https://github.com/Typesetter/Typesetter/commit/d8e4df58b69476638b9939c7c9b953d7c0be5729) should improve it

**Comment by juek** [comment]
> Popper.js documentation is an enigma for me. I can not understand anything.

Yes, it's not for the faint-hearted (no offense). IMO it's also outdated and incomplete.

**Comment by mahotilo** [comment]
I will try it a little later, if you do not mind.

**Comment by mahotilo** [comment]
Well. I have tried it. It brings some relief, but does not completely solve the problem.
I think adding setTimeout for on('mouseenter') will help. It also will improve UX.
But, when I tried to do this, it caused the popper popping on the top of dialog .

**Comment by juek** [comment]
>  I tried to do this …

We will have to store and pass the original event to the timeout function in order to have all the data we then need. 
But delayed triggering of cached events is complicated (or dangerous) because we would have to unbind the original event handler in the meantime and then re-bind it. It should also be possible to cancel everything in the delay span (on mouseleave).

**Comment by juek** [comment]
Hmm … but jQuery delay() might come in handy. I'll try that.

**Comment by juek** [comment]
jQuery [helps us out](https://github.com/Typesetter/Typesetter/commit/59c5bbf8d85550988223e9bcb7aec5d9542b038a)

**Comment by mahotilo** [comment]
After a short fight with the browser cache, I can confirm this and close the issue:)

**Comment by mahotilo** [comment]
8^)

**Wise Popper**
![image](https://user-images.githubusercontent.com/14929385/72742410-5553e380-3bb2-11ea-9a12-f91d2a893043.png)

**Silly Popper**
![image](https://user-images.githubusercontent.com/14929385/72742465-74527580-3bb2-11ea-8abb-cb8525fc8052.png)

**Comment by juek** [comment]
> After a short fight with the browser cache, I can confirm this and close the issue:)

Hmm, not really. The jQuery fx chain / timing functions seem to mess with popper's. It also seems increasingly to stress the browser. 

It's not that easy (as I was afraid of).

I'll revert the last commit.

**Comment by juek** [comment]
> Silly Popper

No, Popper can't help it.
We don't have a hide popover on click. But we also shouldn't.

**Comment by mahotilo** [comment]
> It also seems to increasingly stress the browser.

Hmm

Can we limit Popper to only placement : 'top'? As for me, it is sufficient in our dialog box.

**Comment by juek** [comment]
> Can we limit Popper to only placement: 'top'?

[Sure thing](https://github.com/Typesetter/Typesetter/commit/b9bdef0a5ebb05d1dfad129f16077a458d4bf3b5)

**Comment by mahotilo** [comment]
This stops the jitter for me. (but disabled 'always on top' :)

```
preventOverflow: {
	escapeWithReference : false
}
```

**Comment by juek** [comment]
> This stops the jitter for me. 

And brings us back to https://github.com/Typesetter/Typesetter/issues/475

**Comment by mahotilo** [comment]
> And brings us back to #475 

Can not confirm. I've just tried, all is OK.

**Comment by juek** [comment]
We're a bit running in circles. 
I already spent too much time with popper and all it's strengths and quirks. It's a powerful tool but not too important.

If you find a good solution that works for all cases make a PR.

**Comment by mahotilo** [comment]
PR https://github.com/Typesetter/Typesetter/pull/541

![image](https://user-images.githubusercontent.com/14929385/72746694-6b19d680-3bbb-11ea-958e-cde01698e20d.png)


No Popper no cry

**Comment by juek** [comment]
> No Popper no cry

Sorry, but that's not how a tooltip acts. Hover here - tooltip shows somewhere else. That's UX bullsh*t. Folks would consider it as an implementation error and I would do as well.

**Comment by mahotilo** [comment]
>  Hover here - tooltip shows somewhere else.

Remove arrow and consider it like hint panel:)
Problem is Popper.js itself.
Ok. I will try again:)

**Comment by juek** [comment]
Is it worth? I have no jittering BTW

**Comment by juek** [comment]
> Remove arrow and consider it like hint panel:)

I'd rather go back to the long list with select left and description on the right.

**Comment by mahotilo** [comment]
I have. 
Perhaps this refers to the type of mouse wheel, PC load, etc., but I see jitter

**Comment by mahotilo** [comment]
> I'd rather go back to the long list with select left and description on the right.

I am not sure. Using BS preset in one column will be a challenge for the wheel.

**Comment by mahotilo** [comment]
Honestly, popper without delay is very annoying.
This is very useful when I need to learn about a class, but I do not want to see this flicker when quickly moving to a class for use.

**Comment by mahotilo** [comment]
What about Tippy.js.?
It has delay out of the box.
https://atomiks.github.io/tippyjs/

**Comment by juek** [comment]
Check [this approach](https://github.com/Typesetter/Typesetter/commit/1c143b8661b9e844e12eaac3b20469a138227788). I can't because I have no jittering.

**Comment by juek** [comment]
Tippy is based on popper.js, just like Bootstrap's popover.

Popper.js also has had a delay itself but it seems to have vanished again, probably for some reason.

**Comment by mahotilo** [comment]
It gives a delay, but slows down significantly and bring a lag in scrolling.

**Comment by juek** [comment]
For tippy: It's another 24 kB (minified) but we could also add it for our convenience. 

> It gives a delay, but slows down significantly and bring a lag in scrolling.

Might be your system specs. I'd guess tippy or other js solutions will cause similar artefacts.

**Comment by mahotilo** [comment]
> Might be your system specs.

Old Core I5. 3 tabs in the browser. No mining but a bit of AI in the background:)

You have noticed something similar before.
https://github.com/Typesetter/Typesetter/issues/537#issuecomment-576348135

**Comment by juek** [comment]
> You have noticed something similar before.

Yes I can see it. It's similar - starts after 40-50 events.

> Old Core I5

Probably more a GPU issue.

**Comment by juek** [comment]
[This one](https://github.com/Typesetter/Typesetter/commit/f8c51c0f2d26adbcbda7024ade046a34d3c6f952) seems to solve it for me.

**Comment by mahotilo** [comment]
Yes! Now it works as it should. Congratulations!
