### ISSUE TITLE
Travis: can we request a new check

### ISSUE THREAD

**Issue by juek** [Typesetter/Typesetter#540]
@oyejorge 
I was just wondering if it's possible to tell Travis to re-check a Pull Request, in such cases when the underlying cause of a failed check* is corrected before merging the PR?

edit to be more clear: * an underlying cause like a missing $langmessage key already referenced in the PR but not yet implemented at the time, but then added before merging.

**Comment by mahotilo** [comment]
The question is not to me, but...

Is this what you are asking about?
https://github.com/travis-ci/travis-ci/issues/576#issuecomment-65317915

**Comment by oyejorge** [comment]
Yes, by clicking on the "Restart Build" link as seen here. Only shows up if you're logged in.
![image](https://user-images.githubusercontent.com/1043524/72848349-9eaf3c00-3c61-11ea-8f81-6a90afb4f847.png)

**Comment by juek** [comment]
Thank you both!
