### ISSUE TITLE
Error: extra area Image does not have editing context menu

### ISSUE THREAD

**Issue by mahotilo** [Typesetter/Typesetter#553]
Currently, it is the only place where extra area Image can be edited.
But, it does not work here.

![image](https://user-images.githubusercontent.com/14929385/72963096-fa430c00-3dbe-11ea-8584-2b5e539e94b3.png)

**Comment by mahotilo** [comment]
A rough attempt to solve the problem is here https://github.com/Typesetter/Typesetter/pull/550

**Comment by juek** [comment]
Fixed with https://github.com/Typesetter/Typesetter/commit/99495fbcd964600b7e50a04c5295d27bb5f68654 (and https://github.com/Typesetter/Typesetter/commit/c3ea23f5d0570bca5542854bee84aaffd8c795cf)
