### ISSUE TITLE
fopen() fails to enable crypto on same-server urls

### ISSUE THREAD

**Issue by juek** [Typesetter/Typesetter#558]
With a current project I get this error:

```
fopen(): SSL operation failed with code 1. OpenSSL Error messages: 
    error:1416F086:SSL routines:tls_process_server_certificate:certificate 
    verify failed in: /var/www/webseite/include/tool/RemoteGet.php
    on line: 188  
```

For what I understand, fopen() fails to resolve the (correct, same host) url via https.
Seems to prevent URL rewriting and other stuff.

The certificate is Let's Encrypt and works with regular requests. 

Is this something we could and should care about? 
Any ideas how to resolve it?

update: It's not my server and I'm no sudoer. The server configuration can only be changed via support, if possible at all.

**Comment by mahotilo** [comment]
I have never used TS on https, so it is just a an attempt to help by googling in Russian :)

What I have discovered 

1.  It is from PHP >=5.6
 https://www.php.net/manual/en/migration56.openssl.php

2. 
> Local file should be retrieving using a filesystem path.

3. If you should use redirect to local files, problem can be connected with SSL settings.

> I fixed this by making sure that that OpenSSL was installed on my machine and then adding this to my php.ini:
> openssl.cafile=/usr/local/etc/openssl/cert.pem

4. All other propositions on forums is related to curl usage and different methods how to overcome security checks.

So the general idea is not to use local redirects or fix  SSL settings of server.

**Comment by juek** [comment]
> I have never used TS on https

EU law even requires it since GDPR is in force.

Thx for googling but issue is about attempting to **verify an url** in order to be able to redirect there safely (for permalink settings and rewrites)

**Comment by juek** [comment]
BTW: 

> openssl.cafile=/usr/local/etc/openssl/cert.pem

That's is most likely the cause. But I have no access nor do I know the path to the certificate.
Let's see what the host support says.

I'm just asking if we can work around cases where it's not resolvable via support/server config.

**Comment by mahotilo** [comment]
1. Did you see [this](https://stackoverflow.com/questions/46511717/how-to-fix-ssl-certificate-verification-failure) funny solution?

> my certificate is good (I can go to the HTTPS domain without any issue)
> can't run the same request through PHP's stream_context_create and stream_socket_client
> Testing the same domain through cURL returned:
> curl: (60) SSL certificate problem: certificate is not yet valid
> Turns out my virtual machine in which I've run both PHP and cURL had 11 days of error (december 11th instead of december 22th).

2.
> I'm just asking if we can work around cases where it's not resolvable via support/server config.

As I learned from local forums about this problem (there are a lot of discussions), the answer is No, if we do not try to disable certificate verification.

```
$arrContextOptions=array(
    "ssl"=>array(
        "verify_peer"=>false,
        "verify_peer_name"=>false,
    ),
);  
$sw=file_get_contents(ЛИНК, false, stream_context_create($arrContextOptions));
```

**Comment by juek** [comment]
> Did you see this funny solution?

Yes, but we need to know if the secure connection actually works, so bypassing it is not a solution.

**Comment by juek** [comment]
Admittedly I haven't yet tested if a cURL connection works. It might be a fallback option if fclose() fails. But I'd rather wait for what @oyejorge Josh says. He knows this stuff so much better.

**Comment by oyejorge** [comment]
The RemoteGet  class could def use a good overhaul. (Maybe something to look at closer for 5.3?) Curl is in there though and should already be used as a backup.

**Comment by juek** [comment]
> Curl is in there though and should already be used as a backup.

I've seen it but thought it's used as fallback when remote fopen() is not allowed. The problem is that fopen() basically works. It's the connection to the local host that fails because PHP has no clue of the (local) certificate. But the same may also apply to cURL.
