### ISSUE TITLE
UI: Restore for Current page or Dismiss for Working draft

### ISSUE THREAD

**Issue by mahotilo** [Typesetter/Typesetter#560]
How can I return to the current published version of the page?
We have neither 'dismiss' for the draft, nor 'restore' for the current page.

![image](https://user-images.githubusercontent.com/14929385/73124546-58314880-3fa5-11ea-8fd4-e7ebe5f4b7cb.png)

**Comment by juek** [comment]
Yep, a Dismiss button would be helpful in some situations.

**Comment by juek** [comment]
The question only is if the newest edit should then turn into a draft. I wouldn't say so but I know some folks would.

**Comment by juek** [comment]
Another question arises (slightly off-topic): 

Since we now have revisions without publishing (between current page and draft) shouldn't we increase history limit to at least 50?

**Comment by mahotilo** [comment]
> The question only is if the newest edit should then turn into a draft.

Why? It will happen automatically when I start editing, won't it?

> shouldn't we increase history limit to at least 50?

Or limit history between Draft and Current page to keep the history of releases. If it works like I suppose.

**Comment by juek** [comment]
> Why? It will happen automatically when I start editing, won't it?

You may have edits in between the Current page and the then dismissed draft.

**Comment by juek** [comment]
> Or limit history between Draft and Current page to keep the history of releases.

That's what we have before. I like the new way. It's sort of an undo history. It's only 30 entries are too few now.

**Comment by mahotilo** [comment]
Yes, but I think of the 'Dismiss draft' as the complete deleting of the entire history till the 'Current page'.

**Comment by juek** [comment]
> Yes, but I think of the 'Dismiss draft' as the complete deleting of the entire history till the 'Current page'.

I would also expect this behavior. But the current list view leads to a different expectation. We would need e.g. to highlight all the entries down to the Current page when hovering [Dismiss]. The list may be long, though.

**Comment by mahotilo** [comment]
Well. Let us add 'Restore'button  to the 'Current page'. It will have the same meaning.

**Comment by juek** [comment]
'Restore' is not correct. There is nothing to restore. 'Edit' would be an option, though.

**Comment by mahotilo** [comment]
> There is nothing to restore.

Why not?
Restore my current page, which I see as an administrator, to a state that is visible to the site visitor.

**Comment by mahotilo** [comment]
It is also possible to use "Help, bring it back" or "It was not me":)

**Comment by juek** [comment]
> Restore my current page, which I see as an administrator, to the state that is visible to the site visitor.

It's the 'Restart from here' vs. 'Go Back' dilemma.

**Comment by mahotilo** [comment]
'Go Back to the current page' it is...
I think how to translate it:)

**Comment by juek** [comment]
IMO 'Dismiss Draft' but keep all intermediate edits in history (maybe including the former draft) would be the most fail-safe and clear option.

**Comment by mahotilo** [comment]
If I want to restore the previous edition of Draft, I can easy do it now. We do need an option to completely remove all the wrong branch of drafts.

**Comment by juek** [comment]
![grafik](https://user-images.githubusercontent.com/704283/73126778-f8439d80-3fb6-11ea-9276-a9a4680cb75f.png)

**Comment by mahotilo** [comment]
And what version is in editor at this moment if we have no Working draft?

**Comment by juek** [comment]
> We do need an option to completely remove all the wrong branch of drafts.

But not all edits were necessarily wrong.

**Comment by mahotilo** [comment]
> But not all edits were necessarily wrong.

Can restore last normal edits from history now, can't I?
The problem is just with Current page. I can not restore (well in current terms) it now.

**Comment by juek** [comment]
This would actually be the correct view then (my version)
![grafik](https://user-images.githubusercontent.com/704283/73126857-0f36bf80-3fb8-11ea-8c31-d174f3f5c9e9.png)

**Comment by mahotilo** [comment]
And, can I get my Current page back?

**Comment by juek** [comment]
After that, you would edit the Current page (because there is no draft anymore), just like … 

![grafik](https://user-images.githubusercontent.com/704283/73126888-9be17d80-3fb8-11ea-9cfb-bd417abf9cbf.png)

**Comment by mahotilo** [comment]
Er.. It's going to work But as we say here, it is not easy to understand without a bottle of  sth flammable.

**Comment by juek** [comment]
Both variants re-instate the Current page as editing target.
The difference is only 

- 'Restore' Current page deletes everything newer
- 'Dismiss Draft' keeping all edits (archived but still restorable)

Technically, deleting edits does not bring back older edits (>30) into the list, so it has no benefit.

**Comment by mahotilo** [comment]
Can we have both variants?

**Comment by juek** [comment]
From the programmatic side, dismissing a draft does nothing but archiving it. So it's also much simpler to do.

**Comment by mahotilo** [comment]
> From the programmatic side, dismissing a draft does nothing but archiving it. So it's also much simpler to do.

And what about "restore" Current page?

**Comment by juek** [comment]
- 'Restore' Current page deletes everything newer.

We would additionally have to iterate through the archived edits and delete them

**Comment by mahotilo** [comment]
Well. Let it be option 1.

> dismissing a draft does nothing but archiving it.

Why not simply delete dismissed draft?

**Comment by juek** [comment]
But i have issues with the term 'Restore'. It is currently the **active public** page. It would act different than 'Restore' does for other items

**Comment by juek** [comment]
> Why not simply delete dismissed draft?

For the same reason we keep other edits.

**Comment by mahotilo** [comment]
> And it would act different than 'Restore' does for other items

Do you mean changes in history list?

**Comment by mahotilo** [comment]
> For the same reason we keep other edits.

Other edits appear without my wish as a kind of undo history. When I say "Dismiss" I do not want to see it in undo history. Like it is in regular text processor. Now we will have a loop in history. Am I wrong?

**Comment by juek** [comment]
From a painter's POV it's like: 
One thinks "I don't my like last painting – I have to burn it right now." 
Others may think "Hmm, maybe I paint over it tomorrow"

**Comment by juek** [comment]
> Do you mean changes in history list?

'Restore' makes items to drafts normally, Current page is kept.

**Comment by juek** [comment]
> Now we will have a loop in history. Am I wrong?

No loop, see my fake screenshots

**Comment by mahotilo** [comment]
Good example.

Yesterday, I worked on my plugin and crushed my page many times. Only the Restore saved ~~my..~~ me. And I think now that a beautiful button "Burn all this drafts" is very handy.
I also missed it when the page was crashed during the section reordering. (I haven't seen this in a long time and happy with it:)

**Comment by juek** [comment]
> Why not simply delete dismissed draft?
> For the same reason we keep other edits.

Just deleting the draft would be a (irreversible) option.

**Comment by mahotilo** [comment]
Ok. I rely on your vision. 
The main thing for me is the ability to return the Current page in one way or another. The easier it is from the code side, the better.

**Comment by juek** [comment]
I may sound stubborn but I consider UX directives in this order (in terms of wording, appearance and behavior):

1. Consistency 
2. Accuracy
3. Intuitiveness

**Comment by mahotilo** [comment]
> I may sound stubborn 

No, no. If I am the man who trying to swing the boat, then it must be someone who will keep the course:)

**Comment by mahotilo** [comment]
But, Intuitiveness is not about Revision history. At least for me.

**Comment by juek** [comment]
> But, Intuitiveness is not about Revision history. At least for me.

It could be better. But do you know the UI Wordpress has for it? Try it and you will **love** ours.

**Comment by mahotilo** [comment]
:)
Believe me, I've tried. And that is why my biggest nightmare is the abandoned TS.

**Comment by mahotilo** [comment]
My current findings.
Right after the first editing of the Current Page, we get two drafts. One is Working Draft, and the other is a copy of the Current Page (marked with arrow).

![image](https://user-images.githubusercontent.com/14929385/73692364-d8118e00-46dc-11ea-8d3e-3861db6c1257.png)

So, in order to "restore" the Current Page, in fact, it is enough to just restore the first draft above it!

But, if I persist in editing, this draft will disappear after 30 savings. In this case, the only way to "restore" the Current Page is to delete the Working Draft. 

I have added this possibility to the code. The only problem that I see, is that TS creates not only a new Working Draft but also one more draft. Both of these drafts are copies of the Current Page.
![image](https://user-images.githubusercontent.com/14929385/73693975-d9908580-46df-11ea-8d27-991a3a858852.png)

I think the second draft is redundant, and we have to prevent its creation to save the History and make it clearer to understand.

What do you think?

**Comment by mahotilo** [comment]
I have also added a "restore" for the Current Page. (Yes, I remember, you are against this term)

It does the same as regular restore, creates the copy of the Current Page as the Working Draft. I suppose this is the best variant.

We just have to find the right name. Maybe "Make a copy" or your "Restart from here" is what we need?

**Comment by mahotilo** [comment]
I also suggest hiding editing links for non-active history elements. It may look like a "just an extra click", but for me it is a "check twice before you do it".

![image](https://user-images.githubusercontent.com/14929385/73722018-387ceb80-472e-11ea-9923-93925e7739df.png)
