### ISSUE TITLE
UI: Misleading tab order and button name in New Page

### ISSUE THREAD

**Issue by mahotilo** [Typesetter/Typesetter#561]
I am always confused when I want to create a new page.

1. I think first tab have to be 'Content Type' and not 'Copy'.
2. The button 'Create New page' on the 'Copy' tab should have label like 'Copy with new name'.

![image](https://user-images.githubusercontent.com/14929385/73124647-52883280-3fa6-11ea-96c7-43460a90891b.png)

**Comment by juek** [comment]
I think this decision was made with ver 5.0 (it was the way yo're proposing before)

IMO it's a matter of taste, design complexity and workflow.

Wen initially building a site, creating new pages from scratch is of course the desired variant. 

With medium-size websites (50+ pages) that use multiple similar page designs, copying and then modifying existing pages is the variant that's needed much more often.

**Comment by mahotilo** [comment]
> IMO it's a matter of taste, design complexity and workflow.

Agree, but let us look at this page from the neewbe's point of view

![image](https://user-images.githubusercontent.com/14929385/73126078-eb26ae80-3fb6-11ea-8a88-b7faa0a50f57.png)

**Comment by juek** [comment]
> from the neewbe's point of view

Frequently happens to me as well ;)

**Comment by mahotilo** [comment]
I was thinking of moving both lists to one tab, e.g. Types on the left side and Pages to copy on the right side. But we have same situation in the Insert before/after menu dialog and there are a lot of tabs this dialog:) So, this is not a solution.

Maybe renaming button will be a compromise?

**Comment by juek** [comment]
IMO there are different solutions to improve the UX here:

1. Make the home page selected by default for copying (bad solution)
2. Block the Create button as long as not all required information is given (commonly used practice)
2. Make is wizard-style: Input new Label -> select method -> select source page or content type (most newbie frioendly)

**Comment by mahotilo** [comment]
> Block the Create button

It seems like a compromise. If it is not hard to do.

**Comment by mahotilo** [comment]
I have made a PR https://github.com/Typesetter/Typesetter/pull/564 as a lazy fix.

But I thought about it again. Do we need other types for the new page besides the predefined ones? All the other types I have are a sections and I never used them as a single page.

This dialog can be much simpler and more convenient.

![image](https://user-images.githubusercontent.com/14929385/73134264-35eb0980-403d-11ea-9089-7d852a46d3e4.png)

**Comment by juek** [comment]
> This dialog can be much simpler and more convenient.

Definitely!

**Comment by juek** [comment]
Do you want to implement it?

**Comment by juek** [comment]
> Do we need other types for the new page besides the predefined ones?
Sure. But they don't hurt.

**Comment by mahotilo** [comment]
If you agree with concept, I will try.

> Sure. But they don't hurt.

They take some space, so we will need to use scroll to place everything on one tab.

**Comment by juek** [comment]
> They take some space, so we will need to use scroll to place everything on one tab.
Let's use 

```
#new_section_links {
    max-height: 220px;
    overflow-y: auto;
}
```

**Comment by juek** [comment]
We should also make it consistent in Insert Before / Insert After / Insert Child

**Comment by mahotilo** [comment]
> We should also make it consistent in Insert Before / Insert After / Insert Child

This will be a problem (or impossible) because we have more than 2 options there.

**Comment by juek** [comment]
> I think it's easy. Just combine the New Page and Copy methods. Haven't yet checked the code, though.

**Comment by juek** [comment]
We'll only need bit of JS that shows/hides the correct buttons based on the selection

**Comment by mahotilo** [comment]
So did you mean just to combine "new" and "copy"? Yes, it is possible.

**Comment by juek** [comment]
> So did you mean just to combine "new" and "copy"?

Yep.

**Comment by mahotilo** [comment]
It is not as easy as it seemed to me.
We have two different buttons with 'value=<command>'. One for 'copy' and another for 'new'. All control is done in PHP without JS.
So, combining of lists is not just the lines rearrangements in Ajax::AddHidden()
:(

**Comment by juek** [comment]
If you prefer I can try it (a little later)

**Comment by mahotilo** [comment]
Yes, I give up, and you will need to check my changes anyway:)

**Comment by mahotilo** [comment]
closed with https://github.com/Typesetter/Typesetter/commit/e26c546df4ca552d75299f4d638f599b19e2685f
