### ISSUE TITLE
Error: Extra area publishing status

### ISSUE THREAD

**Issue by mahotilo** [Typesetter/Typesetter#566]
If I have several unpublished Extra areas, publishing one of them through right panel hides **all** the 'Publish' buttons.
Link in top admincontent_panel reacts correctly.

**Comment by juek** [comment]
Good point, needs to be fixed.

**Comment by mahotilo** [comment]
It is here https://github.com/Typesetter/Typesetter/blob/bdb0b136377033c307afd4b5641825025eda2058/include/js/inline_edit/inline_editing.js#L198-L206
As I understand it, the problem lies in the non-selectiveness of the `document.querySelectorAll('.ck_publish').forEach()`.
But I do not know yet how any changes here will affect other CMS functionalityh.

**Comment by mahotilo** [comment]
Got it!

**Comment by mahotilo** [comment]
closed with https://github.com/Typesetter/Typesetter/commit/840869a2e20afb32db2f02a955a140da22ba0097
