### ISSUE TITLE
API: gpOutput::Area and gpOutput::GetArea work badly

### ISSUE THREAD

**Issue by mahotilo** [Typesetter/Typesetter#567]
I tried to use gpOutput::Area and gpOutput::GetArea as described in [Output Functions](https://www.typesettercms.com/Docs/Output_Functions)

It does not seem to work now as expected.

* ~~Clicking on area's 'pencil' menu gives a special dialog with simple 'input'.~~ (as designed)
* Clicking on area with opened CKE gives an empty editor panel. 
* ~~After saving, the '../Admin_Theme_Content/Text' page opens, but no themes is shown.~~ (fixed)
* ~~Changes are saved only once.~~ (fixed)
* ~~This area is not available as Extra.~~ (as designed)

I think such approach to insert area into template should be deprecated in favour of sth like https://github.com/Typesetter/Typesetter/issues/554

UPD
~~The similar happens when you edit an additional menu in a template.~~ (fixed)
I chose the 'another' menu and after save got page `http://www.test:8080/Admin_Theme_Content/Edit/vo22356` without content.

**Comment by juek** [comment]
> Clicking on area's 'pencil' menu gives a special dialog with simple 'input'.

Yes that's hiow gpOutput::Area() always worked. AFAIK it's the ancient predecessor of Extra Content Areas. 

> Clicking on area with opened CKE gives an empty editor panel.
> After saving, the '../Admin_Theme_Content/Text' page opens, but no themes is shown.
> Changes are saved only once.

Definitely buggy.

> This area is not available as Extra.

They are different things. Areas are text-only and were used e.g. for the site name in earlier themes where it's text was used inside the home link. We <s>cannot</s> should't wrap Extra Content areas in &lt;a&gt; elements because easily leads to invalid HTML (e.g. &lt;a&gt; inside &lt;a&gt;)

**Comment by juek** [comment]
> It actually should result in an AJAX response. I traced it back to the point where
ReturnHeader() is called, which is the case. But I cannot see the JS response it should generate.

I just found [this](https://github.com/Typesetter/Typesetter/blob/6e1a65fcb7947bf2754592043fa432bba8ad64f9/include/admin/Layout.php#L113-L131), which explains why the AJAX response cannot work. Must be broken since then.

**Comment by mahotilo** [comment]
I wonder why we have different approaches to the formation of the request URL when editing page's property and textarea?

Maybe we should always use `{pageURL}?cmd=...` scheme?

![image](https://user-images.githubusercontent.com/14929385/75015353-15be3700-5491-11ea-9e11-a41b3e4c0949.png)

![image](https://user-images.githubusercontent.com/14929385/75015428-3be3d700-5491-11ea-8e9c-6446e65f4c73.png)

**Comment by juek** [comment]
For the records: my last finding is bullst*t. addontext -> RedirectText is not the issue.

**Comment by mahotilo** [comment]
I changed the current state of the problems in the first post

**Comment by juek** [comment]
> I changed the current state of the problems in the first post

> UPD
The similar happens when you edit an additional menu in a template. I chose the 'another' menu and after save got page http://www.test:8080/Admin_Theme_Content/Edit/vo22356 without content.

Seems to be the same issue with [ReturnHeader()](https://github.com/Typesetter/Typesetter/blob/6e1a65fcb7947bf2754592043fa432bba8ad64f9/include/admin/Layout/Edit.php#L86)

**Comment by juek** [comment]
> UPD
The similar happens when you edit an additional menu in a template. I chose the 'another' menu and after save got page http://www.test:8080/Admin_Theme_Content/Edit/vo22356 without content.

I cannot reproduce this one. Can you specify it more in deptht?

**Comment by mahotilo** [comment]
1. I added 
```
              <?php gpOutput::Get('Extra', 'Footer_Column_2');
               gpOutput::Get('Menu'); //top two levels
               ?>
```
to Bootswatch4_Scss template

2. I tried to set Custom menu
![image](https://user-images.githubusercontent.com/14929385/75018801-6d13d580-5498-11ea-8db0-2604bb5400e4.png)

actually, with any settings

3. I got page `http://www.test:8080/index.php/Admin_Theme_Content/Edit/22jd2sz`

**Comment by mahotilo** [comment]
And the same empty CKE when clicking on the extra menu after the edited  text section.

**Comment by juek** [comment]
> I wonder why we have different approaches to the formation of the request URL when editing page's property and textarea?

> Maybe we should always use {pageURL}?cmd=... scheme?

We do. In your example it's the homepage therefore the page url is empty.

**Comment by juek** [comment]
>1.  I added [code] to Bootswatch4_Scss template
>2. I tried to set Custom menu

OK, I can reproduce it.
If you add the additional menu via Layout Manager, it works.

**Comment by mahotilo** [comment]
> We do. In your example it's the homepage therefore the page url is empty.

But we do not have fake pages like Admin_|Theme_Context/Text

![image](https://user-images.githubusercontent.com/14929385/75019499-a9940100-5499-11ea-8dca-4b971fa94278.png)

**Comment by juek** [comment]
> But we do not have a "fake" pages like Admin_Theme_Context/Text

If we change page properties we post to the same page. It's all about which RunScript() function will process the values. For regular pages its [this one](https://github.com/Typesetter/Typesetter/blob/542bc8a7609d336d5f9e99a1194418a36e7791ff/include/Page.php#L139)

**Comment by mahotilo** [comment]
Well. One extra menu edit dialog. Two similar forms. Different results. What is the reason?

![image](https://user-images.githubusercontent.com/14929385/75020575-b0bc0e80-549b-11ea-9a6e-4edfa4cf8520.png)

> edit: What you call "fake" pages is called "routing"
Ok

**Comment by juek** [comment]
>Two similar forms. Different results. What is the reason?

Good point - seems [fixed](https://github.com/Typesetter/Typesetter/commit/367b480a6d314432924156cd124c4890002d27f5)

**Comment by mahotilo** [comment]
Yep. One bug is caught. 
But gpOutput::GetArea is still resisting.

**Comment by juek** [comment]
> But gpOutput::GetArea is still resisting.

[Not anymore :)](https://github.com/Typesetter/Typesetter/commit/f31dbabb3abdf6bc4ba4fd4303a6a9d5af6f2a92)

**Comment by mahotilo** [comment]
I still have this

> * Clicking on area with opened CKE gives an empty editor panel.

**Comment by juek** [comment]
Sometimes it's the most obvious things we overlook. It was your form comparison that pointed to the solution.

**Comment by juek** [comment]
> I still have this &bull; Clicking on area with opened CKE gives an empty editor panel.

Let's [try this](https://github.com/Typesetter/Typesetter/commit/51c2911eb74db983cea9430fe36225917781a5df)

**Comment by mahotilo** [comment]
Confirm.
Problems are solved.
