### ISSUE TITLE
JS error on destroying of the popper

### ISSUE THREAD

**Issue by mahotilo** [Typesetter/Typesetter#570]
I caught a number of errors in 'Section Attributes'. Maybe I was acting too fast:)

Console description

> VM827:2070 Uncaught TypeError: Cannot read property 'destroy' of undefined

Place where it appears (~~inline_editing.js~~ manage_sections.js)

> 			})
> 			.on('mouseleave', function(){
> 			--->	this.popup.destroy();
> 
> 				var $popup = $(this).next('.avail_classes_desc:not(:empty)')
> 					.stop()
> 					.hide();
> 			});
>

**Comment by juek** [comment]
Haven't had that yet. Most likely a timing issue. 

could you please try to change the marked line to 

`this.popup && this.popup.destroy();`

and see if it helps?

**Comment by mahotilo** [comment]
Yes. It helps immediately.
(As soon as I managed to find sustainable way to reproduce the error again:)

Can you make a commit to `manage_sections.js`?

**Comment by juek** [comment]
[Sure](https://github.com/Typesetter/Typesetter/commit/b4d2599b4ddbdbe811ebb5fb9d174a06aca6b48a)
