### ISSUE TITLE
Poll: do we need confirmation for 'Dismiss draft'?

### ISSUE THREAD

**Issue by mahotilo** [Typesetter/Typesetter#571]
When working with different languages, the CMS buttons have different sizes and placements and, and it is not easy to get used to. Thus, I found it very easy and frustrating to miss the Publish button and click Dismiss. 

I tried and made some progress in adding confirmation dialogs for Dismis (both in JS and PHP files).  This is not hard to do, I just have to do it in all 4 places. 

So I wonder if we need this, or should I just change my mouse click habits? :)

**Comment by juek** [comment]
I agree that the floating, jumping buttons with variable sizes are not ideal (generally).
I wouldn't implement confirmations right now but rather change the apperance of the editor buttons as part of a visual consistency update we already talked about. 

I'm thinking of using flex in the admin UI in quite some places which can sort this issue as well as improve others.
