### ISSUE TITLE
Artefacts of the debugging process?

### ISSUE THREAD

**Issue by mahotilo** [Typesetter/Typesetter#572]
When I click on the 'Section' in Admin Content Panel, I catch the info in the Console

> no content found for get_edit_area() 0

Do we still need this?

**Comment by juek** [comment]
> Do we still need this?

Probably not like most console logging. Butit can come in handy.
I [bound it](https://github.com/Typesetter/Typesetter/commit/bdb0b136377033c307afd4b5641825025eda2058) to gpdebug, enabled in /gpconfig.php
