### ISSUE TITLE
Project plans?

### ISSUE THREAD

**Issue by SciCrea** [Typesetter/Typesetter#576]
Hello. Thank you for your work! I've been following your project for a long time. I think some time ago the releases of new versions began to fall and popularity began to fall.

I managed to do great projects on your CMS. Then the requirements changed and had to change CMS. I want to go back. Is it interesting to know what plans and how the project will develop? Is it worth trying now to develop new sites on Typesetter?

**Comment by juek** [comment]
> Then the requirements changed and had to change CMS …
Is it worth trying now to develop new sites on Typesetter?

It depends on your requirements. Typesetter will continue to be a small CMS with certain strengths and limits. Technologically it will remain PHP-based. It does not aim to play in the enterprise class, as a community platform or in the eCommerce area. It is well-suited to serve sites up to, let's say, 1,000 pages. 

In my point of view, Typesetter is an extremely fast and solid foundation to develop all kinds of applications. 

When trying to classify what type of tool Typesetter is, I'd call it 
A) an easy-to-use entry-level CMS with WYSIWYG feedback for doing simple things 
**but also** 
B) a very capable Bootatrap/Scss/jQuery-enabled barebone for fast ground-up development and content prototyping (for advanced users)

**Comment by SciCrea** [comment]
I agree with you about the benefits of Typesetter. It took so long, but i could not find a full-fledged analogue.

It's just a question of plans. Support for new versions of PHP, usability improvements, etc. Is there a place to develop?

**Comment by juek** [comment]
> Support for new versions of PHP

The current master is tested up to PHP 7.4 and will be released as ver. 5.2 soon.

> … usability improvements, etc. Is there a place to develop?

The place is here. I'd suggest to fork Typesetter and send your ideas as Pull Requests. We're basically open for new features or meaningful changes. 

But Typesetter also has lots of possibilities to add functionality via plugin hooks. I personally prefer to add new features in form of plugins and only move them to the core after some testing.
