### ISSUE TITLE
Recapcha v2 language

### ISSUE THREAD

**Issue by gtbu** [Typesetter/Typesetter#583]
The recaptcha has a problem with languages . In include/tool/Recaptcha.php in line 50 : $html = '<script src="https://www.google.com/recaptcha/api.js' . $custom_lang . '" async defer></script>';  
The resulting code is : ..>Captcha< script src="https://www.google.com/recaptcha/api.js" async defer>< /script>
A bad example is https://www.universal-path.org/Contact where 'Ich bin kein Roboter' appears.
The resulting code should be https://www.google.com/recaptcha/api.js?hl=en

**Comment by mahotilo** [comment]
1. Yes, it is an error. ReCaptcha ignores the language selected in the Configuration. 
2. This is not a big problem, because reCaptcha is shown in the current browser language. In your case, it is Deutsch, in my case it's Ukrainian. I think it is reasonable to see reCaptcha messages in your system language.
3. I have fixed the error and will do a PR.

**Comment by mahotilo** [comment]
We have another problem
The current TS's list of possible reCaptcha languages (8 items) is outdated. [New one](https://developers.google.com/recaptcha/docs/language ) includes about 67 languages.

I think we can leave only 2 options: 'Browser default language' and 'TS interface language'. If TS's language is not supported by reCaptcha, Google will use English.

**Comment by mahotilo** [comment]
Meanwhile, I have just added new reCaptcha codes to the TS Configuration.
https://github.com/Typesetter/Typesetter/pull/585

**Comment by Sestowner** [comment]
> I think we can leave only 2 options: 'Browser default language' and 'TS interface language'.

I agree, or maybe we can remove this configuration option and display reCaptcha only in the browser language.

**Comment by gtbu** [comment]
In the code the $custom_lang has no function - neither for german or english. It should append '?hl=en' 
So already a functioning cms-language would be sufficient - 72 google-languages are of course better.
An english visitor, who surfs in japan, would otherwise get a japanese browser-language captcha....etc.

**Comment by mahotilo** [comment]
Fix https://github.com/Typesetter/Typesetter/pull/584/commits/01d4641cf79ba76ec13faa8ce7c9ae3195634fa7
should fix it. 
You can try it while it is waiting for approval.

**Comment by juek** [comment]
It's not exactly a super-clean solution because we don't have translations for all reCaptcha lang codes but it should meet everyone's demands. For my part, I could well live with a reCaptcha that always uses the web browser's preferred language.

**Comment by mahotilo** [comment]
Hi @gtbu,
do you still find this problem unsolved?
