### ISSUE TITLE
Can't edit Bootswatch4_Scss layout

### ISSUE THREAD

**Issue by mahotilo** [Typesetter/Typesetter#589]
Any changes (via TS layout editor) in Bootswatch4_Scss layout, e.g. United, have no results.
While the same changes directly in themes/Bootswatch4_Scss/united/variables.scss are visible.

**Comment by juek** [comment]
True, common_variables.scss still don't work this way. I'll have to change some core functions to make it happen. Hmm, I don't like to implement hardcodes folder names.

**Comment by juek** [comment]
Should be fixed with [this commit](https://github.com/Typesetter/Typesetter/commit/b92f8c50fda3d3512a0debdcd8e388a331b3bfeb)

**Comment by mahotilo** [comment]
Can't confirm.
Maybe it is somehow connected with '_layout\xx\custom.scss' which is actually 'variables.scss'?

**Comment by juek** [comment]
Have you uninstalled and reinstalled the theme?

**Comment by mahotilo** [comment]
Yes. 
I have double-checked it again.
The problem seems to be in the loading order.
Additional classes are active, but all changes in BS variables are ignored.

**Comment by juek** [comment]
Funny. It works here.

**Comment by mahotilo** [comment]
Oh, sorry.
My fault.
I have copied entire customized style with this line

`@import '../_common/common_variables.scss';`

This was the  source of the problem.

All works fine. Can be closed!
