### ISSUE TITLE
Notification update problem with slow hosting

### ISSUE THREAD

**Issue by mahotilo** [Typesetter/Typesetter#596]
After the page is published, the notification bell remains unchanged. Page reload helps to update notification state.
The same problem occurs when the page visibility is set to Private.
But when the page visibility is set to Public, the notification bell state changes instantly.

It happens to me on a free hosting with a narrow bandwidth only (to be exactly, on bplaced.net). I do not see any lags on my local server and on a commercial hosting.

**Comment by juek** [comment]
> It happens to me on a free hosting with a narrow bandwidth only (to be exactly, on bplaced.net). I do not see any lags on my local server and on a commercial hosting.

Do you get any timeouts when watching the 'Network' tab in the browser's developer tools

**Comment by mahotilo** [comment]
No, as far as I can see

I attached screenshots and .har file from Network tab

![image](https://user-images.githubusercontent.com/14929385/75433079-1276ef80-5958-11ea-930f-b7575503ccb8.png)

![image](https://user-images.githubusercontent.com/14929385/75433238-510caa00-5958-11ea-954a-4da4d4afb1bf.png)

[4beauty.bplaced.net.zip](https://github.com/Typesetter/Typesetter/files/4260895/4beauty.bplaced.net.zip)

**Comment by juek** [comment]
Please check again only when clicking the options -> toggle visibility link. Should look like this: 

![grafik](https://user-images.githubusercontent.com/704283/75436982-c9be3700-5955-11ea-9c51-e865a647891d.png)

**Comment by juek** [comment]
… with a response like this:

![grafik](https://user-images.githubusercontent.com/704283/75437094-f8d4a880-5955-11ea-93ed-ca0cc663b90b.png)

**Comment by mahotilo** [comment]
![image](https://user-images.githubusercontent.com/14929385/75437798-7e108b00-595f-11ea-87fc-5e6bd1b5eb51.png)

Ajax Response

> Request URL: http://4beauty.bplaced.net/Admin/Menu/Ajax
Request Method: POST
Status Code: 200 OK
Remote Address: 148.251.158.38:80
Referrer Policy: no-referrer-when-downgrade
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Connection: Upgrade, Keep-Alive
Content-Encoding: gzip
Content-Type: application/javascript; charset=UTF-8
Date: Thu, 27 Feb 2020 10:46:56 GMT
Expires: Thu, 27 Feb 2020 10:46:56 GMT
Keep-Alive: timeout=4, max=500
Last-Modified: Thu, 27 Feb 2020 10:46:56 GMT
Pragma: no-cache
Server: Apache/2.4
Transfer-Encoding: chunked
Upgrade: h2,h2c
Vary: Accept,Accept-Encoding
X-BP-NSA-REQID: 85.90.200.117 n.12UID=268792
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
Accept: text/javascript, application/javascript, application/ecmascript, application/x-ecmascript, */*; q=0.01
Accept-Encoding: gzip, deflate
Accept-Language: uk,ru;q=0.9,en-GB;q=0.8,en;q=0.7
Connection: keep-alive
Content-Length: 250
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
Cookie: gpEasy_8e724759fdd2=2; PHPSESSID=390df83b362b01e3ebc66e8f36f49211; SLO_GWPT_Show_Hide_tmp=1; SLO_wptGlobTipTmp=1; gpEasy_0605a0712368=JXv787ztVb7r3MxqB5eWijgCjK6wN3HrdrltfwTV
DNT: 1
Host: 4beauty.bplaced.net
Origin: http://4beauty.bplaced.net
Referer: http://4beauty.bplaced.net/
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.100 Safari/537.36 OPR/67.0.3575.31
X-Requested-With: XMLHttpRequest
cmd: ToggleVisibility
index: a
visibility: private
gpreq: json
jsoncallback: jQuery22406629575345807819_1582800401542
verified: 1d528b53480891bfee608b83f065ca5acbadfde7bc2f285f4f5dac4185d6be477835bef7bd90c91fcec9469e5fe5f2ca59b6403142c7601eb7f6ab524d04ab37

**Comment by mahotilo** [comment]
Sorry, I will be offline for while

**Comment by juek** [comment]
Looks OK but that's only the headers. Please post the content of the use the 'Preview' tab, as seen in my last image.

BTW: I just edited your last post and removed some sensitive data ;)

**Comment by juek** [comment]
> X-BP-NSA-REQID: 85.90.200.117 n.12UID=268792

From a bit of searching the bplaced.net forums, this header value indicates that the request is considered 'unwanted' for some reasons. Free hosting providers always have some restrictions. I'm afraid this one will be rather hard to track down.

**Comment by mahotilo** [comment]
> jQuery22403726307083888798_1582804575548([{DO: "replace", SELECTOR: ".admin-link-toggle-visibility",…},…]);
> 0: {DO: "replace", SELECTOR: ".admin-link-toggle-visibility",…}
> DO: "replace"
> SELECTOR: ".admin-link-toggle-visibility"
> CONTENT: "<a href="/Admin/Menu/Ajax?cmd=ToggleVisibility&amp;index=a" class="admin-link admin-link-toggle-visibility admin-link-visibility-private" data-cmd="postlink" data-nonce="1d528b53480891bfee608b83f065ca5acbadfde7bc2f285f4f5dac4185d6be477835bef7bd90c91fcec9469e5fe5f2ca59b6403142c7601eb7f6ab524d04ab37" title="Видимість: Приватно">Видимість: Приватно</a>"
> 1: {DO: "toggle_vis_class", SELECTOR: true, CONTENT: ""}
> DO: "toggle_vis_class"
> SELECTOR: true
> CONTENT: ""
> 2: {DO: "replace", SELECTOR: ".admin-panel-notifications",…}
> DO: "replace"
> SELECTOR: ".admin-panel-notifications"
> CONTENT: "<div class="panelgroup admin-panel-notifications"><a class="toplink" data-cmd="toplink" data-arg="notifications"><i class="fa fa-bell"></i><span>Сповіщення</span><b class="admin-panel-badge" style="background-color:#ad5f45;color:#fff;">1</b></a><div class="panelgroup2 in_window nodisplay"><ul class="submenu"><li class="submenu_top"><a class="submenu_top">Сповіщення</a></li><li class="expand_child"><a href="/Admin/Notifications?cmd=ShowNotifications&amp;type=Private%20Pages" title="1 Приватні сторінки" class="admin-panel-notification" data-cmd="gpabox">Приватні сторінки <b class="admin-panel-badge" style="background-color:#ad5f45;color:#fff;">1</b></a></li></ul></div></div>"
> 3: {DO: "gp_menu_prep", SELECTOR: "", CONTENT: ""}
> DO: "gp_menu_prep"
> SELECTOR: ""
> CONTENT: ""
> 4: {DO: "inner", SELECTOR: "#admin_menu",…}
> DO: "inner"
> SELECTOR: "#admin_menu"
> CONTENT: "↵<li class=" private-list" style=""><div id="gp_menu_key_a"><a href="#" class="expand_img" data-cmd="expand_img" ></a><a class="gp_label sort " data-cmd="menu_info" data-arg="a" data-json='{"key":"a","url":"\/","history":"\/Admin\/Revisions\/a","title":"\u0413\u043e\u043b\u043e\u0432\u043d\u0430","special":false,"has_layout":false,"layout_color":"#134f5c","layout_label":"Bootswatch 4 Scss\/united","types":"addscript_section, my_shop_cart, my_shop_item, text, wrapper_section","opts":"","size":"53.96 KB","mtime":"","level":0,"time":"Feb 27, 2020 @ 09:53"}'>Головна</a></div></li>↵<li class="" style=""><div id="gp_menu_key_special_contact"><a href="#" class="expand_img" data-cmd="expand_img" ></a><a class="gp_label sort " data-cmd="menu_info" data-arg="special_contact" data-json='{"key":"special_contact","url":"\/Contact","history":"\/Admin\/Revisions\/special_contact","title":"Contact","special":"special","has_layout":false,"layout_color":"#134f5c","layout_label":"Bootswatch 4 Scss\/united","types":"special","opts":"","size":"","mtime":"","level":0}'>Зв&#39;язатися</a></div></li>"
> 5: {DO: "gp_menu_refresh", SELECTOR: "", CONTENT: ""}
> DO: "gp_menu_refresh"
> SELECTOR: ""
> CONTENT: ""
> 6: {DO: "inner", SELECTOR: ".homepage_setting",…}
> DO: "inner"
> SELECTOR: ".homepage_setting"
> CONTENT: "<span class="fa fa-home"></span> Домашня сторінка: <a href="/Admin/Menu/Ajax?cmd=HomepageSelect" data-cmd="gpabox" title="Головна">Головна</a>"
> 7: {DO: "inner", SELECTOR: "#admin_menu_wrap",…}
> DO: "inner"
> SELECTOR: "#admin_menu_wrap"
> CONTENT: "<ul class="menu_top"><li class="li_0"><a href="/Contact" title="Зв'язатися">Зв'язатися</a></li></ul>"

**Comment by mahotilo** [comment]
> BTW: I just edited your last post and removed some sensitive data ;)

Thx. I always forget that it is not a private chat:)

>> X-BP-NSA-REQID: 85.90.200.117 n.12UID=268792
> From a bit of searching the bplaced.net forums, this header value indicates that the request is considered 'unwanted' for some reasons. Free hosting providers always have some restrictions. I'm afraid this one will be rather hard to track down.

Ok. If this is strictly related to hosting and does not indicate an internal TS problem, we have nothing to do with it.

Issue can be closed.

**Comment by juek** [comment]
> Ok. If this is strictly related to hosting and does not indicate an internal TS problem, we have nothing to do with it.

I am not completely sure. I haven't had the error yet anywhere. With the latest response / Preview you posted, the Notification update should actually have worked. Have it?

From what I have read, bplaced.net blocks certain requests, e.g. such that are considered as 'repeatedly sent' like audio/video upstreams. But all the folks on the forum who posted similar issues didn't use such type of requests, so the filter appears to be rather nonspecific. Unfortunately I couldn't find any public documentation about it. Some posters seem to got it sorted by changing their code via instructions provided via support.

In order to limit server load, it's understandable that bplaced.net don't want their free hosting to be 'abused' with high-traffic or frequent-request applications. They explicitly support things like socket connections only with their paid services.

**Comment by mahotilo** [comment]
> With the latest response / Preview you posted, the Notification update should actually have worked. Has it?

No, this does not work as it have to. This must definitely be due to hosting restrictions. But I decided to make an issue, mainly because of the difference in the notification response on page visibility changes.
When I change it to private, the notification state is delayed and updated only after the page reload.
But.
When I change the page visibility to public, the notification state responds instantly. 
What is the reason for such difference in page state processing?

**Comment by juek** [comment]
> What is the reason for such difference in page state processing?

This part of your posted response should actually change the Notifications panelgroup to show 1 private page:

```
DO: "replace"
SELECTOR: ".admin-panel-notifications"
CONTENT: "
Сповіщення1

    Сповіщення
    Приватні сторінки 1

"
```

If it doesn't I have no clue what's happening.

**Comment by mahotilo** [comment]
Just a guess. When I was registering site, I had a problem with the name approval (4beauty). It seems to me that they struggle with s*xual content and use keyword filters. So even our innocent "private" or "published" can be blocked.

**Comment by juek** [comment]
I think we can ignore it for now, as long as everything else works and nobody else reports the issue. 
Time will tell when 5.2 is released.
