### ISSUE TITLE
Broken 'Synchronize with Label' for page's 'Browser Title'

### ISSUE THREAD

**Issue by mahotilo** [Typesetter/Typesetter#597]
1. Page 'Rename / Details'
2. Change 'Browser Title'
3. Save Changes
4. Everything is OK

1. Page 'Rename / Details'
2. Click 'Browser Title' 'Synchronize with Label'
3. Browser Title value is restored, input is greyed
4. Save Changes
5. Browser Title still is changed, not equal to Label

**Comment by juek** [comment]
The issue is likely that 'Synchronize with Label' adds the attribute `disabled` so it won't get posted. IMO it should become 'readonly' then.

**Comment by mahotilo** [comment]
I think I managed to fix it with https://github.com/Typesetter/Typesetter/pull/598. Have you seen it?

**Comment by juek** [comment]
> I think I managed to fix it with #598. Have you seen it?

Yes but I think https://github.com/Typesetter/Typesetter/commit/61d5c7abed593250aec67f73d3be59ec4a70942a is the better solution.

**Comment by mahotilo** [comment]
Oh, sorry, I missed it:)

**Comment by mahotilo** [comment]
Can't confirm the fix, it doesn't work for me.

**Comment by juek** [comment]
> Can't confirm the fix, it doesn't work for me.

Yep, it also needs [this fix](https://github.com/Typesetter/Typesetter/commit/4614359c268d160924651b2f58b3729cd2aa4c7b)

**Comment by mahotilo** [comment]
Yes. It works now.
