### ISSUE TITLE
Make HideAdminUI shortcut language independent

### ISSUE THREAD

**Issue by mahotilo** [Typesetter/Typesetter#602]
I prefer HideAdminUI shortcut ctrl+h working regardless of the current keyboard language

**Comment by juek** [comment]
I'm afraid there are quite some keyboards/layouts that don't have an 'h' at all.
How could we achieve it?

**Comment by juek** [comment]
![grafik](https://user-images.githubusercontent.com/704283/75912858-25a32700-5e52-11ea-9d50-6aa2dcb3b82a.png)
Just sayin'. :)

**Comment by mahotilo** [comment]
Well. And how to input "height: 100vh" with this keyboard? 
Hide AdminUI is mainly fo guys with English layout on buttons.
Like this.
![image](https://user-images.githubusercontent.com/14929385/75913090-f6dd7e80-5e5a-11ea-87a9-569a100613c2.png)

**Comment by juek** [comment]
Are you saying that if you press `Ctrl + Ф` it will appear as Ctrl + a in the input field?

**Comment by mahotilo** [comment]
I have followed your instructions in 
HideAdminUI-master\HideAdminUI.js 

![image](https://user-images.githubusercontent.com/14929385/75913457-a87caf80-5e5b-11ea-9443-9e0290398d4d.png)

**Comment by juek** [comment]
> I have followed your instructions in HideAdminUI-master\HideAdminUI.js

You have files I don't have LOL.

> No, it appears as Ctrl + Ф

So, if you switch to english keyboard layout, the shortcut it will not work anymore?

**Comment by mahotilo** [comment]
> So, if you switch to english keyboard layout, the shortcut it will not work anymore?

Exactly

**Comment by juek** [comment]
If we use evt.which instead of evt.key we should still display a correct hint in the icon title.
Smells like I have to learn to detect the active keyboard layout via JS.

**Comment by mahotilo** [comment]
Is event.code not enough?

![image](https://user-images.githubusercontent.com/14929385/75914701-e5e23c80-5e5d-11ea-85f3-5e5b694b119f.png)

**Comment by juek** [comment]
> Is event.code not enough?

For 'H' it is. AFAIK event.code always refers to the standard english keyboard layout, so when i press 'ä' key on a german keyboard, event.code will be 'Quote'

**Comment by mahotilo** [comment]
Well, some letters have to be sacrificed:)

**Comment by juek** [comment]
> Well, some letters have to be sacrificed:)

Unfortunately that's just the ones which aren't already bound to browser shortcuts.

**Comment by mahotilo** [comment]
I have just cleared ctrl+h and ctrl+d in my Opera and you know what? I am happy:)

**Comment by juek** [comment]
> Smells like I have to learn to detect the active keyboard layout via JS.

I would be the first one who ever did. It's still not possible.
The only thing that appears feasible would be to allow setting two shortcuts for frequent layout switchers.

**Comment by mahotilo** [comment]
> The only thing that appears feasible would be to allow setting two shortcuts for frequent layout switchers.

I suggest adding a switch and supporting both a language-independent hotkey (for users with non-Latin keyboards) and a language-dependent one. Because a language-independent hotkey is the expected behaviour for development tools, e.g. such as Word.

**Comment by juek** [comment]
> I suggest adding a switch

Yes. However, I fear that even with a good description of the problem, it would be difficult for 'normal users' to understand.

What if we automatically use event.code or event.which only for non-ASCII characters?

With cyrillic/ukraininan layout active, this would lead to `Ctrl + KeyA` when depressing `Ctrl + Ф` but would save `Ctrl + a` when entering the same with English layout. 

With german and french layouts it's slightly different because we have almost-standard latin-based layouts. Instead of QWERTY (English default), German = QWERTZ and French = AZERTY

German: 
`Ctrl + a` -> `Ctrl + a`
`Ctrl + ä` -> `Ctrl + Quote`

Maybe I'm just too inexperienced with layout switching. We don't need to in order to enter ASCII characters. I'd guess the same applies to most latin-character languages.

I think, 'layout switchers' are more aware of the whole problem can deal with a `Ctrl + KeyA` feedback and icon hint when they enter `Ctrl + Ф` via config.

German users will always be slightly confused when they press the 'Y' key and get something like 'KeyZ'. 

Maybe in the end it is only the German-speaking people like me who are irritated. That would be bearable :) and we could go for event.code … hmm …

Now that I've thought aloud, I think we should just go for event.code.

**Comment by mahotilo** [comment]
I have met a solution as you think about.
Process event.code, but show event.key (Ctrl + Cyrillic chars) in a hint.

It appears mainly in app based on JAVA and Qt.
But it is perfectly acceptable and more or less familiar.

**Comment by juek** [comment]
> Process event.code, but show event.key (Ctrl + Cyrillic chars) in a hint.

Yep! Let's do that. Perhaps even use event.which 'in the background' since event.code is [only supported](https://caniuse.com/#feat=keyboardevent-code) recent desktop browsers (not on mobile devices).

**Comment by juek** [comment]
Since the code abstraction used for config values->inputs is quite limited, this will become a little JS application. I'll try to code it in a way so we can possibly also use it for other keyboard shortcuts in the future. Will take a little while.

**Comment by mahotilo** [comment]
Such a small function causes such a big work. :/

**Comment by juek** [comment]
Hmm. I just wonder if keyboard shortcuts should be user preferences instead of global config values?
In fact, I don't only wonder but I believe so.

**Comment by mahotilo** [comment]
Personally, I prefer to use default values, so it does not matter to me.
And I usually afraid of changing something in config files (because I like to change everything at once:)
And I think, we can end in a build-in gpconfig.php editor with "reset to defaults", hints and warnings:)

**Comment by juek** [comment]
> build-in gpconfig.php editor

gpconfig.php is nothing admins have to deal with. It's clearly web designer/developer level by design.

**Comment by mahotilo** [comment]
> user preferences instead of global config values

Oh, I misunderstood term "global config".

> I just wonder if keyboard shortcuts should be user preferences

No. Since we do not have independent language preferences for users,  setting up different shortcuts for each user is superfluous.

**Comment by juek** [comment]
> Such a small function causes such a big work. :/

and 

> Personally, I prefer to use default values, so it does not matter to me.

What if we just provide a dropdown select with, let's say, 3 -5 possible default values to select from? Would be much easier and faster to implement for now. 

Current implementation already support all combinations of Ctrl, Shift, Alt, and Meta/Cmd modifier keys. 

The question merely would be, which defaults we should provide?

**Comment by juek** [comment]
> > I just wonder if keyboard shortcuts should be user preferences

> No. Since we do not have independent language preferences for users, setting up different shortcuts for each user is superfluous.

You are right.

**Comment by mahotilo** [comment]
What you want.
I can suggest smth like
Ctrl+H
Ctrl+~
Ctrl+|

**Comment by mahotilo** [comment]
And maybe just single

Esc

**Comment by juek** [comment]
`[Ctrl] [Alt] + H ` and `[Ctrl] [Alt] + I ` appear to be available on all major browsers (Windows)
`[⌘ Cmd] [⌥ Option] + H ` and `[⌘ Cmd] [⌥ Option] +  I ` seem available on Safari / OS X
For Linux I yet have to check - it's most likely the same as on Windows

**Comment by juek** [comment]
Please check out [this commit](https://github.com/Typesetter/Typesetter/commit/c7834c58a811b86dd9a8cd9dbffbdad868ad3f49)

**Comment by juek** [comment]
Adds Apple keyboard support: Screenshot on OS X/Safari

![grafik](https://user-images.githubusercontent.com/704283/76238457-2d871080-6230-11ea-9f6d-df37b0bc4770.png)

**Comment by mahotilo** [comment]
Thx. It works for me.

BTW
I have tried to mimic your Apple example and done something like this 

![image](https://user-images.githubusercontent.com/14929385/76239040-81e2be00-6239-11ea-83e9-aff1fb253556.png)

But, this combination does not only work as it is set. UI hides also with Ctrl+H without pressing Alt and Shift.
