### ISSUE TITLE
Warning when setting only one dimension of IMG

### ISSUE THREAD

**Issue by mahotilo** [Typesetter/Typesetter#614]
I have following msg() when  adding an image with only one specified dimension (height=100, width='') to text section.

Is it an error or a normal warning for `gpdebug = true`.? 

> Warning (2)
> imagecreatetruecolor(): Invalid image dimensions
>     in: D:\Internet\www\root\Ts-b\include\tool\Image.php
>     on line: 481
>     time: 2020-03-14 11:35:00 (1584185700)
>     REQUEST_URI: /%D0%9A%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D1%8B
>     REQUEST_METHOD: POST
>     REMOTE_ADDR: 127.0.0.1
> Show Backtrace
> array(
>    [0] => array(
>       [file] => (string)D:\Internet\www\root\Ts-b\include\tool\Image.php
>       [line] => (integer)481
>       [function] => (string)imagecreatetruecolor
>       [args] => (string)array(2)
>    )
>    [1] => array(
>       [file] => (string)D:\Internet\www\root\Ts-b\include\tool\Editing.php
>       [line] => (integer)168
>       [function] => (string)createImg
>       [class] => (string)gp\tool\Image
>       [type] => (string)::
>       [args] => (string)array(13)
>    )
>    [2] => array(
>       [file] => (string)D:\Internet\www\root\Ts-b\include\tool\Editing.php
>       [line] => (integer)120
>       [function] => (string)CreateImage
>       [class] => (string)gp\tool\Editing
>       [type] => (string)::
>       [args] => (string)array(3)
>    )
>    [3] => array(
>       [file] => (string)D:\Internet\www\root\Ts-b\include\tool\Editing.php
>       [line] => (integer)42
>       [function] => (string)ResizedImage
>       [class] => (string)gp\tool\Editing
>       [type] => (string)::
>       [args] => (string)array(1)
>    )
>    [4] => array(
>       [file] => (string)D:\Internet\www\root\Ts-b\include\tool\Editing.php
>       [line] => (integer)978
>       [function] => (string)ResizeImages
>       [class] => (string)gp\tool\Editing
>       [type] => (string)::
>       [args] => (string)array(2)
>    )
>    [5] => array(
>       [file] => (string)D:\Internet\www\root\Ts-b\include\tool\Editing.php
>       [line] => (integer)788
>       [function] => (string)SectionFromPost_Text
>       [class] => (string)gp\tool\Editing
>       [type] => (string)::
>       [args] => (string)array(1)
>    )
>    [6] => array(
>       [file] => (string)D:\Internet\www\root\Ts-b\include\tool\Editing.php
>       [line] => (integer)1215
>       [function] => (string)SectionFromPost
>       [class] => (string)gp\tool\Editing
>       [type] => (string)::
>       [args] => (string)array(4)
>    )
> )
> User Notice (1024)
> dst_img not created
>     in: D:\Internet\www\root\Ts-b\include\tool\Image.php
>     on line: 483
>     time: 2020-03-14 11:35:00 (1584185700)
>     REQUEST_URI: /%D0%9A%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D1%8B
>     REQUEST_METHOD: POST
>     REMOTE_ADDR: 127.0.0.1
> Show Backtrace
> array(
>    [0] => array(
>       [file] => (string)D:\Internet\www\root\Ts-b\include\tool\Image.php
>       [line] => (integer)483
>       [function] => (string)trigger_error
>       [args] => (string)array(1)
>    )
>    [1] => array(
>       [file] => (string)D:\Internet\www\root\Ts-b\include\tool\Editing.php
>       [line] => (integer)168
>       [function] => (string)createImg
>       [class] => (string)gp\tool\Image
>       [type] => (string)::
>       [args] => (string)array(13)
>    )
>    [2] => array(
>       [file] => (string)D:\Internet\www\root\Ts-b\include\tool\Editing.php
>       [line] => (integer)120
>       [function] => (string)CreateImage
>       [class] => (string)gp\tool\Editing
>       [type] => (string)::
>       [args] => (string)array(3)
>    )
>    [3] => array(
>       [file] => (string)D:\Internet\www\root\Ts-b\include\tool\Editing.php
>       [line] => (integer)42
>       [function] => (string)ResizedImage
>       [class] => (string)gp\tool\Editing
>       [type] => (string)::
>       [args] => (string)array(1)
>    )
>    [4] => array(
>       [file] => (string)D:\Internet\www\root\Ts-b\include\tool\Editing.php
>       [line] => (integer)978
>       [function] => (string)ResizeImages
>       [class] => (string)gp\tool\Editing
>       [type] => (string)::
>       [args] => (string)array(2)
>    )
>    [5] => array(
>       [file] => (string)D:\Internet\www\root\Ts-b\include\tool\Editing.php
>       [line] => (integer)788
>       [function] => (string)SectionFromPost_Text
>       [class] => (string)gp\tool\Editing
>       [type] => (string)::
>       [args] => (string)array(1)
>    )
>    [6] => array(
>       [file] => (string)D:\Internet\www\root\Ts-b\include\tool\Editing.php
>       [line] => (integer)1215
>       [function] => (string)SectionFromPost
>       [class] => (string)gp\tool\Editing
>       [type] => (string)::
>       [args] => (string)array(4)
>    )
> )

**Comment by juek** [comment]
IMO a minor issue because the image resizing simply fails with no further effects. Should still be fixed.

**Comment by mahotilo** [comment]
I have found a quick-and-dirty solution. We can change

https://github.com/Typesetter/Typesetter/blob/a9fa3c27cd9cab305a35fe3c999684fd485d0209/include/tool/Editing.php#L104-L106

to
```
if( !$css_w || !$css_h ){
  return false;
}
```

But, it will stop creating a resized version for such images with only one defined dimension.
Should we try to calculate another dimension via imagesx() and imagesy()?

**Comment by juek** [comment]
In which context does the real-world issue exist?

**Comment by mahotilo** [comment]
Yes, it happens only in such cases

![image](https://user-images.githubusercontent.com/14929385/76796922-23878380-67d5-11ea-99c4-bfe464fac420.png)
![image](https://user-images.githubusercontent.com/14929385/76796950-3306cc80-67d5-11ea-926b-ceec9397dc39.png)

**Comment by mahotilo** [comment]
Sorry, missed the button :)

**Comment by juek** [comment]
> I have found a quick-and-dirty solution.

Quick? Yes. Dirty? Not at all. `https://github.com/Typesetter/Typesetter/commit/5e6b35b5998dd432d82b2b64448db0cb571985d4`

**Comment by mahotilo** [comment]
Well. So be it.
