### ISSUE TITLE
Jshrink -version 

### ISSUE THREAD

**Issue by g7sim** [Typesetter/Typesetter#615]
You use Jshrink 1.0.
The master https://github.com/tedious/JShrink/tree/master/src/JShrink has at least 4 fixes

**Comment by mahotilo** [comment]
The only **code** fix I found is "Fix hex code of space" https://github.com/tedious/JShrink/commit/ab780a6114b466940f66d0f1ef735564f2990b18

I have just updated TS Jshrink to the latest master from https://github.com/tedious/JShrink and it is working flawlessly for me.

**Comment by juek** [comment]
Understood ;)

**Comment by juek** [comment]
… and [updated](https://github.com/Typesetter/Typesetter/commit/ef0337580a32ecad9734517a9ae3e531f805ea4f)
