### ISSUE TITLE
Template style for 'a' affects all admin links

### ISSUE THREAD

**Issue by mahotilo** [Typesetter/Typesetter#617]
Has it been always this way?

![image](https://user-images.githubusercontent.com/14929385/77236646-2e715800-6bc9-11ea-9092-b45216d83d63.png)

**Comment by juek** [comment]
Thx, [fixed](https://github.com/Typesetter/Typesetter/commit/f5ac51051f0f8dccc6c97b96ba0d037d3f3c64c4)

> Has it been always this way?

Probably.

**Comment by juek** [comment]
When I see a CSS rules like …

```
a {
  font-style: italic;
}
```

… I immediately delete it. A no-go, almost as bad as

```
span {
  display: block;
}
```

**Comment by mahotilo** [comment]
Yes, it is bad idea. 
I have seen this issue only due to an error in CSS. But the admin styles should be protected from user's errors. 
Like Bootstap resets all styles.

Nevertheless, it is fixed.

**Comment by juek** [comment]
> Like Bootstap resets all styles.

Not all but all browser defaults. That's a big difference. 

Resetting everything inside #gp_admin_html would require the the full vocabulary of CSS, multiple times. It's not feasible.

**Comment by mahotilo** [comment]
>  It's not feasible.

True. The full vocabulary of CSS is huge, but the user's errors are countless...

**Comment by juek** [comment]
Just imagine [this list](https://www.w3.org/Style/CSS/all-properties.en.html) of properties for every single* element in #gp_admin_html

* except the ones that are inherited, not much better, though.

**Comment by mahotilo** [comment]
We will wait for CSS4 with something like
*: unset
:)

**Comment by juek** [comment]
We [could already](https://caniuse.com/#feat=css-unset-value) give it a go.

**Comment by mahotilo** [comment]
Yes, it works
I have added  `all: unset;` to `#gp_admin_html a` and changed box-shadow to `a`. Admin links are protected.

**Comment by mahotilo** [comment]
But 379 styles in admin.scss...
