### ISSUE TITLE
Poll: Should we make Bootswatch 4 Scss/Flatly the new default theme?

### ISSUE THREAD

**Issue by juek** [Typesetter/Typesetter#620]
Most new users who are already familiar with Bootstrap will rather prefer Bootstrap 4 over 3. 
I'm uncertain. 

Guys, what do you think?

**Comment by mahotilo** [comment]
BS 4.
Flexes rule.

**Comment by florincatalin** [comment]
In Bootstrap 4 are some additions like nav-link class, nav-item class and navigation bar styles.
Flexbox is one such layout model that permits the formation of complex layouts with ease.
Bootstrap 4 offers support to all the major browsers.
In Bootstrap 4 new utility classes have been included.
So Bootstrap 4, I think.

**Comment by gtbu** [comment]
But the colors , the contrast and the flat style of bootswatch are not everybodys taste. I will make another collection of  https://fitodac.github.io/bsnav/ until July which has all choices - independent of this.

**Comment by juek** [comment]
> The threepoint5 - theme is a bit aweful and has no Hamburger...It should be replaced by a responsive skeleton.

That's right, ThreePoint5 is a bit out of date nowadays. But we need a pure CSS fallback theme for the rare cases when a server is incapable of CSS preprocessing. memory-wise. I don't yet want to remove it entirely. Some folks may still want to use it and it cannot be downloaded from typesettercms.com.

Anyway, the new default theme will be Bootstrap 4
