### ISSUE TITLE
Yellow message does not fit a mobile screen

### ISSUE THREAD

**Issue by mahotilo** [Typesetter/Typesetter#622]
Yellow message box is useful as a debug mean, and send mail service uses it, but `messages gp-fixed-adjust` does not fit a mobile screen. And with some layouts it is sometimes impossible to close this message on the phone.

**Comment by juek** [comment]
Yep, it should be responsive and it could even be resizable (at least when logged in)

**Comment by juek** [comment]
… and the close link should stay visible when scrolling.

Do you want to do it or shall I?

**Comment by mahotilo** [comment]
I have tried to play with width in devtool but failed.

**Comment by juek** [comment]
> I have tried to play with width in devtool but failed.

OK, then I'll do it.

**Comment by mahotilo** [comment]
> and the close link should stay visible when its content is scrolled.

Oh, yes!

**Comment by juek** [comment]
[This commit](https://github.com/Typesetter/Typesetter/commit/bf19b27830334f3041ed8625f5d54c08e59148e4) should solve the mobile issue.

**Comment by mahotilo** [comment]
Thx!

**Comment by juek** [comment]
[This commit](https://github.com/Typesetter/Typesetter/commit/8c029075202665bdcefe478bc6dfe8a1ac819604) makes messages resizable in admin mode
