### ISSUE TITLE
Yellow message resize error?

### ISSUE THREAD

**Issue by mahotilo** [Typesetter/Typesetter#623]
It happens, e.g. when I add a new page

![image](https://user-images.githubusercontent.com/14929385/78766098-81048f80-7991-11ea-9308-bbe207a709ff.png)

**Comment by mahotilo** [comment]
I think this appeared after https://github.com/Typesetter/Typesetter/commit/8c029075202665bdcefe478bc6dfe8a1ac819604

**Comment by juek** [comment]
Seems as if the resizable component is not loaded in page manager. I'll check it later today

**Comment by juek** [comment]
Hmm. I don't have the issue. The (jQuery UI) resizable component is loaded.

What action did you take to get the yellow message area?

**Comment by mahotilo** [comment]
Just create a new page.
I have just checked again on a clear installation. The error exists.

**Comment by mahotilo** [comment]
It also happens on a real site when I call msg() for debug purpose.

**Comment by juek** [comment]
[Fixed](https://github.com/Typesetter/Typesetter/commit/6470d46f291baa825616e380eee2ca1144050431)

Resizable was actually missing (it was loaded by some installed plugins)

**Comment by mahotilo** [comment]
Confirm and close
