### ISSUE TITLE
Double Uri

### ISSUE THREAD

**Issue by gtbu** [Typesetter/Typesetter#624]
I tested my site to generate a sitemap - but a site is reachable with /sitename and with /sitename? 
 I tested with 2 Sites with same result(also with https://typesetter-addons.grafikrausz.at/Simple-Image?/ )  Has anybody similar experiences ? - evtl. a solution for the removal of the ? - maybe by htaccess only
At the moment i only know 
RewriteCond %{THE_REQUEST} !^[A-Z]{3,9}\ [a-zA-Z0-9\.\+_/\-\=\&]+\ HTTP/ [NC]
RewriteRule .? - [F,NS,L]
but if a sitename has non-ascii-letters all other letters have to be added like  \=\ (in the above script are \ behind 9 and between + - etc - 
Github absorbes them - see [rewrite.txt](https://github.com/Typesetter/Typesetter/files/4451897/rewrite.txt)
Another method would be a js-redirection and normalization with tools like https://github.com/passy/node-dom-urls or https://github.com/ericf/urljs

**Comment by juek** [comment]
> … site is reachable with /sitename and with /sitename?

Query strings are valid and commonly used parts of URLs.

https://www.mozilla.org/en-US/?
https://www.microsoft.com/en-US/?
https://github.com/gtbu?

Of course, you can also use rewriting or redirection techniques to remove the query from a URL. But then certain things stop working. It's like removing a car's horn. It will still drive, but it will no longer honk.

So what's the issue? What do you want to achieve?

BTW: Your website is also accessible with /sitename# and /sitename#whatever-you-will-write-here

That's how URLs work.

**Comment by gtbu** [comment]
If You echo the Uri, then the ? is not there - It is appended somehow, evtl. by a poor index.php redirection - the sitemapper makes a double long list . . I hope Google does not judge it as a part of the ranking ?

**Comment by juek** [comment]
> the sitemapper makes a double long list

Which sitemapper?

> A ? can also be the beginning of an appended hack

It can, but then the underlying vulnerability should be fixed.

**Comment by juek** [comment]
For all javascript-based redirections: As long as they are executed in the web browser (and not on a JS server like node.js, which we do not use) they will **neither mitigate nor prevent** any hacking attempts.

**Comment by gtbu** [comment]
The sitemapper was xml-sitemaps.com - where i tried to make a sitemap for universelle-lehre.de(cmsimple xh clean).
After i had to see that the site was also reachable with name? and also with name?/ ,  i checked my universal-path and others with the same result. The clean version of universelle-lehre.de has a hackerfilter - i just mind about the google ranking : If a site is reachable with  sitename and ?sitename,  google sees that as not Seo-friendly. 
Of course Javascript is not a good solution. To fix underlying vulnerabilities is a job without end. If possible the cleaning of index.php or the shortening of the uri from the submenus should be improved in php - yes - no point of discussion, it just needs someone who knows how to do that.

**Comment by juek** [comment]
> … the shortening of the uri from the submenus should be improved in PHP

With Typesetter you can create perfect SEO friendly URLs. It's really up to you. Short(ened) URLs are by no means SEO-friendly. Meaningful URLs are.

www.mysite.com/page_1 = bad
www.mysite.com/index.php?page_id=123 = bad either
www.mysite.com/seo/howto = better
www.mysite.com/how-to-do-seo-right = good

**Comment by juek** [comment]
> Youtube cleans a added ?

No it does not. Examples: 
https://www.youtube.com/?
https://www.youtube.com/channel/UCWf2ZlNsCGDS89VBF_awNvA?

But YouTube uses query strings to access most of its content
https://www.youtube.com/watch**?**v=lrIwTzUTEGs

**Comment by gtbu** [comment]
I dont want to argue here with You - i want to avoid Google point losses due to double accessibility. My universal-path is not well known (i.e. in the page-ranking)- maybe also because of other reasons - Goggle is not neutral.
(https://www.youtube.com/channel/UCWf2ZlNsCGDS89VBF_awNvA? has no mp4 - it doesnt remove the ? - but if You append a ? to https://www.youtube.com/watch?v=lrIwTzUTEGs - its is removed.)
If it is not easy possible to inhibit the double reachability - i dont make a worldview out of it.

**Comment by juek** [comment]
>  it doesnt remove the ? - but if You append a ? to https://www.youtube.com/watch?v=lrIwTzUTEGs - its is removed

Of course. Multiple question marks are not allowed in the specification. 
Multiple parameters in the query string are always separated with some delimiter character. Although it is not specified, you will mostly find ampersands: 

www.mysite.com?param1=foo&param2=bar`
