### ISSUE TITLE
Only short less - notice

### ISSUE THREAD

**Issue by gtbu** [Typesetter/Typesetter#625]
While github-user asenar has less up to 1.80 , mediawiki at github changed his notice to 'forked from oyejorge/less.php'  and [published versions 1.82 and 2.0](https://github.com/wikimedia/less.php/releases) (and 3.0 for php7.1+).
Maybe it makes  sense to correct the issuses from version 1.8.1 to 2.0.

**Comment by juek** [comment]
Version 2.0.0 release notes say

> Require PHP 7.2.9+, up from 5.3+ (James Forrester)

Unfortunately there are no ver 1.x and 2.x branches to compare, so the [All Changes](https://github.com/wikimedia/less.php/compare/1.8.1...2.0.0) links in the release notes do not work.

**Comment by juek** [comment]
As [far as I can see](https://github.com/wikimedia/less.php/compare/v1.8.0...master), we are up to date with bug fixes

**Comment by gtbu** [comment]
At https://github.com/wikimedia/less.php/compare/v3.0.0...master are some suspicious code-changes like 
https://github.com/Typesetter/Typesetter/blob/master/include/thirdparty/less.php/Tree/Directive.php like directive.php ( $rules = null, ..) . But i dont know how much this really influences the function.

**Comment by juek** [comment]
> … ( $rules = null..; $this->_oelements_assoc = array();) . But i dont know how much this really influences the momentary functions.

The comments don't clearly state it. It appears to prevent PHP 8 specific warnings. 
We're not testing against PHP 8 yet. 

As long as we do not have real issues I'm currently not willing to maintain a separate PHP 5.6+ fork of less.php, only to avoid some PHP warnings in certain situations. This might change as soon as once real problems arise.

Of course we will not raise our PHP requirements to 7.2+ now.
