### ISSUE TITLE
Login process stuck

### ISSUE THREAD

**Issue by mahotilo** [Typesetter/Typesetter#626]
Have you experienced a stuck during login process? 

Sometimes, when I try to log in, the dialog on a black background does not disappear. But, if I reload the login page, the site appears, and I am logged in.
This has been happening to me for the last couple of weeks on different hostings.

**Comment by juek** [comment]
Do you get a JS error in such cases?
Does the login form submit? you should see the post in the console's network tab then.

**Comment by mahotilo** [comment]
So, you do not have such a problem.

Sorry, as it happened to me while I was updating a site, I started form session cleaning via ftp and checking my plugins.
Only later after another stuck, I realized that it is not my fault, and this can be overcome via the F5. But I forgot to inspect the errors in a hurry. I will do it the next time it happens again.

**Comment by mahotilo** [comment]
> Does the login form submit? you should see the post in the console's network tab then.

I think yes, because after a reloading without re-entering credential, everything works as it should.

**Comment by juek** [comment]
The post should redirect you (via 302 header) to the page you were on when you clicked the login link -  or to /Admin. 
If the phenomenon is new, could it be related to the new SimilarTitles hook? Do you use custom redirect filters or the SimilarTitles hook on the affected sites? Just a suspicion.

**Comment by mahotilo** [comment]
You are right, both sites use SimilarTitles-Example with 1 or 2 uncommented blocks.

```
		// Blacklist Example 1: remove all pages not in the Main Menu
		// <-- remove the * to uncomment this code block
		foreach( \gp\admin\Menu\Tools::GetAvailable() as $index => $title ){
			$blacklist[] = $index;
		}
		//*/

```
and

```
		// Blacklist Example 4: remove all pages using the robots metatag with 'noindex'
		// <-- remove the * to uncomment this code block
		foreach( $gp_titles as $index => $data ){
			if( isset($data['rel']) && strpos($data['rel'], 'noindex') !== false ){
				$blacklist[] = $index;
			}
		}
		//*/

```

**Comment by juek** [comment]
I wonder if we should keep the hook so powerful, then.

**Comment by mahotilo** [comment]
Oh, I really like it :(

The issue is not permanent. Is it possible not to just use the hook during login process?

**Comment by juek** [comment]
The issue is probably not related to SimilarTitles but to a JS error fixed with https://github.com/Typesetter/Typesetter/commit/500068694f3db4ebe49dcdaebb4ba08f3e5cd013 and https://github.com/Typesetter/Typesetter/commit/efe5ab7b5b25c01c3e4eac3e4864edb6c78c18ed

Please give it a go.

**Comment by mahotilo** [comment]
I will try it on my sites.

**Comment by juek** [comment]
Any news on this?

**Comment by mahotilo** [comment]
I am watching. So far, without problems. Let us give it a couple more days.

**Comment by mahotilo** [comment]
It seems to be fixed. So, I close the issue. Hope permanently
