### ISSUE TITLE
 A notice to Bootwatch 4 Layouts

### ISSUE THREAD

**Issue by gtbu** [Typesetter/Typesetter#629]
I installed the newest master at xampp7.4. 
The fonts in the heading of the original https://bootswatch.com/cerulean/   are 16 px, and the dropdowns have rounded corners. Other Themes have 15px and look thin. (I think bootstrap4 switched to 16px ?) Its of course all a question of taste - not mine - i know how to change it quick : 
ul.dropdown-menu{ border-radius:3px !important; font-size:16px; }
ul.nav.navbar-nav{ font-size:16px; }
. (Except from that the Hambuger comes at 990px - Bootswatch 967px - well : I have no tablet)

**Comment by juek** [comment]
> I think bootstrap4 switched to 16px ?

16px is the **default font size of your web browser**. It just will not be changed by the theme.
There is a rule for the &lt;body&gt; element which defines `font-size: 1rem;` and `line-height: 1.5;`. 
Many elements will inherit this font size unless defined different. `1rem` means 100% of the base font size, which can be defined for the &lt;html&gt; element if you wish. 

`html { font-size: 18px; }` will let 1rem equal to 18px.

Bootstrap/Bootswatch 4 uses rem units for most font size definitions. IMO a good decision.

**Comment by gtbu** [comment]
Thats not what i mean : Just look at https://bootswatch.com/yeti/ - the letters in the nav are much too small - the dropdown fits with the style - but in https://bootswatch.com/materia/ the letters are much too small - its not the browser ! It a design of bootswatch who has a programming-damaged taste.  The size of the font depends of course upon the fontset as in https://bootstrapmade.com/demo/Vesperr/.

**Comment by juek** [comment]
Bootstrap standard would be `body{ font-size: 1rem; }` (that's at least what we see at  [getbootstrap.com](https://getbootstrap.com))

Quite a lot of websites use 14px (0.875rem of 16px) as base font size (GitHub, Apple, Adobe, to name a few). But I agree with you that some Bootswatch 4 theme variants use font sizes that are rather small, especially when light weights are in use.

I tend to hold back before tinkering with other people's designs but, yes, I think we should actually adjust them a bit.

> Its more a design of bootswatch who has a programming-damaged taste.

Your choice of words is inappropriate and does not reflect the spirit of open source! Thomas Park offers his Bootswatch themes for free under a very permissive license. Nobody forces you to use them. If you expressed your criticism in this form in [his repository](https://github.com/thomaspark/bootswatch/), I wouldn't be surprised if he ignores you. Just sayin'

**Comment by gtbu** [comment]
Hm - my choice : The lifestyle shapes the taste, and the motivation of publishing something as free can have a very different background(also to be proud to offer something exceptional). Mr Park is not really friendly. I asked him about the reason why the hamburger comes so early - and he gave me  a useless  link for styling ,  but he is completely unmovable regarding a solution on his website which others can also use (switch at 768 etc.). Not all people are friendly just because they are intelligent - in the academic society it is more the opposite (business friendlynes) ! I have a cousin in my relationships with Doctor of Computer Science ....logical thinking shapes personality...and makes the personality one-sided.

**Comment by mahotilo** [comment]
As for the topics, I think that TS should give not improved, but standard themes with expected features, even if they are not perfect.

As for off-topic, everyone can criticize PhD, but not everyone can become him:)

**Comment by gtbu** [comment]
The bootstrap4 themes are more examples - if i bring something out to attract people for Bootstrap 4  then it should be rather perfect.   
I cant admire persons just because they are intelligent. There are higher developed people like spiritual masters, Their intelligence and their personality is billons time better - without timlely delay - they just dont work for materialism (and they hide their possiblities for people - i had contact with some of them )

**Comment by juek** [comment]
@gtbu The curse and blessing of web design is its dynamism. More than other forms of design, it serves to convey constantly changing content. There may be ultimate truths in your spiritual teaching. Nothing like that exists in design, science or technology.

**Comment by gtbu** [comment]
I dont want to  prolog this issue , but  design is also a branch of psychology, which tries to explain why people have certain tastes and moods(and industry ab-uses this knowledge.). The flat design was initiated by american freemasonory, where squares mean firmeness. Now designers have the problem to make elegant flat sites, which are much to cool for the majority of visitors.
(I see no real border between spirituality and real science : In the spiritual-form-worlds  is the origin of  mathematical laws - the lower spiritual worlds are just in a different space with a much faster time. Our  material worlds together with our space and slow time  were created out of transformed spiritual energies and will be slowly withdrawn in about 100000 million years. Science knows now that the Higgs-field is constantly excited and produces elementary particles. If this process ends then everything solves up. All form-worlds underly exact mathematical laws (a real enlightened person sees the still higher worlds and their influences)).

**Comment by juek** [comment]
Should we enable [RFS](https://github.com/twbs/rfs/tree/v8.0.4)? It's not bad but I'm afraid it's a bit too sophisticated for CSS/Scss beginners.

**Comment by juek** [comment]
I'm going to implement 2 additional variables `$navbar-font-size` and `$footer-font-size` which can be changed easily via variables.scss or Layout Manager. 

The question merely is: should we define them relative to the root font size (would be rem units) or relative to the $font-size-base (would be em then). I'd go for rem for consistency. What would you expect?

**Comment by mahotilo** [comment]
Strictly speaking, in BS3 they should be in em, and in BS4 in rem.

**Comment by gtbu** [comment]
https://github.com/twbs/bootstrap/pull/23816      Fixes #23053
* RFS is disabled by default and can be switched on with $enable-responsive-font-sizes
 font-size-properties are switched to the @include font-size()-mixin. 
Stylelint prevents the usage of font-size property.

**Comment by juek** [comment]
When I wrote 'enable RFS', I of course meant 'enable **and use** it for Bootswatch 4 Scss'.
Anyone can activate and use it for their own custom themes.

> So why not include the mixings for less and scss

We don't have LESS-based Bootstrap 4. For Scss, everything is available and in place: https://github.com/Typesetter/Typesetter/blob/e5c199b3171722c18c967f40625c004ca4845dfd/include/thirdparty/Bootstrap4/scss/bootstrap/vendor/_rfs.scss and https://github.com/Typesetter/Typesetter/blob/cfaff31fa9204cfafa37561e54046b4f042596d9/include/thirdparty/Bootstrap4/scss/bootstrap/_mixins.scss#L14

**Comment by gtbu** [comment]
For font-sizes in sass are also https://www.smashingmagazine.com/2015/06/responsive-typography-with-sass-maps/   like          
  $p-font-sizes: (
  null  : 15px,
  480px : 16px,
  640px : 17px,
  1024px: 19px
); -- there with a mixing -

**Comment by juek** [comment]
> null : 15px,
480px : 16px,
…

In Boostswatch 4 Scss we better continue to use Bootstrap breakpoints and rem units.

**Comment by mahotilo** [comment]
Thanks to this discussion about RFS, I finally decided to try turning it on. It is quite useful. I think we should include 

```
//RFS
$enable-responsive-font-sizes: true;
```
to variables.scss in Bootswatch4_Scss theme.

**Comment by juek** [comment]
just [updated](https://github.com/Typesetter/Typesetter/commit/b12fa0f545d740c84ee05bb5a1bbe95c6f558117) the theme

> … RFS … I think we should include (it)

I'll give it a go but we have to make sure not to lock out Layout Editor's ability to change font sizes.

I personally prefer to do such things (calc px + vh and other responsive font resizing techniques) myself and only for elements that require it, such as slide headings / text

**Comment by juek** [comment]
Ad RFS: I'd rather to go for [element queries](https://github.com/marcj/css-element-queries). Thei're much more powerful and probably the way CSS will work in a few years.

**Comment by juek** [comment]
Another question: 
Instead of Bootswatch 4 Scss**/flatly** I'd rather make **/pulse** the new default theme layout. A fresh look and no web fonts. What do you think?

![grafik](https://user-images.githubusercontent.com/704283/80638937-8d947900-8a61-11ea-9320-5009299b7396.png)

**Comment by mahotilo** [comment]
> no web fonts

This is a good idea for users who use non-Latin charset. It is so frustrating when you liked the font, and then you discover that it is not available in e.g. Cyrillic charset.

**Comment by gtbu** [comment]
The violet color assures that users will look for other templates like my coming bsnav ( but nevertheless ).
I just found  https://github.com/thecreation/breakpoints-js  and  https://github.com/reusables/breakpoints.js  for individual breakpoints (good for some users like me , if the title is too big)

**Comment by juek** [comment]
> The violet color assures that users will look for other templates like my coming bsnav

I guess blue is the only correct color, right? That is why Twitch, Yahoo, Milka and finally Bootstrap are such unsuccessful brands. LOL. These poor ignorant people keep using wrong colors. Someone tell them the truth.

BTW: Go to Layout Editor and change `$primary: $purple;` to `$primary: $blue;` and the path to enlightenment is open again.

**Comment by gtbu** [comment]
You are of course right, but for example twitch.tv has now a completly different layout - Also Yohoo removed the violet color slowly.  Milka has violet at his cows...so it fits!
And https://themes.getbootstrap.com/ uses white and blue. 
The problem is that users dont go to layout editor - perhaps You can add a github-wiki with all that.
( and visual studio - one Year they have this layout - the next year they have a new layout - there is a team of stylers working, who are paid for codelines).
 But i dont say that violet is genereal awful - but most sites use white , blue and also green  - in dependence of the theme. -- And is still miss the correct breakpoints. I personnally use my own smartsstrap 4)
( And someting offtopic : https://snyk.io/test/npm/bootstrap/3.3.7 vulnerabilities)

**Comment by juek** [comment]
> The other problem is that users dont go to layout editor - perhaps You can add a github-wiki with all that.

Documentation is by far our biggest problem. With some 10-20 video tutorials I could easily save 50-80% of my support posts. Unfortunately, I don't know any native English speaker with necessary technical insight and willingness to do the language part. I'm not good enough for that myself.

I once started a documentation website with a user, designer and developer part. After about 150 hours I dropped it because by then it was only a fraction of the desired result. Video tutorials are far more efficient.

**Comment by juek** [comment]
But that's OT here

**Comment by juek** [comment]
> … but most sites use white …

Yes, white is nice. I just pulled my old 'Mastering Typesetter CMS' site from the archive. That's what it looked like. I still like the design. If it wasn't that much work, I would start over.
![grafik](https://user-images.githubusercontent.com/704283/80870962-1a317800-8caa-11ea-8242-acff3dde74aa.png)

**Comment by gtbu** [comment]
P.S. Did You let the default-white out ? I cant find it.
2. The first level of the menu just appears, and only the sub-dropdowns function in my installation.

**Comment by juek** [comment]
> Did You let the default-white out ? I cant find it.

There is no white variant anymore in Bootswatch 4 by default. But you can change any of them easily by replacing the classes 
`navbar-dark bg-primary` with `navbar-light bg-white border-bottom` of `&lt;div class="navbar … &gt;` in template.php 

> The first level of the menu just appears, and only the sub-dropdown-lis function in my installation.

That's Bootstrap default behavior. Bootstrap itself doesn't support additional menu levels in dropdown menus.

**Comment by gtbu** [comment]
At https://bootswatch.com/default/ is a default white theme !

**Comment by gtbu** [comment]
HM... thats my favourite one !  You may guess why ...
But what i would still change is, that only the css is different in the various colors-versions. It means that users make a change in all templates, if they alter the template.php

**Comment by juek** [comment]
> because who really uses such layouts !

Maybe you are just too concerned with themes you don't like.

> It means, that users make a change in all templates, if they alter the template.php

In fact, users should not change template.php of default themes at all, as they will be overwritten when the CMS is updated.

I think we should add a plain Bootstrap 4 theme to be used as a boilerplate – for users who want to create their custom theme. With only basic style.scss but a complete set of all Bootstrap Scss variables – all set to default values but commented out. 
Designers could then **make a copy** of that theme folder, make changes to **Addon.ini** and **template.php** and only uncomment/change the variables that should be different from standard Bootstrap. 
This is how custom themes should be created.

**Comment by gtbu** [comment]
* More intersting for users would be to include the https://getbootstrap.com/docs/4.5/examples/

**Comment by mahotilo** [comment]
> With ... a complete set of all Bootstrap Scss variable

I think that only this alone will be a huge job.

**Comment by juek** [comment]
> I thought of Bootswatch_Flatly, where each color has its own template. 

With Bootswatch 4 there is no need to do it this way. They all share the same basic content structure. 

Maybe I'll add some compartmentalization to the plain Bootstrap 4 theme. But it should be kept simple. Let's see…

**Comment by gtbu** [comment]
> With Bootswatch 4 there is no need to do it this way. 

Its not quite so .:  You use  navbar-dark bg-primary.  At  https://getbootstrap.com/docs/4.0/components/navbar/   You  see  navbar-light bg-light , navbar-dark bg-primary etc. 
But I see You are busy . At the moment i fiddle around with smartstrap4, which is suddenly  sticky(hover color) - also the webinstallations - (and smartstrap multi 1.0 is in preparation and also bsnav - after i found a flexible solution -....... my 'dharmaprotector' will give me aweful inspiration - as always..until....)

**Comment by juek** [comment]
Some news and things to try about that topic [here](https://github.com/Typesetter/Typesetter/issues/664)

**Comment by gtbu** [comment]
The 2 sidebars are easy addable within a grid. The disadvantage of this theme is still, that the top menulevel is dead and that it uses  navbar-dark  and navbar-expand-lg (996 px - switchung) - and it has no header . Many sites use 2 small additional headers.  <header>..</header --- <nav>..</nav> ---- <section...</section> (for example .
It should use navbar-md  or navbar-sm (as i said before) - or a sidebar in narrow mode.  
Instead of navbar-dark it could use navbar-tp (or .bd-navbar as above) and define the color an the stylesheet. It is better - but  istill prefer the smartstrap4.

**Comment by juek** [comment]
OK, our new standard theme will be [Bootstrap 4](https://github.com/Typesetter/Typesetter/tree/master/themes/Bootstrap4). Let's continue the discussion [here](https://github.com/Typesetter/Typesetter/issues/664)
