### ISSUE TITLE
Prevent autocomplete for completed class name

### ISSUE THREAD

**Issue by mahotilo** [Typesetter/Typesetter#630]
We can prevent showing the only one autocomplete suggestion when it is equal to current class name. This will indicate that the class name is entered correctly, and that there are no useful suggestions.

![image](https://user-images.githubusercontent.com/14929385/80473141-6305cb80-894e-11ea-87bb-989264d0623a.png)

What do you think aout?

**Comment by juek** [comment]
Disagree. The only left autocomplete value **indicates a correct** class name. No autocomplete value  indicates a mistyped or undefined class name.

**Comment by mahotilo** [comment]
Ok. You must be right.
