### ISSUE TITLE
Select Image button does not open Finder

### ISSUE THREAD

**Issue by mahotilo** [Typesetter/Typesetter#631]
In recent builds, I sometimes have a problem with Select Image button in SlideFactory. It seems to me related with situation when background image was deleted.
Is this a TS problem due to a new Finder or Plugin?

> VM73680:2557 Uncaught TypeError: window.open is not a function
>     at Object.gp_editor.selectUsingFinder (eval at globalEval (jquery.js?v=5.2-rc:2), <anonymous>:2557:30)
>     at HTMLButtonElement.eval (eval at globalEval (jquery.js?v=5.2-rc:2), <anonymous>:2742:15)
>     at HTMLButtonElement.dispatch (jquery.js?v=5.2-rc:3)
>     at HTMLButtonElement.r.handle (jquery.js?v=5.2-rc:3)

EDIT
Have you had such errors?

**Comment by juek** [comment]
> window.open is not a function

This must be a different script that defines 'open' as a global variable.

**Comment by mahotilo** [comment]
Thx. 
I will note it and check the page for conflicts.

**Comment by juek** [comment]
In such a case, type `open` in the browser console and press [Enter]. That should reveal the origin.

**Comment by mahotilo** [comment]
Thx a lot!

**Comment by mahotilo** [comment]
Yes, it was mistyped ';' instead of ',' in one external plugin Var list.
I have to make a PR to the author:)
Thank you again it bothered me for several days.

**Comment by juek** [comment]
> it was mistyped ';' instead of ',' in one external plugin Var list.

LOL. Now I know why I never liked this kind of chained notation,
