### ISSUE TITLE
Htmltidy

### ISSUE THREAD

**Issue by gtbu** [Typesetter/Typesetter#632]
Typesetter leaves the choice to activate Htmltidy, which has limitations. An alternative is [Htmlpurifier](https://github.com/ezyang/htmlpurifier), which has further XSS - protection as a feature for unsafe multiuser-systems. It has implementations for several CMSses.
I am personally not able (at the moment) to implement its as a plugin to replace the choice of htmltidy and would therefore integrate it. But perhaps someone else knows  a code.
It is also an interesting feature for Typesetter 5.2

**Comment by juek** [comment]
Julian [already suggested](https://github.com/Typesetter/Typesetter/issues/153) htmlpurifier back in 2016 and I closed the issue for 5.2 last November. I don't know actually if it's possible as a plugin.

**Comment by gtbu** [comment]
I see the kses 8which is now also at github) for the first time... But - as You are more familiar with Typesetter : Am i right that only in line 472 ($tidy = tidy_parse_string($text,$options,'utf8');) and line 483 of Editing.php ($text = tidy_get_output($tidy);) the output is cleaned or treated ? ( The rest in page.php and Tools.php is just headings). That would make an implementation easy.

**Comment by gtbu** [comment]
The stackoverflow is 9 years old - and htmlpurifier has changed since then ! The standalone version is rather easy to implement as done [in codeigniter](https://github.com/refringe/codeigniter-htmlpurifier)
Actual "HTML Purifier will not only remove all [malicious code (XSS](http://htmlpurifier.org/live/smoketests/xssAttacks.php)) with a thoroughly audited, secure yet permissive whitelist, it will also make sure the documents are standards compliant, something only achievable with a comprehensive knowledge of W3C's specifications." 
But the code has anyway to be tested with several browsers - and so a purifier is not really necessary.

**Comment by juek** [comment]
Just a small example of what it would do with the content of a Simple Image section:

Unfiltered: 

`<a class="Simple_Image_wrapper simpleImage-scale2fit" data-width="simpleImage-scale2fit" data-width-unit="px" data-use-colorbox="false" data-enable-fullscreen="false"><img alt="Test Image" src="/addons/SimpleImage/img/default_image.png"></a>`

Filtered using HTMLpurifier with standard configuration:

`<a class="Simple_Image_wrapper simpleImage-scale2fit"><img alt="Test Image" src="/addons/SimpleImage/img/default_image.png" /></a>`

So, it would not only need a lot of configuration and testing, we would also need to implement a filter config hook for plugins. Every plugin author would have to deal with it. W3C compliance is another thing we do not want normally - it's way too limited for 1) experimental features and 2) many parts of 'living standard'
