### ISSUE TITLE
Uninformative plugin buttons in users's permissions

### ISSUE THREAD

**Issue by mahotilo** [Typesetter/Typesetter#633]
I have just had to set to the user limited right for one page and one plugin. And it was not easy to guess which "Setting" is for which plugin:) 
Maybe we can add the Plugin name to Title="" in "Setting" button?

![image](https://user-images.githubusercontent.com/14929385/80742169-9ea5be80-8b23-11ea-9f64-3118295f8b76.png)

**Comment by juek** [comment]
[Yep](https://github.com/Typesetter/Typesetter/commit/e19256885b0d57a2bcf1a366e6ced75bf2fa8d43)

**Comment by mahotilo** [comment]
You are fast as lightning :) I only managed to locate the Input in the code :)

BUT. It seems to need more. 
I see in hint same admin page name instead of plugin name
![image](https://user-images.githubusercontent.com/14929385/80747578-5a6aec00-8b2c-11ea-8fe8-d9733d429584.png)

**Comment by mahotilo** [comment]
Problem is in SPAN title

**Comment by mahotilo** [comment]
I have changed it to

> 			preg_match('/title="(.*?)".*?>/si', $label, $matches);
> 			echo '<span title='.trim($matches[1]).'>'.$label.'</span>';
> 
And it works now.
But it is very rough.

**Comment by juek** [comment]
Currently the title is only in the icon. The bestter solution of coulrse was to use more explicit labels. I know, I know, I'm guilty myself.

**Comment by juek** [comment]
[Improved](https://github.com/Typesetter/Typesetter/commit/9675ecdb19a0b092b3204bdd94c24078441ba863)

**Comment by mahotilo** [comment]
Confirm.
