### ISSUE TITLE
Several active sections in Section editor

### ISSUE THREAD

**Issue by mahotilo** [Typesetter/Typesetter#636]
Not exactly an error... 

How to reproduce
1. Start editing section
2. Switch to section editor
3. Hover to another section

And we have a bordered top level wrapper, an edited section and a hovered section. 

![image](https://user-images.githubusercontent.com/14929385/81150672-e778cf80-8f88-11ea-92ee-172dd2bff423.png)

Maybe we can manage to set different colors for hovered and edited sections?

**Comment by juek** [comment]
I cannot reproduce your particular case where multiple sections inside different wrappers are highlighted. 

For the wrapper highlighting: That's what the hover event does when 'bubbling up' the content DOM. If we wouldn't do it this way, we would not see anything when sections nested inside collapsed wrappers.

> different colors

I'm not convinced. IMO we already have a lot of complexity and dynamics in the Section Manager UI that already might scare new users away. Colors are strong indicators that should reflect important information.

**Comment by mahotilo** [comment]
> For the wrapper highlighting: That's what the hover event does when 'bubbling up' the content DOM. If we wouldn't do it this way, we would not see anything when hovering sections nested inside collapsed wrappers.

Of course. I have just pointed it out to give a full picture:) 

> Colors are strong indicators that should reflect important information.

Actually, it will be important. "You have an active editing session, beware of typing blindly"  :)

**Comment by mahotilo** [comment]
Closed with https://github.com/Typesetter/Typesetter/pull/646
