### ISSUE TITLE
Template influences

### ISSUE THREAD

**Issue by gtbu** [Typesetter/Typesetter#637]
Some time ago You had doubts that a template can influence the admin-ui. 
I made an fresh 52RC - installation with a smartstrap3-template. 
In the cms - dropdowns the letters are magnified, - and also some headings of ckeditor have big letters  The cms itself  is not influenced. The smartstrap has no thick nav-letters
![rcletters](https://user-images.githubusercontent.com/30436307/82572326-79392d00-9b84-11ea-9cb2-d967572665c8.jpg) 
This effect is not in the CE-Version - and there  ist still the problem of portability of pictures of installations in a subdirectory:  /data/_uploaded/image/..   becomes /www/tprc/data/_uploaded/image/..

( despite from that 52RC is a bit safer, the styling of the filemanger - flat and strange blue - and the  styling of ckeditor is ""not my taste"" - i would clearly use the CE-Version otherwise. Microsoft has a team of designers and ask groups of people for their taste )  - but You and others dont listen to me anyway - so....

**Comment by juek** [comment]
> Some time ago You had doubts that a template can influence the admin-ui.

Must have been a misunderstanding. There is **absolutely no doubt** that a theme can do that.

> … smartstrap3-template. In the cms - dropdowns the letters are magnified 

I don't have your theme but your screenshot looks pretty much like there is a 
```
.submenu {
  font-size: 16px !important;  
}
```
ruleset somewhere in your stylesheets. If so, try to use higher specificity and get along without `!important`. The latter will always overrule, specificity and precedence, for same element selectors.

> filemanger - flat … 

Well, there may be a renaissance of skeuomorphism someday, but not much is yet to be seen.

> … and strange blue

Edit [/include/thirdparty/elFinder/themes/material/images/icons-big.svg](https://github.com/Typesetter/Typesetter/blob/master/include/thirdparty/elFinder/themes/material/images/icons-big.svg) and [/include/thirdparty/elFinder/themes/material/images/icons-small.svg](https://github.com/Typesetter/Typesetter/blob/master/include/thirdparty/elFinder/themes/material/images/icons-small.svg) and replace all occurrences of `#1565c0` with a non-strange color.

**Comment by juek** [comment]
> Microsoft has a team of designers and ask groups of people for their taste

Didn't work too well with the Windows 8 Metro UI. Probably **The Most Epic Design Fail** of all time ;)

**Comment by gtbu** [comment]
* I have copied the include-directory for new - i cant find anything like  .submenu {
  font-size: 16px !important;  } - i never styled that way - it is bootstrap and smartmenu.
![ckheading](https://user-images.githubusercontent.com/30436307/82733740-4aeb5700-9d16-11ea-92e7-cbe734074c62.jpg)
The problem is also in Ckeditor (i think this bug was discussed last Year)

* What i mean with filemanager-style : The psudo3d- style is not homogenous neither subtle ( just look at https://www.color-hex.com/color-palettes/ ) : A Black and white cms-skin --- lightbrown-black ckeditor --- blue filemanager skin , which is not reflected in codemirror(pseudo-clear skin but tolerable) .

**Comment by juek** [comment]
> i never styled that way - it is bootstrap and smartmenus.

It's not Bootstrap. I don't feel like making remote diagnoses. 
Open the inspector and find out where the large font sizes come from. It's so easy: 2 clicks, 5 seconds. I'm getting tired of discussing basic CSS debugging.

> Evtl. an !important for the CMS-submenus could be a solution.

Sure, let's just add a thousand `!important`s everywhere. No, we won't care about every thinkable theming or scripting stupidities that enforce their own style across all boundaries to the whole document scope. The C in CSS means 'cascading'. The cause of your issue is simply poor CSS.

For the rest: it's all about your taste, which you think is the only good one. Everybody else will most likely disagree.

Don't scold - fork it and change it to your liking. It's all FOSS.

**Comment by gtbu** [comment]
In the admin.scss are several inherits. The 'bug' is not at xampp but only in the web. And : Its not a stupidity .... 
Everybody else will most likely disagree....no - just the few developers

**Comment by juek** [comment]
> In the admin.scss are several inherits.

CSS inheritance is about  (parent) elements in the DOM tree. Elements do **not** inherit rules from elsewhere defined CSS rulesets. That would be specificity. A very common misconception BTW.
