### ISSUE TITLE
Private pages in Site_Map?xml

### ISSUE THREAD

**Issue by mahotilo** [Typesetter/Typesetter#639]
Site_Map?xml contains private pages from the main menu, even when they are marked with Nofollow, Noindex

Should it just describe the content of Site_Map page?

**Comment by mahotilo** [comment]
I've made a PR https://github.com/Typesetter/Typesetter/pull/640

**Comment by mahotilo** [comment]
And we only have an embedded http:// protocol

**Comment by mahotilo** [comment]
I have decided to solve the issue via support of "noindex" state.

**Comment by juek** [comment]
> I have decided to solve the issue via support of "noindex" state.
Awesome.

> Or should it be more standart "nofollow"?
No.
