### ISSUE TITLE
Forbidden symbols in slug

### ISSUE THREAD

**Issue by mahotilo** [Typesetter/Typesetter#642]
Now, if page title contains `\, /, ' ,"`, these symbols are not eliminated in the synchronized URL.
Thus, the page with the new name `test"` after renaming causes “crash” without the possibility of changing it back.

**Comment by juek** [comment]
The slash character `/` is not forbidden in slugs (I'm using them a lot)
Double quotes `"` should get encoded as `%22`

Backslashes `\` should translate to `/` slashes.

Works here. 
Could it be your transliteration plugin?

**Comment by mahotilo** [comment]
Guilty, I am working on a plugin right now.
I was clearly checking TS processing, not my JS add, when it happened to me.
But now, I can't reproduce the bad sequence caused crash on clear installation:)
Next time I will double check with a clear TS before reporting.
Sorry

**Comment by mahotilo** [comment]
Ok
The key factors for reproducing the error for me is

- bad name  `Кофе-брейк"/\'`
- `Hide /index.php` in permalink settings
 
With `Use /index.php`, any ugly name works fine, but not with `Hide /index.php`

**Comment by juek** [comment]
Both work here.

![grafik](https://user-images.githubusercontent.com/704283/84501833-7929da00-acb7-11ea-9a97-d81ec72027a9.png)

The actual url is https://sub-domain.tld/%D0%9A%D0%BE%D1%84%D0%B5-%D0%B1%D1%80%D0%B5%D0%B9%D0%BA%22/%27 (when copied from the address bar)

**Comment by mahotilo** [comment]
Hm.
For me it is
![image](https://user-images.githubusercontent.com/14929385/84502358-d8d8b300-acc0-11ea-97d0-0205569825e0.png)

* Open Chaild page
* rename to `Кофе-брейк"/\'` with synchronize
* see 'you will be redirected'
* Forbidden

With /index.htm all works
![image](https://user-images.githubusercontent.com/14929385/84502645-7207c980-acc1-11ea-9fdd-ea8a865f2c88.png)

**Comment by juek** [comment]
Blink Browsers (Opera, Chrome, …) do not unescape the `'` single quotes in the address bar (like Firefox does) but it still works here, with and without index.php.

Probably a local server issue. 
Which one are you using? (XAMPP, EasyPHP-devserver, Server2Go, … ?)

**Comment by mahotilo** [comment]
USBwebserver v8 with custom update:)
Apache 2.4
PHP 7.1

But never mind. If you double-checked this, I agree that this can just be due to local server and server localization settings.

I am closing the issue again:)

**Comment by juek** [comment]
Just came to my mind - because you said 'Hide index.php' plays a role:

Could it be that you have `Options +Indexes` in your vHost configuration. This might cause Apache to interpret `/` slashes in URLs as a directory separators. Just a suspicion.

**Comment by mahotilo** [comment]
I have

> Options Indexes FollowSymLinks

and I have tried to change it to

> Options All

or to default value but without success.

I've also tried 
```
<VirtualHost *>
    AllowEncodedSlashes On
</VirtualHost>

```
Let it be as is.
Really, not a big problem. The only thing that bothered me was the possibility that TS has some hole in slug cleaning.
Thx again for your help.

FYI
I have finished [translit plugin](https://github.com/mahotilo/URLTranslit):) At least, prima facie.

**Comment by juek** [comment]
> I have finished translit plugin

Nice! Who needs PHP :)

**Comment by juek** [comment]
BTW: Try `Options -Indexes`

**Comment by mahotilo** [comment]
> BTW: Try Options -Indexes
Honestly, I have tried all possible options from the Apache examples. It stops working at all or does not help.
Maybe, there are more place to change then I have found.

**Comment by juek** [comment]
> It stops working at all or does not help.

Don't worry, that's normal behavior :)
