### ISSUE TITLE
Is the Trash interface a bit redundant?

### ISSUE THREAD

**Issue by mahotilo** [Typesetter/Typesetter#656]
We have 2 lines for group select/restore/delete on the Trash page. Maybe the bottom one is redundant? At least when there are less than a dozen pages in the Trash.
What do the UI/UX rules say about this?

![image](https://user-images.githubusercontent.com/14929385/87806595-ccb3b880-c85f-11ea-8dcd-49b68ddb9e54.png)

**Comment by juek** [comment]
It's pretty common for bulk actions and potentially longer lists.
I personally don't like having to scroll a page way up or down just to reach a button, like we currently have to do in 'Manage Classes'.

> What do the UI/UX rules say about this?

For what I know, best prectice is to generally separate selection and manipulation methods and always keep action UI elements visible in the viewport. 

Alternatively they can provide a keyboard shortcut, a context menu or even drag'n'drop (thrash icon) methods to apply common actions. As we know, hotkeys and context menus contradict the web browser's native UI concept and are rarley seen in Web CMS but becoming more popular recently (e.g. Ctrl + S in Wordpress editor will overrule the browser's native 'Save as' function)

At the moment, Typesetter is not very consistent in this regard. Unification would be a lot of work.

**Comment by mahotilo** [comment]
Sorry, was offline.

> At the moment, Typesetter is not very consistent in this regard. Unification would be a lot of work.

Yep. But, nevertheless, maybe we need some TS design rules or templates to show that this is good and this is bad. This will be useful not only for changing the TS admin page, but also for the plugin admin pages.
