### ISSUE TITLE
Question about Bootstrap4 popper.js

### ISSUE THREAD

**Issue by gtbu** [Typesetter/Typesetter#657]
I have in all test- installations since at least march 2020 popper.js loaded ofter login. Is that intended ?

**Comment by juek** [comment]
> I have in all test- installations since at least march 2020 popper.js loaded ofter login. Is that intended ?

Yes, we [load it](https://github.com/Typesetter/Typesetter/blob/master/include/tool/Session.php#L724) by default when logged-in and already use it in the admin ui. It's a very capable for positioning elements and can replace all our existing and future demands in this regard.

**Comment by gtbu** [comment]
Well - https://github.com/Flyer53/jsPanel4 has more possibilities.

**Comment by juek** [comment]
> Well - https://github.com/Flyer53/jsPanel4 has more possibilities

They both do different things. 
Popper itself won't **create** popovers, tooltips, panels, you name it … but it will position them for you.
It also doesn't provide own design or content or loading mechanisms. It positions stuff. That's it. And it does it very well. So we can use it for pretty much anything - tooltips, popovers, popouts, callouts, modals, bubbles, toasts, … and another 1000 things that don't have a funny name yet.

**Comment by gtbu** [comment]
Jspanel offers possibilities like https://codepen.io/Flyer53/full/XJKgMz  and  https://codepen.io/Flyer53/full/KwMqNg - of course it would mean to rewrite many things  - and probably too much work.

**Comment by juek** [comment]
From [popper.js.org](https://popper.js.org): 

> In a nutshell, Popper:
> 
> * Places your tooltip or popover **relative to the reference** taking into account their sizes, and positions its arrow centered to the reference.
> * Takes into account the **many different contexts it can live in** relative to the reference (different offsetParents, different or **nested scrolling containers**).
> * Keeps your tooltip or popover **in view as best as possible**. It prevents it from being clipped or cut off (overflow prevention) and changes the placement if the original does not fit (flipping).

That pretty much says it. 

>(jsPanel) It offers possibilities like https://codepen…

Creating fixed popups or modals with close/maximize/minimize buttons, dragging and resizing is a complete different thing, and it can be done with jQuery or vanillla JS with only a few code lines. We don't need a library for that kind of stuff in the admin UI. 

Of course jsPanel might be useful on certain websites.

**Comment by gtbu** [comment]
Jspanel4  is vanilla javascript without jquery (as bootstrap5 ...i will probably first use bootstrap5.5)  - and it has many other options - and at https://github.com/ramazanpolat/dasher is a simple dashboard ( but for typesetter popper may be sufficient)
