### ISSUE TITLE
Error. Bootswatch4_Scss\minty reffers to  common_variables.scss

### ISSUE THREAD

**Issue by mahotilo** [Typesetter/Typesetter#658]
It looks like Bootswatch4_Scss\minty has been missed during theme update.
It still has 
https://github.com/Typesetter/Typesetter/blob/d673a6463577f359890ee8eec802489628c0103c/themes/Bootswatch4_Scss/minty/variables.scss#L5

and error

> /data/_common/common_variables.scss net::ERR_ABORTED 404 (Not Found)

**Comment by juek** [comment]
Thx. Fixed with https://github.com/Typesetter/Typesetter/commit/95092d096f6e45673e73ceb83e5bc75b6fb5c298.

**Comment by gtbu** [comment]
P.S. There is now https://github.com/scssphp/scssphp/releases  1.1.1 . 
Already version 1.0.9 fixes several issuses with Bootstrap 4.4.1.
