### ISSUE TITLE
Fail to create a dir via gallery editor

### ISSUE THREAD

**Issue by mahotilo** [Typesetter/Typesetter#660]
I can't add a dir via gallery editor. Do you have the same problem?

When I press + and enter dir name, the editor closes and no new dir is added.

![image](https://user-images.githubusercontent.com/14929385/89870368-69971680-dbbe-11ea-816c-27eb8c144319.png)

**Comment by juek** [comment]
This https://github.com/Typesetter/Typesetter/commit/23b4c79931e7a81adfa20d8226d5f362865be264 should fix it.

**Comment by mahotilo** [comment]
Yes. 
Thx!
