### ISSUE TITLE
Theme customizer preview error

### ISSUE THREAD

**Issue by mahotilo** [Typesetter/Typesetter#665]
I have just found this

1. Set "Fixed header" on
2. Press "Preview"
3.  Set "Fixed header" off
4.  "Preview" is disabled!

And Theme customizer is cool. 
Thank you.

**Comment by juek** [comment]
We will certainly find more than that bug, I'm absolutely sure with this.

**Comment by mahotilo** [comment]
So it is a separated issue so as not to dim the main features discussion

**Comment by mahotilo** [comment]
UPD
If I start customization from any color selector, the described checkbox issue will not appear.

**Comment by juek** [comment]
should be fixed with https://github.com/Typesetter/Typesetter/commit/c661bb9ea4e76f711c00ad8fd7aeff10d7ad1167

**Comment by mahotilo** [comment]
Confirm
