### ISSUE TITLE
Theme customizer control text error

### ISSUE THREAD

**Issue by mahotilo** [Typesetter/Typesetter#666]
Despite this line https://github.com/Typesetter/Typesetter/blob/a305f6d66a72f3cd116077a887969373628fe2c8/themes/Bootstrap4/sidebars/customizer.php#L195
we see control text with additional ampersand processing
![image](https://user-images.githubusercontent.com/14929385/90598270-65d94480-e1fb-11ea-8d0e-870db802951d.png)

**Comment by juek** [comment]
fixed with https://github.com/Typesetter/Typesetter/commit/68578eee17012db7bfb5723de3e8825b203a4659

**Comment by mahotilo** [comment]
Confirm
