### ISSUE TITLE
ScssPhp 1.2 appears to fail compiling Bootstrap 3 Scss

### ISSUE THREAD

**Issue by juek** [Typesetter/Typesetter#673]
not yet investigated

**Comment by gtbu** [comment]
The best will be to open an issue at https://github.com/scssphp/scssphp/ and ask for support

**Comment by mahotilo** [comment]
What are the symptoms? I had tried the clear site with Bootswatch_Scss and did not see any issues.

**Comment by juek** [comment]
I have yet to find a pattern. I see `@if` or `$web-font-path` in the compiled output.

**Comment by juek** [comment]
excerpt from compiled admin.scss:

… `#admincontent_inner .col-xs-12{float:left}@if ($type == width) and ($index>0){#admincontent_inner .col-xs-0{width:0%}}@if ($type == push) and ($index>0){#admincontent_inner .col-xs-push-0{left:0%}}@if ($type == push) and ($index == 0){#admincontent_inner .col-xs-push-0{left:auto}}@if ($type == pull) and ($index>0){#admincontent_inner .col-xs-pull-0{right:0%}}@if ($type == pull) and` …

Seems as if parts of the mixin code gets outputted, admittedly besides valid CSS. 
So the CSS itself appears to work but it's bloated with invalid code.

**Comment by juek** [comment]
Another example: 

```css
/*
 * Bootstrap v3.3.6 (http://getbootstrap.com)
 * Copyright 2011-2015 Twitter, Inc.
 * Licensed under MIT (https://github.com/twbs/bootstrap/blob/master/LICENSE)
 *//* normalize.css v3.0.3 | MIT License | github.com/necolas/normalize.css */@import url(**$web-font-path**);html{font-family:sans-serif;-ms-text-size-adjust:100%;-webkit-text-size-…
```

**Comment by juek** [comment]
I already noticed with the new Bootstrap4 theme, that I need to unescape ( #{$varname} ) scss variables in places where I normally wouldn't

**Comment by juek** [comment]
There have been quite [some issues, most fixed/closed recently](https://github.com/scssphp/scssphp/issues?q=is%3Aissue+), in this regard. So we should probably try the current master or wait for the next stable release (1.2.1+ or so) before we can release 5.2

**Comment by juek** [comment]
OK, I haven't noticed there is already scssphp 1.2.1

The [update](https://github.com/Typesetter/Typesetter/commit/2ca2f3940eb6afae144f671f632a1520dc8d9de4) seems to fix most issues. 

But we need to keep an eye on it.

**Comment by juek** [comment]
> `@if ($type == width) and ($index>0){#admincontent_inner .col-xs-0{width:0%}}`

Fixed.

> `@import url($web-font-path);`

Also fixed.

Closing for now…

**Comment by mahotilo** [comment]
Oh. It was in CSS code and really without any visible messages.
The update has solved this problem for me as well.

**Comment by mahotilo** [comment]
FYI
v1.0.5 did not have this problem. 
I do not have to update RC-based-sites with v1.0.5 :)
