### ISSUE TITLE
Move from localhost to hoster no image s found.

### ISSUE THREAD

**Issue by JPRuehmann** [Typesetter/Typesetter#680]
I´ve moved my typesetter installation to my hoster and no images are displayed anymore.
What must I do to make them visible again?
Thanks,

**Comment by mahotilo** [comment]
Had you used any subdir in your local installation path, e.g.,  `http://localhost/ts`?
If so, then you have to remove this subdir part from the image src.

UPD
As I can see, it is true (site` www.***.name`). You have a `/Typesetter/` in your image source paths. Try to edit image and manually remove the subdir from the path.

**Comment by JPRuehmann** [comment]
I had it in /Typesetter/, How and ewhere can I remove it?
What do you mean by "edit image"?
Thanks,
I have a Gallery with lots of images.

**Comment by mahotilo** [comment]
> I have a Gallery with lots of images.

Yep, that's a problem.
The easiest way to do this is to use a text editor to find all the instances of ` /Typesetter/` in `data\_pages\`  and replace that substring with the empty one.

> What do you mean by "edit image"?

In case of a simple image in a text section, I mean just double-click it and edit the image path.

UPD
Beware of crashes and create a backup before!

**Comment by JPRuehmann** [comment]
Thanks

Will try that out today.

**Comment by JPRuehmann** [comment]
Worked, Thanks.
