### ISSUE TITLE
Unknown named Parameter $page with 5.1 on Monterey with Apache and PHP8.0

### ISSUE THREAD

**Issue by 8712staefa** [Typesetter/Typesetter#696]
I've replace all curly brackets in array expressions (as curlies are deprecated in php8), but I receive "Oops, an error occurred while generating this page." This after the first setup page, where already an Oops was mentioned without details.

Error Details
array(
   [type] => (integer)1
   [message] => (string)Uncaught Error: Unknown named parameter $page in /Users/res/Sites/Typesetter/include/tool/Output.php:652
Stack trace:
#0 /Users/res/Sites/Typesetter/include/tool/Output.php(652): call_user_func_array(Array, Array)
#1 /Users/res/Sites/Typesetter/include/tool/Output.php(623): gp\tool\Output::ExecClass(false, '\\gp\\tool\\Output...', Array, Array)
#2 /Users/res/Sites/Typesetter/include/tool/Output.php(577): gp\tool\Output::_ExecInfo(Array, Array)
#3 /Users/res/Sites/Typesetter/include/tool/Output.php(538): gp\tool\Output::ExecInfo(Array, Array)
#4 /Users/res/Sites/Typesetter/include/tool/Output.php(515): gp\tool\Output::ExecArea(Array)
#5 /Users/res/Sites/Typesetter/include/tool/Output.php(376): gp\tool\Output::CallOutput(Array, 'VG9wVHdvTWVudTo...')
#6 /Users/res/Sites/Typesetter/include/tool/Output.php(354): gp\tool\Output::ForEachOutput(Array, 'VG9wVHdvTWVudTo...')
#7 /Users/res/Sites/Typesetter/themes/Bootswatch_Scss/template.php(64): gp\tool\Output::Get('TopTwoMenu')
#8 /Users/res/Sites/Typesetter/include/common.php(544): require('/Users/res/Site...')
#9 /Users/res/Sites/Typesetter/include/tool/Output.php(251): IncludeScript('/Users/res/Site...', 'require', Array)
#10 /Users/res/Sites/Typesetter/include/tool/Output.php(2139): gp\tool\Output::Template()
#11 /Users/res/Sites/Typesetter/include/main.php(44): gp\tool\Output::RunOut()
#12 /Users/res/Sites/Typesetter/index.php(35): require_once('/Users/res/Site...')
#13 {main}
  thrown
   [file] => (string)/Users/res/Sites/Typesetter/include/tool/Output.php
   [line] => (integer)652
)

**Comment by gtbu** [comment]
[This](https://php.watch/versions/8.0/named-parameters) is because You use TP 5.1 which isnt php8-ready. For php8 You should upgrade to the Typesetter-p8 at github.com/gtbu. The Typesetter master here isnt php8-ready. Upgrade is [described here](https://github.com/gtbu/Typesetter-5.3-p8/issues/4) .
